from .base import Game
import random

class BinarySequenceGame(Game):

    game_rule_zh = """\
我们来玩一个"周期二值序列推理"游戏，规则如下：

游戏设定了一个长度为 {n} 的序列，索引范围为 [1, {n}]。序列中每个位置 i 被赋予一个标签 v(i)，取值为 0 或 1。

这个序列是由一个隐藏的周期规律生成的：
- 存在一个周期向量，由若干个正整数组成，规定了 0 和 1 交替出现的段长度
- 序列从某个偏移位置开始切入这个周期，形成了当前的 {n} 个位置的标签
- 保证序列中至少存在一个位置的标签为 1

你的目标是找出序列中所有标签为 1 的位置中，最小的索引 f 和最大的索引 l。

你可以使用以下三种查询方式（需要尽可能少的查询次数）：

1. 单点判定：询问位置 i 的标签是否为 1。回答"是"或"否"。
2. 区间最左查询：询问区间 [a, b] 内标签为 1 的最小索引。回答该索引或"没有"。
3. 区间最右查询：询问区间 [a, b] 内标签为 1 的最大索引。回答该索引或"没有"。

注意：区间查询 [a, b] 必须满足 1 小于等于 a 小于等于 b 小于等于 {n}，且区间长度 (b-a+1) 不能超过 {max_interval_len}。

每次只能提交一个查询或答案。请使用以下 XML 格式：

- 单点判定（例如查询位置 5）：
<query_point>5</query_point>

- 区间最左查询（例如查询区间 [3, 10]）：
<query_left>3,10</query_left>

- 区间最右查询（例如查询区间 [3, 10]）：
<query_right>3,10</query_right>

提交最终答案时，给出最小索引 f 和最大索引 l，格式如下：
<answer>f=5, l=20</answer>
"""

    game_rule_en = """\
Let's play a "Periodic Binary Sequence Reasoning" game. Here are the rules:

A sequence of length {n} has been set up, with index range [1, {n}]. Each position i is assigned a label v(i), which is either 0 or 1.

This sequence is generated by a hidden periodic pattern:
- There exists a period vector consisting of several positive integers that specify the alternating segment lengths of 0s and 1s
- The sequence starts from a certain offset position within this period, forming the current {n} position labels
- It is guaranteed that at least one position in the sequence has a label of 1

Your goal is to find the minimum index f and the maximum index l among all positions where the label is 1.

You can use the following three types of queries (try to use as few queries as possible):

1. Point Query: Ask if the label at position i is 1. Answer "Yes" or "No".
2. Left Query: Ask for the minimum index with label 1 in interval [a, b]. Answer the index or "None".
3. Right Query: Ask for the maximum index with label 1 in interval [a, b]. Answer the index or "None".

Note: For interval queries [a, b], it must satisfy 1 less than or equal to a less than or equal to b less than or equal to {n}, and the interval length (b-a+1) cannot exceed {max_interval_len}.

Each submission must contain only one query or answer. Use the following XML format:

- Point Query (e.g., querying position 5):
<query_point>5</query_point>

- Left Query (e.g., querying interval [3, 10]):
<query_left>3,10</query_left>

- Right Query (e.g., querying interval [3, 10]):
<query_right>3,10</query_right>

When submitting the final answer, provide the minimum index f and maximum index l in this format:
<answer>f=5, l=20</answer>
"""

    contextualized_rule_zh_1 = """\
我们来操作“智能交通路网拥堵监测”系统，规则如下：

系统正在监控一条路线上连续的 {n} 个交通监测站，索引范围为 [1, {n}]。每个监测站 i 的状态标签 v(i) 为 0（畅通）或 1（拥堵）。

道路的拥堵分布遵循某种隐藏的周期规律：
- 存在一个周期模式，规定了畅通路段与拥堵路段交替出现的连续长度。
- 系统从某个偏移位置开始切入这个周期，形成了当前的 {n} 个监测站的状态。
- 保证这批监测站中至少存在一个监测站处于拥堵状态（标签为 1）。

你的目标是找出所有拥堵监测站中，最小的索引 f（首个发生拥堵的监测站）和最大的索引 l（最后发生拥堵的监测站），以界定拥堵波及的整体路段。

你可以使用以下三种查询方式（需要尽可能少的查询次数）：

1. 单点判定：询问监测站 i 是否拥堵（即标签为 1）。回答"是"或"否"。
2. 区间最左查询：询问区间 [a, b] 内最早发生拥堵的监测站索引。回答该索引或"没有"。
3. 区间最右查询：询问区间 [a, b] 内最晚发生拥堵的监测站索引。回答该索引或"没有"。

注意：区间查询 [a, b] 必须满足 1 小于等于 a 小于等于 b 小于等于 {n}，且区间长度 (b-a+1) 不能超过 {max_interval_len}。

每次只能提交一个查询或答案。请使用以下 XML 格式：

- 单点判定（例如查询监测站 5）：
<query_point>5</query_point>

- 区间最左查询（例如查询区间 [3, 10]）：
<query_left>3,10</query_left>

- 区间最右查询（例如查询区间 [3, 10]）：
<query_right>3,10</query_right>

提交最终答案时，给出最小索引 f 和最大索引 l，格式如下：
<answer>f=5, l=20</answer>
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
Let's operate the "Intelligent Traffic Congestion Monitoring" system. Here are the rules:

The system is monitoring a continuous sequence of {n} traffic stations along a route, with index range [1, {n}]. Each station i is assigned a status label v(i), which is either 0 (clear) or 1 (congested).

The distribution of congestion follows a hidden periodic pattern:
- There exists a period vector specifying the alternating segment lengths of clear and congested road sections.
- The monitoring sequence starts from a certain offset position within this period, forming the current {n} station statuses.
- It is guaranteed that at least one station is congested (label 1).

Your goal is to find the minimum index f (the first congested station) and the maximum index l (the last congested station) among all congested stations, in order to delimit the entire affected road segment.

You can use the following three types of queries (try to use as few queries as possible):

1. Point Query: Ask if station i is congested (label 1). Answer "Yes" or "No".
2. Left Query: Ask for the minimum congested station index in interval [a, b]. Answer the index or "None".
3. Right Query: Ask for the maximum congested station index in interval [a, b]. Answer the index or "None".

Note: For interval queries [a, b], it must satisfy 1 less than or equal to a less than or equal to b less than or equal to {n}, and the interval length (b-a+1) cannot exceed {max_interval_len}.

Each submission must contain only one query or answer. Use the following XML format:

- Point Query (e.g., querying station 5):
<query_point>5</query_point>

- Left Query (e.g., querying interval [3, 10]):
<query_left>3,10</query_left>

- Right Query (e.g., querying interval [3, 10]):
<query_right>3,10</query_right>

When submitting the final answer, provide the minimum index f and maximum index l in this format:
<answer>f=5, l=20</answer>
"""

    contextualized_rule_zh_2 = """\
我们来操作“动态心电图异常节律监测”系统，规则如下：

系统记录了一段连续的 {n} 个心电信号片段，索引范围为 [1, {n}]。每个片段 i 被系统赋予状态标签 v(i)，取值为 0（正常窦性心律）或 1（心律失常/异常）。

异常心律的出现受到人体生理循环的影响，呈现一种隐藏的周期规律：
- 存在一个周期模式，规定了正常片段与异常片段交替出现的连续长度。
- 这段监测数据从该周期的某个偏移位置开始，形成了当前的 {n} 个片段标签。
- 保证在这段监测记录中，至少存在一个片段检测为异常（标签为 1）。

你的目标是找出所有异常片段中，最早出现的索引 f 和最晚出现的索引 l，以确定异常节律的整体时间跨度。

你可以使用以下三种查询方式（需要尽可能少的查询次数）：

1. 单点判定：询问片段 i 是否为异常（标签为 1）。回答"是"或"否"。
2. 区间最左查询：询问区间 [a, b] 内最早出现的异常片段索引。回答该索引或"没有"。
3. 区间最右查询：询问区间 [a, b] 内最晚出现的异常片段索引。回答该索引或"没有"。

注意：区间查询 [a, b] 必须满足 1 小于等于 a 小于等于 b 小于等于 {n}，且区间长度 (b-a+1) 不能超过 {max_interval_len}。

每次只能提交一个查询或答案。请使用以下 XML 格式：

- 单点判定（例如查询片段 5）：
<query_point>5</query_point>

- 区间最左查询（例如查询区间 [3, 10]）：
<query_left>3,10</query_left>

- 区间最右查询（例如查询区间 [3, 10]）：
<query_right>3,10</query_right>

提交最终答案时，给出最小索引 f 和最大索引 l，格式如下：
<answer>f=5, l=20</answer>
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
Let's operate the "Holter ECG Abnormal Rhythm Monitoring" system. Here are the rules:

The system has recorded a continuous sequence of {n} ECG signal segments, with index range [1, {n}]. Each segment i is assigned a status label v(i), which is either 0 (normal sinus rhythm) or 1 (arrhythmia/abnormal).

The occurrence of abnormal rhythms is influenced by physiological cycles, presenting a hidden periodic pattern:
- There exists a period vector specifying the alternating segment lengths of normal and abnormal rhythms.
- The monitoring data starts from a certain offset position within this period, forming the current {n} segment labels.
- It is guaranteed that at least one segment in the record is detected as abnormal (label 1).

Your goal is to find the minimum index f (earliest appearance) and the maximum index l (latest appearance) among all abnormal segments, to determine the overall time span of the abnormal rhythm.

You can use the following three types of queries (try to use as few queries as possible):

1. Point Query: Ask if segment i is abnormal (label 1). Answer "Yes" or "No".
2. Left Query: Ask for the earliest abnormal segment index in interval [a, b]. Answer the index or "None".
3. Right Query: Ask for the latest abnormal segment index in interval [a, b]. Answer the index or "None".

Note: For interval queries [a, b], it must satisfy 1 less than or equal to a less than or equal to b less than or equal to {n}, and the interval length (b-a+1) cannot exceed {max_interval_len}.

Each submission must contain only one query or answer. Use the following XML format:

- Point Query (e.g., querying segment 5):
<query_point>5</query_point>

- Left Query (e.g., querying interval [3, 10]):
<query_left>3,10</query_left>

- Right Query (e.g., querying interval [3, 10]):
<query_right>3,10</query_right>

When submitting the final answer, provide the minimum index f and maximum index l in this format:
<answer>f=5, l=20</answer>
"""

    contextualized_rule_zh_3 = """\
我们来操作“自适应学习行为测评”系统，规则如下：

系统按照课程进度列出了连续的 {n} 个知识点考查项，索引范围为 [1, {n}]。每个知识点 i 根据学生的作答表现被赋予标签 v(i)，取值为 0（掌握熟练）或 1（掌握薄弱，需复习）。

学生对知识点的遗忘与认知呈现出一种隐藏的周期规律：
- 存在一个周期模式，规定了熟练掌握与薄弱知识点交替出现的连续长度。
- 本次测评序列从该学习周期的某个偏移位置开始，形成了当前的 {n} 个考查项标签。
- 保证在这份测评中，学生至少存在一个薄弱知识点（标签为 1）。

你的目标是找出所有薄弱知识点中，最前置的知识点索引 f 和最后置的知识点索引 l，以此划定学生需要集中补习的课程范围。

你可以使用以下三种查询方式（需要尽可能少的查询次数）：

1. 单点判定：询问知识点 i 是否薄弱（标签为 1）。回答"是"或"否"。
2. 区间最左查询：询问区间 [a, b] 内最靠前的薄弱知识点索引。回答该索引或"没有"。
3. 区间最右查询：询问区间 [a, b] 内最靠后的薄弱知识点索引。回答该索引或"没有"。

注意：区间查询 [a, b] 必须满足 1 小于等于 a 小于等于 b 小于等于 {n}，且区间长度 (b-a+1) 不能超过 {max_interval_len}。

每次只能提交一个查询或答案。请使用以下 XML 格式：

- 单点判定（例如查询知识点 5）：
<query_point>5</query_point>

- 区间最左查询（例如查询区间 [3, 10]）：
<query_left>3,10</query_left>

- 区间最右查询（例如查询区间 [3, 10]）：
<query_right>3,10</query_right>

提交最终答案时，给出最小索引 f 和最大索引 l，格式如下：
<answer>f=5, l=20</answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Let's operate the "Adaptive Learning Behavior Assessment" system. Here are the rules:

The system lists a continuous sequence of {n} knowledge points based on the course progress, with index range [1, {n}]. Each knowledge point i is assigned a label v(i) based on the student's performance, which is either 0 (mastered) or 1 (weak, needs review).

The student's retention and cognition exhibit a hidden periodic pattern:
- There exists a period vector specifying the alternating segment lengths of mastered and weak knowledge points.
- This assessment sequence starts from a certain offset position within the learning cycle, forming the current {n} evaluation labels.
- It is guaranteed that the student has at least one weak knowledge point (label 1) in this assessment.

Your goal is to find the minimum index f (the first weak point) and the maximum index l (the last weak point) among all weak knowledge points, in order to delimit the course range for intensive tutoring.

You can use the following three types of queries (try to use as few queries as possible):

1. Point Query: Ask if knowledge point i is weak (label 1). Answer "Yes" or "No".
2. Left Query: Ask for the earliest weak knowledge point index in interval [a, b]. Answer the index or "None".
3. Right Query: Ask for the latest weak knowledge point index in interval [a, b]. Answer the index or "None".

Note: For interval queries [a, b], it must satisfy 1 less than or equal to a less than or equal to b less than or equal to {n}, and the interval length (b-a+1) cannot exceed {max_interval_len}.

Each submission must contain only one query or answer. Use the following XML format:

- Point Query (e.g., querying knowledge point 5):
<query_point>5</query_point>

- Left Query (e.g., querying interval [3, 10]):
<query_left>3,10</query_left>

- Right Query (e.g., querying interval [3, 10]):
<query_right>3,10</query_right>

When submitting the final answer, provide the minimum index f and maximum index l in this format:
<answer>f=5, l=20</answer>
"""

    contextualized_rule_zh_4 = """\
我们来操作“流水线产品质量自动化检测”系统，规则如下：

系统正在对流水线上连续生产的 {n} 个零部件进行质检，零部件编号范围为 [1, {n}]。每个零部件 i 的质检结果被标记为 v(i)，取值为 0（合格品）或 1（存在缺陷）。

由于生产设备的周期性振动与模具磨损特征，产品缺陷的出现遵循一种隐藏的周期规律：
- 存在一个周期模式，规定了连续合格品与连续缺陷品交替出现的批次长度。
- 当前抽检的序列刚好从生产周期的某个偏移位置切入，形成了这 {n} 个零部件的质检标签。
- 保证在这批零部件中，至少存在一个存在缺陷的产品（标签为 1）。

你的目标是找出所有缺陷品中，首个出现缺陷的零部件编号 f 和最后一个出现缺陷的零部件编号 l，以便圈定需要返工的生产批次范围。

你可以使用以下三种查询方式（需要尽可能少的查询次数）：

1. 单点判定：询问零部件 i 是否存在缺陷（标签为 1）。回答"是"或"否"。
2. 区间最左查询：询问编号区间 [a, b] 内首个出现缺陷的零部件编号。回答该编号或"没有"。
3. 区间最右查询：询问编号区间 [a, b] 内最后一个出现缺陷的零部件编号。回答该编号或"没有"。

注意：区间查询 [a, b] 必须满足 1 小于等于 a 小于等于 b 小于等于 {n}，且区间长度 (b-a+1) 不能超过 {max_interval_len}。

每次只能提交一个查询或答案。请使用以下 XML 格式：

- 单点判定（例如查询零部件 5）：
<query_point>5</query_point>

- 区间最左查询（例如查询区间 [3, 10]）：
<query_left>3,10</query_left>

- 区间最右查询（例如查询区间 [3, 10]）：
<query_right>3,10</query_right>

提交最终答案时，给出最小编号 f 和最大编号 l，格式如下：
<answer>f=5, l=20</answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
Let's operate the "Assembly Line Automated Quality Inspection" system. Here are the rules:

The system is inspecting a continuous batch of {n} components produced on the assembly line, with index range [1, {n}]. The quality inspection result for each component i is marked as v(i), which is either 0 (qualified) or 1 (defective).

Due to the periodic vibration of production equipment and mold wear, the occurrence of product defects follows a hidden periodic pattern:
- There exists a period vector specifying the alternating segment lengths of qualified and defective products.
- The currently sampled sequence happens to start from a certain offset position within the production cycle, forming the inspection labels for these {n} components.
- It is guaranteed that there is at least one defective product (label 1) in this batch.

Your goal is to find the minimum index f (the first defective component) and the maximum index l (the last defective component) among all defective products, in order to delimit the batch range that requires rework.

You can use the following three types of queries (try to use as few queries as possible):

1. Point Query: Ask if component i is defective (label 1). Answer "Yes" or "No".
2. Left Query: Ask for the first defective component index in interval [a, b]. Answer the index or "None".
3. Right Query: Ask for the last defective component index in interval [a, b]. Answer the index or "None".

Note: For interval queries [a, b], it must satisfy 1 less than or equal to a less than or equal to b less than or equal to {n}, and the interval length (b-a+1) cannot exceed {max_interval_len}.

Each submission must contain only one query or answer. Use the following XML format:

- Point Query (e.g., querying component 5):
<query_point>5</query_point>

- Left Query (e.g., querying interval [3, 10]):
<query_left>3,10</query_left>

- Right Query (e.g., querying interval [3, 10]):
<query_right>3,10</query_right>

When submitting the final answer, provide the minimum index f and maximum index l in this format:
<answer>f=5, l=20</answer>
"""

    contextualized_rule_zh_5 = """\
我们来操作“司法卷宗合规性审查”系统，规则如下：

系统提取了一份按时间排序的合同，包含连续的 {n} 个关键条款，编号范围为 [1, {n}]。每个条款 i 经过初步自然语言处理分析后，被标记为状态 v(i)，取值为 0（合规合法）或 1（存在法律风险/违规）。

由于这份合同由不同法务团队分块起草，违规条款的分布呈现出一种隐藏的周期规律：
- 存在一个周期模式，规定了连续合规条款与连续违规条款交替出现的长度。
- 该合同条款序列正好从起草周期的某个偏移位置开始，形成了当前的 {n} 个条款标签。
- 保证在整个合同中，至少存在一条具有法律风险的条款（标签为 1）。

你的目标是找出所有违规条款中，最早出现风险的条款编号 f 和最晚出现风险的条款编号 l，从而划定需要重点进行人工复核的合同章节。

你可以使用以下三种查询方式（需要尽可能少的查询次数）：

1. 单点判定：询问条款 i 是否存在法律风险（标签为 1）。回答"是"或"否"。
2. 区间最左查询：询问条款区间 [a, b] 内最早出现的违规条款编号。回答该编号或"没有"。
3. 区间最右查询：询问条款区间 [a, b] 内最晚出现的违规条款编号。回答该编号或"没有"。

注意：区间查询 [a, b] 必须满足 1 小于等于 a 小于等于 b 小于等于 {n}，且区间长度 (b-a+1) 不能超过 {max_interval_len}。

每次只能提交一个查询或答案。请使用以下 XML 格式：

- 单点判定（例如查询条款 5）：
<query_point>5</query_point>

- 区间最左查询（例如查询区间 [3, 10]）：
<query_left>3,10</query_left>

- 区间最右查询（例如查询区间 [3, 10]）：
<query_right>3,10</query_right>

提交最终答案时，给出最小编号 f 和最大编号 l，格式如下：
<answer>f=5, l=20</answer>
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
Let's operate the "Judicial Dossier Compliance Review" system. Here are the rules:

The system has extracted a chronologically ordered contract containing a continuous sequence of {n} key clauses, with index range [1, {n}]. After preliminary natural language processing, each clause i is marked with a status v(i), which is either 0 (compliant and legal) or 1 (contains legal risks/violations).

Because the contract was drafted in blocks by different legal teams, the distribution of violating clauses exhibits a hidden periodic pattern:
- There exists a period vector specifying the alternating segment lengths of compliant clauses and violating clauses.
- The sequence of contract clauses happens to start from a certain offset position within the drafting cycle, forming the current {n} clause labels.
- It is guaranteed that there is at least one clause with legal risks (label 1) in the entire contract.

Your goal is to find the minimum index f (earliest risk occurrence) and the maximum index l (latest risk occurrence) among all violating clauses, to delineate the contract sections that require intensive manual review.

You can use the following three types of queries (try to use as few queries as possible):

1. Point Query: Ask if clause i contains legal risks (label 1). Answer "Yes" or "No".
2. Left Query: Ask for the earliest violating clause index in interval [a, b]. Answer the index or "None".
3. Right Query: Ask for the latest violating clause index in interval [a, b]. Answer the index or "None".

Note: For interval queries [a, b], it must satisfy 1 less than or equal to a less than or equal to b less than or equal to {n}, and the interval length (b-a+1) cannot exceed {max_interval_len}.

Each submission must contain only one query or answer. Use the following XML format:

- Point Query (e.g., querying clause 5):
<query_point>5</query_point>

- Left Query (e.g., querying interval [3, 10]):
<query_left>3,10</query_left>

- Right Query (e.g., querying interval [3, 10]):
<query_right>3,10</query_right>

When submitting the final answer, provide the minimum index f and maximum index l in this format:
<answer>f=5, l=20</answer>
"""

    tags = ["answer", "query_point", "query_left", "query_right"]
    
    reasoning_type = "归纳推理"
    data_structure = "序列"

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 20,
                "k": 2,
                "period": [3, 2],
                "offset": 1,
            },
            2: {
                "n": 30,
                "k": 3,
                "period": [2, 3, 4],
                "offset": 2,
            },
            3: {
                "n": 40,
                "k": 3,
                "period": [5, 2, 3],
                "offset": 4,
            },
            4: {
                "n": 50,
                "k": 4,
                "period": [3, 2, 4, 3],
                "offset": 5,
            },
            5: {
                "n": 60,
                "k": 4,
                "period": [4, 3, 5, 2],
                "offset": 7,
            },
        },
        "en": {
            1: {
                "n": 20,
                "k": 2,
                "period": [3, 2],
                "offset": 1,
            },
            2: {
                "n": 30,
                "k": 3,
                "period": [2, 3, 4],
                "offset": 2,
            },
            3: {
                "n": 40,
                "k": 3,
                "period": [5, 2, 3],
                "offset": 4,
            },
            4: {
                "n": 50,
                "k": 4,
                "period": [3, 2, 4, 3],
                "offset": 5,
            },
            5: {
                "n": 60,
                "k": 4,
                "period": [4, 3, 5, 2],
                "offset": 7,
            },
        },
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = int(self.config.difficulty)

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        self.n = cfg["n"]
        self.k = cfg["k"]
        self.period = cfg["period"]
        self.offset = cfg["offset"]
        
        self.max_interval_len = self.n // 7
        
        self._game_info["n"] = self.n
        self._game_info["max_interval_len"] = self.max_interval_len

        self.sequence = self._generate_sequence()
        
        ones_positions = [i for i in range(1, self.n + 1) if self.sequence[i] == 1]
        if not ones_positions:
            raise ValueError("Generated sequence has no 1s, which violates game rules")
        
        self.correct_f = ones_positions[0]
        self.correct_l = ones_positions[-1]

    def _generate_sequence(self):
        R = sum(self.period)
        
        needed_length = self.offset + self.n
        full_sequence = []
        
        seg_counter = 0
        while len(full_sequence) < needed_length:
            for seg_len in self.period:
                value = seg_counter % 2
                full_sequence.extend([value] * seg_len)
                seg_counter += 1
                if len(full_sequence) >= needed_length:
                    break
        
        sequence = {i: full_sequence[self.offset + i - 1] for i in range(1, self.n + 1)}
        
        return sequence

    def evaluate(self, parsed_info):
        raw_ans = parsed_info["answer"]
        
        try:
            kv_pairs = [x.strip() for x in raw_ans.split(",")]
            ans_dict = {}
            for kv in kv_pairs:
                k, v = kv.split("=", 1)
                ans_dict[k.strip()] = int(v.strip())
            
            if "f" not in ans_dict or "l" not in ans_dict:
                return False
            
            model_f = ans_dict["f"]
            model_l = ans_dict["l"]
            
            return model_f == self.correct_f and model_l == self.correct_l
            
        except:
            return False

    def _cf_core_produce(self, parsed_info):
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
            none_res = "没有"
            error_range = "错误：索引超出范围。"
            error_interval = "错误：区间长度超过限制或格式无效。"
        else:
            yes_res, no_res = "Yes", "No"
            none_res = "None"
            error_range = "Error: Index out of range."
            error_interval = "Error: Interval length exceeds limit or invalid format."

        if "query_point" in parsed_info:
            try:
                i = int(parsed_info["query_point"].strip())
                if i < 1 or i > self.n:
                    return error_range
                return yes_res if self.sequence[i] == 1 else no_res
            except:
                return error_range

        elif "query_left" in parsed_info:
            try:
                raw = parsed_info["query_left"]
                a, b = [int(x.strip()) for x in raw.split(",")]
                
                if a < 1 or b > self.n or a > b:
                    return error_range
                if (b - a + 1) > self.max_interval_len:
                    return error_interval
                
                for i in range(a, b + 1):
                    if self.sequence[i] == 1:
                        return str(i)
                return none_res
                
            except:
                return error_interval

        elif "query_right" in parsed_info:
            try:
                raw = parsed_info["query_right"]
                a, b = [int(x.strip()) for x in raw.split(",")]
                
                if a < 1 or b > self.n or a > b:
                    return error_range
                if (b - a + 1) > self.max_interval_len:
                    return error_interval
                
                for i in range(b, a - 1, -1):
                    if self.sequence[i] == 1:
                        return str(i)
                return none_res
                
            except:
                return error_interval

        else:
            raise ValueError("No valid query tag found.")

    def get_all_possible_queries(self) -> list[dict]:
        results = []

        for i in range(1, self.n + 1):
            query_val = str(i)
            query_str = f"<query_point>{query_val}</query_point>"
            parsed = {"query_point": query_val}
            answer = self._cf_core_produce(parsed)
            results.append({"query": query_str, "answer": answer})

        for a in range(1, self.n + 1):
            max_b = min(self.n, a + self.max_interval_len - 1)
            
            for b in range(a, max_b + 1):
                query_val = f"{a},{b}"
                
                query_str_left = f"<query_left>{query_val}</query_left>"
                parsed_left = {"query_left": query_val}
                ans_left = self._cf_core_produce(parsed_left)
                results.append({"query": query_str_left, "answer": ans_left})
                
                query_str_right = f"<query_right>{query_val}</query_right>"
                parsed_right = {"query_right": query_val}
                ans_right = self._cf_core_produce(parsed_right)
                results.append({"query": query_str_right, "answer": ans_right})

        return results

    def _cf_make_wrong(self, correct: str) -> str:
        if correct.isdigit():
            return str(int(correct) + 1)
        
        if self.config.language == "zh":
            if correct == "是":
                return "否"
            elif correct == "否":
                return "是"
            elif correct == "没有":
                return "1"
        else:
            if correct == "Yes":
                return "No"
            elif correct == "No":
                return "Yes"
            elif correct == "None":
                return "1"

        return correct + "_WRONG"

