from .base import Game
import random

class SequenceInferenceGame(Game):

    game_rule_zh = """\
我们来玩一个"序列推理"游戏，规则如下：

游戏设定了一个长度为 N 的正整数有序序列 a[1..N]，索引从 1 开始。序列长度 N = {n}。

这个序列由以下隐藏参数生成：
- 周期 L：一个整数，3 到 7 之间。
- 模板 M：一个长度为 L 的正整数列表，每个元素取值于 1 到 9。
- 块增量 D：一个整数，0 到 5 之间。

生成方式：对于序列中的每个位置 i（1 到 N），令 k = floor((i−1)/L)，j = i − k·L（j 的范围是 1 到 L），则 a[i] = M[j] + k·D。

你的目标是通过查询推断出隐藏参数 L、D 和 M，并能够正确预测任意区间的和。

所有查询的区间都是闭区间，且区间长度必须大于等于 2（即不允许查询单个元素）：

1. 区间求和：查询区间 [l, r] 的和，返回该区间所有元素的总和。
2. 区间最大值：查询区间 [l, r] 的最大值，返回该区间的最大元素。
3. 区间最小值：查询区间 [l, r] 的最小值，返回该区间的最小元素。
4. 区间和比较：比较两个区间 [l1, r1] 和 [l2, r2] 的和，返回"前者大""后者大"或"相等"。

1. 你可以发起最多 25 次查询（需尽可能少地使用查询次数）。
2. 当你收集足够信息后，提交最终答案（宣告），包括周期 L、块增量 D 和模板 M。
3. 宣告后，系统会给出 3 个验证区间，你需要预测这 3 个区间的和。
4. 若 3 个预测值均正确，则游戏成功；否则失败。

每次只能包含一个查询或操作标签。使用以下 XML 格式：

- 区间求和（查询区间 [3, 7]）：
<query_sum>3,7</query_sum>

- 区间最大值（查询区间 [1, 5]）：
<query_max>1,5</query_max>

- 区间最小值（查询区间 [2, 8]）：
<query_min>2,8</query_min>

- 区间和比较（比较区间 [1, 3] 和 [4, 6]）：
<query_compare_sum>1,3,4,6</query_compare_sum>

- 提交宣告（周期为 5，块增量为 2，模板为 [1,3,2,4,5]）：
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- 提交验证预测（三个区间和分别为 15, 28, 42）：
<answer>15,28,42</answer>
"""

    game_rule_en = """\
Let's play a "Sequence Inference" game. Here are the rules:

A positive integer ordered sequence a[1..N] of length N is set up, with indices starting from 1. The sequence length N = {n}.

This sequence is generated by the following hidden parameters:
- Period L: An integer between 3 and 7.
- Template M: A list of L positive integers, each element is between 1 and 9.
- Block increment D: An integer between 0 and 5.

Generation method: For each position i in the sequence (1 to N), let k = floor((i−1)/L), j = i − k·L (j ranges from 1 to L), then a[i] = M[j] + k·D.

Your goal is to infer the hidden parameters L, D, and M through queries, and be able to correctly predict the sum of any interval.

All query intervals are closed intervals, and the interval length must be at least 2 (i.e., querying a single element is not allowed):

1. Interval Sum: Query the sum of interval [l, r], returns the total sum of all elements in the interval.
2. Interval Max: Query the maximum value of interval [l, r], returns the maximum element in the interval.
3. Interval Min: Query the minimum value of interval [l, r], returns the minimum element in the interval.
4. Interval Sum Comparison: Compare the sums of two intervals [l1, r1] and [l2, r2], returns "first larger", "second larger", or "equal".

1. You can make at most 25 queries (use as few queries as possible).
2. When you have gathered enough information, submit your final answer (declaration), including period L, block increment D, and template M.
3. After declaration, the system will provide 3 verification intervals, and you need to predict the sums of these 3 intervals.
4. If all 3 predictions are correct, the game succeeds; otherwise, it fails.

Each query can only contain one query or operation tag. Use the following XML format:

- Interval Sum (query interval [3, 7]):
<query_sum>3,7</query_sum>

- Interval Max (query interval [1, 5]):
<query_max>1,5</query_max>

- Interval Min (query interval [2, 8]):
<query_min>2,8</query_min>

- Interval Sum Comparison (compare intervals [1, 3] and [4, 6]):
<query_compare_sum>1,3,4,6</query_compare_sum>

- Submit Declaration (period is 5, block increment is 2, template is [1,3,2,4,5]):
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- Submit Verification Predictions (three interval sums are 15, 28, 42):
<answer>15,28,42</answer>
"""

    contextualized_rule_zh_1 = """\
【交通流特征分析系统】
你需要分析一段长度为 N 的连续时段内的交通流量序列 a[1..N]（索引从 1 开始）。当前监测总时段数 N = {n}。

该交通流序列由以下隐藏参数主导：
- 交通周期 L：一个整数，3 到 7 之间（代表一个完整的高峰/平峰循环阶段数）。
- 基准流量模板 M：一个长度为 L 的正整数列表，每个元素取值于 1 到 9（代表周期内各阶段的基准车流量）。
- 增量趋势 D：一个整数，0 到 5 之间（代表随着时间推移，每个周期额外增加的车流量基数）。

生成方式：对于监测时段 i（1 到 N），令经历的完整周期数 k = floor((i−1)/L)，当前处于周期内的阶段 j = i − k·L（j 的范围是 1 到 L），则该时段的真实车流量 a[i] = M[j] + k·D。

你的目标是通过系统查询推断出隐藏参数 L、D 和 M，并能够正确预测任意区间的总车流量。

所有查询的区间都是闭区间，且长度必须大于等于 2：

1. 区间总流量：查询区间 [l, r] 的流量总和，返回该区间所有时段车流量的总和。
2. 区间峰值：查询区间 [l, r] 的最大流量，返回该区间的最高车流量。
3. 区间谷值：查询区间 [l, r] 的最小流量，返回该区间的最低车流量。
4. 流量总和比较：比较两个区间 [l1, r1] 和 [l2, r2] 的总流量，返回"前者大""后者大"或"相等"。

1. 你可以发起最多 25 次查询（需尽可能少地使用查询次数）。
2. 当你收集足够信息后，提交最终答案（宣告），包括交通周期 L、增量趋势 D 和基准流量模板 M。
3. 宣告后，系统会给出 3 个验证区间，你需要预测这 3 个区间的总车流量。
4. 若 3 个预测值均正确，则分析成功；否则失败。

每次只能包含一个查询或操作标签。使用以下 XML 格式：

- 区间总流量（查询区间 [3, 7]）：
<query_sum>3,7</query_sum>

- 区间峰值（查询区间 [1, 5]）：
<query_max>1,5</query_max>

- 区间谷值（查询区间 [2, 8]）：
<query_min>2,8</query_min>

- 流量总和比较（比较区间 [1, 3] 和 [4, 6]）：
<query_compare_sum>1,3,4,6</query_compare_sum>

- 提交宣告（交通周期为 5，增量趋势为 2，基准流量模板为 [1,3,2,4,5]）：
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- 提交验证预测（三个区间总车流量分别为 15, 28, 42）：
<answer>15,28,42</answer>
"""

    contextualized_rule_en_1 = """\
[Transportation Scenario]
You need to analyze a traffic flow sequence a[1..N] over N consecutive time intervals (indices start from 1). The total number of monitored intervals N = {n}.

This traffic flow sequence is governed by the following hidden parameters:
- Traffic Cycle L: An integer between 3 and 7 (representing the number of phases in a complete peak/off-peak cycle).
- Baseline Flow Template M: A list of L positive integers, each element between 1 and 9 (representing the base traffic volume for each phase in the cycle).
- Trend Increment D: An integer between 0 and 5 (representing the additional traffic volume added per cycle as time progresses).

Generation method: For each monitored interval i (1 to N), let the number of completed cycles k = floor((i−1)/L), and the current phase within the cycle j = i − k·L (j ranges from 1 to L), then the actual traffic volume for that interval a[i] = M[j] + k·D.

Your goal is to infer the hidden parameters L, D, and M through system queries, and be able to correctly predict the total traffic volume of any interval.

All query intervals are closed intervals, and the interval length must be at least 2:

1. Interval Total Volume: Query the total volume of interval [l, r], returns the sum of traffic volumes in all intervals within the range.
2. Interval Peak Volume: Query the maximum volume of interval [l, r], returns the highest traffic volume in the range.
3. Interval Lowest Volume: Query the minimum volume of interval [l, r], returns the lowest traffic volume in the range.
4. Volume Sum Comparison: Compare the total volumes of two intervals [l1, r1] and [l2, r2], returns "first larger", "second larger", or "equal".

1. You can make at most 25 queries (use as few queries as possible).
2. When you have gathered enough information, submit your final answer (declaration), including traffic cycle L, trend increment D, and baseline flow template M.
3. After declaration, the system will provide 3 verification intervals, and you need to predict the total traffic volumes of these 3 intervals.
4. If all 3 predictions are correct, the analysis succeeds; otherwise, it fails.

Each query can only contain one query or operation tag. Use the following XML format:

- Interval Total Volume (query interval [3, 7]):
<query_sum>3,7</query_sum>

- Interval Peak Volume (query interval [1, 5]):
<query_max>1,5</query_max>

- Interval Lowest Volume (query interval [2, 8]):
<query_min>2,8</query_min>

- Volume Sum Comparison (compare intervals [1, 3] and [4, 6]):
<query_compare_sum>1,3,4,6</query_compare_sum>

- Submit Declaration (traffic cycle is 5, trend increment is 2, baseline flow template is [1,3,2,4,5]):
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- Submit Verification Predictions (three interval total volumes are 15, 28, 42):
<answer>15,28,42</answer>
"""

    contextualized_rule_zh_2 = """\
【生命体征连续监测系统】
你需要分析一段长度为 N 的连续监测点位上的生命体征指数序列 a[1..N]（索引从 1 开始）。总监测点位数 N = {n}。

该体征序列由以下隐藏参数主导：
- 生理周期 L：一个整数，3 到 7 之间（代表一个完整的代谢或生理波动阶段数）。
- 基准体征模板 M：一个长度为 L 的正整数列表，每个元素取值于 1 到 9（代表周期内各阶段的基准体征数值）。
- 演进增量 D：一个整数，0 到 5 之间（代表随着病情演进，每个周期基础体征增加的偏移量）。

生成方式：对于监测点位 i（1 到 N），令经历的完整周期数 k = floor((i−1)/L)，当前处于周期内的阶段 j = i − k·L（j 的范围是 1 到 L），则该点位的真实体征数值 a[i] = M[j] + k·D。

你的目标是通过系统查询推断出隐藏参数 L、D 和 M，并能够正确预测任意区间的累积生理负荷（体征总和）。

所有查询的区间都是闭区间，且长度必须大于等于 2：

1. 区间累积负荷：查询区间 [l, r] 的体征总和，返回该区间所有点位体征指数的总和。
2. 区间体征峰值：查询区间 [l, r] 的最大体征，返回该区间的最高体征数值。
3. 区间体征谷值：查询区间 [l, r] 的最小体征，返回该区间的最低体征数值。
4. 累积负荷比较：比较两个区间 [l1, r1] 和 [l2, r2] 的累积负荷，返回"前者大""后者大"或"相等"。

1. 你可以发起最多 25 次查询（需尽可能少地使用查询次数）。
2. 当你收集足够信息后，提交最终诊断（宣告），包括生理周期 L、演进增量 D 和基准体征模板 M。
3. 宣告后，系统会给出 3 个验证区间，你需要预测这 3 个区间的累积生理负荷。
4. 若 3 个预测值均正确，则诊断成功；否则失败。

每次只能包含一个查询或操作标签。使用以下 XML 格式：

- 区间累积负荷（查询区间 [3, 7]）：
<query_sum>3,7</query_sum>

- 区间体征峰值（查询区间 [1, 5]）：
<query_max>1,5</query_max>

- 区间体征谷值（查询区间 [2, 8]）：
<query_min>2,8</query_min>

- 累积负荷比较（比较区间 [1, 3] 和 [4, 6]）：
<query_compare_sum>1,3,4,6</query_compare_sum>

- 提交宣告（生理周期为 5，演进增量为 2，基准体征模板为 [1,3,2,4,5]）：
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- 提交验证预测（三个区间累积负荷分别为 15, 28, 42）：
<answer>15,28,42</answer>
"""

    contextualized_rule_en_2 = """\
[Healthcare Scenario]
You need to analyze a continuous vital sign index sequence a[1..N] over N consecutive monitoring checkpoints (indices start from 1). The total number of checkpoints N = {n}.

This vital sequence is governed by the following hidden parameters:
- Physiological Cycle L: An integer between 3 and 7 (representing the number of phases in a complete metabolic or physiological fluctuation cycle).
- Baseline Vital Template M: A list of L positive integers, each element between 1 and 9 (representing the base vital sign value for each phase in the cycle).
- Progression Increment D: An integer between 0 and 5 (representing the offset added to the base vital signs per cycle as the condition evolves).

Generation method: For each checkpoint i (1 to N), let the number of completed cycles k = floor((i−1)/L), and the current phase within the cycle j = i − k·L (j ranges from 1 to L), then the actual vital sign value for that checkpoint a[i] = M[j] + k·D.

Your goal is to infer the hidden parameters L, D, and M through system queries, and be able to correctly predict the cumulative physiological load (sum of vitals) of any interval.

All query intervals are closed intervals, and the interval length must be at least 2:

1. Interval Cumulative Load: Query the total sum of interval [l, r], returns the sum of vital indices in all checkpoints within the range.
2. Interval Peak Vital Sign: Query the maximum vital sign of interval [l, r], returns the highest vital sign value in the range.
3. Interval Lowest Vital Sign: Query the minimum vital sign of interval [l, r], returns the lowest vital sign value in the range.
4. Cumulative Load Comparison: Compare the cumulative loads of two intervals [l1, r1] and [l2, r2], returns "first larger", "second larger", or "equal".

1. You can make at most 25 queries (use as few queries as possible).
2. When you have gathered enough information, submit your final diagnosis (declaration), including physiological cycle L, progression increment D, and baseline vital template M.
3. After declaration, the system will provide 3 verification intervals, and you need to predict the cumulative physiological loads of these 3 intervals.
4. If all 3 predictions are correct, the diagnosis succeeds; otherwise, it fails.

Each query can only contain one query or operation tag. Use the following XML format:

- Interval Cumulative Load (query interval [3, 7]):
<query_sum>3,7</query_sum>

- Interval Peak Vital Sign (query interval [1, 5]):
<query_max>1,5</query_max>

- Interval Lowest Vital Sign (query interval [2, 8]):
<query_min>2,8</query_min>

- Cumulative Load Comparison (compare intervals [1, 3] and [4, 6]):
<query_compare_sum>1,3,4,6</query_compare_sum>

- Submit Declaration (physiological cycle is 5, progression increment is 2, baseline vital template is [1,3,2,4,5]):
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- Submit Verification Predictions (three interval cumulative loads are 15, 28, 42):
<answer>15,28,42</answer>
"""

    contextualized_rule_zh_3 = """\
【学习认知负荷追踪系统】
你需要分析一段长度为 N 的连续学习模块中的认知负荷指数序列 a[1..N]（索引从 1 开始）。总模块数 N = {n}。

该负荷序列由以下隐藏参数主导：
- 教学单元周期 L：一个整数，3 到 7 之间（代表一个包含授课、练习、反馈等环节的完整教学单元长度）。
- 基准认知模板 M：一个长度为 L 的正整数列表，每个元素取值于 1 到 9（代表单元内各环节的基础认知负荷值）。
- 疲劳积累增量 D：一个整数，0 到 5 之间（代表随着课程深入，每个教学单元额外增加的疲劳负荷）。

生成方式：对于学习模块 i（1 到 N），令经历的完整单元数 k = floor((i−1)/L)，当前处于单元内的环节 j = i − k·L（j 的范围是 1 到 L），则该模块的真实认知负荷 a[i] = M[j] + k·D。

你的目标是通过系统查询推断出隐藏参数 L、D 和 M，并能够正确预测任意区间的总认知负荷。

所有查询的区间都是闭区间，且长度必须大于等于 2：

1. 区间总负荷：查询区间 [l, r] 的认知负荷总和，返回该区间所有模块负荷的总计。
2. 区间最高负荷：查询区间 [l, r] 的最大负荷，返回该区间的峰值负荷数值。
3. 区间最低负荷：查询区间 [l, r] 的最小负荷，返回该区间的谷值负荷数值。
4. 总负荷比较：比较两个区间 [l1, r1] 和 [l2, r2] 的总负荷，返回"前者大""后者大"或"相等"。

1. 你可以发起最多 25 次查询（需尽可能少地使用查询次数）。
2. 当你收集足够信息后，提交最终评估（宣告），包括教学单元周期 L、疲劳积累增量 D 和基准认知模板 M。
3. 宣告后，系统会给出 3 个验证区间，你需要预测这 3 个区间的总认知负荷。
4. 若 3 个预测值均正确，则追踪成功；否则失败。

每次只能包含一个查询或操作标签。使用以下 XML 格式：

- 区间总负荷（查询区间 [3, 7]）：
<query_sum>3,7</query_sum>

- 区间最高负荷（查询区间 [1, 5]）：
<query_max>1,5</query_max>

- 区间最低负荷（查询区间 [2, 8]）：
<query_min>2,8</query_min>

- 总负荷比较（比较区间 [1, 3] 和 [4, 6]）：
<query_compare_sum>1,3,4,6</query_compare_sum>

- 提交宣告（教学单元周期为 5，疲劳积累增量为 2，基准认知模板为 [1,3,2,4,5]）：
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- 提交验证预测（三个区间总负荷分别为 15, 28, 42）：
<answer>15,28,42</answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
You need to analyze a continuous cognitive load index sequence a[1..N] over N consecutive learning modules (indices start from 1). The total number of modules N = {n}.

This cognitive load sequence is governed by the following hidden parameters:
- Teaching Unit Cycle L: An integer between 3 and 7 (representing the length of a complete unit containing lectures, practices, feedback, etc.).
- Baseline Cognitive Template M: A list of L positive integers, each element between 1 and 9 (representing the base cognitive load for each segment in the unit).
- Fatigue Accumulation Increment D: An integer between 0 and 5 (representing the extra fatigue load added per unit as the course progresses).

Generation method: For each module i (1 to N), let the number of completed units k = floor((i−1)/L), and the current segment within the unit j = i − k·L (j ranges from 1 to L), then the actual cognitive load for that module a[i] = M[j] + k·D.

Your goal is to infer the hidden parameters L, D, and M through system queries, and be able to correctly predict the total cognitive load of any interval.

All query intervals are closed intervals, and the interval length must be at least 2:

1. Interval Total Load: Query the total load of interval [l, r], returns the sum of cognitive loads across all modules within the range.
2. Interval Peak Load: Query the maximum load of interval [l, r], returns the highest load value in the range.
3. Interval Lowest Load: Query the minimum load of interval [l, r], returns the lowest load value in the range.
4. Total Load Comparison: Compare the total loads of two intervals [l1, r1] and [l2, r2], returns "first larger", "second larger", or "equal".

1. You can make at most 25 queries (use as few queries as possible).
2. When you have gathered enough information, submit your final assessment (declaration), including teaching unit cycle L, fatigue accumulation increment D, and baseline cognitive template M.
3. After declaration, the system will provide 3 verification intervals, and you need to predict the total cognitive loads of these 3 intervals.
4. If all 3 predictions are correct, the tracking succeeds; otherwise, it fails.

Each query can only contain one query or operation tag. Use the following XML format:

- Interval Total Load (query interval [3, 7]):
<query_sum>3,7</query_sum>

- Interval Peak Load (query interval [1, 5]):
<query_max>1,5</query_max>

- Interval Lowest Load (query interval [2, 8]):
<query_min>2,8</query_min>

- Total Load Comparison (compare intervals [1, 3] and [4, 6]):
<query_compare_sum>1,3,4,6</query_compare_sum>

- Submit Declaration (teaching unit cycle is 5, fatigue accumulation increment is 2, baseline cognitive template is [1,3,2,4,5]):
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- Submit Verification Predictions (three interval total loads are 15, 28, 42):
<answer>15,28,42</answer>
"""

    contextualized_rule_zh_4 = """\
【工业设备应力监测系统】
你需要分析一段长度为 N 的连续生产批次中的设备应力指数序列 a[1..N]（索引从 1 开始）。总批次数 N = {n}。

该应力序列由以下隐藏参数主导：
- 运作周期 L：一个整数，3 到 7 之间（代表一个包含多道工序的标准作业循环的批次数）。
- 基准应力模板 M：一个长度为 L 的正整数列表，每个元素取值于 1 到 9（代表循环内各批次的基础应力值）。
- 磨损损耗增量 D：一个整数，0 到 5 之间（代表随着设备老化，每个完整周期额外增加的应力偏置）。

生成方式：对于生产批次 i（1 到 N），令经历的完整周期数 k = floor((i−1)/L)，当前处于周期内的批次节点 j = i − k·L（j 的范围是 1 到 L），则该批次的真实应力指数 a[i] = M[j] + k·D。

你的目标是通过系统查询推断出隐藏参数 L、D 和 M，并能够正确预测任意区间的累积应力总和。

所有查询的区间都是闭区间，且长度必须大于等于 2：

1. 区间累积应力：查询区间 [l, r] 的应力总和，返回该区间所有批次应力指数的累加值。
2. 区间峰值应力：查询区间 [l, r] 的最大应力，返回该区间的最高应力数值。
3. 区间最低应力：查询区间 [l, r] 的最小应力，返回该区间的最低应力数值。
4. 累积应力比较：比较两个区间 [l1, r1] 和 [l2, r2] 的累积应力，返回"前者大""后者大"或"相等"。

1. 你可以发起最多 25 次查询（需尽可能少地使用查询次数）。
2. 当你收集足够信息后，提交最终判定（宣告），包括运作周期 L、磨损损耗增量 D 和基准应力模板 M。
3. 宣告后，系统会给出 3 个验证区间，你需要预测这 3 个区间的累积应力总和。
4. 若 3 个预测值均正确，则监测成功；否则失败。

每次只能包含一个查询或操作标签。使用以下 XML 格式：

- 区间累积应力（查询区间 [3, 7]）：
<query_sum>3,7</query_sum>

- 区间峰值应力（查询区间 [1, 5]）：
<query_max>1,5</query_max>

- 区间最低应力（查询区间 [2, 8]）：
<query_min>2,8</query_min>

- 累积应力比较（比较区间 [1, 3] 和 [4, 6]）：
<query_compare_sum>1,3,4,6</query_compare_sum>

- 提交宣告（运作周期为 5，磨损损耗增量为 2，基准应力模板为 [1,3,2,4,5]）：
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- 提交验证预测（三个区间累积应力分别为 15, 28, 42）：
<answer>15,28,42</answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
You need to analyze an equipment stress index sequence a[1..N] over N consecutive production batches (indices start from 1). The total number of batches N = {n}.

This stress sequence is governed by the following hidden parameters:
- Operation Cycle L: An integer between 3 and 7 (representing the number of batches in a standard operational loop covering multiple processes).
- Baseline Stress Template M: A list of L positive integers, each element between 1 and 9 (representing the base stress value for each batch in the loop).
- Wear Increment D: An integer between 0 and 5 (representing the extra stress bias added per complete cycle as the equipment ages).

Generation method: For each batch i (1 to N), let the number of completed cycles k = floor((i−1)/L), and the current batch node within the cycle j = i − k·L (j ranges from 1 to L), then the actual stress index for that batch a[i] = M[j] + k·D.

Your goal is to infer the hidden parameters L, D, and M through system queries, and be able to correctly predict the cumulative stress total of any interval.

All query intervals are closed intervals, and the interval length must be at least 2:

1. Interval Cumulative Stress: Query the total stress of interval [l, r], returns the sum of stress indices across all batches within the range.
2. Interval Peak Stress: Query the maximum stress of interval [l, r], returns the highest stress value in the range.
3. Interval Lowest Stress: Query the minimum stress of interval [l, r], returns the lowest stress value in the range.
4. Cumulative Stress Comparison: Compare the cumulative stresses of two intervals [l1, r1] and [l2, r2], returns "first larger", "second larger", or "equal".

1. You can make at most 25 queries (use as few queries as possible).
2. When you have gathered enough information, submit your final judgment (declaration), including operation cycle L, wear increment D, and baseline stress template M.
3. After declaration, the system will provide 3 verification intervals, and you need to predict the cumulative stress totals of these 3 intervals.
4. If all 3 predictions are correct, the monitoring succeeds; otherwise, it fails.

Each query can only contain one query or operation tag. Use the following XML format:

- Interval Cumulative Stress (query interval [3, 7]):
<query_sum>3,7</query_sum>

- Interval Peak Stress (query interval [1, 5]):
<query_max>1,5</query_max>

- Interval Lowest Stress (query interval [2, 8]):
<query_min>2,8</query_min>

- Cumulative Stress Comparison (compare intervals [1, 3] and [4, 6]):
<query_compare_sum>1,3,4,6</query_compare_sum>

- Submit Declaration (operation cycle is 5, wear increment is 2, baseline stress template is [1,3,2,4,5]):
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- Submit Verification Predictions (three interval cumulative stresses are 15, 28, 42):
<answer>15,28,42</answer>
"""

    contextualized_rule_zh_5 = """\
【法律案件流程耗时审计系统】
你需要分析一段长度为 N 的连续诉讼程序步骤中的计费小时数序列 a[1..N]（索引从 1 开始）。总步骤数 N = {n}。

该计费序列由以下隐藏参数主导：
- 核心程序周期 L：一个整数，3 到 7 之间（代表一个包含立案、取证、庭审等环节的标准化程序阶段数）。
- 基准耗时模板 M：一个长度为 L 的正整数列表，每个元素取值于 1 到 9（代表各程序环节的基础计费小时数）。
- 案件延宕增量 D：一个整数，0 到 5 之间（代表随着案情复杂化，每经历一个程序周期额外增加的文书或沟通耗时）。

生成方式：对于程序步骤 i（1 到 N），令经历的完整周期数 k = floor((i−1)/L)，当前处于周期内的环节 j = i − k·L（j 的范围是 1 到 L），则该步骤的真实计费小时数 a[i] = M[j] + k·D。

你的目标是通过系统查询推断出隐藏参数 L、D 和 M，并能够正确预测任意区间的总计费小时数。

所有查询的区间都是闭区间，且长度必须大于等于 2：

1. 区间总计费小时：查询区间 [l, r] 的耗时总和，返回该区间所有步骤计费小时数的总计。
2. 区间最高耗时：查询区间 [l, r] 的最大耗时，返回该区间的最高单步计费小时数。
3. 区间最低耗时：查询区间 [l, r] 的最小耗时，返回该区间的最低单步计费小时数。
4. 总耗时比较：比较两个区间 [l1, r1] 和 [l2, r2] 的总计费小时，返回"前者大""后者大"或"相等"。

1. 你可以发起最多 25 次查询（需尽可能少地使用查询次数）。
2. 当你收集足够信息后，提交最终审计（宣告），包括核心程序周期 L、案件延宕增量 D 和基准耗时模板 M。
3. 宣告后，系统会给出 3 个验证区间，你需要预测这 3 个区间的总计费小时数。
4. 若 3 个预测值均正确，则审计成功；否则失败。

每次只能包含一个查询或操作标签。使用以下 XML 格式：

- 区间总计费小时（查询区间 [3, 7]）：
<query_sum>3,7</query_sum>

- 区间最高耗时（查询区间 [1, 5]）：
<query_max>1,5</query_max>

- 区间最低耗时（查询区间 [2, 8]）：
<query_min>2,8</query_min>

- 总耗时比较（比较区间 [1, 3] 和 [4, 6]）：
<query_compare_sum>1,3,4,6</query_compare_sum>

- 提交宣告（核心程序周期为 5，案件延宕增量为 2，基准耗时模板为 [1,3,2,4,5]）：
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- 提交验证预测（三个区间总耗时分别为 15, 28, 42）：
<answer>15,28,42</answer>
"""

    contextualized_rule_en_5 = """\
[Law Scenario]
You need to analyze a sequence of billable hours a[1..N] across N consecutive procedural steps (indices start from 1). The total number of steps N = {n}.

This billable sequence is governed by the following hidden parameters:
- Core Procedural Cycle L: An integer between 3 and 7 (representing the number of stages in a standardized procedural cycle covering filing, discovery, trial, etc.).
- Baseline Time Template M: A list of L positive integers, each element between 1 and 9 (representing the base billable hours for each procedural step).
- Delay Escalation Increment D: An integer between 0 and 5 (representing the extra documentation or communication time added per cycle as the case becomes more complex).

Generation method: For each step i (1 to N), let the number of completed cycles k = floor((i−1)/L), and the current step within the cycle j = i − k·L (j ranges from 1 to L), then the actual billable hours for that step a[i] = M[j] + k·D.

Your goal is to infer the hidden parameters L, D, and M through system queries, and be able to correctly predict the total billable hours of any interval.

All query intervals are closed intervals, and the interval length must be at least 2:

1. Interval Total Billable Hours: Query the total time of interval [l, r], returns the sum of billable hours across all steps within the range.
2. Interval Highest Hours: Query the maximum time of interval [l, r], returns the highest single-step billable hours in the range.
3. Interval Lowest Hours: Query the minimum time of interval [l, r], returns the lowest single-step billable hours in the range.
4. Total Hours Comparison: Compare the total billable hours of two intervals [l1, r1] and [l2, r2], returns "first larger", "second larger", or "equal".

1. You can make at most 25 queries (use as few queries as possible).
2. When you have gathered enough information, submit your final audit (declaration), including core procedural cycle L, delay escalation increment D, and baseline time template M.
3. After declaration, the system will provide 3 verification intervals, and you need to predict the total billable hours of these 3 intervals.
4. If all 3 predictions are correct, the audit succeeds; otherwise, it fails.

Each query can only contain one query or operation tag. Use the following XML format:

- Interval Total Billable Hours (query interval [3, 7]):
<query_sum>3,7</query_sum>

- Interval Highest Hours (query interval [1, 5]):
<query_max>1,5</query_max>

- Interval Lowest Hours (query interval [2, 8]):
<query_min>2,8</query_min>

- Total Hours Comparison (compare intervals [1, 3] and [4, 6]):
<query_compare_sum>1,3,4,6</query_compare_sum>

- Submit Declaration (core procedural cycle is 5, delay escalation increment is 2, baseline time template is [1,3,2,4,5]):
<declare>L=5, D=2, M=[1,3,2,4,5]</declare>

- Submit Verification Predictions (three interval total hours are 15, 28, 42):
<answer>15,28,42</answer>
"""

    tags = ["query_sum", "query_max", "query_min", "query_compare_sum", "declare", "answer"]

    reasoning_type = "归纳推理"
    data_structure = "序列"

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 24,
                "L": 3,
                "D": 1,
                "M": [2, 5, 3],
            },
            2: {
                "n": 30,
                "L": 5,
                "D": 2,
                "M": [1, 4, 2, 6, 3],
            },
            3: {
                "n": 42,
                "L": 6,
                "D": 3,
                "M": [2, 5, 1, 7, 4, 3],
            },
            4: {
                "n": 49,
                "L": 7,
                "D": 4,
                "M": [3, 6, 2, 8, 1, 5, 4],
            },
            5: {
                "n": 60,
                "L": 7,
                "D": 5,
                "M": [1, 7, 3, 9, 2, 6, 4],
            },
        },
        "en": {
            1: {
                "n": 24,
                "L": 3,
                "D": 1,
                "M": [2, 5, 3],
            },
            2: {
                "n": 30,
                "L": 5,
                "D": 2,
                "M": [1, 4, 2, 6, 3],
            },
            3: {
                "n": 42,
                "L": 6,
                "D": 3,
                "M": [2, 5, 1, 7, 4, 3],
            },
            4: {
                "n": 49,
                "L": 7,
                "D": 4,
                "M": [3, 6, 2, 8, 1, 5, 4],
            },
            5: {
                "n": 60,
                "L": 7,
                "D": 5,
                "M": [1, 7, 3, 9, 2, 6, 4],
            },
        },
    }

    def __init__(self, config):
        self.query_count = 0
        self.declared = False
        self.verification_intervals = None
        self.verification_answers = None
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = self.config.difficulty

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        self.n = cfg["n"]
        self.L = cfg["L"]
        self.D = cfg["D"]
        self.M = cfg["M"]

        self._game_info["n"] = self.n

        self.sequence = [0]
        for i in range(1, self.n + 1):
            k = (i - 1) // self.L
            j = i - k * self.L
            a_i = self.M[j - 1] + k * self.D
            self.sequence.append(a_i)

        self.verification_intervals = []
        self.verification_answers = []
        random.seed(diff * 100 + self.n)
        for _ in range(3):
            length = random.randint(3, self.L + 2)
            start = random.randint(1, self.n - length + 1)
            end = start + length - 1
            self.verification_intervals.append((start, end))
            interval_sum = sum(self.sequence[start:end + 1])
            self.verification_answers.append(interval_sum)

    def _validate_interval(self, l, r):
        if not (1 <= l <= r <= self.n):
            return False, "区间越界" if self.config.language == "zh" else "Interval out of bounds"
        if r - l + 1 < 2:
            return False, "区间长度必须大于等于2" if self.config.language == "zh" else "Interval length must be at least 2"
        return True, ""

    def evaluate(self, parsed_info):
        try:
            raw_ans = parsed_info["answer"].strip()
            predictions = [int(x.strip()) for x in raw_ans.split(",")]
            
            if len(predictions) != 3:
                return False
            
            return predictions == self.verification_answers
        except:
            return False

    def _cf_core_produce(self, parsed_info):
        if self.declared:
            if self.config.language == "zh":
                return "错误：已经宣告，不能再进行查询。"
            else:
                return "Error: Already declared, no more queries allowed."
        
        if "declare" in parsed_info:
            try:
                raw_declare = parsed_info["declare"]
                declare_dict = {}
                parts = raw_declare.split(",")
                
                for part in parts:
                    if "=" in part:
                        if "M=" in part:
                            m_part = raw_declare.split("M=")[1].strip()
                            if "[" in m_part and "]" in m_part:
                                m_content = m_part[m_part.index("[") + 1:m_part.index("]")]
                                declare_dict["M"] = [int(x.strip()) for x in m_content.split(",")]
                        else:
                            k, v = part.split("=")
                            declare_dict[k.strip()] = int(v.strip())
                
                if "L" not in declare_dict or "D" not in declare_dict or "M" not in declare_dict:
                    raise ValueError
                
                self.declared = True
                
                if self.config.language == "zh":
                    intervals_str = ", ".join([f"[{l},{r}]" for l, r in self.verification_intervals])
                    return f"宣告已接收。请预测以下3个区间的和：{intervals_str}"
                else:
                    intervals_str = ", ".join([f"[{l},{r}]" for l, r in self.verification_intervals])
                    return f"Declaration received. Please predict the sums of the following 3 intervals: {intervals_str}"
                    
            except:
                self.state.set_state("failed", "invalid declaration format")
                return "错误：宣告格式无效" if self.config.language == "zh" else "Error: Invalid declaration format"
        
        if self.query_count >= 25:
            self.state.set_state("failed", "exceeded query limit")
            if self.config.language == "zh":
                return "错误：超过查询次数限制（25次）。"
            else:
                return "Error: Exceeded query limit (25 queries)."
        
        if "query_sum" in parsed_info:
            try:
                l, r = [int(x.strip()) for x in parsed_info["query_sum"].split(",")]
                valid, msg = self._validate_interval(l, r)
                if not valid:
                    self.state.set_state("failed", "invalid query")
                    return f"错误：{msg}" if self.config.language == "zh" else f"Error: {msg}"
                
                self.query_count += 1
                result = sum(self.sequence[l:r + 1])
                return str(result)
            except:
                self.state.set_state("failed", "invalid query format")
                return "错误：查询格式无效" if self.config.language == "zh" else "Error: Invalid query format"
        
        elif "query_max" in parsed_info:
            try:
                l, r = [int(x.strip()) for x in parsed_info["query_max"].split(",")]
                valid, msg = self._validate_interval(l, r)
                if not valid:
                    self.state.set_state("failed", "invalid query")
                    return f"错误：{msg}" if self.config.language == "zh" else f"Error: {msg}"
                
                self.query_count += 1
                result = max(self.sequence[l:r + 1])
                return str(result)
            except:
                self.state.set_state("failed", "invalid query format")
                return "错误：查询格式无效" if self.config.language == "zh" else "Error: Invalid query format"
        
        elif "query_min" in parsed_info:
            try:
                l, r = [int(x.strip()) for x in parsed_info["query_min"].split(",")]
                valid, msg = self._validate_interval(l, r)
                if not valid:
                    self.state.set_state("failed", "invalid query")
                    return f"错误：{msg}" if self.config.language == "zh" else f"Error: {msg}"
                
                self.query_count += 1
                result = min(self.sequence[l:r + 1])
                return str(result)
            except:
                self.state.set_state("failed", "invalid query format")
                return "错误：查询格式无效" if self.config.language == "zh" else "Error: Invalid query format"
        
        elif "query_compare_sum" in parsed_info:
            try:
                parts = [int(x.strip()) for x in parsed_info["query_compare_sum"].split(",")]
                if len(parts) != 4:
                    raise ValueError
                l1, r1, l2, r2 = parts
                
                valid1, msg1 = self._validate_interval(l1, r1)
                valid2, msg2 = self._validate_interval(l2, r2)
                
                if not valid1:
                    self.state.set_state("failed", "invalid query")
                    return f"错误：第一个区间 - {msg1}" if self.config.language == "zh" else f"Error: First interval - {msg1}"
                if not valid2:
                    self.state.set_state("failed", "invalid query")
                    return f"错误：第二个区间 - {msg2}" if self.config.language == "zh" else f"Error: Second interval - {msg2}"
                
                self.query_count += 1
                sum1 = sum(self.sequence[l1:r1 + 1])
                sum2 = sum(self.sequence[l2:r2 + 1])
                
                if self.config.language == "zh":
                    if sum1 > sum2:
                        return "前者大"
                    elif sum1 < sum2:
                        return "后者大"
                    else:
                        return "相等"
                else:
                    if sum1 > sum2:
                        return "first larger"
                    elif sum1 < sum2:
                        return "second larger"
                    else:
                        return "equal"
            except:
                self.state.set_state("failed", "invalid query format")
                return "错误：查询格式无效" if self.config.language == "zh" else "Error: Invalid query format"
        
        else:
            self.state.set_state("failed", "no valid query tag")
            return "错误：未找到有效的查询标签" if self.config.language == "zh" else "Error: No valid query tag found"

    def _cf_make_wrong(self, correct: str) -> str:
        if correct.lstrip("-").isdigit():
            return str(int(correct) + 1)
        
        if self.config.language == "zh":
            if correct == "前者大":
                return "后者大"
            elif correct == "后者大":
                return "相等"
            elif correct == "相等":
                return "前者大"
            elif "是" in correct:
                return correct.replace("是", "否")
            elif "否" in correct:
                return correct.replace("否", "是")
        else:
            if correct == "first larger":
                return "second larger"
            elif correct == "second larger":
                return "equal"
            elif correct == "equal":
                return "first larger"
            lower_correct = correct.lower()
            if "yes" in lower_correct:
                return correct.replace("Yes", "No").replace("yes", "no").replace("YES", "NO")
            elif "no" in lower_correct:
                return correct.replace("No", "Yes").replace("no", "yes").replace("NO", "YES")
        
        return correct + "_WRONG"

    def get_all_possible_queries(self) -> list[dict]:
        queries = []
        
        for l in range(1, self.n):
            for r in range(l + 1, self.n + 1):
                query_str_sum = f"{l},{r}"
                ans_sum = str(sum(self.sequence[l:r + 1]))
                queries.append({
                    "query": f"<query_sum>{query_str_sum}</query_sum>",
                    "answer": ans_sum
                })

                query_str_max = f"{l},{r}"
                ans_max = str(max(self.sequence[l:r + 1]))
                queries.append({
                    "query": f"<query_max>{query_str_max}</query_max>",
                    "answer": ans_max
                })

                query_str_min = f"{l},{r}"
                ans_min = str(min(self.sequence[l:r + 1]))
                queries.append({
                    "query": f"<query_min>{query_str_min}</query_min>",
                    "answer": ans_min
                })
        
        return queries