from .base import Game
import re
import random as _random

class PeriodicSequenceGame(Game):

    game_rule_zh = """\
我们现在来玩一个"周期序列推理"游戏，规则如下：

游戏设定了一个长度为 {n} 的二值序列（位置索引为 1 到 {n}），序列中每个位置的值为 0 或 1。这个序列由一个隐藏的周期模式重复生成，周期长度在 2 到 10 之间，并且周期模式中至少包含一个 0 和一个 1。

你的目标是找出所有值为 1 的位置，并以严格升序列表的形式提交答案。你可以通过以下三种查询方式获取信息（每次只能进行一种查询）：

1. 点值查询：询问某个位置 i 的值是 0 还是 1。回答"0"或"1"。
2. 区间计数查询：询问区间 [a, b] 内有多少个位置的值为 1。回答一个非负整数。
3. 子串等同性查询：询问从位置 a 开始长度为 L 的子串，与从位置 b 开始长度为 L 的子串是否完全相同。回答"是"或"否"。

请尽可能少地使用查询次数来找到答案。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 点值查询（例如查询位置 5）：
<query_point>5</query_point>

- 区间计数查询（例如查询区间 [3, 7]）：
<query_range>3,7</query_range>

- 子串等同性查询（例如查询从位置 2 开始长度 3 的子串与从位置 5 开始长度 3 的子串是否相同）：
<query_substring>2,5,3</query_substring>

提交最终答案时，必须列出所有值为 1 的位置，按升序排列，用逗号分隔。如果没有任何位置为 1，则提交空列表。格式如下：

<answer>1,3,5,7</answer>

或（若无 1）：

<answer></answer>
"""

    game_rule_en = """\
Let's play a "Periodic Sequence Inference" game. Here are the rules:

The game has a binary sequence of length {n} (positions indexed from 1 to {n}), where each position contains either 0 or 1. This sequence is generated by repeating a hidden periodic pattern. The period length is between 2 and 10, and the pattern contains at least one 0 and one 1.

Your goal is to find all positions with value 1 and submit them as a strictly ascending list. You can obtain information through three types of queries (only one query per turn):

1. Point Query: Ask for the value (0 or 1) at position i. Answer "0" or "1".
2. Range Count Query: Ask how many positions in the range [a, b] have value 1. Answer a non-negative integer.
3. Substring Equality Query: Ask whether the substring starting at position a with length L is identical to the substring starting at position b with length L. Answer "Yes" or "No".

Please use as few queries as possible to find the answer.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying position 5):
<query_point>5</query_point>

- Range Count Query (e.g., querying range [3, 7]):
<query_range>3,7</query_range>

- Substring Equality Query (e.g., comparing substring starting at 2 with length 3 to substring starting at 5 with length 3):
<query_substring>2,5,3</query_substring>

When submitting the final answer, list all positions with value 1 in ascending order, separated by commas. If no positions have value 1, submit an empty list. Use this format:

<answer>1,3,5,7</answer>

Or (if no 1s):

<answer></answer>
"""

    contextualized_rule_zh_1 = """\
我们现在来进行一项“交通信号系统故障排查”任务。

系统监控了一条主干道上连续的 {n} 个路口（编号 1 到 {n}），每个路口的信号灯状态要么为“故障”（值为 1），要么为“正常”（值为 0）。由于交通控制网络存在隐蔽的周期性干扰信号，路口故障呈现出一个隐藏的周期模式（周期长度在 2 到 10 之间，且一个周期内至少包含一个故障路口和一个正常路口）。

你的目标是找出所有存在故障（值为 1）的路口，并以严格升序列表的形式提交答案。你可以通过以下三种监控系统查询方式获取信息（每次只能进行一种查询）：

1. 点值查询：询问某一路口 i 是正常(0)还是故障(1)。回答"0"或"1"。
2. 区间计数查询：询问从路口 a 到路口 b 的区间内共有多少个故障路口。回答一个非负整数。
3. 子串等同性查询：询问从路口 a 开始的连续 L 个路口的故障分布，与从路口 b 开始连续 L 个路口是否完全相同。回答"是"或"否"。

请尽可能少地使用查询次数来定位所有故障路口。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 点值查询（例如查询路口 5）：
<query_point>5</query_point>

- 区间计数查询（例如查询路口 3 到 7）：
<query_range>3,7</query_range>

- 子串等同性查询（例如对比路口 2 开始连续 3 个与路口 5 开始连续 3 个的状态分布）：
<query_substring>2,5,3</query_substring>

提交最终答案时，必须列出所有故障路口（值为 1）的编号，按升序排列，用逗号分隔。如果没有故障，则提交空列表。格式如下：

<answer>1,3,5,7</answer>

或（若无故障）：

<answer></answer>
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
We are now conducting a "Traffic Signal System Fault Troubleshooting" task.

The monitoring system tracks {n} consecutive intersections along a main road (indexed from 1 to {n}). The traffic light state at each intersection is either "faulty" (value 1) or "normal" (value 0). Due to hidden periodic interference in the traffic control network, the faults exhibit a repeating periodic pattern. The period length is between 2 and 10, and the pattern contains at least one faulty intersection and one normal intersection.

Your goal is to find all faulty intersections (value 1) and submit them as a strictly ascending list. You can obtain information through three types of system queries (only one query per turn):

1. Point Query: Ask for the state (0 or 1) at intersection i. Answer "0" or "1".
2. Range Count Query: Ask how many faulty intersections exist in the range [a, b]. Answer a non-negative integer.
3. Substring Equality Query: Ask whether the fault distribution of L consecutive intersections starting at a is identical to that of L consecutive intersections starting at b. Answer "Yes" or "No".

Please use as few queries as possible to locate all faults.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying intersection 5):
<query_point>5</query_point>

- Range Count Query (e.g., querying range [3, 7]):
<query_range>3,7</query_range>

- Substring Equality Query (e.g., comparing 3 intersections starting at 2 with 3 starting at 5):
<query_substring>2,5,3</query_substring>

When submitting the final answer, list all faulty intersection indices in ascending order, separated by commas. If there are no faults, submit an empty list. Use this format:

<answer>1,3,5,7</answer>

Or (if no faults):

<answer></answer>
"""

    contextualized_rule_zh_2 = """\
我们现在来进行一项“持续性生命体征异常排查”任务。

医疗监测系统记录了一名患者连续 {n} 个小时（时间点索引从 1 到 {n}）的生理数据。每个时间点的数据状态分为“异常”（值为 1）或“正常”（值为 0）。由于患者生理节律的影响，异常指标的变化呈现出隐藏的周期性模式（周期长度在 2 到 10 个小时之间，且一个周期内至少包含一个异常小时和一个正常小时）。

你的目标是找出所有指标异常（值为 1）的时间点，并以严格升序列表的形式提交答案。你可以通过以下三种病历数据库查询方式获取信息（每次只能进行一种查询）：

1. 点值查询：询问特定时间点 i 的状态是正常(0)还是异常(1)。回答"0"或"1"。
2. 区间计数查询：询问从时间点 a 到时间点 b 之间共有多少个小时出现异常。回答一个非负整数。
3. 子串等同性查询：询问从时间点 a 开始的连续 L 个小时的异常模式，与从时间点 b 开始连续 L 个小时是否完全一致。回答"是"或"否"。

请尽可能少地使用查询次数来定位所有异常发生的时间。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 点值查询（例如查询时间点 5）：
<query_point>5</query_point>

- 区间计数查询（例如查询区间 [3, 7]）：
<query_range>3,7</query_range>

- 子串等同性查询（例如对比时间点 2 和 5 开始的连续 3 个小时的状态）：
<query_substring>2,5,3</query_substring>

提交最终答案时，必须列出所有异常的时间点，按升序排列，用逗号分隔。如果无异常，则提交空列表。格式如下：

<answer>1,3,5,7</answer>

或（若无异常）：

<answer></answer>
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
We are now conducting a "Continuous Vital Signs Anomaly Detection" task.

The medical monitoring system has recorded a patient's physiological data over {n} consecutive hours (indexed from 1 to {n}). The data state at each hour is either "abnormal" (value 1) or "normal" (value 0). Influenced by the patient's circadian rhythms, the anomalous indicators exhibit a hidden periodic pattern. The period length is between 2 and 10 hours, containing at least one abnormal hour and one normal hour.

Your goal is to find all abnormal hours (value 1) and submit them as a strictly ascending list. You can query the medical database in three ways (only one query per turn):

1. Point Query: Ask for the state (0 or 1) at hour i. Answer "0" or "1".
2. Range Count Query: Ask how many abnormal hours occurred during the range [a, b]. Answer a non-negative integer.
3. Substring Equality Query: Ask whether the anomaly pattern of L consecutive hours starting at hour a is identical to that of L hours starting at b. Answer "Yes" or "No".

Please use as few queries as possible to locate all anomalies.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying hour 5):
<query_point>5</query_point>

- Range Count Query (e.g., querying range [3, 7]):
<query_range>3,7</query_range>

- Substring Equality Query (e.g., comparing 3 hours starting at 2 with 3 hours starting at 5):
<query_substring>2,5,3</query_substring>

When submitting the final answer, list all abnormal hours in ascending order, separated by commas. If there are no anomalies, submit an empty list. Use this format:

<answer>1,3,5,7</answer>

Or (if no anomalies):

<answer></answer>
"""

    contextualized_rule_zh_3 = """\
我们现在来进行一项“智能题库超纲检测”任务。

在一次自适应在线测试中，系统连续生成了 {n} 道题目（题号从 1 到 {n}）。每道题的难度状态分为“超纲”（值为 1）或“正常”（值为 0）。由于底层出题算法存在固定的模板循环，题目的超纲情况呈现出一种隐蔽的周期模式（周期长度在 2 到 10 题之间，且一个周期内至少包含一道超纲题和一道正常题）。

你的目标是找出所有超纲（值为 1）的题号，并以严格升序列表的形式提交答案。你可以通过以下三种题库系统查询方式获取信息（每次只能进行一种查询）：

1. 点值查询：询问第 i 题是正常(0)还是超纲(1)。回答"0"或"1"。
2. 区间计数查询：询问从题号 a 到 b 的区间内共有多少道超纲题目。回答一个非负整数。
3. 子串等同性查询：询问从题号 a 开始连续 L 道题的超纲分布，与从题号 b 开始连续 L 道题是否完全一致。回答"是"或"否"。

请尽可能少地使用查询次数来定位所有超纲题目。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 点值查询（例如查询第 5 题）：
<query_point>5</query_point>

- 区间计数查询（例如查询题号 3 到 7）：
<query_range>3,7</query_range>

- 子串等同性查询（例如对比第 2 题和第 5 题开始的连续 3 道题的状态分布）：
<query_substring>2,5,3</query_substring>

提交最终答案时，必须列出所有超纲题号，按升序排列，用逗号分隔。如果无超纲题，则提交空列表。格式如下：

<answer>1,3,5,7</answer>

或（若无超纲）：

<answer></answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
We are now conducting an "Intelligent Question Bank Out-of-Syllabus Detection" task.

In an adaptive online test, the system generated {n} consecutive questions (indexed from 1 to {n}). The difficulty status of each question is either "out-of-syllabus" (value 1) or "normal" (value 0). Due to the fixed cyclic templates in the underlying generation algorithm, the occurrence of out-of-syllabus questions follows a hidden periodic pattern. The period length is between 2 and 10 questions, containing at least one out-of-syllabus question and one normal question.

Your goal is to find all out-of-syllabus questions (value 1) and submit them as a strictly ascending list. You can query the question bank system in three ways (only one query per turn):

1. Point Query: Ask whether question i is normal (0) or out-of-syllabus (1). Answer "0" or "1".
2. Range Count Query: Ask how many out-of-syllabus questions exist in the range [a, b]. Answer a non-negative integer.
3. Substring Equality Query: Ask whether the status pattern of L consecutive questions starting at a is identical to that of L questions starting at b. Answer "Yes" or "No".

Please use as few queries as possible to locate all out-of-syllabus questions.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying question 5):
<query_point>5</query_point>

- Range Count Query (e.g., querying range [3, 7]):
<query_range>3,7</query_range>

- Substring Equality Query (e.g., comparing 3 questions starting at 2 with 3 questions starting at 5):
<query_substring>2,5,3</query_substring>

When submitting the final answer, list all out-of-syllabus question indices in ascending order, separated by commas. If none are out-of-syllabus, submit an empty list. Use this format:

<answer>1,3,5,7</answer>

Or (if none):

<answer></answer>
"""

    contextualized_rule_zh_4 = """\
我们现在来进行一项“自动化流水线不良品排查”任务。

质检系统监控了生产线上连续加工的 {n} 个批次的产品（批次编号从 1 到 {n}），每个批次的质量状态要么为“不合格”（值为 1），要么为“合格”（值为 0）。由于机械传动部件存在周期性的轻微偏移，不良品的出现呈现出一个隐藏的机械周期模式（周期跨度在 2 到 10 个批次之间，且一个周期内至少包含一个不合格批次和一个合格批次）。

你的目标是找出所有不合格（值为 1）的批次，并以严格升序列表的形式提交答案。你可以通过以下三种质检系统查询方式获取信息（每次只能进行一种查询）：

1. 点值查询：询问批次 i 是合格(0)还是不合格(1)。回答"0"或"1"。
2. 区间计数查询：询问从批次 a 到批次 b 之间共有多少个不合格批次。回答一个非负整数。
3. 子串等同性查询：询问从批次 a 开始连续 L 个批次的质量分布，与从批次 b 开始连续 L 个批次是否完全相同。回答"是"或"否"。

请尽可能少地使用查询次数来定位所有不良品的生产批次。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 点值查询（例如查询批次 5）：
<query_point>5</query_point>

- 区间计数查询（例如查询区间 [3, 7]）：
<query_range>3,7</query_range>

- 子串等同性查询（例如对比批次 2 和批次 5 开始的连续 3 个批次的质量情况）：
<query_substring>2,5,3</query_substring>

提交最终答案时，必须列出所有不合格批次的编号，按升序排列，用逗号分隔。如果全合格，则提交空列表。格式如下：

<answer>1,3,5,7</answer>

或（若全合格）：

<answer></answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
We are now conducting an "Automated Assembly Line Defect Troubleshooting" task.

The quality inspection system monitors {n} consecutive production batches (indexed from 1 to {n}). The quality status of each batch is either "defective" (value 1) or "qualified" (value 0). Due to periodic slight deviations in the mechanical transmission parts, the occurrence of defective batches exhibits a hidden mechanical periodic pattern. The period length spans between 2 and 10 batches, containing at least one defective batch and one qualified batch.

Your goal is to find all defective batches (value 1) and submit them as a strictly ascending list. You can query the inspection system in three ways (only one query per turn):

1. Point Query: Ask whether batch i is qualified (0) or defective (1). Answer "0" or "1".
2. Range Count Query: Ask how many defective batches are in the range [a, b]. Answer a non-negative integer.
3. Substring Equality Query: Ask whether the quality distribution of L consecutive batches starting at a is identical to that of L batches starting at b. Answer "Yes" or "No".

Please use as few queries as possible to locate all defective batches.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying batch 5):
<query_point>5</query_point>

- Range Count Query (e.g., querying range [3, 7]):
<query_range>3,7</query_range>

- Substring Equality Query (e.g., comparing 3 batches starting at 2 with 3 batches starting at 5):
<query_substring>2,5,3</query_substring>

When submitting the final answer, list all defective batch indices in ascending order, separated by commas. If all are qualified, submit an empty list. Use this format:

<answer>1,3,5,7</answer>

Or (if all qualified):

<answer></answer>
"""

    contextualized_rule_zh_5 = """\
我们现在来进行一项“商业合同合规漏洞排查”任务。

法务审查系统正在分析一份包含 {n} 个连续条款的商业合同（条款编号从 1 到 {n}）。每个条款的状态要么为“有漏洞”（值为 1），要么为“合规”（值为 0）。由于起草该合同时引用了带有缺陷的标准化条款库，漏洞的分布呈现出一种隐藏的周期性模式（周期长度在 2 到 10 个条款之间，且一个模板周期内至少包含一个漏洞条款和一个合规条款）。

你的目标是找出所有存在漏洞（值为 1）的条款编号，并以严格升序列表的形式提交答案。你可以通过以下三种审查辅助工具查询获取信息（每次只能进行一种查询）：

1. 点值查询：询问条款 i 是合规(0)还是有漏洞(1)。回答"0"或"1"。
2. 区间计数查询：询问从条款 a 到条款 b 的区间内共有多少个漏洞条款。回答一个非负整数。
3. 子串等同性查询：询问从条款 a 开始的连续 L 个条款的漏洞分布，与从条款 b 开始连续 L 个条款是否完全相同。回答"是"或"否"。

请尽可能少地使用查询次数来定位所有合规风险。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 点值查询（例如查询条款 5）：
<query_point>5</query_point>

- 区间计数查询（例如查询条款 3 到 7）：
<query_range>3,7</query_range>

- 子串等同性查询（例如对比条款 2 和条款 5 开始的连续 3 个条款的合规状态）：
<query_substring>2,5,3</query_substring>

提交最终答案时，必须列出所有存在漏洞的条款编号，按升序排列，用逗号分隔。如果完全合规，则提交空列表。格式如下：

<answer>1,3,5,7</answer>

或（若完全合规）：

<answer></answer>
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
We are now conducting a "Commercial Contract Compliance Risk Troubleshooting" task.

The legal review system is analyzing a commercial contract with {n} consecutive clauses (indexed from 1 to {n}). The compliance status of each clause is either "vulnerable" (value 1) or "compliant" (value 0). Because the contract was drafted using a flawed standardized clause library, the distribution of vulnerabilities exhibits a hidden periodic pattern. The period length is between 2 and 10 clauses, and a template cycle contains at least one vulnerable clause and one compliant clause.

Your goal is to find all vulnerable clauses (value 1) and submit them as a strictly ascending list. You can query the review assistant tool in three ways (only one query per turn):

1. Point Query: Ask whether clause i is compliant (0) or vulnerable (1). Answer "0" or "1".
2. Range Count Query: Ask how many vulnerable clauses exist in the range [a, b]. Answer a non-negative integer.
3. Substring Equality Query: Ask whether the vulnerability distribution of L consecutive clauses starting at a is identical to that of L clauses starting at b. Answer "Yes" or "No".

Please use as few queries as possible to locate all compliance risks.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying clause 5):
<query_point>5</query_point>

- Range Count Query (e.g., querying range [3, 7]):
<query_range>3,7</query_range>

- Substring Equality Query (e.g., comparing 3 clauses starting at 2 with 3 clauses starting at 5):
<query_substring>2,5,3</query_substring>

When submitting the final answer, list all vulnerable clause indices in ascending order, separated by commas. If perfectly compliant, submit an empty list. Use this format:

<answer>1,3,5,7</answer>

Or (if perfectly compliant):

<answer></answer>
"""

    tags = ["answer", "query_point", "query_range", "query_substring"]

    reasoning_type = "归纳推理"
    data_structure = "序列"

    DIFFICULTY_CONFIG = {
        1: {"n": 10, "period_range": (2, 3)},
        2: {"n": 15, "period_range": (3, 4)},
        3: {"n": 20, "period_range": (3, 5)},
        4: {"n": 25, "period_range": (4, 6)},
        5: {"n": 30, "period_range": (5, 8)},
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        diff = int(self.config.difficulty)
        if diff not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[diff]
        n = cfg["n"]
        self._game_info["n"] = n
        
        rng = _random.Random(getattr(self.config, 'seed', 42))
        lo, hi = cfg["period_range"]
        period = rng.randint(lo, hi)
        
        while True:
            pattern = [rng.randint(0, 1) for _ in range(period)]
            if 0 in pattern and 1 in pattern:
                break
        
        self.sequence = [pattern[(i - 1) % period] for i in range(1, n + 1)]
        
        self.ones_positions = {i for i in range(1, n + 1) if self.sequence[i - 1] == 1}

    def evaluate(self, parsed_info):
        raw_ans = parsed_info["answer"].strip()
        
        if raw_ans == "":
            model_positions = set()
        else:
            try:
                positions = [int(x.strip()) for x in raw_ans.split(",") if x.strip()]
                
                if positions != sorted(positions):
                    return False
                
                if len(positions) != len(set(positions)):
                    return False
                
                n = self._game_info["n"]
                for pos in positions:
                    if pos < 1 or pos > n:
                        return False
                
                model_positions = set(positions)
            except:
                return False
        
        return model_positions == self.ones_positions

    def _cf_core_produce(self, parsed_info):
        n = self._game_info["n"]
        
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
            error_format = "错误：格式无效。"
            error_range = "错误：位置越界。"
        else:
            yes_res, no_res = "Yes", "No"
            error_format = "Error: Invalid format."
            error_range = "Error: Position out of range."
        
        if "query_point" in parsed_info:
            try:
                i = int(parsed_info["query_point"].strip())
                if i < 1 or i > n:
                    return error_range
                return str(self.sequence[i - 1])
            except Exception:
                return error_format
        
        elif "query_range" in parsed_info:
            try:
                raw = parsed_info["query_range"].strip()
                parts = [x.strip() for x in raw.split(",")]
                if len(parts) != 2:
                    return error_format
                a, b = int(parts[0]), int(parts[1])
                if a < 1 or b > n or a > b:
                    return error_range
                
                count = sum(self.sequence[i - 1] for i in range(a, b + 1))
                return str(count)
            except Exception:
                return error_format
        
        elif "query_substring" in parsed_info:
            try:
                raw = parsed_info["query_substring"].strip()
                parts = [x.strip() for x in raw.split(",")]
                if len(parts) != 3:
                    return error_format
                a, b, L = int(parts[0]), int(parts[1]), int(parts[2])
                
                if L < 1:
                    return error_format
                if a < 1 or a + L - 1 > n or b < 1 or b + L - 1 > n:
                    return error_range
                
                substring_a = self.sequence[a - 1:a - 1 + L]
                substring_b = self.sequence[b - 1:b - 1 + L]
                
                return yes_res if substring_a == substring_b else no_res
            except Exception:
                return error_format
        
        else:
            raise ValueError("No valid query tag found.")

    def _cf_make_wrong(self, correct):
        if self.config.language == "zh":
            if correct == "是":
                return "否"
            if correct == "否":
                return "是"
        else:
            if correct.lower() == "yes":
                return "No"
            if correct.lower() == "no":
                return "Yes"
        
        if correct.isdigit():
            val = int(correct)
            if val == 0:
                return "1"
            elif val == 1:
                return "0"
            else:
                return str(val + 1)
        
        return correct + "_WRONG"

    def get_all_possible_queries(self) -> list[dict]:
        results = []
        n = self._game_info["n"]
        
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
        else:
            yes_res, no_res = "Yes", "No"
            
        for i in range(1, n + 1):
            ans = str(self.sequence[i - 1])
            results.append({
                "query": f"<query_point>{i}</query_point>",
                "answer": ans
            })
            
        for a in range(1, n + 1):
            for b in range(a, n + 1):
                count = sum(self.sequence[k] for k in range(a - 1, b))
                results.append({
                    "query": f"<query_range>{a},{b}</query_range>",
                    "answer": str(count)
                })
                
        max_L = min(n, 10)
        for L in range(1, max_L + 1):
            max_start = n - L + 1
            for a in range(1, max_start + 1):
                for b in range(a + 1, max_start + 1):
                    substring_a = self.sequence[a - 1 : a - 1 + L]
                    substring_b = self.sequence[b - 1 : b - 1 + L]
                    ans = yes_res if substring_a == substring_b else no_res
                    results.append({
                        "query": f"<query_substring>{a},{b},{L}</query_substring>",
                        "answer": ans
                    })
                    
        return results