# -*- coding: utf-8 -*-
# 自动生成 | 模型: api/claude-sonnet-4-5-20250929
# 推理类型: 溯因推理（明确有若干种可能性，模型需要判断那种是正确的）：面对当前的状态（反馈），推测原因。
# 数据结构: 图：存在一个由节点和边构成的图。
# 知识点:   路径总权重：某条给定路径的边权之和是多少
# ============================================================

from .base import Game
import re


class PathInferenceGame(Game):

    game_rule_zh = """\
我们来玩一个"路径推理"游戏，规则如下：

给定一个无向简单图，节点为 A, B, C, D, E, F。图中的每条边都有公开的整数权重和颜色（红或蓝）。

## 图结构（边的权重和颜色）

{edges_description}

## 路径定义

- **简单路径**：不允许重复访问节点的路径。
- 对于任意简单路径 p：
  - **真实里程 S(p)**：路径上所有边的权重之和。
  - **显示值 T(p)**：T(p) = S(p) + f(p)，其中 f(p) 是一个附加项（0 或 1），由某个未知的全局规则生成。

## 未知附加规则（四选一）

系统已秘密选定以下四种附加规则之一，并在整个游戏中保持一致：

1. **规则 α**：f(p) 恒等于 0
2. **规则 β**：f(p) = 蓝色边条数的奇偶性（奇数为 1，偶数为 0）
3. **规则 γ**：f(p) = 路径是否包含节点 D（包含为 1，不包含为 0）
4. **规则 δ**：f(p) = 颜色切换次数的奇偶性（奇数为 1，偶数为 0）
   - 颜色切换次数：按路径边的顺序，若相邻两条边颜色不同则计一次

## 你可以发起的查询

每次只能提出一个查询，使用以下格式：

1. **显示值查询**：询问某条简单路径的显示值 T(p)
   格式：<query_display>A-B-C</query_display>

2. **里程核对**：询问某条简单路径的真实里程 S(p)（可通过公开边权验证）
   格式：<query_mileage>A-B-C</query_mileage>

3. **特征统计**：询问某条简单路径的特征计数（如蓝边条数或颜色切换次数等）
   格式：<query_feature>A-B-C</query_feature>

## 游戏目标

1. 通过多次查询（特别是显示值查询），推断出系统采用的是哪一种附加规则（α、β、γ 或 δ）
2. 在确定规则后，计算并提交目标路径 **{target_path}** 的显示值 T

## 提交答案格式

当你确定了附加规则并计算出目标路径的显示值后，请使用以下格式提交：

<answer>rule=β, target_T=13</answer>

其中 rule 为 α、β、γ 或 δ 之一，target_T 为目标路径的显示值（整数）。

## 注意事项

- 所有显示值查询的反馈都基于同一个未知规则，保证一致性
- 查询的路径必须是合法的简单路径（节点不重复且边存在）
- 需要尽可能少的查询次数来推断规则
"""

    game_rule_en = """\
Let's play a "Path Inference" game with the following rules:

Given an undirected simple graph with nodes A, B, C, D, E, F. Each edge has a public integer weight and color (Red or Blue).

## Graph Structure (Edge Weights and Colors)

{edges_description}

## Path Definition

- **Simple Path**: A path that does not revisit any node.
- For any simple path p:
  - **True Mileage S(p)**: Sum of all edge weights on the path.
  - **Display Value T(p)**: T(p) = S(p) + f(p), where f(p) is an additional term (0 or 1) generated by an unknown global rule.

## Unknown Additional Rule (One of Four)

The system has secretly selected one of the following four additional rules and maintains it consistently throughout the game:

1. **Rule α**: f(p) is always 0
2. **Rule β**: f(p) = parity of blue edge count (odd is 1, even is 0)
3. **Rule γ**: f(p) = whether path contains node D (contains is 1, otherwise 0)
4. **Rule δ**: f(p) = parity of color switch count (odd is 1, even is 0)
   - Color switch count: Following the edge order in path, count each time adjacent edges have different colors

## Available Queries

You can make one query at a time using the following formats:

1. **Display Value Query**: Ask for the display value T(p) of a simple path
   Format: <query_display>A-B-C</query_display>

2. **Mileage Check**: Ask for the true mileage S(p) of a simple path (verifiable through public edge weights)
   Format: <query_mileage>A-B-C</query_mileage>

3. **Feature Statistics**: Ask for feature counts of a simple path (such as blue edge count or color switch count)
   Format: <query_feature>A-B-C</query_feature>

## Game Objective

1. Through multiple queries (especially display value queries), infer which additional rule (α, β, γ, or δ) the system is using
2. After determining the rule, calculate and submit the display value T for the target path **{target_path}**

## Answer Submission Format

When you have determined the additional rule and calculated the display value for the target path, submit using this format:

<answer>rule=β, target_T=13</answer>

Where rule is one of α, β, γ, or δ, and target_T is the display value for the target path (integer).

## Notes

- All display value query responses are based on the same unknown rule, ensuring consistency
- Queried paths must be valid simple paths (no repeated nodes and edges exist)
- Try to infer the rule with as few queries as possible
"""

    contextualized_rule_zh_1 = """\
这是交通物流规划系统的路径测算模块。
给定一个由物流节点 A, B, C, D, E, F 组成的运输网络。每条路线都有公开的基础耗时（分钟）和道路类型（红色代表城市道路，蓝色代表高速公路）。

## 网络结构（基础耗时与道路类型）

{edges_description}

## 路径定义

- **有效路线**：不重复经过任何节点的运输路线。
- 对于任意有效路线 p：
  - **理论耗时 S(p)**：路线上所有路段的基础耗时之和。
  - **实际耗时 T(p)**：T(p) = S(p) + f(p)，其中 f(p) 是一个由于特定路况引发的附加耗时（0 或 1 分钟），由一个未知的全局规则生成。

## 未知路况规则（四选一）

系统因实时路况秘密启用了以下四种规则之一，并在测算期间保持一致：

1. **规则 α**：f(p) 恒等于 0，路况极佳。
2. **规则 β**：f(p) = 高速路段（蓝色）数量的奇偶性（奇数为 1，偶数为 0）。
3. **规则 γ**：f(p) = 路线是否经过拥堵节点 D（经过为 1，不经过为 0）。
4. **规则 δ**：f(p) = 道路类型切换次数的奇偶性（奇数为 1，偶数为 0）。
   - 切换次数：按路段顺序，若相邻两段道路类型（颜色）不同则计一次。

## 你可以发起的查询

每次只能提出一个查询，使用以下格式：

1. **实际耗时查询**：询问某条路线的实际耗时 T(p)
   格式：<query_display>A-B-C</query_display>

2. **理论耗时核对**：询问某条路线的理论耗时 S(p)
   格式：<query_mileage>A-B-C</query_mileage>

3. **路况特征统计**：询问某条路线的特征（如蓝路数量或切换次数等）
   格式：<query_feature>A-B-C</query_feature>

## 系统目标

1. 通过多次查询，推断出系统当前采用的是哪一种路况规则（α、β、γ 或 δ）。
2. 在确定规则后，计算并提交目标路线 **{target_path}** 的实际耗时 T。

## 提交答案格式

格式如下：
<answer>rule=β, target_T=13</answer>
其中 rule 为 α、β、γ 或 δ 之一，target_T 为目标路线的实际耗时（整数）。
"""

    contextualized_rule_en_1 = """\
[Transportation Scenario]
This is the route calculation module of the logistics planning system.
Given a transport network consisting of logistics nodes A, B, C, D, E, and F. Each route has a public base travel time (minutes) and road type (Red for Local roads, Blue for Highways).

## Network Structure (Base Time & Road Type)

{edges_description}

## Path Definition

- **Valid Route**: A transport route that does not revisit any node.
- For any valid route p:
  - **Theoretical Time S(p)**: Sum of the base travel times of all segments on the route.
  - **Actual Time T(p)**: T(p) = S(p) + f(p), where f(p) is an additional delay (0 or 1 minute) caused by specific traffic conditions, generated by an unknown global rule.

## Unknown Traffic Rule (One of Four)

The system has secretly activated one of the following four rules due to real-time traffic, maintaining it consistently:

1. **Rule α**: f(p) is always 0, excellent traffic.
2. **Rule β**: f(p) = parity of Highway (Blue) segments count (odd is 1, even is 0).
3. **Rule γ**: f(p) = whether the route passes through congestion node D (passes is 1, otherwise 0).
4. **Rule δ**: f(p) = parity of road type switch count (odd is 1, even is 0).
   - Switch count: Following the route order, count each time adjacent segments have different road types (colors).

## Available Queries

You can make one query at a time using the following formats:

1. **Actual Time Query**: Ask for the actual time T(p) of a route
   Format: <query_display>A-B-C</query_display>

2. **Theoretical Time Check**: Ask for the theoretical time S(p) of a route
   Format: <query_mileage>A-B-C</query_mileage>

3. **Traffic Feature Stats**: Ask for feature counts of a route (e.g., Highway count or switch count)
   Format: <query_feature>A-B-C</query_feature>

## System Objective

1. Through multiple queries, infer which traffic rule (α, β, γ, or δ) the system is currently using.
2. After determining the rule, calculate and submit the actual time T for the target route **{target_path}**.

## Answer Submission Format

Format:
<answer>rule=β, target_T=13</answer>
Where rule is one of α, β, γ, or δ, and target_T is the actual time for the target route (integer).
"""

    contextualized_rule_zh_2 = """\
这是医院管理系统中的诊疗路径计费测算模块。
给定一个由医疗科室 A, B, C, D, E, F 组成的转诊网络。每项转诊操作都有公开的基础费用和科室类型（红色代表普通科室，蓝色代表特需科室）。

## 网络结构（基础费用与科室类型）

{edges_description}

## 路径定义

- **有效诊疗路径**：不重复经过任何科室的路径。
- 对于任意诊疗路径 p：
  - **基础账单 S(p)**：路径上所有转诊操作的基础费用之和。
  - **最终结算 T(p)**：T(p) = S(p) + f(p)，其中 f(p) 是系统附加的一项核算费用（0 或 1），由医保结算系统的未知规则生成。

## 未知核算规则（四选一）

医保系统后台固定了以下四种规则之一，在本次核算中保持一致：

1. **规则 α**：f(p) 恒等于 0，无附加费用。
2. **规则 β**：f(p) = 特需科室（蓝色）操作次数的奇偶性（奇数为 1，偶数为 0）。
3. **规则 γ**：f(p) = 路径是否包含重点监护科室 D（包含为 1，不包含为 0）。
4. **规则 δ**：f(p) = 科室类型切换次数的奇偶性（奇数为 1，偶数为 0）。
   - 切换次数：按转诊顺序，若相邻两次操作科室类型（颜色）不同则计一次。

## 你可以发起的查询

每次只能提出一个查询，使用以下格式：

1. **最终结算查询**：询问某条路径的最终结算 T(p)
   格式：<query_display>A-B-C</query_display>

2. **基础账单核对**：询问某条路径的基础账单 S(p)
   格式：<query_mileage>A-B-C</query_mileage>

3. **路径特征统计**：询问某条路径的特征计数（如特需科室次数或类型切换次数等）
   格式：<query_feature>A-B-C</query_feature>

## 系统目标

1. 通过多次查询，推断出医保系统采用的是哪一种核算规则（α、β、γ 或 δ）。
2. 在确定规则后，计算并提交目标诊疗路径 **{target_path}** 的最终结算 T。

## 提交答案格式

格式如下：
<answer>rule=β, target_T=13</answer>
其中 rule 为 α、β、γ 或 δ 之一，target_T 为目标路径的最终结算（整数）。
"""

    contextualized_rule_en_2 = """\
[Healthcare Scenario]
This is the billing calculation module for clinical pathways in the hospital management system.
Given a referral network consisting of medical departments A, B, C, D, E, and F. Each transfer procedure has a public base fee and department type (Red for General departments, Blue for Specialist departments).

## Network Structure (Base Fee & Department Type)

{edges_description}

## Path Definition

- **Valid Clinical Pathway**: A pathway that does not revisit any department.
- For any clinical pathway p:
  - **Base Bill S(p)**: Sum of the base fees of all transfer procedures on the pathway.
  - **Final Settlement T(p)**: T(p) = S(p) + f(p), where f(p) is an additional accounting surcharge (0 or 1) generated by an unknown rule in the medical insurance system.

## Unknown Accounting Rule (One of Four)

The insurance background system has fixed one of the following four rules, maintaining it consistently during this calculation:

1. **Rule α**: f(p) is always 0, no surcharge.
2. **Rule β**: f(p) = parity of Specialist (Blue) procedures count (odd is 1, even is 0).
3. **Rule γ**: f(p) = whether the pathway includes intensive care department D (includes is 1, otherwise 0).
4. **Rule δ**: f(p) = parity of department type switch count (odd is 1, even is 0).
   - Switch count: Following the transfer order, count each time adjacent procedures have different department types (colors).

## Available Queries

You can make one query at a time using the following formats:

1. **Final Settlement Query**: Ask for the final settlement T(p) of a pathway
   Format: <query_display>A-B-C</query_display>

2. **Base Bill Check**: Ask for the base bill S(p) of a pathway
   Format: <query_mileage>A-B-C</query_mileage>

3. **Pathway Feature Stats**: Ask for feature counts of a pathway (e.g., Specialist count or switch count)
   Format: <query_feature>A-B-C</query_feature>

## System Objective

1. Through multiple queries, infer which accounting rule (α, β, γ, or δ) the insurance system is using.
2. After determining the rule, calculate and submit the final settlement T for the target pathway **{target_path}**.

## Answer Submission Format

Format:
<answer>rule=β, target_T=13</answer>
Where rule is one of α, β, γ, or δ, and target_T is the final settlement for the target pathway (integer).
"""

    contextualized_rule_zh_3 = """\
这是智能教育平台的学习路径评估模块。
给定一个由知识模块 A, B, C, D, E, F 组成的学习网络。模块间的学习环节都有公开的基础学时和课程属性（红色代表理论课，蓝色代表实践课）。

## 网络结构（基础学时与课程属性）

{edges_description}

## 路径定义

- **有效学习路径**：不重复学习任何模块的路径。
- 对于任意学习路径 p：
  - **基础学时 S(p)**：路径上所有学习环节的基础学时之和。
  - **认证学时 T(p)**：T(p) = S(p) + f(p)，其中 f(p) 是一项综合评定附加学时（0 或 1），由教务系统的未知规则生成。

## 未知评定规则（四选一）

系统设定了以下四种评定规则之一，且对所有学生保持一致：

1. **规则 α**：f(p) 恒等于 0，无需附加学时。
2. **规则 β**：f(p) = 实践课（蓝色）环节数的奇偶性（奇数为 1，偶数为 0）。
3. **规则 γ**：f(p) = 路径是否包含核心考核模块 D（包含为 1，不包含为 0）。
4. **规则 δ**：f(p) = 课程属性切换次数的奇偶性（奇数为 1，偶数为 0）。
   - 切换次数：按学习顺序，若相邻两个环节属性（颜色）不同则计一次。

## 你可以发起的查询

每次只能提出一个查询，使用以下格式：

1. **认证学时查询**：询问某条路径的认证学时 T(p)
   格式：<query_display>A-B-C</query_display>

2. **基础学时核对**：询问某条路径的基础学时 S(p)
   格式：<query_mileage>A-B-C</query_mileage>

3. **课程特征统计**：询问某条路径的特征计数（如实践课环节数或属性切换次数等）
   格式：<query_feature>A-B-C</query_feature>

## 系统目标

1. 通过多次查询，推断出教务系统当前采用的是哪一种评定规则（α、β、γ 或 δ）。
2. 在确定规则后，计算并提交目标学习路径 **{target_path}** 的认证学时 T。

## 提交答案格式

格式如下：
<answer>rule=β, target_T=13</answer>
其中 rule 为 α、β、γ 或 δ 之一，target_T 为目标路径的认证学时（整数）。
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
This is the learning path evaluation module of the smart education platform.
Given a learning network consisting of knowledge modules A, B, C, D, E, and F. The study links between modules have public base study hours and course attributes (Red for Theoretical courses, Blue for Practical courses).

## Network Structure (Base Hours & Course Attributes)

{edges_description}

## Path Definition

- **Valid Learning Path**: A learning path that does not revisit any module.
- For any learning path p:
  - **Base Hours S(p)**: Sum of the base study hours of all links on the path.
  - **Certified Hours T(p)**: T(p) = S(p) + f(p), where f(p) is an additional assessment hour (0 or 1) generated by an unknown rule of the academic system.

## Unknown Assessment Rule (One of Four)

The system has set one of the following four rules, maintaining it consistently for all students:

1. **Rule α**: f(p) is always 0, no extra hours.
2. **Rule β**: f(p) = parity of Practical (Blue) links count (odd is 1, even is 0).
3. **Rule γ**: f(p) = whether the path includes the core exam module D (includes is 1, otherwise 0).
4. **Rule δ**: f(p) = parity of course attribute switch count (odd is 1, even is 0).
   - Switch count: Following the study order, count each time adjacent links have different attributes (colors).

## Available Queries

You can make one query at a time using the following formats:

1. **Certified Hours Query**: Ask for the certified hours T(p) of a learning path
   Format: <query_display>A-B-C</query_display>

2. **Base Hours Check**: Ask for the base hours S(p) of a learning path
   Format: <query_mileage>A-B-C</query_mileage>

3. **Course Feature Stats**: Ask for feature counts of a learning path (e.g., Practical links count or switch count)
   Format: <query_feature>A-B-C</query_feature>

## System Objective

1. Through multiple queries, infer which assessment rule (α, β, γ, or δ) the academic system is currently using.
2. After determining the rule, calculate and submit the certified hours T for the target learning path **{target_path}**.

## Answer Submission Format

Format:
<answer>rule=β, target_T=13</answer>
Where rule is one of α, β, γ, or δ, and target_T is the certified hours for the target path (integer).
"""

    contextualized_rule_zh_4 = """\
这是工业制造中心的流水线能耗监测模块。
给定一个由加工工位 A, B, C, D, E, F 组成的生产网络。工位间的传送带都有公开的基础能耗和运行模式（红色代表常速传送，蓝色代表高速传送）。

## 网络结构（基础能耗与运行模式）

{edges_description}

## 路径定义

- **有效生产线**：不重复经过任何工位的流水线路径。
- 对于任意生产线 p：
  - **理论能耗 S(p)**：流水线上所有传送带的基础能耗之和。
  - **实际能耗 T(p)**：T(p) = S(p) + f(p)，其中 f(p) 是一项动态热损耗（0 或 1），由车间环境的未知规则决定。

## 未知热损耗规则（四选一）

车间当前生效了以下四种损耗规则之一，并保持全局一致：

1. **规则 α**：f(p) 恒等于 0，无动态热损耗。
2. **规则 β**：f(p) = 高速传送（蓝色）带数量的奇偶性（奇数为 1，偶数为 0）。
3. **规则 γ**：f(p) = 生产线是否途经高功率工位 D（途经为 1，不途经为 0）。
4. **规则 δ**：f(p) = 运行模式切换次数的奇偶性（奇数为 1，偶数为 0）。
   - 切换次数：按传送顺序，若相邻两条传送带运行模式（颜色）不同则计一次。

## 你可以发起的查询

每次只能提出一个查询，使用以下格式：

1. **实际能耗查询**：询问某条生产线的实际能耗 T(p)
   格式：<query_display>A-B-C</query_display>

2. **理论能耗核对**：询问某条生产线的理论能耗 S(p)
   格式：<query_mileage>A-B-C</query_mileage>

3. **流水线特征统计**：询问某条生产线的特征计数（如高速带数量或模式切换次数等）
   格式：<query_feature>A-B-C</query_feature>

## 系统目标

1. 通过多次查询，推断出车间采用的是哪一种热损耗规则（α、β、γ 或 δ）。
2. 在确定规则后，计算并提交目标生产线 **{target_path}** 的实际能耗 T。

## 提交答案格式

格式如下：
<answer>rule=β, target_T=13</answer>
其中 rule 为 α、β、γ 或 δ 之一，target_T 为目标生产线的实际能耗（整数）。
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
This is the assembly line energy monitoring module of the industrial manufacturing center.
Given a production network consisting of workstations A, B, C, D, E, and F. The conveyor belts between workstations have public base energy consumption and operating modes (Red for Standard speed, Blue for High-speed).

## Network Structure (Base Energy & Operating Mode)

{edges_description}

## Path Definition

- **Valid Production Line**: An assembly line path that does not revisit any workstation.
- For any production line p:
  - **Theoretical Energy S(p)**: Sum of the base energy consumption of all conveyor belts on the line.
  - **Actual Energy T(p)**: T(p) = S(p) + f(p), where f(p) is a dynamic heat loss (0 or 1) determined by an unknown rule of the workshop environment.

## Unknown Heat Loss Rule (One of Four)

The workshop has activated one of the following four loss rules, maintaining it globally consistent:

1. **Rule α**: f(p) is always 0, no dynamic heat loss.
2. **Rule β**: f(p) = parity of High-speed (Blue) belts count (odd is 1, even is 0).
3. **Rule γ**: f(p) = whether the line passes through high-power workstation D (passes is 1, otherwise 0).
4. **Rule δ**: f(p) = parity of operating mode switch count (odd is 1, even is 0).
   - Switch count: Following the conveyor order, count each time adjacent belts have different operating modes (colors).

## Available Queries

You can make one query at a time using the following formats:

1. **Actual Energy Query**: Ask for the actual energy T(p) of a production line
   Format: <query_display>A-B-C</query_display>

2. **Theoretical Energy Check**: Ask for the theoretical energy S(p) of a production line
   Format: <query_mileage>A-B-C</query_mileage>

3. **Line Feature Stats**: Ask for feature counts of a line (e.g., High-speed belt count or switch count)
   Format: <query_feature>A-B-C</query_feature>

## System Objective

1. Through multiple queries, infer which heat loss rule (α, β, γ, or δ) the workshop is using.
2. After determining the rule, calculate and submit the actual energy T for the target production line **{target_path}**.

## Answer Submission Format

Format:
<answer>rule=β, target_T=13</answer>
Where rule is one of α, β, γ, or δ, and target_T is the actual energy for the target line (integer).
"""

    contextualized_rule_zh_5 = """\
这是司法案件流转系统的程序时效测算模块。
给定一个由司法审查阶段 A, B, C, D, E, F 组成的流转图。阶段间的程序交接均有公开的法定基础办理天数和程序类型（红色代表普通程序，蓝色代表优先程序）。

## 流转图结构（基础办理天数与程序类型）

{edges_description}

## 路径定义

- **有效流转路径**：不重复经历任何审查阶段的流转过程。
- 对于任意流转路径 p：
  - **法定基准时效 S(p)**：路径上所有程序交接的基础办理天数之和。
  - **实际办理时效 T(p)**：T(p) = S(p) + f(p)，其中 f(p) 是由于特定司法管辖权引起的程序阻滞天数（0 或 1），由内部规则生成。

## 未知阻滞规则（四选一）

系统内部遵循以下四种阻滞规则之一，对当前所有案件保持一致：

1. **规则 α**：f(p) 恒等于 0，无阻滞天数。
2. **规则 β**：f(p) = 优先程序（蓝色）交接次数的奇偶性（奇数为 1，偶数为 0）。
3. **规则 γ**：f(p) = 流转是否经过合议庭审查阶段 D（经过为 1，不经过为 0）。
4. **规则 δ**：f(p) = 程序类型切换次数的奇偶性（奇数为 1，偶数为 0）。
   - 切换次数：按交接顺序，若相邻两次交接的程序类型（颜色）不同则计一次。

## 你可以发起的查询

每次只能提出一个查询，使用以下格式：

1. **实际办理时效查询**：询问某条路径的实际办理时效 T(p)
   格式：<query_display>A-B-C</query_display>

2. **法定基准核对**：询问某条路径的法定基准时效 S(p)
   格式：<query_mileage>A-B-C</query_mileage>

3. **程序特征统计**：询问某条路径的特征计数（如优先程序次数或切换次数等）
   格式：<query_feature>A-B-C</query_feature>

## 系统目标

1. 通过多次查询，推断出系统采用的是哪一种阻滞规则（α、β、γ 或 δ）。
2. 在确定规则后，计算并提交目标流转路径 **{target_path}** 的实际办理时效 T。

## 提交答案格式

格式如下：
<answer>rule=β, target_T=13</answer>
其中 rule 为 α、β、γ 或 δ 之一，target_T 为目标路径的实际办理时效（整数）。
"""

    contextualized_rule_en_5 = """\
[Law Scenario]
This is the procedural timeline calculation module for the judicial case flow system.
Given a flow graph consisting of judicial review phases A, B, C, D, E, and F. The procedural transitions between phases have public statutory base days and procedure types (Red for Standard procedure, Blue for Priority procedure).

## Flow Graph Structure (Base Days & Procedure Type)

{edges_description}

## Path Definition

- **Valid Flow Path**: A case flow path that does not revisit any review phase.
- For any flow path p:
  - **Statutory Base Timeline S(p)**: Sum of the base processing days of all transitions on the path.
  - **Actual Processing Timeline T(p)**: T(p) = S(p) + f(p), where f(p) is an administrative hold (0 or 1 day) caused by specific jurisdiction rules.

## Unknown Hold Rule (One of Four)

The internal system follows one of the following four hold rules, maintaining it consistently for all current cases:

1. **Rule α**: f(p) is always 0, no hold days.
2. **Rule β**: f(p) = parity of Priority (Blue) transitions count (odd is 1, even is 0).
3. **Rule γ**: f(p) = whether the flow involves the collegiate bench review phase D (involves is 1, otherwise 0).
4. **Rule δ**: f(p) = parity of procedure type switch count (odd is 1, even is 0).
   - Switch count: Following the transition order, count each time adjacent transitions have different procedure types (colors).

## Available Queries

You can make one query at a time using the following formats:

1. **Actual Timeline Query**: Ask for the actual processing timeline T(p) of a path
   Format: <query_display>A-B-C</query_display>

2. **Statutory Base Check**: Ask for the statutory base timeline S(p) of a path
   Format: <query_mileage>A-B-C</query_mileage>

3. **Procedure Feature Stats**: Ask for feature counts of a path (e.g., Priority transitions count or switch count)
   Format: <query_feature>A-B-C</query_feature>

## System Objective

1. Through multiple queries, infer which hold rule (α, β, γ, or δ) the system is currently using.
2. After determining the rule, calculate and submit the actual processing timeline T for the target flow path **{target_path}**.

## Answer Submission Format

Format:
<answer>rule=β, target_T=13</answer>
Where rule is one of α, β, γ, or δ, and target_T is the actual processing timeline for the target path (integer).
"""

    tags = ["answer", "query_display", "query_mileage", "query_feature"]
    
    reasoning_type = "溯因推理"
    data_structure = "图"
    enable_counterfactual = False   # 设为 True 时开启反事实干预模式

    # 难度配置：
    # 1 (简单)       - 规则 α，目标路径 A-B-C
    # 2 (中等偏下)   - 规则 γ，目标路径 A-C-D
    # 3 (中等偏上)   - 规则 β，目标路径 A-B-D-F
    # 4 (较难)       - 规则 δ，目标路径 A-C-E-F
    # 5 (难)         - 规则 β，目标路径 A-B-D-F（与题目描述一致）

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "rule": "α",
                "target_path": "A-B-C",
                "edges_desc": "- A-B: 权重 4，蓝色\n- A-C: 权重 3，红色\n- A-D: 权重 5，蓝色\n- B-C: 权重 2，蓝色\n- B-D: 权重 6，红色\n- B-E: 权重 1，红色\n- C-D: 权重 4，红色\n- C-E: 权重 7，蓝色\n- D-E: 权重 3，蓝色\n- D-F: 权重 2，红色\n- E-F: 权重 5，红色",
            },
            2: {
                "rule": "γ",
                "target_path": "A-C-D",
                "edges_desc": "- A-B: 权重 4，蓝色\n- A-C: 权重 3，红色\n- A-D: 权重 5，蓝色\n- B-C: 权重 2，蓝色\n- B-D: 权重 6，红色\n- B-E: 权重 1，红色\n- C-D: 权重 4，红色\n- C-E: 权重 7，蓝色\n- D-E: 权重 3，蓝色\n- D-F: 权重 2，红色\n- E-F: 权重 5，红色",
            },
            3: {
                "rule": "β",
                "target_path": "A-B-D-F",
                "edges_desc": "- A-B: 权重 4，蓝色\n- A-C: 权重 3，红色\n- A-D: 权重 5，蓝色\n- B-C: 权重 2，蓝色\n- B-D: 权重 6，红色\n- B-E: 权重 1，红色\n- C-D: 权重 4，红色\n- C-E: 权重 7，蓝色\n- D-E: 权重 3，蓝色\n- D-F: 权重 2，红色\n- E-F: 权重 5，红色",
            },
            4: {
                "rule": "δ",
                "target_path": "A-C-E-F",
                "edges_desc": "- A-B: 权重 4，蓝色\n- A-C: 权重 3，红色\n- A-D: 权重 5，蓝色\n- B-C: 权重 2，蓝色\n- B-D: 权重 6，红色\n- B-E: 权重 1，红色\n- C-D: 权重 4，红色\n- C-E: 权重 7，蓝色\n- D-E: 权重 3，蓝色\n- D-F: 权重 2，红色\n- E-F: 权重 5，红色",
            },
            5: {
                "rule": "δ",
                "target_path": "A-B-E-D-F",
                "edges_desc": "- A-B: 权重 4，蓝色\n- A-C: 权重 3，红色\n- A-D: 权重 5，蓝色\n- B-C: 权重 2，蓝色\n- B-D: 权重 6，红色\n- B-E: 权重 1，红色\n- C-D: 权重 4，红色\n- C-E: 权重 7，蓝色\n- D-E: 权重 3，蓝色\n- D-F: 权重 2，红色\n- E-F: 权重 5，红色",
            },
        },
        "en": {
            1: {
                "rule": "α",
                "target_path": "A-B-C",
                "edges_desc": "- A-B: weight 4, Blue\n- A-C: weight 3, Red\n- A-D: weight 5, Blue\n- B-C: weight 2, Blue\n- B-D: weight 6, Red\n- B-E: weight 1, Red\n- C-D: weight 4, Red\n- C-E: weight 7, Blue\n- D-E: weight 3, Blue\n- D-F: weight 2, Red\n- E-F: weight 5, Red",
            },
            2: {
                "rule": "γ",
                "target_path": "A-C-D",
                "edges_desc": "- A-B: weight 4, Blue\n- A-C: weight 3, Red\n- A-D: weight 5, Blue\n- B-C: weight 2, Blue\n- B-D: weight 6, Red\n- B-E: weight 1, Red\n- C-D: weight 4, Red\n- C-E: weight 7, Blue\n- D-E: weight 3, Blue\n- D-F: weight 2, Red\n- E-F: weight 5, Red",
            },
            3: {
                "rule": "β",
                "target_path": "A-B-D-F",
                "edges_desc": "- A-B: weight 4, Blue\n- A-C: weight 3, Red\n- A-D: weight 5, Blue\n- B-C: weight 2, Blue\n- B-D: weight 6, Red\n- B-E: weight 1, Red\n- C-D: weight 4, Red\n- C-E: weight 7, Blue\n- D-E: weight 3, Blue\n- D-F: weight 2, Red\n- E-F: weight 5, Red",
            },
            4: {
                "rule": "δ",
                "target_path": "A-C-E-F",
                "edges_desc": "- A-B: weight 4, Blue\n- A-C: weight 3, Red\n- A-D: weight 5, Blue\n- B-C: weight 2, Blue\n- B-D: weight 6, Red\n- B-E: weight 1, Red\n- C-D: weight 4, Red\n- C-E: weight 7, Blue\n- D-E: weight 3, Blue\n- D-F: weight 2, Red\n- E-F: weight 5, Red",
            },
            5: {
                "rule": "δ",
                "target_path": "A-B-E-D-F",
                "edges_desc": "- A-B: weight 4, Blue\n- A-C: weight 3, Red\n- A-D: weight 5, Blue\n- B-C: weight 2, Blue\n- B-D: weight 6, Red\n- B-E: weight 1, Red\n- C-D: weight 4, Red\n- C-E: weight 7, Blue\n- D-E: weight 3, Blue\n- D-F: weight 2, Red\n- E-F: weight 5, Red",
            },
        },
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = int(self.config.difficulty)

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        
        # 图的边定义（权重和颜色）
        # 格式: (node1, node2): (weight, color)
        self.edges = {
            ("A", "B"): (4, "Blue" if lang == "en" else "蓝色"),
            ("A", "C"): (3, "Red" if lang == "en" else "红色"),
            ("A", "D"): (5, "Blue" if lang == "en" else "蓝色"),
            ("B", "C"): (2, "Blue" if lang == "en" else "蓝色"),
            ("B", "D"): (6, "Red" if lang == "en" else "红色"),
            ("B", "E"): (1, "Red" if lang == "en" else "红色"),
            ("C", "D"): (4, "Red" if lang == "en" else "红色"),
            ("C", "E"): (7, "Blue" if lang == "en" else "蓝色"),
            ("D", "E"): (3, "Blue" if lang == "en" else "蓝色"),
            ("D", "F"): (2, "Red" if lang == "en" else "红色"),
            ("E", "F"): (5, "Red" if lang == "en" else "红色"),
        }
        
        # 添加反向边（无向图）
        edges_copy = dict(self.edges)
        for (u, v), (w, c) in edges_copy.items():
            self.edges[(v, u)] = (w, c)
        
        self.rule = cfg["rule"]
        self.target_path = cfg["target_path"]
        self._game_info["target_path"] = self.target_path
        self._game_info["edges_description"] = cfg["edges_desc"]
        
        # 计算目标路径的正确答案
        target_nodes = self.target_path.split("-")
        target_mileage = self._calculate_mileage(target_nodes)
        target_f = self._calculate_f(target_nodes)
        self.target_answer = target_mileage + target_f
        
        # 用于跟踪显示值查询次数
        self.display_query_count = 0

    def _validate_path(self, nodes):
        """验证路径是否合法（节点不重复且边存在）"""
        # 检查节点是否重复
        if len(nodes) != len(set(nodes)):
            return False
        
        # 检查所有边是否存在
        for i in range(len(nodes) - 1):
            if (nodes[i], nodes[i+1]) not in self.edges:
                return False
        
        return True

    def _calculate_mileage(self, nodes):
        """计算路径的真实里程 S(p)"""
        mileage = 0
        for i in range(len(nodes) - 1):
            weight, _ = self.edges[(nodes[i], nodes[i+1])]
            mileage += weight
        return mileage

    def _calculate_f(self, nodes):
        """根据当前规则计算附加项 f(p)"""
        if self.rule == "α":
            return 0
        elif self.rule == "β":
            # 蓝色边条数的奇偶性
            blue_count = 0
            blue_keywords = ["Blue", "蓝色"]
            for i in range(len(nodes) - 1):
                _, color = self.edges[(nodes[i], nodes[i+1])]
                if color in blue_keywords:
                    blue_count += 1
            return blue_count % 2
        elif self.rule == "γ":
            # 是否包含节点 D
            return 1 if "D" in nodes else 0
        elif self.rule == "δ":
            # 颜色切换次数的奇偶性
            switch_count = 0
            for i in range(len(nodes) - 2):
                _, color1 = self.edges[(nodes[i], nodes[i+1])]
                _, color2 = self.edges[(nodes[i+1], nodes[i+2])]
                if color1 != color2:
                    switch_count += 1
            return switch_count % 2
        else:
            raise ValueError(f"Unknown rule: {self.rule}")

    def _calculate_display_value(self, nodes):
        """计算路径的显示值 T(p) = S(p) + f(p)"""
        mileage = self._calculate_mileage(nodes)
        f_value = self._calculate_f(nodes)
        return mileage + f_value

    def _get_path_features(self, nodes):
        """获取路径的各种特征统计"""
        blue_keywords = ["Blue", "蓝色"]
        
        # 蓝色边条数
        blue_count = 0
        for i in range(len(nodes) - 1):
            _, color = self.edges[(nodes[i], nodes[i+1])]
            if color in blue_keywords:
                blue_count += 1
        
        # 红色边条数
        red_count = len(nodes) - 1 - blue_count
        
        # 颜色切换次数
        switch_count = 0
        for i in range(len(nodes) - 2):
            _, color1 = self.edges[(nodes[i], nodes[i+1])]
            _, color2 = self.edges[(nodes[i+1], nodes[i+2])]
            if color1 != color2:
                switch_count += 1
        
        # 是否包含节点 D
        contains_d = 1 if "D" in nodes else 0
        
        if self.config.language == "zh":
            return f"蓝色边条数: {blue_count}, 红色边条数: {red_count}, 颜色切换次数: {switch_count}, 包含节点D: {'是' if contains_d else '否'}"
        else:
            return f"Blue edges: {blue_count}, Red edges: {red_count}, Color switches: {switch_count}, Contains node D: {'Yes' if contains_d else 'No'}"

    def evaluate(self, parsed_info):
        """评估最终答案是否正确"""
        # 解析答案: rule=X, target_T=Y
        raw_ans = parsed_info["answer"]
        
        # 提取 rule 和 target_T
        rule_match = re.search(r'rule\s*[=＝]\s*([αβγδ])', raw_ans, re.IGNORECASE)
        target_match = re.search(r'target_T\s*[=＝]\s*(\d+)', raw_ans, re.IGNORECASE)
        
        if not rule_match or not target_match:
            return False
        
        model_rule = rule_match.group(1)
        try:
            model_target = int(target_match.group(1))
        except:
            return False
        
        # 检查规则和目标值是否都正确
        return model_rule == self.rule and model_target == self.target_answer

    def get_all_possible_queries(self) -> list[dict]:
        """
        枚举所有合法查询并返回对应的正确答案。

        Returns:
            list of dict, 每项格式：
            {
                "query" : str,   # 查询内容字符串，与游戏中 parsed_info["query"] 的值格式一致
                "answer": str,   # 调用游戏逻辑后得到的正确答案字符串
            }
        """
        # 提取图的所有节点
        all_nodes = set()
        for u, v in self.edges.keys():
            all_nodes.add(u)
            all_nodes.add(v)
        sorted_nodes = sorted(list(all_nodes))
        
        # 搜索所有简单路径 (DFS)
        all_paths = []

        def dfs(current_path):
            # 记录当前路径
            # 我们只关心至少有一条边的路径（长度>=2），这样的查询才有意义
            if len(current_path) >= 2:
                all_paths.append(current_path[:])
            
            last_node = current_path[-1]
            # 遍历邻居
            for neighbor in sorted_nodes:
                if neighbor in current_path:
                    continue
                # 检查是否存在边
                if (last_node, neighbor) in self.edges:
                    dfs(current_path + [neighbor])

        for node in sorted_nodes:
            dfs([node])

        queries = []
        for nodes in all_paths:
            path_str = "-".join(nodes)
            
            # 1. 构造 query_display
            display_val = self._calculate_display_value(nodes)
            queries.append({
                "query": f"<query_display>{path_str}</query_display>",
                "answer": str(display_val)
            })
            
            # 2. 构造 query_mileage
            mileage_val = self._calculate_mileage(nodes)
            queries.append({
                "query": f"<query_mileage>{path_str}</query_mileage>",
                "answer": str(mileage_val)
            })
            
            # 3. 构造 query_feature
            feature_val = self._get_path_features(nodes)
            queries.append({
                "query": f"<query_feature>{path_str}</query_feature>",
                "answer": str(feature_val)
            })
            
        return queries

    def _cf_core_produce(self, parsed_info):
        """原始业务逻辑"""
        # 优先级：display > mileage > feature
        
        if "query_display" in parsed_info:
            # 显示值查询
            path_str = parsed_info["query_display"].strip()
            nodes = [n.strip() for n in path_str.split("-")]
            
            if not self._validate_path(nodes):
                return "错误：无效的路径（节点重复或边不存在）。" if self.config.language == "zh" else "Error: Invalid path (repeated nodes or non-existent edges)."
            
            self.display_query_count += 1
            display_value = self._calculate_display_value(nodes)
            return str(display_value)
        
        elif "query_mileage" in parsed_info:
            # 里程核对查询
            path_str = parsed_info["query_mileage"].strip()
            nodes = [n.strip() for n in path_str.split("-")]
            
            if not self._validate_path(nodes):
                return "错误：无效的路径（节点重复或边不存在）。" if self.config.language == "zh" else "Error: Invalid path (repeated nodes or non-existent edges)."
            
            mileage = self._calculate_mileage(nodes)
            return str(mileage)
        
        elif "query_feature" in parsed_info:
            # 特征统计查询
            path_str = parsed_info["query_feature"].strip()
            nodes = [n.strip() for n in path_str.split("-")]
            
            if not self._validate_path(nodes):
                return "错误：无效的路径（节点重复或边不存在）。" if self.config.language == "zh" else "Error: Invalid path (repeated nodes or non-existent edges)."
            
            features = self._get_path_features(nodes)
            return features
        
        else:
            raise ValueError("No valid query tag found.")

    def _cf_make_wrong(self, correct):
        """生成错误答案"""
        # 若 correct 是纯整数字符串（可能含负号）
        try:
            val = int(correct)
            return str(val + 1)
        except ValueError:
            pass
        
        # 否则按语言替换关键词（使用单词边界避免误替换）
        if self.config.language == "zh":
            if "是" in correct:
                return correct.replace("是", "否", 1)
            elif "否" in correct:
                return correct.replace("否", "是", 1)
        else:
            # 英文使用单词边界 \b 避免误替换如 "node" 中的 "no"
            if re.search(r'\bYes\b', correct, re.IGNORECASE):
                return re.sub(r'\bYes\b', 'No', correct, count=1, flags=re.IGNORECASE)
            elif re.search(r'\bNo\b', correct, re.IGNORECASE):
                return re.sub(r'\bNo\b', 'Yes', correct, count=1, flags=re.IGNORECASE)
        
        # 若都不匹配
        return correct + "_WRONG"