# -*- coding: utf-8 -*-
# 自动生成 | 模型: api/gpt-5-2025-08-07
# 推理类型: 归纳推理（完全自主总结规律）：从多次反馈的样本中，总结出背后隐藏的规律/模式。例如猜拳游戏，模型需要总结对手出拳的模式。
# 数据结构: 序列：存在一个长度为N的有序序列。
# 知识点:   子串匹配：某模式串是否作为连续子串出现在序列中
# ============================================================

from .base import Game
import random
import itertools


class SequencePatternGame(Game):

    game_rule_zh = """\
我们来玩一个"序列模式推理"游戏，规则如下：

游戏设定了一个固定但未知的序列 S，由字母 A、B、C、D 组成，长度在 30 到 60 之间。这个序列具有特殊的结构：它可以由某个最短的"基块" B 通过重复生成，即 S 由 B 重复若干次，再加上 B 的一个前缀（可能为空）拼接而成。

例如：若基块 B = "ABC"，则 S 可能是 "ABCABCAB"（B 重复 2 次 + 前缀"AB"）。

你的目标是通过查询推断出这个序列的结构。你可以反复向我提出以下三类查询（每次仅限一个查询），我会如实回答：

1. 存在查询：询问某个模式串 P 是否作为连续子串出现在 S 中。回答"是"或"否"。
2. 次数查询：询问某个模式串 P 在 S 中出现的次数（允许重叠计数）。回答一个非负整数。
3. 位置查询：询问某个模式串 P 在 S 中最左出现的位置（从 1 开始计数），若不存在则返回 0。回答一个非负整数。

注意：
- 模式串 P 必须由字母 A、B、C、D 组成，长度至少为 1。
- 所有查询的答案都基于同一个固定的序列 S。

当你收集足够信息后，可以提交最终答案。你可以选择以下两种提交方式之一：
1. 提交最短基块 B。
2. 提交完整序列 S。

若答案错误或格式不符，游戏失败。请尽可能用较少的查询次数完成推理。

## 查询与提交答案的格式（必须严格遵守）

每次查询只能包含一个标签。请使用以下 XML 格式：

- 存在查询（例如询问模式"AB"）：
<query_exists>AB</query_exists>

- 次数查询（例如询问模式"ABC"）：
<query_count>ABC</query_count>

- 位置查询（例如询问模式"ABCD"）：
<query_position>ABCD</query_position>

提交最终答案时，请使用以下格式之一：

- 提交最短基块（例如基块为"ABC"）：
<answer>block=ABC</answer>

- 提交完整序列（例如序列为"ABCABC"）：
<answer>sequence=ABCABC</answer>
"""

    game_rule_en = """\
Let's play a "Sequence Pattern Inference" game. Here are the rules:

There is a fixed but unknown sequence S, composed of letters A, B, C, D, with length between 30 and 60. This sequence has a special structure: it can be generated by repeating a shortest "block" B, i.e., S consists of B repeated several times, followed by a prefix of B (possibly empty).

For example: if block B = "ABC", then S might be "ABCABCAB" (B repeated 2 times + prefix "AB").

Your goal is to infer the structure of this sequence through queries. You can repeatedly ask me three types of queries (one per turn), and I will answer truthfully:

1. Existence Query: Ask if a pattern string P appears as a contiguous substring in S. Answer "Yes" or "No".
2. Count Query: Ask how many times a pattern string P appears in S (overlapping occurrences counted). Answer a non-negative integer.
3. Position Query: Ask the leftmost position where pattern string P appears in S (1-indexed), or 0 if not found. Answer a non-negative integer.

Note:
- Pattern string P must be composed of letters A, B, C, D, with length at least 1.
- All query answers are based on the same fixed sequence S.

When you have enough information, submit your final answer. You can choose one of two submission methods:
1. Submit the shortest block B.
2. Submit the complete sequence S.

If the answer is wrong or the format is invalid, the game fails. Try to complete the inference with as few queries as possible.

## Query and Answer Format (strictly required)

Each query must contain only one tag. Use the following XML format:

- Existence Query (e.g., asking about pattern "AB"):
<query_exists>AB</query_exists>

- Count Query (e.g., asking about pattern "ABC"):
<query_count>ABC</query_count>

- Position Query (e.g., asking about pattern "ABCD"):
<query_position>ABCD</query_position>

When submitting the final answer, use one of the following formats:

- Submit shortest block (e.g., block is "ABC"):
<answer>block=ABC</answer>

- Submit complete sequence (e.g., sequence is "ABCABC"):
<answer>sequence=ABCABC</answer>
"""

    contextualized_rule_zh_1 = """\
我们来进行一项"交通路线模式分析"任务，规则如下：

系统记录了一条固定但未知的公交运行站点序列 S，由站点类型 A、B、C、D 组成，总长度在 30 到 60 站之间。这条路线具有特殊的环线结构：它由一个最短的"基础环线" B 通过重复运行生成，即 S 由基础环线 B 重复行驶若干次，再加上最后一次未跑完的部分（B 的一个前缀，可能为空）拼接而成。

例如：若基础环线 B = "ABC"，则路线序列 S 可能是 "ABCABCAB"（B 完整运行 2 次 + 额外跑了前缀"AB"）。

你的目标是通过调度查询推断出这条路线的结构。你可以反复向调度系统提出以下三类查询（每次仅限一个查询），系统会如实回答：

1. 存在查询：询问某个站点组合模式 P 是否作为连续路段出现在 S 中。回答"是"或"否"。
2. 次数查询：询问某个站点组合模式 P 在 S 中出现的次数（允许重叠路段计数）。回答一个非负整数。
3. 位置查询：询问某个站点组合模式 P 在 S 中最早出现的位置（从 1 开始计数，代表第几站），若不存在则返回 0。回答一个非负整数。

注意：
- 站点模式串 P 必须由类型 A、B、C、D 组成，长度至少为 1。
- 所有查询的答案都基于同一条固定的路线序列 S。

当你收集足够信息后，可以提交最终的路线结构。你可以选择以下两种提交方式之一：
1. 提交最短基础环线 B。
2. 提交完整路线序列 S。

若答案错误或格式不符，任务失败。请尽可能用较少的查询次数完成分析。

## 查询与提交答案的格式（必须严格遵守）

每次查询只能包含一个标签。请使用以下 XML 格式：

- 存在查询（例如询问模式"AB"）：
<query_exists>AB</query_exists>

- 次数查询（例如询问模式"ABC"）：
<query_count>ABC</query_count>

- 位置查询（例如询问模式"ABCD"）：
<query_position>ABCD</query_position>

提交最终答案时，请使用以下格式之一：

- 提交最短基础环线（例如基础环线为"ABC"）：
<answer>block=ABC</answer>

- 提交完整路线序列（例如路线为"ABCABC"）：
<answer>sequence=ABCABC</answer>
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
Let's perform a "Traffic Route Pattern Analysis" task. Here are the rules:

The system has recorded a fixed but unknown public transit stop sequence S, composed of stop types A, B, C, and D, with a total length between 30 and 60 stops. This route features a special loop structure: it is generated by repeating a shortest "base loop" B. That is, S consists of the base loop B traveled several times, followed by an incomplete final run (a prefix of B, possibly empty).

For example: if base loop B = "ABC", then the route sequence S might be "ABCABCAB" (B completed 2 times + prefix "AB").

Your goal is to infer the structure of this route through dispatch queries. You can repeatedly ask the dispatch system three types of queries (one per turn), and it will answer truthfully:

1. Existence Query: Ask if a specific stop pattern P appears as a continuous segment in S. Answer "Yes" or "No".
2. Count Query: Ask how many times a stop pattern P appears in S (overlapping segments counted). Answer a non-negative integer.
3. Position Query: Ask the earliest position where stop pattern P appears in S (1-indexed, representing the stop number), or 0 if not found. Answer a non-negative integer.

Note:
- Stop pattern P must be composed of types A, B, C, D, with length at least 1.
- All query answers are based on the same fixed route sequence S.

When you have enough information, submit the final route structure. You can choose one of two submission methods:
1. Submit the shortest base loop B.
2. Submit complete route sequence S.

If the answer is wrong or the format is invalid, the task fails. Try to complete the analysis with as few queries as possible.

## Query and Answer Format (strictly required)

Each query must contain only one tag. Use the following XML format:

- Existence Query (e.g., asking about pattern "AB"):
<query_exists>AB</query_exists>

- Count Query (e.g., asking about pattern "ABC"):
<query_count>ABC</query_count>

- Position Query (e.g., asking about pattern "ABCD"):
<query_position>ABCD</query_position>

When submitting the final answer, use one of the following formats:

- Submit shortest base loop (e.g., base loop is "ABC"):
<answer>block=ABC</answer>

- Submit complete route sequence (e.g., sequence is "ABCABC"):
<answer>sequence=ABCABC</answer>
"""

    contextualized_rule_zh_2 = """\
我们来进行一项"病毒基因序列测定"任务，规则如下：

系统截获了一段固定但未知的病毒基因序列 S，由核苷酸类型 A、B、C、D 组成，长度在 30 到 60 之间。这段基因序列具有特殊的复制结构：它由某个最短的"核心基因片段" B 通过不断复制生成，即 S 由核心片段 B 重复复制若干次，再加上最后一次未完全复制的部分（B 的一个前缀，可能为空）拼接而成。

例如：若核心片段 B = "ABC"，则基因序列 S 可能是 "ABCABCAB"（B 复制 2 次 + 前缀"AB"）。

你的目标是通过测序查询推断出这段基因的结构。你可以反复向生信分析系统提出以下三类查询（每次仅限一个查询），系统会如实回答：

1. 存在查询：询问某个基因片段模式 P 是否作为连续序列出现在 S 中。回答"是"或"否"。
2. 次数查询：询问某个基因片段模式 P 在 S 中出现的次数（允许重叠片段计数）。回答一个非负整数。
3. 位置查询：询问某个基因片段模式 P 在 S 中最左侧出现的位点（从 1 开始计数），若不存在则返回 0。回答一个非负整数。

注意：
- 基因片段模式 P 必须由核苷酸 A、B、C、D 组成，长度至少为 1。
- 所有查询的答案都基于同一段固定的基因序列 S。

当你收集足够信息后，可以提交最终的序列解析结果。你可以选择以下两种提交方式之一：
1. 提交最短核心基因片段 B。
2. 提交完整基因序列 S。

若答案错误或格式不符，测定失败。请尽可能用较少的查询次数完成推断。

## 查询与提交答案的格式（必须严格遵守）

每次查询只能包含一个标签。请使用以下 XML 格式：

- 存在查询（例如询问模式"AB"）：
<query_exists>AB</query_exists>

- 次数查询（例如询问模式"ABC"）：
<query_count>ABC</query_count>

- 位置查询（例如询问模式"ABCD"）：
<query_position>ABCD</query_position>

提交最终答案时，请使用以下格式之一：

- 提交最短核心片段（例如片段为"ABC"）：
<answer>block=ABC</answer>

- 提交完整基因序列（例如序列为"ABCABC"）：
<answer>sequence=ABCABC</answer>
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
Let's perform a "Viral Genome Sequence Determination" task. Here are the rules:

The system has intercepted a fixed but unknown viral genome sequence S, composed of nucleotide types A, B, C, and D, with a length between 30 and 60. This gene sequence has a special replication structure: it is generated by continuous replication of a shortest "core gene segment" B. That is, S consists of the core segment B replicated several times, followed by an incompletely replicated portion (a prefix of B, possibly empty).

For example: if core segment B = "ABC", then the gene sequence S might be "ABCABCAB" (B replicated 2 times + prefix "AB").

Your goal is to infer the structure of this gene sequence through sequencing queries. You can repeatedly ask the bioinformatics analysis system three types of queries (one per turn), and it will answer truthfully:

1. Existence Query: Ask if a specific gene segment pattern P appears as a continuous sequence in S. Answer "Yes" or "No".
2. Count Query: Ask how many times a gene segment pattern P appears in S (overlapping segments counted). Answer a non-negative integer.
3. Position Query: Ask the leftmost locus where gene segment pattern P appears in S (1-indexed), or 0 if not found. Answer a non-negative integer.

Note:
- Gene segment pattern P must be composed of nucleotides A, B, C, D, with length at least 1.
- All query answers are based on the same fixed gene sequence S.

When you have enough information, submit the final sequence analysis result. You can choose one of two submission methods:
1. Submit the shortest core gene segment B.
2. Submit the complete gene sequence S.

If the answer is wrong or the format is invalid, the determination fails. Try to complete the inference with as few queries as possible.

## Query and Answer Format (strictly required)

Each query must contain only one tag. Use the following XML format:

- Existence Query (e.g., asking about pattern "AB"):
<query_exists>AB</query_exists>

- Count Query (e.g., asking about pattern "ABC"):
<query_count>ABC</query_count>

- Position Query (e.g., asking about pattern "ABCD"):
<query_position>ABCD</query_position>

When submitting the final answer, use one of the following formats:

- Submit shortest core segment (e.g., segment is "ABC"):
<answer>block=ABC</answer>

- Submit complete gene sequence (e.g., sequence is "ABCABC"):
<answer>sequence=ABCABC</answer>
"""

    contextualized_rule_zh_3 = """\
我们来进行一项"学习行为模式分析"任务，规则如下：

教育系统记录了一名学生固定但未知的学习行为序列 S，由行为代码 A、B、C、D 组成，总长度在 30 到 60 之间。这段行为序列具有特殊的周期性结构：它由某个最短的"核心学习节律" B 通过重复生成，即 S 由核心节律 B 重复多次，再加上最后一段未完成的部分（B 的一个前缀，可能为空）拼接而成。

例如：若核心学习节律 B = "ABC"，则行为序列 S 可能是 "ABCABCAB"（B 循环 2 次 + 前缀"AB"）。

你的目标是通过分析查询推断出学生的行为模式结构。你可以反复向系统提出以下三类查询（每次仅限一个查询），系统会如实回答：

1. 存在查询：询问某个行为模式 P 是否作为连续片段出现在 S 中。回答"是"或"否"。
2. 次数查询：询问某个行为模式 P 在 S 中出现的次数（允许重叠行为计数）。回答一个非负整数。
3. 位置查询：询问某个行为模式 P 在 S 中最先发生的位置（从 1 开始计数，代表第几个行为），若不存在则返回 0。回答一个非负整数。

注意：
- 行为模式 P 必须由代码 A、B、C、D 组成，长度至少为 1。
- 所有查询的答案都基于同一段固定的学习行为序列 S。

当你收集足够信息后，可以提交最终的模式推演结果。你可以选择以下两种提交方式之一：
1. 提交最短核心学习节律 B。
2. 提交完整学习行为序列 S。

若答案错误或格式不符，分析失败。请尽可能用较少的查询次数完成推断。

## 查询与提交答案的格式（必须严格遵守）

每次查询只能包含一个标签。请使用以下 XML 格式：

- 存在查询（例如询问模式"AB"）：
<query_exists>AB</query_exists>

- 次数查询（例如询问模式"ABC"）：
<query_count>ABC</query_count>

- 位置查询（例如询问模式"ABCD"）：
<query_position>ABCD</query_position>

提交最终答案时，请使用以下格式之一：

- 提交最短核心节律（例如节律为"ABC"）：
<answer>block=ABC</answer>

- 提交完整行为序列（例如序列为"ABCABC"）：
<answer>sequence=ABCABC</answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Let's perform a "Learning Behavior Pattern Analysis" task. Here are the rules:

The education system has recorded a fixed but unknown learning behavior sequence S for a student, composed of behavior codes A, B, C, and D, with a total length between 30 and 60. This behavior sequence has a special periodic structure: it is generated by repeating a shortest "core learning rhythm" B. That is, S consists of the core rhythm B repeated multiple times, followed by an incomplete final segment (a prefix of B, possibly empty).

For example: if core learning rhythm B = "ABC", then the behavior sequence S might be "ABCABCAB" (B cycled 2 times + prefix "AB").

Your goal is to infer the structure of the student's behavior pattern through analytical queries. You can repeatedly ask the system three types of queries (one per turn), and it will answer truthfully:

1. Existence Query: Ask if a specific behavior pattern P appears as a continuous segment in S. Answer "Yes" or "No".
2. Count Query: Ask how many times a behavior pattern P appears in S (overlapping behaviors counted). Answer a non-negative integer.
3. Position Query: Ask the earliest position where behavior pattern P occurs in S (1-indexed, representing the nth behavior), or 0 if not found. Answer a non-negative integer.

Note:
- Behavior pattern P must be composed of codes A, B, C, D, with length at least 1.
- All query answers are based on the same fixed learning behavior sequence S.

When you have enough information, submit the final pattern inference result. You can choose one of two submission methods:
1. Submit the shortest core learning rhythm B.
2. Submit the complete learning behavior sequence S.

If the answer is wrong or the format is invalid, the analysis fails. Try to complete the inference with as few queries as possible.

## Query and Answer Format (strictly required)

Each query must contain only one tag. Use the following XML format:

- Existence Query (e.g., asking about pattern "AB"):
<query_exists>AB</query_exists>

- Count Query (e.g., asking about pattern "ABC"):
<query_count>ABC</query_count>

- Position Query (e.g., asking about pattern "ABCD"):
<query_position>ABCD</query_position>

When submitting the final answer, use one of the following formats:

- Submit shortest core rhythm (e.g., rhythm is "ABC"):
<answer>block=ABC</answer>

- Submit complete behavior sequence (e.g., sequence is "ABCABC"):
<answer>sequence=ABCABC</answer>
"""

    contextualized_rule_zh_4 = """\
我们来进行一项"工业流水线工序解析"任务，规则如下：

系统监控到一段固定但未知的自动化流水线操作序列 S，由机器指令代码 A、B、C、D 组成，总长度在 30 到 60 之间。这段操作序列具有特殊的循环结构：它由一套最短的"标准工序组合" B 通过重复执行生成，即 S 由标准工序 B 完整执行若干次，再加上最后一次被中断的操作（B 的一个前缀，可能为空）拼接而成。

例如：若标准工序 B = "ABC"，则操作序列 S 可能是 "ABCABCAB"（B 执行 2 次 + 前缀指令"AB"）。

你的目标是通过诊断查询推断出流水线的加工结构。你可以反复向控制中心提出以下三类查询（每次仅限一个查询），控制中心会如实回答：

1. 存在查询：询问某段指令模式 P 是否作为连续操作出现在 S 中。回答"是"或"否"。
2. 次数查询：询问某段指令模式 P 在 S 中执行的次数（允许重叠指令计数）。回答一个非负整数。
3. 位置查询：询问某段指令模式 P 在 S 中最先被执行的指令位（从 1 开始计数），若未执行过则返回 0。回答一个非负整数。

注意：
- 指令模式 P 必须由机器代码 A、B、C、D 组成，长度至少为 1。
- 所有查询的答案都基于同一段固定的操作序列 S。

当你收集足够信息后，可以提交最终的工序解析结果。你可以选择以下两种提交方式之一：
1. 提交最短标准工序组合 B。
2. 提交完整操作序列 S。

若答案错误或格式不符，解析失败。请尽可能用较少的查询次数完成诊断。

## 查询与提交答案的格式（必须严格遵守）

每次查询只能包含一个标签。请使用以下 XML 格式：

- 存在查询（例如询问模式"AB"）：
<query_exists>AB</query_exists>

- 次数查询（例如询问模式"ABC"）：
<query_count>ABC</query_count>

- 位置查询（例如询问模式"ABCD"）：
<query_position>ABCD</query_position>

提交最终答案时，请使用以下格式之一：

- 提交最短标准工序组合（例如工序为"ABC"）：
<answer>block=ABC</answer>

- 提交完整操作序列（例如序列为"ABCABC"）：
<answer>sequence=ABCABC</answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing/Industrial Scenario]
Let's perform an "Industrial Assembly Line Process Analysis" task. Here are the rules:

The system has monitored a fixed but unknown automated assembly line operation sequence S, composed of machine instruction codes A, B, C, and D, with a total length between 30 and 60. This operation sequence has a special loop structure: it is generated by repeatedly executing a shortest "standard process set" B. That is, S consists of the standard process B executed completely several times, followed by a final interrupted operation (a prefix of B, possibly empty).

For example: if standard process B = "ABC", then the operation sequence S might be "ABCABCAB" (B executed 2 times + prefix instructions "AB").

Your goal is to infer the processing structure of the assembly line through diagnostic queries. You can repeatedly ask the control center three types of queries (one per turn), and the control center will answer truthfully:

1. Existence Query: Ask if a specific instruction pattern P appears as a continuous operation in S. Answer "Yes" or "No".
2. Count Query: Ask how many times an instruction pattern P is executed in S (overlapping instructions counted). Answer a non-negative integer.
3. Position Query: Ask the earliest instruction position where pattern P is executed in S (1-indexed), or 0 if not executed. Answer a non-negative integer.

Note:
- Instruction pattern P must be composed of machine codes A, B, C, D, with length at least 1.
- All query answers are based on the same fixed operation sequence S.

When you have enough information, submit the final process analysis result. You can choose one of two submission methods:
1. Submit the shortest standard process set B.
2. Submit the complete operation sequence S.

If the answer is wrong or the format is invalid, the analysis fails. Try to complete the diagnosis with as few queries as possible.

## Query and Answer Format (strictly required)

Each query must contain only one tag. Use the following XML format:

- Existence Query (e.g., asking about pattern "AB"):
<query_exists>AB</query_exists>

- Count Query (e.g., asking about pattern "ABC"):
<query_count>ABC</query_count>

- Position Query (e.g., asking about pattern "ABCD"):
<query_position>ABCD</query_position>

When submitting the final answer, use one of the following formats:

- Submit shortest standard process set (e.g., process is "ABC"):
<answer>block=ABC</answer>

- Submit complete operation sequence (e.g., sequence is "ABCABC"):
<answer>sequence=ABCABC</answer>
"""

    contextualized_rule_zh_5 = """\
我们来进行一项"合规审查流程推断"任务，规则如下：

法务系统记录了一段固定但未知的案件审查流程序列 S，由审批环节 A、B、C、D 组成，总环节数在 30 到 60 之间。这段审查流程具有特殊的标准化结构：它由某个最短的"核心审查回路" B 通过不断迭代生成，即 S 由核心回路 B 重复执行若干次，再加上最后一次尚在进行中的环节（B 的一个前缀，可能为空）拼接而成。

例如：若核心审查回路 B = "ABC"，则审查流程序列 S 可能是 "ABCABCAB"（B 循环审查 2 次 + 前缀环节"AB"）。

你的目标是通过审计查询推断出该合规审查的结构。你可以反复向审计系统提出以下三类查询（每次仅限一个查询），系统会如实回答：

1. 存在查询：询问某个环节组合 P 是否作为连续流程序列出现在 S 中。回答"是"或"否"。
2. 次数查询：询问某个环节组合 P 在 S 中发生的次数（允许重叠环节计数）。回答一个非负整数。
3. 位置查询：询问某个环节组合 P 在 S 中最早处于第几个环节（从 1 开始计数），若不存在则返回 0。回答一个非负整数。

注意：
- 环节组合 P 必须由审查环节 A、B、C、D 组成，长度至少为 1。
- 所有查询的答案都基于同一段固定的审查流程序列 S。

当你收集足够信息后，可以提交最终的流程重构结果。你可以选择以下两种提交方式之一：
1. 提交最短核心审查回路 B。
2. 提交完整审查流程序列 S。

若答案错误或格式不符，推断失败。请尽可能用较少的查询次数完成审计。

## 查询与提交答案的格式（必须严格遵守）

每次查询只能包含一个标签。请使用以下 XML 格式：

- 存在查询（例如询问模式"AB"）：
<query_exists>AB</query_exists>

- 次数查询（例如询问模式"ABC"）：
<query_count>ABC</query_count>

- 位置查询（例如询问模式"ABCD"）：
<query_position>ABCD</query_position>

提交最终答案时，请使用以下格式之一：

- 提交最短核心审查回路（例如回路为"ABC"）：
<answer>block=ABC</answer>

- 提交完整审查流程序列（例如序列为"ABCABC"）：
<answer>sequence=ABCABC</answer>
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
Let's perform a "Compliance Review Process Inference" task. Here are the rules:

The legal system has recorded a fixed but unknown case review process sequence S, composed of approval steps A, B, C, and D, with a total step count between 30 and 60. This review process has a special standardized structure: it is generated by continuously iterating a shortest "core review loop" B. That is, S consists of the core loop B repeatedly executed several times, followed by the currently ongoing steps (a prefix of B, possibly empty).

For example: if core review loop B = "ABC", then the review process sequence S might be "ABCABCAB" (B looped 2 times + prefix steps "AB").

Your goal is to infer the structure of this compliance review through audit queries. You can repeatedly ask the audit system three types of queries (one per turn), and the system will answer truthfully:

1. Existence Query: Ask if a specific step combination P appears as a continuous process sequence in S. Answer "Yes" or "No".
2. Count Query: Ask how many times a step combination P occurs in S (overlapping steps counted). Answer a non-negative integer.
3. Position Query: Ask the earliest position where step combination P occurs in S (1-indexed), or 0 if not found. Answer a non-negative integer.

Note:
- Step combination P must be composed of approval steps A, B, C, D, with length at least 1.
- All query answers are based on the same fixed review process sequence S.

When you have enough information, submit the final process reconstruction result. You can choose one of two submission methods:
1. Submit the shortest core review loop B.
2. Submit the complete review process sequence S.

If the answer is wrong or the format is invalid, the inference fails. Try to complete the audit with as few queries as possible.

## Query and Answer Format (strictly required)

Each query must contain only one tag. Use the following XML format:

- Existence Query (e.g., asking about pattern "AB"):
<query_exists>AB</query_exists>

- Count Query (e.g., asking about pattern "ABC"):
<query_count>ABC</query_count>

- Position Query (e.g., asking about pattern "ABCD"):
<query_position>ABCD</query_position>

When submitting the final answer, use one of the following formats:

- Submit shortest core review loop (e.g., loop is "ABC"):
<answer>block=ABC</answer>

- Submit complete review process sequence (e.g., sequence is "ABCABC"):
<answer>sequence=ABCABC</answer>
"""

    tags = ["answer", "query_exists", "query_count", "query_position"]
    
    reasoning_type = "归纳推理"
    data_structure = "序列"

    # 难度配置：
    # 1 (简单)      - 短基块，完整重复
    # 2 (中等偏下)  - 中等基块，带小前缀
    # 3 (中等偏上)  - 较长基块，多次重复
    # 4 (较难)      - 复杂基块，不规则前缀
    # 5 (难)        - 长基块，接近最大长度

    DIFFICULTY_CONFIG = {
        1: {
            "block_len": 3,
            "repetitions": 10,
            "prefix_len": 0,
            # 生成：ABCABCABCABCABCABCABCABCABCABC (长度30)
        },
        2: {
            "block_len": 4,
            "repetitions": 9,
            "prefix_len": 2,
            # 生成：ABCDABCDABCDABCDABCDABCDABCDABCDABCDAB (长度38)
        },
        3: {
            "block_len": 5,
            "repetitions": 8,
            "prefix_len": 3,
            # 生成：ABCDAABCDAABCDAABCDAABCDAABCDAABCDAABCDAABC (长度43)
        },
        4: {
            "block_len": 6,
            "repetitions": 7,
            "prefix_len": 4,
            # 生成：ABCDABABCDABABCDABABCDABABCDABABCDABABCDABABCD (长度46)
        },
        5: {
            "block_len": 8,
            "repetitions": 7,
            "prefix_len": 4,
            # 长度 = 8*7 + 4 = 60
        },
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        diff = self.config.difficulty

        if diff not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[diff]
        
        # 使用确定性随机种子生成基块，保证可复现但不被记忆
        rng = random.Random(42 + diff)
        chars = "ABCD"
        block_len = cfg["block_len"]
        
        # 生成一个不可再分的随机基块
        while True:
            block = ''.join(rng.choice(chars) for _ in range(block_len))
            # 验证不可分解性：没有更短的周期
            is_primitive = True
            for shorter_len in range(1, block_len):
                if block_len % shorter_len == 0:
                    candidate = block[:shorter_len] * (block_len // shorter_len)
                    if candidate == block:
                        is_primitive = False
                        break
            if is_primitive:
                break
        
        reps = cfg["repetitions"]
        prefix_len = cfg["prefix_len"]

        # 生成序列 S = B^k + B[1..t]
        self.block = block
        self.sequence = block * reps + block[:prefix_len]
        self.sequence_length = len(self.sequence)

        # 验证长度在合理范围内
        if not (30 <= self.sequence_length <= 60):
            # 动态调整以确保在范围内
            target_len = 45
            reps = target_len // len(block)
            prefix_len = target_len % len(block)
            self.sequence = block * reps + block[:prefix_len]
            self.sequence_length = len(self.sequence)

        self._game_info["n"] = self.sequence_length

    def evaluate(self, parsed_info):
        """
        验证玩家提交的答案
        支持两种提交方式：
        1. block=XXX - 提交最短基块
        2. sequence=XXX - 提交完整序列
        """
        raw_ans = parsed_info["answer"].strip()
        
        # 解析答案
        if "=" not in raw_ans:
            return False
            
        key, value = raw_ans.split("=", 1)
        key = key.strip()
        value = value.strip()

        # 验证字符集
        if not all(c in "ABCD" for c in value):
            return False

        if key == "sequence":
            # 方式1：直接提交完整序列
            return value == self.sequence
            
        elif key == "block":
            # 方式2：提交最短基块
            submitted_block = value
            
            # 检查提交的基块是否能生成原序列
            if len(submitted_block) == 0:
                return False
                
            # 检查是否存在 k, t 使得 S = B^k + B[1..t]
            block_len = len(submitted_block)
            seq_len = len(self.sequence)
            
            # 计算需要的重复次数
            full_reps = seq_len // block_len
            remainder = seq_len % block_len
            
            # 生成候选序列
            candidate = submitted_block * full_reps + submitted_block[:remainder]
            
            if candidate != self.sequence:
                return False
            
            # 验证是否是最短基块：检查是否存在更短的基块能生成相同序列
            for shorter_len in range(1, block_len):
                shorter_block = self.sequence[:shorter_len]
                test_reps = seq_len // shorter_len
                test_remainder = seq_len % shorter_len
                test_seq = shorter_block * test_reps + shorter_block[:test_remainder]
                if test_seq == self.sequence:
                    return False
            
            return True
            
        else:
            return False

    def _cf_core_produce(self, parsed_info):
        """
        原始的响应生成逻辑
        """
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
            error_format = "错误：模式串格式无效。"
            error_length = "错误：模式串长度超出范围。"
        else:
            yes_res, no_res = "Yes", "No"
            error_format = "Error: Invalid pattern format."
            error_length = "Error: Pattern length out of range."

        # 优先级：exists > count > position
        if "query_exists" in parsed_info:
            pattern = parsed_info["query_exists"].strip()
            
            # 验证模式串
            if not pattern or not all(c in "ABCD" for c in pattern):
                return error_format
            if len(pattern) > self.sequence_length:
                return error_length
                
            # 检查是否存在
            return yes_res if pattern in self.sequence else no_res

        elif "query_count" in parsed_info:
            pattern = parsed_info["query_count"].strip()
            
            # 验证模式串
            if not pattern or not all(c in "ABCD" for c in pattern):
                return error_format
            if len(pattern) > self.sequence_length:
                return error_length
            
            # 计数（允许重叠）
            count = 0
            start = 0
            while True:
                pos = self.sequence.find(pattern, start)
                if pos == -1:
                    break
                count += 1
                start = pos + 1  # 允许重叠，所以从下一个位置开始
            
            return str(count)

        elif "query_position" in parsed_info:
            pattern = parsed_info["query_position"].strip()
            
            # 验证模式串
            if not pattern or not all(c in "ABCD" for c in pattern):
                return error_format
            if len(pattern) > self.sequence_length:
                return error_length
            
            # 查找最左位置（1-indexed）
            pos = self.sequence.find(pattern)
            return str(pos + 1) if pos != -1 else "0"

        else:
            raise ValueError("No valid query tag found.")

    def _cf_make_wrong(self, correct):
        # 若 correct 是纯数字字符串（包含 "0"）
        if correct.isdigit():
            val = int(correct)
            if val == 0:
                return "1"
            else:
                return str(val + 1)
        
        # yes/no 替换
        if correct == "是":
            return "否"
        elif correct == "否":
            return "是"
        elif correct.lower() == "yes":
            return "No" if correct[0].isupper() else "no"
        elif correct.lower() == "no":
            return "Yes" if correct[0].isupper() else "yes"
        
        # 错误消息或其他情况 —— 返回一个明确的错误标记
        return correct + "_WRONG"

    def get_all_possible_queries(self) -> list[dict]:
        """
        枚举合理规模的合法查询并返回对应的正确答案。
        限制子串最大长度以保持查询总数可控。
        """
        queries = []
        
        seq = self.sequence
        n = len(seq)
        
        # 限制枚举子串的最大长度，避免爆炸
        max_substr_len = min(n, len(self.block) + 3)
        
        patterns = set()
        for length in range(1, max_substr_len + 1):
            for i in range(n - length + 1):
                patterns.add(seq[i : i + length])
        
        # 补充长度 1-3 的所有组合（包含负例）
        chars = "ABCD"
        for length in range(1, 4):
            for p in itertools.product(chars, repeat=length):
                patterns.add("".join(p))
        
        sorted_patterns = sorted(list(patterns), key=lambda x: (len(x), x))
        
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
        else:
            yes_res, no_res = "Yes", "No"
            
        for pat in sorted_patterns:
            # --- Exists Query ---
            exists = pat in seq
            ans_exists = yes_res if exists else no_res
            queries.append({
                "query": f"<query_exists>{pat}</query_exists>",
                "answer": ans_exists
            })
            
            # --- Count Query (with overlap) ---
            count = 0
            start = 0
            while True:
                pos = seq.find(pat, start)
                if pos == -1:
                    break
                count += 1
                start = pos + 1
            queries.append({
                "query": f"<query_count>{pat}</query_count>",
                "answer": str(count)
            })
            
            # --- Position Query (1-indexed) ---
            pos_idx = seq.find(pat)
            ans_pos = str(pos_idx + 1) if pos_idx != -1 else "0"
            queries.append({
                "query": f"<query_position>{pat}</query_position>",
                "answer": ans_pos
            })
            
        return queries