# -*- coding: utf-8 -*-
# 自动生成 | 模型: api/gpt-5-2025-08-07
# 推理类型: 溯因推理（明确有若干种可能性，模型需要判断那种是正确的）：面对当前的状态（反馈），推测原因。
# 数据结构: 序列：存在一个长度为N的有序序列。
# 知识点:   区间包含：某子序列是否完整出现在给定区间内
# ============================================================

import random
import itertools
from .base import Game

class SequencePatternRuleGame(Game):

    # ======= 原始规则 =======
    game_rule_zh = """\
我们来玩一个"序列模式规则推理"游戏，规则如下：

游戏设定了一个长度为 {n} 的序列 S，每个位置的元素从字母表 {{A, B, C, D, E}} 中取值。序列内容为：
{sequence}

同时，我秘密选择了一种"索引集合生成规则"，该规则可以将任意一对索引 (L, R) 映射为一个索引集合 W。规则类型只有三种，分别记为 α、β、γ（具体定义我不会告诉你）。

你的目标是：
1. 通过提问推断出我使用的是哪种规则（α、β 或 γ）。
2. 找到一对索引 (L*, R*)，使得根据该规则生成的索引集合 W* 能够完全包含目标模式 T = {target_pattern} 在序列 S 中的某个线性连续出现。

你可以反复向我提出查询（请尽可能少地使用查询次数），每次查询的形式为：

查询 Q(L, R, P)：
- L, R 是索引（范围 1 到 {n}）
- P 是一个长度为 2 到 4 的字母序列（由 A、B、C、D、E 组成）

我会根据以下逻辑回答"是"或"否"：
- 首先根据我选择的规则和 (L, R) 计算出索引集合 W
- 然后检查模式 P 是否在序列 S 中线性连续出现，且该出现的所有位置都在 W 中
- 如果存在这样的匹配，回答"是"；否则回答"否"

注意：模式 P 必须在 S 中连续出现（不能跨越序列末尾和开头）。

## 查询与提交答案的格式

每次只能提交一个标签。请使用以下 XML 格式：

- 查询（例如 L=3, R=7, P=ABD）：
<query>3,7,ABD</query>

提交最终答案时，必须说明规则类型（α、β 或 γ）以及索引对 (L*, R*)，格式如下：

<answer>rule=α, L=3, R=10</answer>
"""

    game_rule_en = """\
Let's play a "Sequence Pattern Rule Deduction" game with the following rules:

The game defines a sequence S of length {n}, where each position contains an element from the alphabet {{A, B, C, D, E}}. The sequence is:
{sequence}

I have secretly chosen an "index set generation rule" that maps any pair of indices (L, R) to an index set W. There are only three rule types, denoted α, β, γ (I won't tell you their exact definitions).

Your goals are:
1. Infer which rule (α, β, or γ) I am using through queries.
2. Find a pair of indices (L*, R*) such that the index set W* generated by this rule completely contains a linear continuous occurrence of the target pattern T = {target_pattern} in sequence S.

You may repeatedly submit queries (please use as few queries as possible). Each query has the form:

Query Q(L, R, P):
- L, R are indices (ranging from 1 to {n})
- P is a letter sequence of length 2 to 4 (composed of A, B, C, D, E)

I will answer "Yes" or "No" based on the following logic:
- First, calculate the index set W based on my chosen rule and (L, R)
- Then check if pattern P appears as a linear continuous substring in sequence S, and all positions of that occurrence are within W
- If such a match exists, answer "Yes"; otherwise answer "No"

Note: Pattern P must appear continuously in S (cannot wrap around from end to beginning).

## Query and Answer Format

Only one tag can be submitted at a time. Use the following XML format:

- Query (e.g., L=3, R=7, P=ABD):
<query>3,7,ABD</query>

When submitting the final answer, specify the rule type (α, β, or γ) and the index pair (L*, R*) in this format:

<answer>rule=α, L=3, R=10</answer>
"""

    # ======= 场景 1：交通 =======
    contextualized_rule_zh_1 = """\
欢迎使用“智能交通路网监测系统”。

系统记录了一条主干道上连续 {n} 个路段的实时路况序列 S，状态分为 {{A, B, C, D, E}}（如：A-畅通，B-缓行，C-拥堵等）。路况序列如下：
{sequence}

监控中心部署了一种“巡查区域生成策略”，该策略根据输入的起始和终止站点编号 (L, R) 生成一个实际的巡查路段集合 W。策略分为三种类型：α、β、γ（具体生成逻辑已加密）。

你的任务是：
1. 通过模拟查询，推断出中心当前使用的是哪种策略（α、β 或 γ）。
2. 提供一对站点编号 (L*, R*)，使得由该策略生成的巡查集合 W* 能够完全覆盖特定的交通异常模式 T = {target_pattern}（该模式在序列 S 中呈现为连续的线性路段状态）。

你可以反复向系统提交查询（请尽可能优化查询次数），每次查询包含：
查询 Q(L, R, P)：
- L, R：站点编号（范围 1 到 {n}）
- P：路况模式，长度为 2 到 4 的状态序列（由 A, B, C, D, E 组成）

系统将返回“是”或“否”：
- 首先根据当前策略和 (L, R) 计算出巡查集合 W
- 检查模式 P 是否在主干道上连续出现，且该出现的所有路段均位于 W 范围内
- 如果存在完全包含在 W 内的匹配模式，返回“是”；否则返回“否”。

注意：模式 P 必须是连续的路段状态（不得首尾相连跨越）。

## 查询与提交答案格式
每次仅允许提交一个标签，请使用以下 XML 格式：
- 查询（例如 L=3, R=7, P=ABD）：
<query>3,7,ABD</query>

最终提交答案时，说明策略类型及参数 (L*, R*)：
<answer>rule=α, L=3, R=10</answer>
"""

    contextualized_rule_en_1 = """\
[Transportation Scenario]
Welcome to the "Intelligent Traffic Network Monitoring System".

The system has recorded the real-time traffic condition sequence S of {n} continuous segments on a main road, categorized into {{A, B, C, D, E}} (e.g., A-Clear, B-Slow, C-Congested). The sequence is:
{sequence}

The monitoring center has deployed a "Patrol Area Generation Strategy" that maps a pair of station indices (L, R) into an actual set of patrol segments W. There are three types of strategies: α, β, and γ (the exact logic is encrypted).

Your tasks are:
1. Deduce which strategy (α, β, or γ) is currently in use through simulated queries.
2. Find a pair of station indices (L*, R*) such that the patrol set W* generated by this strategy completely covers a specific abnormal traffic pattern T = {target_pattern} (which appears continuously in sequence S).

You may repeatedly submit queries (minimize your query count). Each query format is:
Query Q(L, R, P):
- L, R: Station indices (1 to {n})
- P: Traffic pattern, a sequence of length 2 to 4 (from A, B, C, D, E)

The system will respond with "Yes" or "No" based on:
- Calculating the patrol set W using the current strategy and (L, R).
- Checking if pattern P appears continuously on the road, and all segments of that occurrence fall entirely within W.
- If such a match exists, it returns "Yes"; otherwise "No".

Note: Pattern P must appear continuously (no wrapping around the ends).

## Query and Answer Format
Submit only one tag at a time using XML format:
- Query (e.g., L=3, R=7, P=ABD):
<query>3,7,ABD</query>

To submit the final answer, specify the strategy type and parameters (L*, R*):
<answer>rule=α, L=3, R=10</answer>
"""

    # ======= 场景 2：医疗 =======
    contextualized_rule_zh_2 = """\
欢迎使用“临床病理特征分析系统”。

系统提取了患者连续 {n} 个时间窗口的生理特征序列 S，标记为 {{A, B, C, D, E}} 五种生化反应类型。序列内容为：
{sequence}

医疗干预程序内置了“给药作用周期生成规则”，输入起始和终止参数 (L, R) 后，会映射出药物实际起效的时间集合 W。规则分为 α、β、γ 三类（临床机密暂不公开）。

你的目标：
1. 通过药效查询，推断正在使用哪种生成规则（α、β 或 γ）。
2. 设定参数对 (L*, R*)，使得该规则生成的起效集合 W* 完全覆盖靶向的病理发作模式 T = {target_pattern}（在序列 S 中的连续反应）。

查询方式 Q(L, R, P)：
- L, R：时间窗口参数（1 到 {n}）
- P：观察的病理模式，长度为 2 到 4（A 到 E 组成）

系统反馈“是”或“否”：
- 按所选规则和 (L, R) 计算出起效集合 W
- 检查模式 P 是否在序列 S 中连续发生，且该过程完全处于 W 覆盖下
- 若匹配则回答“是”，否则“否”。

注意：模式 P 必须是连续发生的特征序列。

## 交互格式
使用 XML 格式提交：
- 查询（例：L=3, R=7, P=ABD）：
<query>3,7,ABD</query>

最终提交干预方案（标明规则与参数）：
<answer>rule=α, L=3, R=10</answer>
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
Welcome to the "Clinical Pathological Feature Analysis System".

The system has extracted a patient's physiological feature sequence S across {n} continuous time windows, categorized into 5 biochemical reaction types {{A, B, C, D, E}}. The sequence is:
{sequence}

The medical intervention program features a "Medication Efficacy Cycle Generation Rule" that maps input parameters (L, R) to an effective time set W. Rules are classified into α, β, and γ (clinical confidentiality applies).

Your goals:
1. Deduce the active generation rule (α, β, or γ) via efficacy queries.
2. Determine a parameter pair (L*, R*) so the generated effective set W* completely covers the targeted pathological onset pattern T = {target_pattern} (appearing continuously in S).

Query Format Q(L, R, P):
- L, R: Time window parameters (1 to {n})
- P: Observed pathological pattern, length 2 to 4 (A to E)

System responses ("Yes" or "No"):
- Computes effective set W based on the rule and (L, R).
- Checks if pattern P occurs continuously in S and falls entirely within W.
- Returns "Yes" if matched; otherwise "No".

Note: Pattern P must be continuous in sequence S.

## Interaction Format
Use XML format for submission:
- Query (e.g., L=3, R=7, P=ABD):
<query>3,7,ABD</query>

Submit the final intervention plan (rule and parameters):
<answer>rule=α, L=3, R=10</answer>
"""

    # ======= 场景 3：教育 =======
    contextualized_rule_zh_3 = """\
欢迎进入“自适应学习轨迹评估平台”。

平台追踪了学生在 {n} 个连续学习模块中的认知表现序列 S，评级从 {{A, B, C, D, E}}（如：A-极佳，E-薄弱）。当前表现序列：
{sequence}

辅导系统内置了“复习区间推送策略”，输入起止模块索引 (L, R) 后，将生成一个待复习的模块集合 W。策略有 α、β、γ 三种（底层分配逻辑未公开）。

任务要求：
1. 提问诊断，判断系统当前激活的是哪种策略（α、β 或 γ）。
2. 提供最优参数 (L*, R*)，使得该策略生成的复习集合 W* 恰好完全包含学生的典型薄弱表现模式 T = {target_pattern}（在学习序列 S 中连续出现）。

可发起诊断查询 Q(L, R, P)：
- L, R：模块索引（1 到 {n}）
- P：特定表现模式，长度 2 到 4（A 到 E）

系统判定“是”或“否”：
- 根据激活策略和 (L, R) 划定复习集合 W
- 验证模式 P 是否在学生的表现序列 S 中连续存在，且发生位置全都在 W 范围内
- 完全包含即回复“是”，否则“否”。

注意：表现模式 P 必须为连续模块。

## 提交规范
通过 XML 格式执行操作：
- 查询测试（例：L=3, R=7, P=ABD）：
<query>3,7,ABD</query>

最终结论提交（包含策略及推送参数）：
<answer>rule=α, L=3, R=10</answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Welcome to the "Adaptive Learning Trajectory Assessment Platform".

The platform tracks a student's cognitive performance sequence S across {n} continuous learning modules, graded from {{A, B, C, D, E}} (e.g., A-Excellent, E-Weak). The performance sequence is:
{sequence}

The tutoring system includes a "Review Interval Push Strategy" that maps starting and ending module indices (L, R) to a review module set W. Strategies are α, β, and γ (internal logic undisclosed).

Task Requirements:
1. Conduct diagnostic queries to determine the active strategy (α, β, or γ).
2. Provide the optimal parameter pair (L*, R*) so the resulting review set W* completely encapsulates the typical weak performance pattern T = {target_pattern} (appearing continuously in S).

Diagnostic Query Q(L, R, P):
- L, R: Module indices (1 to {n})
- P: Specific performance pattern, length 2 to 4 (A to E)

System evaluation ("Yes" or "No"):
- Defines review set W using the active strategy and (L, R).
- Verifies if pattern P continuously exists in S and occurs entirely within W.
- Returns "Yes" for complete inclusion, else "No".

Note: Pattern P must span continuous modules.

## Submission Guidelines
Execute operations via XML:
- Query Test (e.g., L=3, R=7, P=ABD):
<query>3,7,ABD</query>

Final conclusion submission (strategy and parameters):
<answer>rule=α, L=3, R=10</answer>
"""

    # ======= 场景 4：制造业/工业 =======
    contextualized_rule_zh_4 = """\
欢迎操作“工业智造质检溯源系统”。

生产线传感器采集了连续 {n} 个工件的质量评级序列 S，级别分为 {{A, B, C, D, E}}（如：A为优良，E为残次）。当前批次序列为：
{sequence}

质检系统拥有一套“抽检批次划分算法”，由操作员输入批次界限 (L, R) 来生成抽样集合 W。算法类型包括 α、β、γ 三种（算法内核封装不可见）。

你需要完成：
1. 通过测试指令，逆向分析出系统目前运行的划分算法（α、β 或 γ）。
2. 输入精准界限 (L*, R*)，使得计算出的抽样集合 W* 能够完整包裹住某个特定的连续缺陷模式 T = {target_pattern}。

指令输入格式 Q(L, R, P)：
- L, R：工件流水号（1 到 {n}）
- P：质量波动模式，长度 2 到 4（A-E）

系统输出“是”或“否”：
- 通过算法及 (L, R) 划定抽样集合 W
- 追踪模式 P 是否在流水线上连续出现，且涉及的所有工件均落在 W 集合内
- 若满足条件返回“是”，否则“否”。

注意：模式 P 必须为连续产出的工件序列。

## 指令及报告格式
仅支持单次 XML 标签提交：
- 测试指令（如 L=3, R=7, P=ABD）：
<query>3,7,ABD</query>

最终质检报告提交格式：
<answer>rule=α, L=3, R=10</answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing/Industry Scenario]
Welcome to the "Industrial Smart Manufacturing Quality Traceability System".

Line sensors have captured the quality rating sequence S of {n} continuous workpieces, graded into {{A, B, C, D, E}} (e.g., A-Premium, E-Defective). The current batch sequence is:
{sequence}

The quality inspection system features a "Sampling Batch Partition Algorithm", generating a sample set W from input boundaries (L, R). Algorithm types are α, β, and γ (core logic encapsulated).

You need to:
1. Reverse-engineer the active algorithm (α, β, or γ) via test commands.
2. Input precise boundaries (L*, R*) so the generated sampling set W* entirely encompasses a specific continuous defect pattern T = {target_pattern}.

Command Input Q(L, R, P):
- L, R: Workpiece serial numbers (1 to {n})
- P: Quality fluctuation pattern, length 2 to 4 (A to E)

System Output ("Yes" or "No"):
- Defines sampling set W via the algorithm and (L, R).
- Traces if pattern P appears continuously on the line and falls fully within W.
- Returns "Yes" if conditions are met, else "No".

Note: Pattern P must represent continuous workpieces.

## Command & Report Format
Submit single XML tags only:
- Test Command (e.g., L=3, R=7, P=ABD):
<query>3,7,ABD</query>

Final quality report submission format:
<answer>rule=α, L=3, R=10</answer>
"""

    # ======= 场景 5：法律 =======
    contextualized_rule_zh_5 = """\
欢迎访问“智能合规与风险审查系统”。

系统正在解析一份核心合同，包含连续 {n} 个条款环节构成的风险评级序列 S，评级类别包含 {{A, B, C, D, E}}。案卷序列如下：
{sequence}

审查引擎具备一种“条款靶向提取机制”，通过指定条款锚点 (L, R)提取出关联审查集合 W。提取机制包含三种法定规则 α、β、γ（具体映射逻辑保密）。

请履行审查职责：
1. 提交验证质询，推演出当前生效的提取规则（α、β 或 γ）。
2. 拟定最佳锚点 (L*, R*)，确保提取集合 W* 能够毫无遗漏地覆盖特定的高危违约模式 T = {target_pattern}（在合同中呈连续条款出现）。

质询方式 Q(L, R, P)：
- L, R：条款锚点编号（1 到 {n}）
- P：审查的风险模式，长度为 2 到 4（A 到 E）

系统裁定“是”或“否”：
- 依当前提取规则和 (L, R) 计算审查集合 W
- 核查模式 P 是否在合同序列中连续存在，并且涵盖的条款均属于集合 W
- 如完全包含则裁定“是”，否则“否”。

注意：风险模式 P 必须为顺次排列的连续条款。

## 质询与裁决格式
请使用 XML 标签履行操作：
- 质询（如 L=3, R=7, P=ABD）：
<query>3,7,ABD</query>

最终出具审查裁决（指明规则与锚点）：
<answer>rule=α, L=3, R=10</answer>
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
Welcome to the "Intelligent Compliance and Risk Review System".

The system is parsing a core contract, comprising a risk rating sequence S of {n} continuous clause segments, categorized into {{A, B, C, D, E}}. The dossier sequence is:
{sequence}

The review engine employs a "Clause Targeted Extraction Mechanism", mapping designated clause anchors (L, R) to a related review set W. Mechanisms consist of three statutory rules: α, β, and γ (mapping logic is strictly confidential).

Please fulfill your review duties:
1. Submit verification queries to deduce the active extraction rule (α, β, or γ).
2. Draft the optimal anchors (L*, R*) ensuring the extraction set W* comprehensively covers a specific high-risk default pattern T = {target_pattern} (appearing as continuous clauses).

Query Format Q(L, R, P):
- L, R: Clause anchor numbers (1 to {n})
- P: Risk pattern under review, length 2 to 4 (A to E)

System Ruling ("Yes" or "No"):
- Computes review set W via the active rule and (L, R).
- Verifies if pattern P exists continuously in the contract and all covered clauses belong to W.
- Rules "Yes" if completely contained, else "No".

Note: Risk pattern P must represent sequentially arranged clauses.

## Query & Ruling Format
Perform operations using XML tags:
- Query (e.g., L=3, R=7, P=ABD):
<query>3,7,ABD</query>

Issue the final review ruling (specifying rule and anchors):
<answer>rule=α, L=3, R=10</answer>
"""

    tags = ["answer", "query"]

    # 1. 类属性配置
    reasoning_type = "溯因推理"
    data_structure = "序列"

    # 五种难度配置
    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 10,
                "sequence": "1:A, 2:B, 3:D, 4:C, 5:A, 6:E, 7:B, 8:D, 9:C, 10:E",
                "sequence_list": ["A", "B", "D", "C", "A", "E", "B", "D", "C", "E"],
                "target_pattern": "A, B, D, C",
                "target_list": ["A", "B", "D", "C"],
                "rule_type": "α",
            },
            2: {
                "n": 12,
                "sequence": "1:C, 2:A, 3:B, 4:D, 5:C, 6:E, 7:A, 8:B, 9:D, 10:C, 11:E, 12:A",
                "sequence_list": ["C", "A", "B", "D", "C", "E", "A", "B", "D", "C", "E", "A"],
                "target_pattern": "A, B, D, C",
                "target_list": ["A", "B", "D", "C"],
                "rule_type": "β",
            },
            3: {
                "n": 14,
                "sequence": "1:A, 2:B, 3:C, 4:A, 5:D, 6:E, 7:A, 8:B, 9:D, 10:C, 11:A, 12:B, 13:C, 14:D",
                "sequence_list": ["A", "B", "C", "A", "D", "E", "A", "B", "D", "C", "A", "B", "C", "D"],
                "target_pattern": "A, B, D, C",
                "target_list": ["A", "B", "D", "C"],
                "rule_type": "γ",
            },
            4: {
                "n": 16,
                "sequence": "1:D, 2:E, 3:A, 4:A, 5:B, 6:D, 7:C, 8:E, 9:A, 10:B, 11:D, 12:C, 13:E, 14:A, 15:B, 16:C",
                "sequence_list": ["D", "E", "A", "A", "B", "D", "C", "E", "A", "B", "D", "C", "E", "A", "B", "C"],
                "target_pattern": "A, B, D, C",
                "target_list": ["A", "B", "D", "C"],
                "rule_type": "α",
            },
            5: {
                "n": 18,
                "sequence": "1:B, 2:D, 3:C, 4:E, 5:A, 6:B, 7:D, 8:A, 9:C, 10:E, 11:A, 12:B, 13:D, 14:C, 15:E, 16:A, 17:D, 18:B",
                "sequence_list": ["B", "D", "C", "E", "A", "B", "D", "A", "C", "E", "A", "B", "D", "C", "E", "A", "D", "B"],
                "target_pattern": "A, B, D, C",
                "target_list": ["A", "B", "D", "C"],
                "rule_type": "γ",
            },
        },
        "en": {
            1: {
                "n": 10,
                "sequence": "1:A, 2:B, 3:D, 4:C, 5:A, 6:E, 7:B, 8:D, 9:C, 10:E",
                "sequence_list": ["A", "B", "D", "C", "A", "E", "B", "D", "C", "E"],
                "target_pattern": "A, B, D, C",
                "target_list": ["A", "B", "D", "C"],
                "rule_type": "α",
            },
            2: {
                "n": 12,
                "sequence": "1:C, 2:A, 3:B, 4:D, 5:C, 6:E, 7:A, 8:B, 9:D, 10:C, 11:E, 12:A",
                "sequence_list": ["C", "A", "B", "D", "C", "E", "A", "B", "D", "C", "E", "A"],
                "target_pattern": "A, B, D, C",
                "target_list": ["A", "B", "D", "C"],
                "rule_type": "β",
            },
            3: {
                "n": 14,
                "sequence": "1:A, 2:B, 3:C, 4:A, 5:D, 6:E, 7:A, 8:B, 9:D, 10:C, 11:A, 12:B, 13:C, 14:D",
                "sequence_list": ["A", "B", "C", "A", "D", "E", "A", "B", "D", "C", "A", "B", "C", "D"],
                "target_pattern": "A, B, D, C",
                "target_list": ["A", "B", "D", "C"],
                "rule_type": "γ",
            },
            4: {
                "n": 16,
                "sequence": "1:D, 2:E, 3:A, 4:A, 5:B, 6:D, 7:C, 8:E, 9:A, 10:B, 11:D, 12:C, 13:E, 14:A, 15:B, 16:C",
                "sequence_list": ["D", "E", "A", "A", "B", "D", "C", "E", "A", "B", "D", "C", "E", "A", "B", "C"],
                "target_pattern": "A, B, D, C",
                "target_list": ["A", "B", "D", "C"],
                "rule_type": "α",
            },
            5: {
                "n": 18,
                "sequence": "1:B, 2:D, 3:C, 4:E, 5:A, 6:B, 7:D, 8:A, 9:C, 10:E, 11:A, 12:B, 13:D, 14:C, 15:E, 16:A, 17:D, 18:B",
                "sequence_list": ["B", "D", "C", "E", "A", "B", "D", "A", "C", "E", "A", "B", "D", "C", "E", "A", "D", "B"],
                "target_pattern": "A, B, D, C",
                "target_list": ["A", "B", "D", "C"],
                "rule_type": "γ",
            },
        },
    }

    def __init__(self, config):
        self.query_count = 0
        self.max_queries = 8
        super().__init__(config)

    def _initialize_game(self):
        """初始化游戏：根据难度和语言选择配置"""
        lang = self.config.language
        diff = int(self.config.difficulty)

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        self._game_info["n"] = cfg["n"]
        self._game_info["sequence"] = cfg["sequence"]
        self._game_info["target_pattern"] = cfg["target_pattern"]
        
        # 内部使用的序列列表（1-indexed，所以在index 0放一个占位符）
        self.sequence = [""] + cfg["sequence_list"]  # 1-indexed
        self.n = cfg["n"]
        self.target = cfg["target_list"]
        self.rule_type = cfg["rule_type"]

    def _compute_index_set(self, L, R, rule):
        """根据规则类型计算索引集合 W"""
        if rule == "α":
            # 线性有向闭区间：L <= R 时为 [L, R]，否则为空集
            if L <= R:
                return set(range(L, R + 1))
            else:
                return set()
        elif rule == "β":
            # 线性无向闭区间：[min(L,R), max(L,R)]
            return set(range(min(L, R), max(L, R) + 1))
        elif rule == "γ":
            # 环形闭区间
            if L <= R:
                return set(range(L, R + 1))
            else:
                # L > R：从 L 到 n，再从 1 到 R
                return set(range(L, self.n + 1)) | set(range(1, R + 1))
        else:
            raise ValueError(f"Unknown rule type: {rule}")

    def _find_pattern_in_sequence(self, pattern):
        """找到模式 P 在序列 S 中所有线性连续出现的起始位置"""
        positions = []
        pattern_len = len(pattern)
        for i in range(1, self.n - pattern_len + 2):
            match = True
            for j in range(pattern_len):
                if self.sequence[i + j] != pattern[j]:
                    match = False
                    break
            if match:
                positions.append(i)
        return positions

    def _check_query(self, L, R, pattern, rule):
        """检查查询 Q(L, R, P) 是否满足条件"""
        # 计算索引集合 W
        W = self._compute_index_set(L, R, rule)
        
        # 找到模式在序列中的所有出现
        positions = self._find_pattern_in_sequence(pattern)
        
        # 检查是否存在某个出现完全包含在 W 中
        pattern_len = len(pattern)
        for start_pos in positions:
            occurrence_indices = set(range(start_pos, start_pos + pattern_len))
            if occurrence_indices.issubset(W):
                return True
        return False

    def evaluate(self, parsed_info):
        """评估最终答案"""
        raw_ans = parsed_info["answer"]
        
        # 解析答案：rule=X, L=Y, R=Z
        kv_pairs = [x.strip() for x in raw_ans.split(",")]
        ans_dict = {}
        for kv in kv_pairs:
            if "=" not in kv:
                continue
            k, v = kv.split("=", 1)
            ans_dict[k.strip()] = v.strip()
        
        if "rule" not in ans_dict or "L" not in ans_dict or "R" not in ans_dict:
            return False
        
        # 1. 检查规则类型是否正确
        if ans_dict["rule"] != self.rule_type:
            return False
        
        # 2. 检查 L* 和 R* 是否有效
        try:
            L_star = int(ans_dict["L"])
            R_star = int(ans_dict["R"])
            if L_star < 1 or L_star > self.n or R_star < 1 or R_star > self.n:
                return False
        except:
            return False
        
        # 3. 检查 W* 是否包含目标模式 T 的某个线性出现
        W_star = self._compute_index_set(L_star, R_star, self.rule_type)
        target_positions = self._find_pattern_in_sequence(self.target)
        
        target_len = len(self.target)
        for start_pos in target_positions:
            occurrence_indices = set(range(start_pos, start_pos + target_len))
            if occurrence_indices.issubset(W_star):
                return True
        
        return False

    def _cf_core_produce(self, parsed_info):
        """生成对查询的响应（核心逻辑）"""
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
            error_format = "错误：查询格式无效。"
            error_range = "错误：索引超出范围。"
            error_pattern = "错误：模式长度必须在 2 到 4 之间。"
            error_max = "错误：已达到最大查询次数限制。"
        else:
            yes_res, no_res = "Yes", "No"
            error_format = "Error: Invalid query format."
            error_range = "Error: Index out of range."
            error_pattern = "Error: Pattern length must be between 2 and 4."
            error_max = "Error: Maximum query limit reached."

        if "query" in parsed_info:
            # 检查查询次数
            if self.query_count >= self.max_queries:
                self.state.set_state("failed", "over_max_queries")
                return error_max
            
            self.query_count += 1
            
            # 解析查询：L,R,P
            try:
                raw_query = parsed_info["query"].strip()
                parts = [x.strip() for x in raw_query.split(",")]
                if len(parts) != 3:
                    return error_format
                
                L = int(parts[0])
                R = int(parts[1])
                P = parts[2]
            except ValueError:
                return error_format
                
            # 验证索引范围
            if L < 1 or L > self.n or R < 1 or R > self.n:
                return error_range
            
            # 验证模式长度
            if len(P) < 2 or len(P) > 4:
                return error_pattern
            
            # 验证模式字母
            pattern_list = list(P)
            for char in pattern_list:
                if char not in ['A', 'B', 'C', 'D', 'E']:
                    return error_format
            
            # 执行查询逻辑
            result = self._check_query(L, R, pattern_list, self.rule_type)
            return yes_res if result else no_res
            
        else:
            raise ValueError("No valid query tag found.")

    def _cf_make_wrong(self, correct):
        # 1. 纯整数处理
        if correct.isdigit():
            return str(int(correct) + 1)
        
        # 2. 中文关键词替换
        if correct == "是": return "否"
        if correct == "否": return "是"
        
        # 3. 英文关键词替换（忽略大小写，保持原始大小写风格）
        low_c = correct.lower()
        if low_c == "yes":
            return "No" if correct[0].isupper() else "no"
        if low_c == "no":
            return "Yes" if correct[0].isupper() else "yes"
            
        # 4. 其他情况
        return correct + "_WRONG"

    def get_all_possible_queries(self) -> list[dict]:
        """
        枚举有意义的查询（只包含在序列中实际出现的模式，
        以及覆盖这些出现的有代表性的 (L, R) 对），
        以保持查询数量在合理范围内。
        """
        alphabet = ['A', 'B', 'C', 'D', 'E']
        
        if self.config.language == "zh":
            ans_yes = "是"
            ans_no = "否"
        else:
            ans_yes = "Yes"
            ans_no = "No"

        # 只生成在序列中实际出现的模式
        existing_patterns = []
        for length in range(2, 5):
            for i in range(1, self.n - length + 2):
                p = [self.sequence[i + j] for j in range(length)]
                p_str = "".join(p)
                if p_str not in [ep[0] for ep in existing_patterns]:
                    existing_patterns.append((p_str, list(p)))

        # 去重
        seen = set()
        unique_patterns = []
        for p_str, p_list in existing_patterns:
            if p_str not in seen:
                seen.add(p_str)
                unique_patterns.append((p_str, p_list))

        # 选择有代表性的 (L, R) 对：边界值 + 均匀采样
        lr_pairs = set()
        # 始终包含一些关键的 (L, R) 对
        for v in [1, self.n]:
            for v2 in [1, self.n]:
                lr_pairs.add((v, v2))
        # 均匀采样
        step = max(1, self.n // 5)
        for L in range(1, self.n + 1, step):
            for R in range(1, self.n + 1, step):
                lr_pairs.add((L, R))
        # 也添加目标模式出现位置附近的 (L, R) 对
        target_positions = self._find_pattern_in_sequence(self.target)
        for pos in target_positions:
            end = pos + len(self.target) - 1
            for dl in range(-1, 2):
                for dr in range(-1, 2):
                    ll = max(1, min(self.n, pos + dl))
                    rr = max(1, min(self.n, end + dr))
                    lr_pairs.add((ll, rr))

        queries = []
        for L, R in sorted(lr_pairs):
            W = self._compute_index_set(L, R, self.rule_type)
            for p_str, p_list in unique_patterns:
                query_str = f"<query>{L},{R},{p_str}</query>"
                positions = self._find_pattern_in_sequence(p_list)
                is_match = False
                for start in positions:
                    occ = set(range(start, start + len(p_list)))
                    if occ.issubset(W):
                        is_match = True
                        break
                queries.append({
                    "query": query_str,
                    "answer": ans_yes if is_match else ans_no,
                })
        
        return queries