# -*- coding: utf-8 -*-

from .base import Game
import random

class PeriodicSequenceGame(Game):

    game_rule_zh = """\
我们来玩一个"周期序列推理"游戏，规则如下：

游戏设定了一个长度为 {n} 的二值序列 x[1..{n}]（索引从 1 开始），每个位置的值为 0 或 1。

序列由周期性生成规则产生：
- 存在一个周期 K（2 小于等于 K 小于等于 {max_k}）
- 存在一个余数集合 S（S 是 {{0, 1, ..., K-1}} 的非空真子集）
- {offset_hint}

生成规则为：序列中第 i 个位置的值 x_i = 1，当且仅当 (i{offset_formula}) mod K 属于集合 S，否则 x_i = 0。

你的目标是推断出{target_params}。你可以反复向我提出区间计数查询（请尽可能少地使用查询次数），我会根据真实设定如实回答：

- 区间计数查询：询问区间 [L, R] 内值为 1 的元素个数（1 小于等于 L 小于等于 R 小于等于 {n}）。

当你收集足够信息后，请提交最终答案。若答案错误或格式不符，游戏失败。

## 询问与提交答案的格式（必须严格遵守）

每次询问只能包含一个标签。请使用以下 XML 格式：

- 区间计数查询（例如查询区间 [3, 7]）：
<query_count>3,7</query_count>

提交最终答案时，必须说明周期 K、余数集合 S{offset_answer_format}，格式如下：

{answer_example}
"""

    game_rule_en = """\
Let's play a "Periodic Sequence Deduction" game. Here are the rules:

The game has set up a binary sequence x[1..{n}] of length {n} (indexed from 1), where each position has value 0 or 1.

The sequence is generated by a periodic rule:
- There exists a period K (2 less than or equal to K less than or equal to {max_k})
- There exists a remainder set S (S is a non-empty proper subset of {{0, 1, ..., K-1}})
- {offset_hint}

Generation rule: The value at position i is x_i = 1 if and only if (i{offset_formula}) mod K belongs to set S, otherwise x_i = 0.

Your goal is to infer{target_params}. You can repeatedly make interval count queries (use as few queries as possible), and I will answer truthfully based on the actual setup:

- Interval Count Query: Ask for the count of 1s in interval [L, R] (1 less than or equal to L less than or equal to R less than or equal to {n}).

When you have gathered enough information, submit your final answer. If the answer is wrong or the format is invalid, the game fails.

## Query and Answer Format (must strictly follow)

Each query must contain only one tag. Use the following XML format:

- Interval Count Query (e.g., querying interval [3, 7]):
<query_count>3,7</query_count>

When submitting the final answer, specify period K, remainder set S{offset_answer_format}, using this format:

{answer_example}
"""

    contextualized_rule_zh_1 = """\
欢迎使用“城市交通信号链路推演系统”。

系统已为您接入一段主干道上长度为 {n} 的红绿灯时段放行状态序列（时段索引从 1 到 {n}），每个时段的状态记录为 0（红灯拥堵）或 1（绿灯畅通）。

该信号灯的绿灯放行呈现严格的周期性控制规律：
- 存在一个信号控制周期 K（2 小于等于 K 小于等于 {max_k}）
- 存在一个绿灯相位余数集合 S（S 是 {{0, 1, ..., K-1}} 的非空真子集）
- {offset_hint}

放行状态生成规则为：第 i 个时段为绿灯（x_i = 1），当且仅当 (i{offset_formula}) mod K 属于集合 S，否则为红灯（x_i = 0）。

您的任务是作为交通规划师，推断出控制该路段的{target_params}。您可以反复向指挥中心提出时段区间统计查询（请尽可能优化查询次数），系统会如实反馈真实路况数据：

- 时段区间统计查询：询问在时间段 [L, R] 内共有多少个时段处于绿灯畅通状态（1 小于等于 L 小于等于 R 小于等于 {n}）。

当您完成分析后，请提交最终的信号灯配置参数。若推演错误或报告格式不符，演练将直接判定为失败。

## 询问与提交答案的格式（必须严格遵守）

每次指令只能包含一个操作标签。请使用以下 XML 格式：

- 时段区间统计查询（例如查询时段 [3, 7]）：
<query_count>3,7</query_count>

提交最终分析报告时，必须说明{target_params}，包含周期 K、余数集合 S{offset_answer_format}，格式如下：

{answer_example}
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
Welcome to the "Urban Traffic Signal Link Deduction System".

The system has connected you to a traffic light state sequence of length {n} on a main road (time slot index from 1 to {n}), where each slot's state is recorded as 0 (red light/congested) or 1 (green light/clear).

The green light state strictly follows a periodic control rule:
- There exists a signal control period K (2 less than or equal to K less than or equal to {max_k})
- There exists a green light phase remainder set S (S is a non-empty proper subset of {{0, 1, ..., K-1}})
- {offset_hint}

The state generation rule is: the i-th time slot is green (x_i = 1) if and only if (i{offset_formula}) mod K belongs to set S, otherwise it is red (x_i = 0).

Your task as a traffic planner is to deduce the {target_params} controlling this road section. You can repeatedly submit time interval count queries to the command center (please optimize the number of queries), and the system will provide actual traffic data:

- Time Interval Count Query: Ask for the total number of green light slots within the time interval [L, R] (1 less than or equal to L less than or equal to R less than or equal to {n}).

Once you have gathered sufficient intelligence, please submit the final signal configuration. The simulation will fail if the deduction is incorrect or the report format is invalid.

## Query and Answer Format (must strictly follow)

Each command must contain only one operation tag. Use the following XML format:

- Time Interval Count Query (e.g., querying interval [3, 7]):
<query_count>3,7</query_count>

When submitting the final analysis report, you must specify {target_params}, including period K, remainder set S{offset_answer_format}, using this format:

{answer_example}
"""

    contextualized_rule_zh_2 = """\
欢迎使用“慢性病周期性发作规律分析系统”。

系统已录入某患者长达 {n} 天的连续临床症状监测序列（天数索引从 1 到 {n}），每一天的发病状态记录为 0（无症状）或 1（症状发作）。

该疾病的发作呈现潜在的生物钟周期性规律：
- 存在一个疾病生物钟周期 K（2 小于等于 K 小于等于 {max_k}）
- 存在一个易感余数集合 S（S 是 {{0, 1, ..., K-1}} 的非空真子集）
- {offset_hint}

发病状态的生成规则为：第 i 天症状发作（x_i = 1），当且仅当 (i{offset_formula}) mod K 属于集合 S，否则该天无症状（x_i = 0）。

您的任务是作为主治医师，推断出该患者的{target_params}。您可以反复向医疗数据库提出病程区间频次查询（请尽量减少对系统算力的占用），数据库将依据临床记录真实作答：

- 病程区间频次查询：询问在第 L 天到第 R 天的观察区间 [L, R] 内，共有多少天出现了症状发作（1 小于等于 L 小于等于 R 小于等于 {n}）。

当您查明病理规律后，请提交最终的诊断参数。若诊断错误或处方格式不符，病例分析将以失败告终。

## 询问与提交答案的格式（必须严格遵守）

每次调阅只能包含一个检索标签。请使用以下 XML 格式：

- 病程区间频次查询（例如查询第 3 到第 7 天）：
<query_count>3,7</query_count>

提交最终诊断报告时，必须说明{target_params}，包含周期 K、余数集合 S{offset_answer_format}，格式如下：

{answer_example}
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
Welcome to the "Chronic Disease Periodic Onset Analysis System".

The system has loaded a continuous clinical symptom monitoring sequence of length {n} days for a patient (day index from 1 to {n}), where each day's onset state is recorded as 0 (asymptomatic) or 1 (symptom onset).

The onset of the disease exhibits a latent biological clock periodic pattern:
- There exists a disease biological clock period K (2 less than or equal to K less than or equal to {max_k})
- There exists a susceptible remainder set S (S is a non-empty proper subset of {{0, 1, ..., K-1}})
- {offset_hint}

The onset state generation rule is: the patient experiences symptom onset on the i-th day (x_i = 1) if and only if (i{offset_formula}) mod K belongs to set S, otherwise asymptomatic (x_i = 0).

Your task as the attending physician is to deduce the {target_params} for this patient. You can repeatedly make disease course interval frequency queries to the medical database (please minimize computing resource usage), and the database will answer truthfully based on clinical records:

- Disease Course Interval Frequency Query: Ask for the total number of onset days within the observation interval [L, R] (1 less than or equal to L less than or equal to R less than or equal to {n}).

When you have uncovered the pathological pattern, submit your final diagnostic parameters. If the diagnosis is incorrect or the prescription format is invalid, the case analysis fails.

## Query and Answer Format (must strictly follow)

Each retrieval must contain only one search tag. Use the following XML format:

- Disease Course Interval Frequency Query (e.g., querying days [3, 7]):
<query_count>3,7</query_count>

When submitting the final diagnostic report, you must specify {target_params}, including period K, remainder set S{offset_answer_format}, using this format:

{answer_example}
"""

    contextualized_rule_zh_3 = """\
欢迎登录“自适应在线课程大纲解析平台”。

课程库为您分配了一门包含 {n} 个连续学习模块的教学序列（模块索引从 1 到 {n}），每个模块的属性被标注为 0（普通理论学习）或 1（高强度考核测评）。

该课程的考核节点设置遵循着严格的教学周期编排规律：
- 存在一个教学编排周期 K（2 小于等于 K 小于等于 {max_k}）
- 存在一个考核位置余数集合 S（S 是 {{0, 1, ..., K-1}} 的非空真子集）
- {offset_hint}

模块属性的生成规则为：第 i 个模块为考核测评（x_i = 1），当且仅当 (i{offset_formula}) mod K 属于集合 S，否则为普通学习（x_i = 0）。

您的任务是作为教研专家，逆向推断出该大纲的{target_params}。您可以反复向平台提出进度区间考评数量查询（请尽量用最少的查询量完成任务），平台会根据实际教学大纲如实反馈：

- 进度区间考评数量查询：询问在学习模块区间 [L, R] 内，共包含了多少个考核测评模块（1 小于等于 L 小于等于 R 小于等于 {n}）。

当您摸清考核排布后，请提交最终的大纲规律。若推演错误或提交格式不合规，大纲解析任务将直接失败。

## 询问与提交答案的格式（必须严格遵守）

每次交互只能包含一个解析标签。请使用以下 XML 格式：

- 进度区间考评数量查询（例如查询模块 [3, 7]）：
<query_count>3,7</query_count>

提交最终大纲规律时，必须说明{target_params}，包含周期 K、余数集合 S{offset_answer_format}，格式如下：

{answer_example}
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Welcome to the "Adaptive Online Course Syllabus Analysis Platform".

The course repository has assigned you a teaching sequence consisting of {n} consecutive learning modules (module index from 1 to {n}), where each module's attribute is marked as 0 (standard theoretical learning) or 1 (high-intensity assessment).

The placement of assessment nodes follows a strict teaching period scheduling rule:
- There exists a teaching scheduling period K (2 less than or equal to K less than or equal to {max_k})
- There exists an assessment position remainder set S (S is a non-empty proper subset of {{0, 1, ..., K-1}})
- {offset_hint}

The module attribute generation rule is: the i-th module is an assessment (x_i = 1) if and only if (i{offset_formula}) mod K belongs to set S, otherwise standard learning (x_i = 0).

Your task as an educational research expert is to reverse-engineer the {target_params} of this syllabus. You can repeatedly submit progress interval assessment count queries to the platform (please complete the task with minimal queries), and the platform will provide true feedback based on the actual syllabus:

- Progress Interval Assessment Count Query: Ask for the total number of assessment modules contained within the learning module interval [L, R] (1 less than or equal to L less than or equal to R less than or equal to {n}).

When you have grasped the assessment layout, submit the final syllabus pattern. If the deduction is wrong or the submission format is non-compliant, the syllabus analysis task fails.

## Query and Answer Format (must strictly follow)

Each interaction must contain only one analysis tag. Use the following XML format:

- Progress Interval Assessment Count Query (e.g., querying modules [3, 7]):
<query_count>3,7</query_count>

When submitting the final syllabus pattern, you must specify {target_params}, including period K, remainder set S{offset_answer_format}, using this format:

{answer_example}
"""

    contextualized_rule_zh_4 = """\
欢迎操作“智能流水线质检站分布反演系统”。

系统监控到一条包含 {n} 个连续工位的自动化流水线序列（工位编号从 1 到 {n}），每个工位的设备配置被记录为 0（普通加工站）或 1（高精度质检站）。

为了配合设备的维保周期，质检站的架设符合固定的工业排布规律：
- 存在一个流水线排布周期 K（2 小于等于 K 小于等于 {max_k}）
- 存在一个质检工位余数集合 S（S 是 {{0, 1, ..., K-1}} 的非空真子集）
- {offset_hint}

工位配置的生成规则为：第 i 个工位装配为质检站（x_i = 1），当且仅当 (i{offset_formula}) mod K 属于集合 S，否则为普通加工站（x_i = 0）。

您的任务是作为工业自动化工程师，推测出该产线的{target_params}。您可以反复向控制中枢发起工序段质检站计数查询（请在保证效率的前提下减少查询），中枢会读取真实硬件配置并返回数据：

- 工序段质检站计数查询：询问在工位编号区间 [L, R] 内，合计部署了多少个质检站（1 小于等于 L 小于等于 R 小于等于 {n}）。

当您测算出流水线的排布参数后，请进行最终录入。若参数错误或指令格式异常，系统校准程序将报错终止。

## 询问与提交答案的格式（必须严格遵守）

每次通信只能包含一个指令标签。请使用以下 XML 格式：

- 工序段质检站计数查询（例如查询工位 [3, 7]）：
<query_count>3,7</query_count>

提交最终排布参数时，必须说明{target_params}，包含周期 K、余数集合 S{offset_answer_format}，格式如下：

{answer_example}
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
Welcome to the "Smart Assembly Line Quality Inspection Station Distribution Inversion System".

The system is monitoring an automated assembly line sequence containing {n} consecutive workstations (station number from 1 to {n}), where each station's equipment configuration is recorded as 0 (standard processing station) or 1 (high-precision quality inspection station).

To align with equipment maintenance cycles, the installation of inspection stations adheres to a fixed industrial layout rule:
- There exists an assembly line layout period K (2 less than or equal to K less than or equal to {max_k})
- There exists an inspection station remainder set S (S is a non-empty proper subset of {{0, 1, ..., K-1}})
- {offset_hint}

The station configuration generation rule is: the i-th station is equipped as an inspection station (x_i = 1) if and only if (i{offset_formula}) mod K belongs to set S, otherwise it is a standard processing station (x_i = 0).

Your task as an industrial automation engineer is to deduce the {target_params} of this production line. You can repeatedly initiate process segment inspection station count queries to the control hub (please reduce queries while ensuring efficiency), and the hub will read the true hardware configuration and return data:

- Process Segment Inspection Station Count Query: Ask for the total number of inspection stations deployed within the workstation number interval [L, R] (1 less than or equal to L less than or equal to R less than or equal to {n}).

When you have calculated the assembly line's layout parameters, please make the final entry. If the parameters are incorrect or the command format is abnormal, the system calibration program will terminate with an error.

## Query and Answer Format (must strictly follow)

Each communication must contain only one command tag. Use the following XML format:

- Process Segment Inspection Station Count Query (e.g., querying stations [3, 7]):
<query_count>3,7</query_count>

When submitting the final layout parameters, you must specify {target_params}, including period K, remainder set S{offset_answer_format}, using this format:

{answer_example}
"""

    contextualized_rule_zh_5 = """\
欢迎登入“经侦案件异常资金流追踪系统”。

专案组调取了嫌疑企业长达 {n} 个月的连续资金往来序列（月份索引从 1 到 {n}），每个月的账户异动状态被审计为 0（财务正常）或 1（存在异常资金转移）。

经初步排查，该犯罪团伙的洗钱行为具有极其隐秘的周期性特征：
- 存在一个固定的作案周期 K（2 小于等于 K 小于等于 {max_k}）
- 存在一个异常转移月份的余数集合 S（S 是 {{0, 1, ..., K-1}} 的非空真子集）
- {offset_hint}

异动状态的生成规则为：第 i 个月发生异常资金转移（x_i = 1），当且仅当 (i{offset_formula}) mod K 属于集合 S，否则财务正常（x_i = 0）。

您的任务是作为经侦法务专家，精准反推出该洗钱网络的{target_params}。您可以反复向审计数据库提交财报区间异常频次查询（请尽量少地惊动系统底层的审计警报），数据库将根据真实账本反馈涉案情况：

- 财报区间异常频次查询：询问在第 L 个月到第 R 个月的侦查区间 [L, R] 内，共有多少个月份发生了异常资金转移（1 小于等于 L 小于等于 R 小于等于 {n}）。

当您锁定洗钱规律后，请提交最终的结案报告。若规律指控错误或文书格式不符，案件侦破将被判定为失败。

## 询问与提交答案的格式（必须严格遵守）

每次取证只能包含一个调证标签。请使用以下 XML 格式：

- 财报区间异常频次查询（例如查询第 3 到 7 个月）：
<query_count>3,7</query_count>

提交最终结案报告时，必须说明{target_params}，包含周期 K、余数集合 S{offset_answer_format}，格式如下：

{answer_example}
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
Welcome to the "Economic Investigation Abnormal Fund Flow Tracking System".

The special task force has retrieved a continuous financial transaction sequence of the suspect enterprise over {n} months (month index from 1 to {n}), where each month's account anomaly state is audited as 0 (financially normal) or 1 (abnormal fund transfer present).

Initial screening reveals that the criminal syndicate's money laundering activities exhibit a highly stealthy periodic characteristic:
- There exists a fixed operational period K (2 less than or equal to K less than or equal to {max_k})
- There exists a remainder set of abnormal transfer months S (S is a non-empty proper subset of {{0, 1, ..., K-1}})
- {offset_hint}

The anomaly state generation rule is: an abnormal fund transfer occurs in the i-th month (x_i = 1) if and only if (i{offset_formula}) mod K belongs to set S, otherwise it is financially normal (x_i = 0).

Your task as an economic investigation legal expert is to accurately reverse-engineer the {target_params} of this money laundering network. You can repeatedly submit financial report interval anomaly frequency queries to the audit database (please minimize triggering underlying audit alerts), and the database will feedback the case status based on true ledgers:

- Financial Report Interval Anomaly Frequency Query: Ask for the total number of months abnormal fund transfers occurred within the investigation interval [L, R] (1 less than or equal to L less than or equal to R less than or equal to {n}).

Once you lock onto the money laundering pattern, submit the final case closure report. If the pattern accusation is wrong or the document format is non-compliant, the case resolution will be deemed a failure.

## Query and Answer Format (must strictly follow)

Each evidence collection must contain only one retrieval tag. Use the following XML format:

- Financial Report Interval Anomaly Frequency Query (e.g., querying months [3, 7]):
<query_count>3,7</query_count>

When submitting the final case closure report, you must specify {target_params}, including period K, remainder set S{offset_answer_format}, using this format:

{answer_example}
"""

    tags = ["answer", "query_count"]
    reasoning_type = "归纳推理"
    data_structure = "序列"

    # 难度配置说明：
    # 1 (简单)       - N=12, K=3, 无偏移, S包含1个元素
    # 2 (中等偏下)   - N=18, K=4, 无偏移, S包含2个元素
    # 3 (中等偏上)   - N=20, K=5, 无偏移, S包含2个元素
    # 4 (较难)       - N=24, K=6, 有偏移O, S包含3个元素
    # 5 (难)         - N=30, K=7, 有偏移O, S包含3个元素

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 12,
                "k": 3,
                "s": [1],
                "o": 0,
                "has_offset": False,
            },
            2: {
                "n": 18,
                "k": 4,
                "s": [1, 2],
                "o": 0,
                "has_offset": False,
            },
            3: {
                "n": 20,
                "k": 5,
                "s": [0, 3],
                "o": 0,
                "has_offset": False,
            },
            4: {
                "n": 24,
                "k": 6,
                "s": [1, 2, 4],
                "o": 2,
                "has_offset": True,
            },
            5: {
                "n": 30,
                "k": 7,
                "s": [0, 2, 5],
                "o": 3,
                "has_offset": True,
            },
        },
        "en": {
            1: {
                "n": 12,
                "k": 3,
                "s": [1],
                "o": 0,
                "has_offset": False,
            },
            2: {
                "n": 18,
                "k": 4,
                "s": [1, 2],
                "o": 0,
                "has_offset": False,
            },
            3: {
                "n": 20,
                "k": 5,
                "s": [0, 3],
                "o": 0,
                "has_offset": False,
            },
            4: {
                "n": 24,
                "k": 6,
                "s": [1, 2, 4],
                "o": 2,
                "has_offset": True,
            },
            5: {
                "n": 30,
                "k": 7,
                "s": [0, 2, 5],
                "o": 3,
                "has_offset": True,
            },
        },
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        """
        初始化游戏配置：根据语言和难度加载参数，生成真实序列
        """
        lang = self.config.language
        diff = int(self.config.difficulty)

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        
        # 游戏参数
        self.n = cfg["n"]
        self.k = cfg["k"]
        self.s = set(cfg["s"])  # 余数集合
        self.o = cfg["o"]  # 偏移量
        self.has_offset = cfg["has_offset"]
        
        # 生成真实序列（索引从1开始，所以用None占位0位置）
        self.sequence = [None]  # 索引0不使用
        for i in range(1, self.n + 1):
            val = 1 if ((i + self.o) % self.k) in self.s else 0
            self.sequence.append(val)
        
        # 查询计数器
        self.query_count = 0
        
        # 填充 game_info 用于规则模板
        self._game_info["n"] = self.n
        self._game_info["max_k"] = self.n // 2
        
        if self.has_offset:
            if lang == "zh":
                self._game_info["offset_hint"] = "存在一个偏移量 O（0 小于等于 O 小于 K）"
                self._game_info["offset_formula"] = "+O"
                self._game_info["target_params"] = "周期 K、余数集合 S 以及偏移量 O"
                self._game_info["offset_answer_format"] = "和偏移量 O"
                self._game_info["answer_example"] = "<answer>K=5, S=0,2, O=1</answer>"
            else:
                self._game_info["offset_hint"] = "there exists an offset O (0 less than or equal to O less than K)"
                self._game_info["offset_formula"] = "+O"
                self._game_info["target_params"] = " period K, remainder set S, and offset O"
                self._game_info["offset_answer_format"] = " and offset O"
                self._game_info["answer_example"] = "<answer>K=5, S=0,2, O=1</answer>"
        else:
            if lang == "zh":
                self._game_info["offset_hint"] = "偏移量 O = 0（无偏移）"
                self._game_info["offset_formula"] = ""
                self._game_info["target_params"] = "周期 K 和余数集合 S"
                self._game_info["offset_answer_format"] = ""
                self._game_info["answer_example"] = "<answer>K=4, S=1,2</answer>"
            else:
                self._game_info["offset_hint"] = "offset O = 0 (no offset)"
                self._game_info["offset_formula"] = ""
                self._game_info["target_params"] = " period K and remainder set S"
                self._game_info["offset_answer_format"] = ""
                self._game_info["answer_example"] = "<answer>K=4, S=1,2</answer>"

    def evaluate(self, parsed_info):
        """
        评估最终答案是否正确。
        支持等价参数组合（不同的 O 和 S 组合可能生成相同的序列）。
        """
        raw_ans = parsed_info["answer"]
        
        try:
            # 解析键值对
            parts = [x.strip() for x in raw_ans.split(",")]
            ans_dict = {}
            current_key = None
            current_val = []
            
            for part in parts:
                if "=" in part:
                    # 保存之前的键值对
                    if current_key and current_val:
                        ans_dict[current_key] = ",".join(current_val)
                    # 解析新的键值对
                    k, v = part.split("=", 1)
                    current_key = k.strip()
                    current_val = [v.strip()]
                else:
                    # 继续累加到当前值（处理 S=1,2,3 的情况）
                    if current_key:
                        current_val.append(part.strip())
            
            # 保存最后一个键值对
            if current_key and current_val:
                ans_dict[current_key] = ",".join(current_val)
            
            # 检查必需字段
            if "K" not in ans_dict or "S" not in ans_dict:
                return False
            
            if self.has_offset and "O" not in ans_dict:
                return False
            
            # 解析 K
            submitted_k = int(ans_dict["K"])
            
            # 解析 S（升序排列的余数集合）
            s_str = ans_dict["S"]
            submitted_s = set(int(x.strip()) for x in s_str.split(",") if x.strip())
            
            # 解析 O（如果有偏移版）
            if self.has_offset:
                submitted_o = int(ans_dict["O"])
            else:
                submitted_o = 0
                
            # 验证 K 和 S 的合法性
            if not (2 <= submitted_k <= self.n // 2):
                return False
            if len(submitted_s) == 0 or len(submitted_s) >= submitted_k:
                return False
                
            # 验证生成的序列是否与真实序列一致
            for i in range(1, self.n + 1):
                val = 1 if ((i + submitted_o) % submitted_k) in submitted_s else 0
                if val != self.sequence[i]:
                    return False
            
            return True
            
        except Exception as e:
            # 解析失败
            return False

    def _cf_core_produce(self, parsed_info):
        """
        处理区间计数查询，返回指定区间内值为 1 的元素个数（原始核心逻辑）
        """
        if "query_count" not in parsed_info:
            if self.config.language == "zh":
                return "错误：未识别到有效的查询标签。"
            else:
                return "Error: No valid query tag found."
        
        try:
            # 解析区间 [L, R]
            raw = parsed_info["query_count"].strip()
            parts = [x.strip() for x in raw.split(",")]
            
            if len(parts) != 2:
                raise ValueError("Invalid interval format")
            
            L = int(parts[0])
            R = int(parts[1])
            
            # 验证区间合法性
            if L < 1 or R > self.n or L > R:
                if self.config.language == "zh":
                    return f"错误：区间不合法。要求 1 小于等于 L 小于等于 R 小于等于 {self.n}。"
                else:
                    return f"Error: Invalid interval. Required 1 <= L <= R <= {self.n}."
            
            # 计算区间内 1 的个数
            count = sum(self.sequence[i] for i in range(L, R + 1))
            self.query_count += 1
            
            return str(count)
            
        except Exception as e:
            if self.config.language == "zh":
                return "错误：查询格式无效，请使用 <query_count>L,R</query_count> 格式。"
            else:
                return "Error: Invalid query format. Please use <query_count>L,R</query_count> format."

    def _cf_make_wrong(self, correct: str) -> str:
        if correct.isdigit() or (correct.startswith("-") and correct[1:].isdigit()):
            return str(int(correct) + 1)
        
        # 关键词替换
        if self.config.language == "zh":
            if "是" in correct:
                return correct.replace("是", "否")
            if "否" in correct:
                return correct.replace("否", "是")
        else:
            if "Yes" in correct:
                return correct.replace("Yes", "No")
            if "yes" in correct:
                return correct.replace("yes", "no")
            if "No" in correct:
                return correct.replace("No", "Yes")
            if "no" in correct:
                return correct.replace("no", "yes")
        
        # 默认追加
        return correct + "_WRONG"

    def get_all_possible_queries(self) -> list[dict]:
        """
        枚举所有合法查询并返回对应的正确答案。

        Returns:
            list of dict, 每项格式：
            {
                "query" : str,   # 查询内容字符串，与游戏中 parsed_info["query"] 的值格式一致
                "answer": str,   # 调用游戏逻辑后得到的正确答案字符串
            }
        """
        queries = []
        # 遍历所有合法的区间 [L, R]
        # 1 <= L <= R <= n
        for L in range(1, self.n + 1):
            for R in range(L, self.n + 1):
                # 计算区间内 1 的个数
                # self.sequence 索引从 1 开始对应实际值
                # 直接使用 self.sequence 避免修改 self.query_count
                count = sum(self.sequence[i] for i in range(L, R + 1))
                
                query_content = f"<query_count>{L},{R}</query_count>"
                queries.append({
                    "query": query_content,
                    "answer": str(count)
                })
        return queries