# -*- coding: utf-8 -*-
# 自动生成 | 模型: api/gemini-3-pro-preview
# 推理类型: 归纳推理（完全自主总结规律）：从多次反馈的样本中，总结出背后隐藏的规律/模式。例如猜拳游戏，模型需要总结对手出拳的模式。
# 数据结构: 图：存在一个由节点和边构成的图。
# 知识点:   桥判断：某条给定边是否为桥（删除后图不再连通）
# ============================================================

from .base import Game
import math

class HiddenStepBridgeGame(Game):

    game_rule_zh = """\
我们现在来玩一个"隐藏步长与桥边推理"游戏，规则如下：

游戏设定了一个无向图，顶点编号为 0 到 {n_minus_1}（共 {n} 个顶点）。图中包含以下两类边：

1. **路径边**：所有相邻顶点之间的边 (i, i+1)，其中 i 从 0 到 {n_minus_2}。
2. **隐藏边**：由一个未知的固定整数步长 s 生成（s 的范围在 2 到 {n_minus_2} 之间）。对于每个满足以下条件的 i，会加入一条隐藏边 (i, i+s)：
   - i 是 s 的倍数
   - i 小于等于 {n_minus_1} 减去 s

图始终是连通的。现在指定了一条**目标路径边** e_t = ({target}, {target_plus_1})。

**你的任务**：判断目标路径边 e_t 是否为**桥边**（即移除它后图是否会变得不连通）。

## 允许的提问方式

你可以反复向我提出以下两类问题（每次仅限一个问题）：

1. **隐藏边起点判定**：询问"顶点 i 是否存在隐藏边起点？"
   - 我会回答"是"或"否"。
   - 当且仅当 i 是 s 的倍数且 i 小于等于 {n_minus_1} 减去 s 时，回答"是"。

2. **非目标路径边移除连通性测试**：询问"若移除路径边 (x, x+1)（要求 x 不等于 {target}），图的连通分量数是多少？"
   - 我会回答"1"（仍连通，该边不是桥）或"2"（变为两个连通分量，该边是桥）。
   - 若你询问的 x 等于 {target}，我会回答"非法"且不计入有效提问。

**注意**：你至少需要进行 **3 次有效提问**后才能提交最终答案，否则答案会被视为无效。

## 提问与提交答案的格式（必须严格遵守）

每次提问只能包含一个标签，使用以下 XML 格式：

- 隐藏边起点判定（例如询问顶点 5）：
<query_hidden>5</query_hidden>

- 非目标路径边移除连通性测试（例如询问路径边起点为 3）：
<query_remove>3</query_remove>

提交最终答案时，必须说明目标边是否为桥（回答"是"或"否"），格式如下：

<answer>是</answer>

或

<answer>否</answer>
"""

    game_rule_en = """\
Let's play a "Hidden Step Bridge Inference" game. Here are the rules:

The game has an undirected graph with vertices numbered from 0 to {n_minus_1} (total {n} vertices). The graph contains two types of edges:

1. **Path edges**: All edges between adjacent vertices (i, i+1), where i ranges from 0 to {n_minus_2}.
2. **Hidden edges**: Generated by an unknown fixed integer step size s (s ranges from 2 to {n_minus_2}). For each i satisfying the following conditions, a hidden edge (i, i+s) is added:
   - i is a multiple of s
   - i is less than or equal to {n_minus_1} minus s

The graph is always connected. A **target path edge** e_t = ({target}, {target_plus_1}) has been specified.

**Your task**: Determine whether the target path edge e_t is a **bridge** (i.e., whether removing it would disconnect the graph).

## Allowed Query Types

You may repeatedly ask me the following two types of questions (one per turn):

1. **Hidden edge starting point check**: Ask "Does vertex i have a hidden edge starting point?"
   - I will answer "Yes" or "No".
   - The answer is "Yes" if and only if i is a multiple of s and i is less than or equal to {n_minus_1} minus s.

2. **Non-target path edge removal connectivity test**: Ask "If path edge (x, x+1) is removed (where x is not equal to {target}), how many connected components does the graph have?"
   - I will answer "1" (still connected, edge is not a bridge) or "2" (becomes two connected components, edge is a bridge).
   - If you query x equal to {target}, I will answer "Invalid" and it won't count as a valid query.

**Note**: You must make at least **3 valid queries** before submitting your final answer, otherwise the answer will be considered invalid.

## Query and Answer Format (strictly required)

Each query must contain only one tag. Use the following XML format:

- Hidden edge starting point check (e.g., asking about vertex 5):
<query_hidden>5</query_hidden>

- Non-target path edge removal connectivity test (e.g., asking about path edge starting at 3):
<query_remove>3</query_remove>

When submitting the final answer, specify whether the target edge is a bridge (answer "Yes" or "No"), using this format:

<answer>Yes</answer>

or

<answer>No</answer>
"""

    # 场景 1：交通
    contextualized_rule_zh_1 = """\
欢迎进入铁路交通调度网络风险评估系统。

本系统设定了一个铁路管网无向图，站点编号为 0 到 {n_minus_1}（共 {n} 个站点）。管网中包含以下两类连接：

1. **常规铁路线（路径边）**：所有相邻站点之间的线路 (i, i+1)，其中 i 从 0 到 {n_minus_2}。
2. **直达特快隧道（隐藏边）**：由一个未知的固定跨度 s 建成（s 的范围在 2 到 {n_minus_2} 之间）。对于每个满足以下条件的站点 i，建有一条直达特快隧道 (i, i+s)：
   - i 是 s 的倍数
   - i 小于等于 {n_minus_1} 减去 s

系统目前整体是连通的。现在由于地质原因，指定了一条**目标常规铁路线** e_t = ({target}, {target_plus_1}) 面临停运风险。

**你的任务**：评估该目标常规铁路线 e_t 是否为**交通瓶颈（桥边）**（即移除它后整个铁路网络是否会被切断成两部分）。

## 允许的系统指令

你可以反复向调度中心发出以下两类探测指令（每次仅限一个指令）：

1. **隧道入口判定**：询问"站点 i 是否存在直达特快隧道入口？"
   - 调度中心会回答"是"或"否"。
   - 当且仅当 i 是 s 的倍数且 i 小于等于 {n_minus_1} 减去 s 时，回答"是"。

2. **常规铁路线移除连通性测试**：询问"若临时关闭常规铁路线 (x, x+1)（要求 x 不等于 {target}），整个管网的连通分量数是多少？"
   - 调度中心会回答"1"（仍连通，不是瓶颈）或"2"（断为两截，是瓶颈）。
   - 若你询问的 x 等于 {target}，调度中心会提示"非法"且不计入有效指令。

**注意**：你至少需要进行 **3 次有效探测**后才能提交最终评估报告，否则报告将被驳回。

## 指令与提交报告的格式（必须严格遵守）

每次探测只能包含一个标签，使用以下 XML 格式：

- 隧道入口判定（例如探测站点 5）：
<query_hidden>5</query_hidden>

- 常规铁路线移除连通性测试（例如切断起点为 3 的线路）：
<query_remove>3</query_remove>

提交最终评估报告时，必须说明目标线路是否为交通瓶颈（回答"是"或"否"），格式如下：

<answer>是</answer>

或

<answer>否</answer>
"""

    contextualized_rule_en_1 = """\
[Transportation Scenario]
Welcome to the Railway Traffic Dispatch Risk Assessment System.

The system features an undirected railway network graph, with stations numbered from 0 to {n_minus_1} (total {n} stations). The network contains two types of connections:

1. **Regular Railway Lines (Path edges)**: Lines between all adjacent stations (i, i+1), where i ranges from 0 to {n_minus_2}.
2. **Express Tunnels (Hidden edges)**: Constructed with an unknown fixed span s (s ranges from 2 to {n_minus_2}). For each station i satisfying the following conditions, an express tunnel (i, i+s) is built:
   - i is a multiple of s
   - i is less than or equal to {n_minus_1} minus s

The network is entirely connected. Due to geological reasons, a **target regular railway line** e_t = ({target}, {target_plus_1}) is facing operational suspension risks.

**Your task**: Evaluate whether the target railway line e_t is a **traffic bottleneck (bridge)** (i.e., whether removing it would separate the network into two isolated parts).

## Allowed System Directives

You may repeatedly send the following two types of probes to the dispatch center (one per turn):

1. **Tunnel Entrance Detection**: Ask "Does station i have an express tunnel entrance?"
   - The center will answer "Yes" or "No".
   - The answer is "Yes" if and only if i is a multiple of s and i is less than or equal to {n_minus_1} minus s.

2. **Regular Line Suspension Connectivity Test**: Ask "If regular line (x, x+1) is temporarily closed (where x is not equal to {target}), how many connected components will the network have?"
   - The center will answer "1" (still connected, not a bottleneck) or "2" (disconnected into two parts, is a bottleneck).
   - If you query x equal to {target}, the center will return "Invalid" and it won't count as a valid probe.

**Note**: You must execute at least **3 valid probes** before submitting your final assessment, otherwise the report will be rejected.

## Probe and Answer Format (strictly required)

Each probe must contain only one tag. Use the following XML format:

- Tunnel Entrance Detection (e.g., probing station 5):
<query_hidden>5</query_hidden>

- Regular Line Suspension Connectivity Test (e.g., closing line starting at 3):
<query_remove>3</query_remove>

When submitting the final report, specify whether the target line is a traffic bottleneck (answer "Yes" or "No"), using this format:

<answer>Yes</answer>

or

<answer>No</answer>
"""

    # 场景 2：医疗
    contextualized_rule_zh_2 = """\
欢迎使用代谢与神经通路分析系统。

本系统构建了一个体内微观代谢网络的无向图模型，节点编号为 0 到 {n_minus_1}（共 {n} 个节点）。通路网络中包含以下两类连接：

1. **常规生化通路（路径边）**：所有相邻代谢节点之间的反应级联通路 (i, i+1)，其中 i 从 0 到 {n_minus_2}。
2. **跳跃旁路通路（隐藏边）**：由某种未知的调节因子按固定步长 s 激活（s 的范围在 2 到 {n_minus_2} 之间）。对于每个满足以下条件的节点 i，会形成一条旁路通路 (i, i+s)：
   - i 是 s 的倍数
   - i 小于等于 {n_minus_1} 减去 s

系统目前整体是正常运作并连通的。现在由于靶向药物作用，指定了一条**目标常规生化通路** e_t = ({target}, {target_plus_1}) 面临被完全阻断的风险。

**你的任务**：评估该目标生化通路 e_t 是否为**代谢网络瓶颈（桥边）**（即被药物阻断后，整个代谢系统是否会彻底瘫痪中断并分成两截）。

## 允许的系统探测

你可以反复向分析中心提出以下两类探测指令（每次仅限一个指令）：

1. **旁路受体判定**：询问"节点 i 是否存在旁路通路的激活受体起点？"
   - 分析中心会回答"是"或"否"。
   - 当且仅当 i 是 s 的倍数且 i 小于等于 {n_minus_1} 减去 s 时，回答"是"。

2. **常规通路基因敲除测试**：询问"若通过基因手段阻断常规生化通路 (x, x+1)（要求 x 不等于 {target}），整个代谢网络的连通分量数是多少？"
   - 分析中心会回答"1"（仍连通，可代偿）或"2"（断裂瘫痪，是瓶颈）。
   - 若你询问的 x 等于 {target}，系统会提示"非法"且不计入有效探测。

**注意**：你至少需要进行 **3 次有效探测**后才能提交最终诊断结论，否则结论将被系统拒收。

## 探测与提交诊断的格式（必须严格遵守）

每次探测只能包含一个标签，使用以下 XML 格式：

- 旁路受体判定（例如探测节点 5）：
<query_hidden>5</query_hidden>

- 常规通路基因敲除测试（例如阻断起点为 3 的通路）：
<query_remove>3</query_remove>

提交最终诊断结论时，必须说明目标生化通路是否为代谢瓶颈（回答"是"或"否"），格式如下：

<answer>是</answer>

或

<answer>否</answer>
"""

    contextualized_rule_en_2 = """\
[Healthcare Scenario]
Welcome to the Metabolic and Neural Pathway Analysis System.

The system features an in-vivo microscopic metabolic network modeled as an undirected graph, with nodes numbered from 0 to {n_minus_1} (total {n} nodes). The network contains two types of connections:

1. **Sequential Biochemical Pathways (Path edges)**: Reaction cascades between all adjacent metabolic nodes (i, i+1), where i ranges from 0 to {n_minus_2}.
2. **Bypass Pathways (Hidden edges)**: Activated by an unknown regulatory factor with a fixed step size s (s ranges from 2 to {n_minus_2}). For each node i satisfying the following conditions, a bypass pathway (i, i+s) is formed:
   - i is a multiple of s
   - i is less than or equal to {n_minus_1} minus s

The biological network is entirely connected. Due to targeted drug effects, a **target biochemical pathway** e_t = ({target}, {target_plus_1}) is facing complete blockage risks.

**Your task**: Evaluate whether the target biochemical pathway e_t is a **metabolic bottleneck (bridge)** (i.e., whether blocking it would completely paralyze the metabolic communication and sever it into two isolated parts).

## Allowed System Probes

You may repeatedly send the following two types of probes to the analysis center (one per turn):

1. **Bypass Receptor Detection**: Ask "Does node i have a bypass pathway activation receptor starting point?"
   - The center will answer "Yes" or "No".
   - The answer is "Yes" if and only if i is a multiple of s and i is less than or equal to {n_minus_1} minus s.

2. **Sequential Pathway Knockout Test**: Ask "If biochemical pathway (x, x+1) is blocked via gene knockout (where x is not equal to {target}), how many connected components will the metabolic network have?"
   - The center will answer "1" (still connected, can compensate) or "2" (paralyzed and separated, is a bottleneck).
   - If you query x equal to {target}, the system will return "Invalid" and it won't count as a valid probe.

**Note**: You must execute at least **3 valid probes** before submitting your final diagnostic conclusion, otherwise it will be rejected.

## Probe and Answer Format (strictly required)

Each probe must contain only one tag. Use the following XML format:

- Bypass Receptor Detection (e.g., probing node 5):
<query_hidden>5</query_hidden>

- Sequential Pathway Knockout Test (e.g., blocking pathway starting at 3):
<query_remove>3</query_remove>

When submitting the final diagnosis, specify whether the target pathway is a metabolic bottleneck (answer "Yes" or "No"), using this format:

<answer>Yes</answer>

or

<answer>No</answer>
"""

    # 场景 3：教育
    contextualized_rule_zh_3 = """\
欢迎进入知识体系结构评估系统。

本系统展示了一个核心学科知识模块网络，模块编号从 0 到 {n_minus_1}（共 {n} 个模块）。该认知网络中包含两类依赖关系：

1. **基础先修关联（路径边）**：按序号递进的相邻模块之间的学习路径 (i, i+1)，其中 i 从 0 到 {n_minus_2}。
2. **跨学科进阶跳跃关联（隐藏边）**：由于学科融合形成的一种具有固定跨度 s 的进阶链路（s 的范围在 2 到 {n_minus_2} 之间）。对于满足以下条件的模块 i，存在一条进阶跳跃关联 (i, i+s)：
   - i 是 s 的倍数
   - i 小于等于 {n_minus_1} 减去 s

学生的知识体系初始状态是无缝连通的。现在由于教学大纲改革，拟定移除一条**目标基础先修关联** e_t = ({target}, {target_plus_1})。

**你的任务**：评估该基础先修关联 e_t 是否为**认知枢纽（桥边）**（即评估若移除它，整个知识体系是否会出现断层，导致部分模块无法通过任何关联推导）。

## 允许的系统调研

你可以反复向教研系统提出以下两类调研请求（每次仅限一个请求）：

1. **进阶跳跃关联起点调研**：询问"知识模块 i 是否存在跨学科跳跃关联的起点特征？"
   - 系统会回答"是"或"否"。
   - 当且仅当 i 是 s 的倍数且 i 小于等于 {n_minus_1} 减去 s 时，回答"是"。

2. **基础先修关联移除推演**：询问"如果在沙盘中移除基础先修关联 (x, x+1)（要求 x 不等于 {target}），整个网络分裂成的独立知识体系数量是多少？"
   - 系统会回答"1"（依然连通，不是枢纽）或"2"（出现认知断层，是枢纽）。
   - 若你询问的 x 等于 {target}，系统会提示"非法"且不计入有效调研。

**注意**：你至少需要进行 **3 次有效调研**后才能提交最终教改建议，否则建议将不予受理。

## 调研与提交建议的格式（必须严格遵守）

每次调研只能包含一个标签，使用以下 XML 格式：

- 进阶跳跃关联起点调研（例如调研模块 5）：
<query_hidden>5</query_hidden>

- 基础先修关联移除推演（例如推演移除起点为 3 的先修关联）：
<query_remove>3</query_remove>

提交最终教改建议时，必须说明目标先修关联是否为认知枢纽（回答"是"或"否"），格式如下：

<answer>是</answer>

或

<answer>否</answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Welcome to the Knowledge System Structure Evaluation System.

The system displays a network of core knowledge modules, numbered from 0 to {n_minus_1} (total {n} modules). This cognitive network contains two types of dependencies:

1. **Sequential Prerequisites (Path edges)**: Progressive learning paths between adjacent modules (i, i+1), where i ranges from 0 to {n_minus_2}.
2. **Cross-disciplinary Leap Linkages (Hidden edges)**: Advanced links formed by subject integration with a fixed span s (s ranges from 2 to {n_minus_2}). For each module i satisfying the following conditions, a leap linkage (i, i+s) exists:
   - i is a multiple of s
   - i is less than or equal to {n_minus_1} minus s

The students' knowledge system is initially fully connected. Due to curriculum reform, a **target sequential prerequisite** e_t = ({target}, {target_plus_1}) is proposed to be removed.

**Your task**: Evaluate whether the target prerequisite connection e_t is a **cognitive hub (bridge)** (i.e., whether removing it would cause a cognitive fault line, making some modules logically unreachable).

## Allowed System Probes

You may repeatedly submit the following two types of probes to the academic research system (one per turn):

1. **Leap Linkage Origin Survey**: Ask "Does knowledge module i have the starting characteristics of a cross-disciplinary leap linkage?"
   - The system will answer "Yes" or "No".
   - The answer is "Yes" if and only if i is a multiple of s and i is less than or equal to {n_minus_1} minus s.

2. **Sequential Prerequisite Removal Simulation**: Ask "If sequential prerequisite (x, x+1) is removed in the sandbox (where x is not equal to {target}), how many independent knowledge networks will it split into?"
   - The system will answer "1" (still connected, not a hub) or "2" (cognitive fault line occurs, is a hub).
   - If you query x equal to {target}, the system will return "Invalid" and it won't count as a valid probe.

**Note**: You must execute at least **3 valid probes** before submitting your final reform recommendation, otherwise it will not be accepted.

## Probe and Recommendation Format (strictly required)

Each probe must contain only one tag. Use the following XML format:

- Leap Linkage Origin Survey (e.g., surveying module 5):
<query_hidden>5</query_hidden>

- Sequential Prerequisite Removal Simulation (e.g., simulating removal of prerequisite starting at 3):
<query_remove>3</query_remove>

When submitting the final recommendation, specify whether the target prerequisite is a cognitive hub (answer "Yes" or "No"), using this format:

<answer>Yes</answer>

or

<answer>No</answer>
"""

    # 场景 4：制造业/工业
    contextualized_rule_zh_4 = """\
欢迎使用智能制造流水线诊断系统。

本系统虚拟化了车间内的一条连续装配流水线图谱，工位编号从 0 到 {n_minus_1}（共 {n} 个工位）。物流系统内包含两类传输机制：

1. **常规传送带（路径边）**：相邻工位之间铺设的标准化传送带 (i, i+1)，其中 i 从 0 到 {n_minus_2}。
2. **高速机械臂抓取路线（隐藏边）**：为提高效率而配置的固定跨度 s 的空中物料直达机制（s 的范围在 2 到 {n_minus_2} 之间）。对于满足以下条件的工位 i，部署了一条机械臂抓取路线 (i, i+s)：
   - i 是 s 的倍数
   - i 小于等于 {n_minus_1} 减去 s

整条生产线的物流调度当前处于连通流转状态。然而，一条**目标常规传送带** e_t = ({target}, {target_plus_1}) 因机械故障正面临强制停机检修。

**你的任务**：评估该目标传送带 e_t 是否为整条生产线的**物流命脉（桥边）**（即一旦切断它，是否会导致物流调度彻底中断，形成无法互相转运的孤岛）。

## 允许的系统诊断

你可以反复向控制台发起以下两类诊断查询（每次仅限一个查询）：

1. **机械臂起点排查**：询问"装配工位 i 是否部署了高速机械臂的抓取起点？"
   - 控制台会回答"是"或"否"。
   - 当且仅当 i 是 s 的倍数且 i 小于等于 {n_minus_1} 减去 s 时，回答"是"。

2. **传送带切断连通性测试**：询问"若在控制台中模拟切断常规传送带 (x, x+1)（要求 x 不等于 {target}），物料流转子网络的数量是多少？"
   - 控制台会回答"1"（仍保持整体流转，非命脉）或"2"（断成两截，是命脉）。
   - 若你询问的 x 等于 {target}，控制台会提示"非法"且不计入有效查询。

**注意**：你至少需要进行 **3 次有效诊断查询**后才能提交最终检修批复，否则系统将驳回请求。

## 诊断与提交批复的格式（必须严格遵守）

每次诊断只能包含一个标签，使用以下 XML 格式：

- 机械臂起点排查（例如排查工位 5）：
<query_hidden>5</query_hidden>

- 传送带切断连通性测试（例如切断起点为 3 的传送带）：
<query_remove>3</query_remove>

提交最终检修批复时，必须说明目标传送带是否为物流命脉（回答"是"或"否"），格式如下：

<answer>是</answer>

或

<answer>否</answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing/Industry Scenario]
Welcome to the Smart Manufacturing Assembly Line Diagnostic System.

The system maps out a continuous assembly line graph in the workshop, with workstations numbered from 0 to {n_minus_1} (total {n} workstations). The logistics system contains two types of transfer mechanisms:

1. **Standard Conveyor Belts (Path edges)**: Standard belts laid between adjacent workstations (i, i+1), where i ranges from 0 to {n_minus_2}.
2. **High-speed Robotic Arm Transfer Routes (Hidden edges)**: Aerial material express mechanisms configured with a fixed span s to boost efficiency (s ranges from 2 to {n_minus_2}). For each workstation i satisfying the following conditions, a robotic arm transfer route (i, i+s) is deployed:
   - i is a multiple of s
   - i is less than or equal to {n_minus_1} minus s

The logistics dispatch of the entire production line is currently fully connected. However, a **target regular conveyor belt** e_t = ({target}, {target_plus_1}) is facing mandatory shutdown for maintenance due to mechanical failure.

**Your task**: Evaluate whether the target conveyor belt e_t is a **logistics lifeline (bridge)** for the production line (i.e., whether cutting it off would completely disrupt the logistics flow, forming isolated logistics islands).

## Allowed System Diagnostics

You may repeatedly issue the following two types of diagnostic queries to the console (one per turn):

1. **Robotic Arm Origin Inspection**: Ask "Is a high-speed robotic arm starting point deployed at workstation i?"
   - The console will answer "Yes" or "No".
   - The answer is "Yes" if and only if i is a multiple of s and i is less than or equal to {n_minus_1} minus s.

2. **Conveyor Belt Cutoff Connectivity Test**: Ask "If regular conveyor belt (x, x+1) is simulated to be cut off in the console (where x is not equal to {target}), what is the number of material flow subnetworks?"
   - The console will answer "1" (still flowing collectively, not a lifeline) or "2" (broken into two segments, is a lifeline).
   - If you query x equal to {target}, the console will return "Invalid" and it won't count as a valid query.

**Note**: You must execute at least **3 valid diagnostic queries** before submitting your final maintenance approval, otherwise the request will be rejected.

## Query and Approval Format (strictly required)

Each query must contain only one tag. Use the following XML format:

- Robotic Arm Origin Inspection (e.g., inspecting workstation 5):
<query_hidden>5</query_hidden>

- Conveyor Belt Cutoff Connectivity Test (e.g., cutting off belt starting at 3):
<query_remove>3</query_remove>

When submitting the final maintenance approval, specify whether the target conveyor belt is a logistics lifeline (answer "Yes" or "No"), using this format:

<answer>Yes</answer>

or

<answer>No</answer>
"""

    # 场景 5：法律
    contextualized_rule_zh_5 = """\
欢迎使用案件证据链逻辑推演系统。

本系统构建了一个复杂刑事案件的证据图谱，证据节点编号从 0 到 {n_minus_1}（共 {n} 个关键证据节点）。证据网络中包含两类关联：

1. **直接推导逻辑链（路径边）**：根据案发时间或因果规律连接相邻证据节点的逻辑链 (i, i+1)，其中 i 从 0 到 {n_minus_2}。
2. **跨越性印证关系（隐藏边）**：由隐蔽的客观线索串联起来的具有固定跨度 s 的印证关系（s 的范围在 2 到 {n_minus_2} 之间）。对于满足以下条件的节点 i，存在一条跨越性印证关系 (i, i+s)：
   - i 是 s 的倍数
   - i 小于等于 {n_minus_1} 减去 s

目前，检方提供的整个案件证据链形成了一个完整的闭环（连通）。但在庭审中，辩方律师对一条**目标直接推导逻辑链** e_t = ({target}, {target_plus_1}) 提出了强烈质疑并试图向法庭申请排除。

**你的任务**：评估该目标推导逻辑链 e_t 是否为整个指控体系的**关键逻辑断点（桥边）**（即若被法庭排除，整个案件的证据网络是否会立刻断裂成无法互相印证的两部分）。

## 允许的法庭质询操作

你可以反复通过系统辅助工具进行以下两类预演操作（每次仅限一个操作）：

1. **印证关系起点质询**：询问"证据节点 i 是否包含跨越性印证关系的线索起点？"
   - 系统判定会回答"是"或"否"。
   - 当且仅当 i 是 s 的倍数且 i 小于等于 {n_minus_1} 减去 s 时，回答"是"。

2. **逻辑链排除连通性评估**：询问"若在辩论中模拟排除直接推导逻辑链 (x, x+1)（要求 x 不等于 {target}），剩余证据链条形成的孤立分支数量是多少？"
   - 系统评估会回答"1"（证据链依然互锁连通，非关键断点）或"2"（断裂瘫痪，是关键断点）。
   - 若你询问的 x 等于 {target}，系统会提示"非法"且不计入有效质询。

**注意**：你至少需要进行 **3 次有效质询预演**后才能提交最终法庭应对策略，否则策略将无法通过法庭逻辑校验。

## 质询与提交策略的格式（必须严格遵守）

每次预演操作只能包含一个标签，使用以下 XML 格式：

- 印证关系起点质询（例如质询证据节点 5）：
<query_hidden>5</query_hidden>

- 逻辑链排除连通性评估（例如模拟排除起点为 3 的逻辑链）：
<query_remove>3</query_remove>

提交最终法庭应对策略时，必须明确判定目标推导逻辑链是否为关键逻辑断点（回答"是"或"否"），格式如下：

<answer>是</answer>

或

<answer>否</answer>
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
Welcome to the Legal Evidence Chain Logical Deduction System.

The system constructs an evidence graph for a complex criminal case, with evidence nodes numbered from 0 to {n_minus_1} (total {n} key evidence nodes). The evidence network contains two types of correlations:

1. **Direct Logical Derivations (Path edges)**: Logical chains connecting adjacent evidence nodes based on time of occurrence or causality (i, i+1), where i ranges from 0 to {n_minus_2}.
2. **Cross-corroborating Connections (Hidden edges)**: Corroborating relationships connected by hidden objective clues with a fixed span s (s ranges from 2 to {n_minus_2}). For each node i satisfying the following conditions, a cross-corroborating connection (i, i+s) exists:
   - i is a multiple of s
   - i is less than or equal to {n_minus_1} minus s

Currently, the prosecution's entire evidence chain forms a fully connected closed loop. However, during the trial, the defense attorney strongly challenged a **target direct logical derivation** e_t = ({target}, {target_plus_1}) and attempted to request its exclusion in court.

**Your task**: Evaluate whether the target logical derivation chain e_t is a **critical logical breakpoint (bridge)** for the entire accusation framework (i.e., whether excluding it in court would instantly sever the evidence network into two uncorroboratable parts).

## Allowed Court Interrogation Maneuvers

You may repeatedly perform the following two types of simulation maneuvers via the system's analytical tool (one per turn):

1. **Corroborating Origin Inquiry**: Ask "Does evidence node i contain the starting clue of a cross-corroborating connection?"
   - The system judgment will answer "Yes" or "No".
   - The answer is "Yes" if and only if i is a multiple of s and i is less than or equal to {n_minus_1} minus s.

2. **Logical Chain Exclusion Connectivity Evaluation**: Ask "If direct logical derivation (x, x+1) is simulated to be excluded during the debate (where x is not equal to {target}), what is the number of isolated branches formed by the remaining evidence chains?"
   - The system evaluation will answer "1" (evidence chain remains interlocked and connected, not a critical breakpoint) or "2" (fractured and paralyzed, is a critical breakpoint).
   - If you query x equal to {target}, the system will return "Invalid" and it won't count as a valid interrogation.

**Note**: You must perform at least **3 valid interrogation simulations** before submitting your final court response strategy, otherwise the strategy will fail the court's logical validation.

## Interrogation and Strategy Format (strictly required)

Each simulation maneuver must contain only one tag. Use the following XML format:

- Corroborating Origin Inquiry (e.g., inquiring evidence node 5):
<query_hidden>5</query_hidden>

- Logical Chain Exclusion Connectivity Evaluation (e.g., simulating exclusion of logical chain starting at 3):
<query_remove>3</query_remove>

When submitting the final court response strategy, specify whether the target logical chain is a critical logical breakpoint (answer "Yes" or "No"), using this format:

<answer>Yes</answer>

or

<answer>No</answer>
"""

    tags = ["answer", "query_hidden", "query_remove"]
    
    reasoning_type = "归纳推理"
    data_structure = "图"

    # 难度配置：
    # 1 (简单)     - N=8,  s=3, t=5  (t > J_max, 是桥)
    # 2 (中等偏下) - N=10, s=3, t=2  (t <= J_max, 不是桥)
    # 3 (中等偏上) - N=12, s=4, t=7  (t <= J_max, 不是桥)
    # 4 (较难)     - N=15, s=5, t=11 (t >= J_max+1, 是桥)
    # 5 (难)       - N=20, s=6, t=12 (需仔细计算，t <= J_max, 不是桥)

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {"n": 8, "s": 3, "t": 5},
            2: {"n": 10, "s": 3, "t": 2},
            3: {"n": 12, "s": 4, "t": 7},
            4: {"n": 15, "s": 5, "t": 11},
            5: {"n": 20, "s": 6, "t": 12},
        },
        "en": {
            1: {"n": 8, "s": 3, "t": 5},
            2: {"n": 10, "s": 3, "t": 2},
            3: {"n": 12, "s": 4, "t": 7},
            4: {"n": 15, "s": 5, "t": 11},
            5: {"n": 20, "s": 6, "t": 12},
        },
    }

    def __init__(self, config):
        super().__init__(config)
        self.query_count = 0  # 有效提问计数

    def _initialize_game(self):
        lang = self.config.language
        diff = self.config.difficulty

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        self.n = cfg["n"]
        self.s = cfg["s"]
        self.t = cfg["t"]
        
        # 计算 J_max = s * floor((N-1)/s) - 1
        self.j_max = self.s * math.floor((self.n - 1) / self.s) - 1
        
        # 判断目标边是否为桥
        # 若 t <= J_max，则不是桥；若 t >= J_max + 1，则是桥
        self.is_bridge = (self.t >= self.j_max + 1)
        
        # 设置游戏信息用于格式化规则
        self._game_info["n"] = self.n
        self._game_info["n_minus_1"] = self.n - 1
        self._game_info["n_minus_2"] = self.n - 2
        self._game_info["target"] = self.t
        self._game_info["target_plus_1"] = self.t + 1

    def _has_hidden_edge_start(self, i):
        """判断顶点 i 是否为隐藏边起点"""
        # i 是 s 的倍数且 i <= N-1-s
        return (i % self.s == 0) and (i <= self.n - 1 - self.s)

    def _is_bridge_after_removal(self, x):
        """判断移除路径边 (x, x+1) 后图是否不连通（即该边是否为桥）"""
        # 构建图的邻接表（不包含要移除的边）
        adj = [set() for _ in range(self.n)]
        
        # 添加路径边（除了 (x, x+1)）
        for i in range(self.n - 1):
            if i != x:
                adj[i].add(i + 1)
                adj[i + 1].add(i)
        
        # 添加隐藏边
        i = 0
        while i <= self.n - 1 - self.s:
            if i % self.s == 0:
                adj[i].add(i + self.s)
                adj[i + self.s].add(i)
            i += self.s
        
        # BFS 检查连通性
        visited = [False] * self.n
        queue = [0]
        visited[0] = True
        count = 1
        
        while queue:
            node = queue.pop(0)
            for neighbor in adj[node]:
                if not visited[neighbor]:
                    visited[neighbor] = True
                    count += 1
                    queue.append(neighbor)
        
        # 如果访问到所有顶点，则仍连通（不是桥）
        return count < self.n

    def evaluate(self, parsed_info):
        """评估最终答案是否正确"""
        # 检查是否至少进行了 3 次有效提问
        if self.query_count < 3:
            return False
        
        raw_ans = parsed_info["answer"].strip()
        
        if self.config.language == "zh":
            expected_yes = "是"
            expected_no = "否"
        else:
            expected_yes = "Yes"
            expected_no = "No"
        
        if self.is_bridge:
            return raw_ans == expected_yes
        else:
            return raw_ans == expected_no

    def _cf_core_produce(self, parsed_info):
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
            invalid_res = "非法"
            error_res = "错误：参数无效或超出范围。"
        else:
            yes_res, no_res = "Yes", "No"
            invalid_res = "Invalid"
            error_res = "Error: Invalid parameter or out of range."

        # 优先级：query_hidden > query_remove
        if "query_hidden" in parsed_info:
            try:
                i = int(parsed_info["query_hidden"].strip())
                if i < 0 or i >= self.n:
                    return error_res
                self.query_count += 1
                return yes_res if self._has_hidden_edge_start(i) else no_res
            except:
                return error_res

        elif "query_remove" in parsed_info:
            try:
                x = int(parsed_info["query_remove"].strip())
                if x < 0 or x >= self.n - 1:
                    return error_res
                if x == self.t:
                    # 询问目标边，返回非法且不计入有效提问
                    return invalid_res
                self.query_count += 1
                # 返回连通分量数：1（不是桥）或 2（是桥）
                return "2" if self._is_bridge_after_removal(x) else "1"
            except:
                return error_res

        else:
            raise ValueError("No valid query tag found.")

    def _cf_make_wrong(self, correct):
        if correct.isdigit():
            return str(int(correct) + 1)
        
        low_c = correct.lower()
        if self.config.language == "zh":
            if correct == "是": return "否"
            if correct == "否": return "是"
        else:
            if low_c == "yes": return "No" if correct[0].isupper() else "no"
            if low_c == "no": return "Yes" if correct[0].isupper() else "yes"
            
        return correct + "_WRONG"

    def get_all_possible_queries(self) -> list[dict]:
        """
        枚举所有合法查询并返回对应的正确答案。
        """
        results = []
        
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
        else:
            yes_res, no_res = "Yes", "No"

        # 1. 隐藏边起点判定 (query_hidden)
        # 范围：0 到 n-1
        for i in range(self.n):
            query_str = f"<query_hidden>{i}</query_hidden>"
            
            # 逻辑：_has_hidden_edge_start 不会修改状态
            ans = yes_res if self._has_hidden_edge_start(i) else no_res
            
            results.append({
                "query": query_str,
                "answer": ans
            })

        # 2. 非目标路径边移除连通性测试 (query_remove)
        # 范围：0 到 n-2，且不能是 target
        for x in range(self.n - 1):
            if x == self.t:
                continue
            
            query_str = f"<query_remove>{x}</query_remove>"
            
            # 逻辑：_is_bridge_after_removal 不会修改状态
            is_bridge = self._is_bridge_after_removal(x)
            ans = "2" if is_bridge else "1"
            
            results.append({
                "query": query_str,
                "answer": ans
            })
            
        return results