from .base import Game
import re


class PeriodicSequenceGame(Game):

    game_rule_zh = """\
我们现在来玩一个"周期序列推理"游戏，规则如下：

游戏设定了一个长度为 {n} 的二进制序列 A，索引从 1 到 {n}。该序列由一个隐藏的周期模板生成：
- 存在一个周期长度 P（2 到 10 之间）和一个长度为 P 的二进制模板 M（由 0 和 1 组成，至少包含一个 1）。
- 序列 A 从位置 1 开始，按照模板 M 周期性重复生成。即对于任意位置 i（1 到 {n}），A[i] 的值等于模板 M 中第 ((i-1) 取模 P + 1) 个位置的值。

你的目标是推断出序列中所有值为 1 的位置，并提交一个有序列表。你可以通过以下两种方式向我提问：

1. 区间计数查询：询问区间 [L, R] 内有多少个位置的值为 1。
   - 约束：L 和 R 必须满足 1 小于等于 L 小于等于 R 小于等于 {n}，且区间长度（R - L + 1）必须大于等于 {wmin}。
   - 回答：返回一个整数，表示该区间内值为 1 的位置数量。

2. 单点探测查询：询问某个特定位置 i 的值是否为 1。
   - 约束：i 必须在 1 到 {n} 之间。
   - 回答："是"或"否"。
   - 注意：单点探测次数有限制，最多只能使用 {smax} 次。

查询约束：
- 总查询次数（区间计数 + 单点探测）不能超过 {qmax} 次。
- 单点探测次数不能超过 {smax} 次。
- 任何不合法或越界的查询仍会计入总查询次数。
- 超出查询预算或单点探测预算将导致游戏失败。

当你收集足够信息后，请提交最终答案。答案应包含所有且仅有值为 1 的位置，按升序排列。

## 询问与提交答案的格式（必须严格遵守）

每次询问只能包含一个标签。请使用以下 XML 格式：

- 区间计数查询（例如询问区间 [5, 12]）：
<query_range>5,12</query_range>

- 单点探测查询（例如询问位置 7）：
<query_point>7</query_point>

提交最终答案时，必须列出所有值为 1 的位置（用逗号分隔，按升序排列），格式如下：

<answer>1,4,7,10,13</answer>

如果认为没有任何位置的值为 1，则提交空答案：

<answer></answer>
"""

    game_rule_en = """\
Let's play a "Periodic Sequence Deduction" game. Here are the rules:

The game has set up a binary sequence A of length {n}, indexed from 1 to {n}. This sequence is generated by a hidden periodic template:
- There exists a period length P (between 2 and 10) and a binary template M of length P (consisting of 0s and 1s, with at least one 1).
- Sequence A is generated by repeating template M periodically starting from position 1. That is, for any position i (1 to {n}), A[i] equals the value at position ((i-1) modulo P + 1) in template M.

Your goal is to infer all positions where the value is 1 and submit an ordered list. You can ask questions in two ways:

1. Range Count Query: Ask how many positions in the range [L, R] have value 1.
   - Constraint: L and R must satisfy 1 less than or equal to L less than or equal to R less than or equal to {n}, and the range length (R - L + 1) must be greater than or equal to {wmin}.
   - Response: Returns an integer representing the count of positions with value 1 in that range.

2. Point Probe Query: Ask whether a specific position i has value 1.
   - Constraint: i must be between 1 and {n}.
   - Response: "Yes" or "No".
   - Note: Point probe queries are limited to a maximum of {smax} uses.

Query Constraints:
- Total query count (range count + point probe) cannot exceed {qmax} times.
- Point probe count cannot exceed {smax} times.
- Any illegal or out-of-bounds query still counts toward the total query count.
- Exceeding the query budget or point probe budget will result in game failure.

When you have gathered enough information, submit your final answer. The answer should contain all and only the positions with value 1, in ascending order.

## Query and Answer Format (must be strictly followed)

Each query must contain only one tag. Use the following XML format:

- Range Count Query (e.g., asking about range [5, 12]):
<query_range>5,12</query_range>

- Point Probe Query (e.g., asking about position 7):
<query_point>7</query_point>

When submitting the final answer, list all positions with value 1 (comma-separated, in ascending order), using this format:

<answer>1,4,7,10,13</answer>

If you believe no position has value 1, submit an empty answer:

<answer></answer>
"""

    contextualized_rule_zh_1 = """\
我们现在来玩一个“潮汐车流拥堵推理”游戏，规则如下：

作为交管中心调度员，你需要监控一条干道上连续的 {n} 个监测点（索引从 1 到 {n}）。受潮汐车流影响，拥堵状态呈周期性分布：
- 存在一个隐藏的周期长度 P（2 到 10 之间）和一个长度为 P 的拥堵模板 M（由 0代表畅通 和 1代表拥堵 组成，至少包含一个拥堵点 1）。
- 监测点序列 A 从位置 1 开始，按照模板 M 周期性重复生成。即对于任意监测点 i（1 到 {n}），状态 A[i] 的值等于模板 M 中第 ((i-1) 取模 P + 1) 个位置的值。

你的目标是推断出所有状态为 1（拥堵）的监测点位置，并提交一个有序列表。你可以通过以下两种方式向系统提问：

1. 无人机区间扫描（区间计数查询）：询问区间 [L, R] 内有多少个监测点处于拥堵状态（值为 1）。
   - 约束：L 和 R 必须满足 1 小于等于 L 小于等于 R 小于等于 {n}，且扫描区间长度（R - L + 1）必须大于等于 {wmin}。
   - 回答：返回一个整数，表示该区间内拥堵点的数量。

2. 警力定点核查（单点探测查询）：询问特定监测点 i 的状态是否为拥堵（值为 1）。
   - 约束：i 必须在 1 到 {n} 之间。
   - 回答：“是”或“否”。
   - 注意：警力有限，定点核查次数最多只能使用 {smax} 次。

查询约束：
- 总查询次数（区间扫描 + 定点核查）不能超过 {qmax} 次。
- 定点核查次数不能超过 {smax} 次。
- 任何不合法或越界的指令仍会计入总查询次数。
- 超出指令预算或警力预算将导致排查失败。

当你收集足够信息后，请提交最终排查报告。答案应包含所有且仅有状态为 1 的监测点，按升序排列。

## 询问与提交答案的格式（必须严格遵守）

每次询问只能包含一个标签。请使用以下 XML 格式：

- 区间计数查询（例如扫描区间 [5, 12]）：
<query_range>5,12</query_range>

- 单点探测查询（例如核查位置 7）：
<query_point>7</query_point>

提交最终答案时，必须列出所有状态为 1 的位置（用逗号分隔，按升序排列），格式如下：

<answer>1,4,7,10,13</answer>

如果认为没有任何位置处于拥堵状态，则提交空答案：

<answer></answer>
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
Let's play a "Tidal Traffic Congestion Deduction" game. Here are the rules:

As a traffic control dispatcher, you need to monitor a main road with a length of {n} continuous monitoring points (indexed from 1 to {n}). Due to tidal traffic flow, congestion states are distributed periodically:
- There exists a hidden period length P (between 2 and 10) and a binary congestion template M of length P (consisting of 0s for clear and 1s for congested, with at least one 1).
- Sequence A of monitoring point states is generated by repeating template M periodically starting from position 1. That is, for any position i (1 to {n}), the state A[i] equals the value at position ((i-1) modulo P + 1) in template M.

Your goal is to infer all positions where the state is 1 (congested) and submit an ordered list. You can ask questions in two ways:

1. Drone Range Scan (Range Count Query): Ask how many monitoring points in the range [L, R] have state 1.
   - Constraint: L and R must satisfy 1 less than or equal to L less than or equal to R less than or equal to {n}, and the scan range length (R - L + 1) must be greater than or equal to {wmin}.
   - Response: Returns an integer representing the count of congested points in that range.

2. Police Point Check (Point Probe Query): Ask whether a specific position i has state 1.
   - Constraint: i must be between 1 and {n}.
   - Response: "Yes" or "No".
   - Note: Police resources are limited; point checks are limited to a maximum of {smax} uses.

Query Constraints:
- Total query count (range scan + point check) cannot exceed {qmax} times.
- Point check count cannot exceed {smax} times.
- Any illegal or out-of-bounds command still counts toward the total query count.
- Exceeding the query budget or police resource budget will result in inspection failure.

When you have gathered enough information, submit your final inspection report. The answer should contain all and only the positions with state 1, in ascending order.

## Query and Answer Format (must be strictly followed)

Each query must contain only one tag. Use the following XML format:

- Range Count Query (e.g., scanning range [5, 12]):
<query_range>5,12</query_range>

- Point Probe Query (e.g., checking position 7):
<query_point>7</query_point>

When submitting the final answer, list all positions with state 1 (comma-separated, in ascending order), using this format:

<answer>1,4,7,10,13</answer>

If you believe no position has state 1, submit an empty answer:

<answer></answer>
"""

    contextualized_rule_zh_2 = """\
我们现在来玩一个“心电信号周期异常推理”游戏，规则如下：

作为临床数据分析师，你需要分析一段长度为 {n} 的连续心电图信号序列（采样点索引从 1 到 {n}）。该信号中隐藏着周期性的异常电生理活动：
- 存在一个隐藏的异常周期长度 P（2 到 10 之间）和一个长度为 P 的信号模板 M（由 0代表正常 和 1代表异常 组成，至少包含一个异常点 1）。
- 信号序列 A 从位置 1 开始，按照模板 M 周期性重复生成。即对于任意采样点 i（1 到 {n}），异常状态 A[i] 的值等于模板 M 中第 ((i-1) 取模 P + 1) 个位置的值。

你的目标是推断出序列中所有值为 1（异常）的采样点位置，并提交一个有序列表。你可以通过以下两种方式向系统提问：

1. 频域区间扫描（区间计数查询）：询问采样点区间 [L, R] 内有多少个位置的状态为 1。
   - 约束：L 和 R 必须满足 1 小于等于 L 小于等于 R 小于等于 {n}，且扫描区间长度（R - L + 1）必须大于等于 {wmin}。
   - 回答：返回一个整数，表示该区间内异常点的数量。

2. 定点高精度复核（单点探测查询）：询问某个特定采样点 i 的状态是否为 1。
   - 约束：i 必须在 1 到 {n} 之间。
   - 回答：“是”或“否”。
   - 注意：高精度复核次数有限制，最多只能使用 {smax} 次。

查询约束：
- 总查询次数（区间扫描 + 定点复核）不能超过 {qmax} 次。
- 定点复核次数不能超过 {smax} 次。
- 任何不合法或越界的指令仍会计入总查询次数。
- 超出指令预算或复核预算将导致分析失败。

当你收集足够信息后，请提交最终诊断报告。答案应包含所有且仅有状态为 1 的采样点位置，按升序排列。

## 询问与提交答案的格式（必须严格遵守）

每次询问只能包含一个标签。请使用以下 XML 格式：

- 区间计数查询（例如扫描区间 [5, 12]）：
<query_range>5,12</query_range>

- 单点探测查询（例如复核位置 7）：
<query_point>7</query_point>

提交最终答案时，必须列出所有状态为 1 的位置（用逗号分隔，按升序排列），格式如下：

<answer>1,4,7,10,13</answer>

如果认为没有任何位置的状态为 1，则提交空答案：

<answer></answer>
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
Let's play a "Periodic ECG Anomaly Deduction" game. Here are the rules:

As a clinical data analyst, you need to analyze a continuous electrocardiogram (ECG) signal sequence of length {n} (sampling points indexed from 1 to {n}). The signal conceals periodic anomalous electrophysiological activities:
- There exists a hidden anomaly period length P (between 2 and 10) and a signal template M of length P (consisting of 0s for normal and 1s for anomalous, with at least one 1).
- The signal sequence A is generated by repeating template M periodically starting from position 1. That is, for any sampling point i (1 to {n}), the anomaly state A[i] equals the value at position ((i-1) modulo P + 1) in template M.

Your goal is to infer all positions where the state is 1 (anomalous) and submit an ordered list. You can ask questions in two ways:

1. Frequency Domain Range Scan (Range Count Query): Ask how many positions in the sampling range [L, R] have state 1.
   - Constraint: L and R must satisfy 1 less than or equal to L less than or equal to R less than or equal to {n}, and the scan range length (R - L + 1) must be greater than or equal to {wmin}.
   - Response: Returns an integer representing the count of anomalous points in that range.

2. Point High-Precision Review (Point Probe Query): Ask whether a specific sampling point i has state 1.
   - Constraint: i must be between 1 and {n}.
   - Response: "Yes" or "No".
   - Note: High-precision reviews are limited to a maximum of {smax} uses.

Query Constraints:
- Total query count (range scan + point review) cannot exceed {qmax} times.
- Point review count cannot exceed {smax} times.
- Any illegal or out-of-bounds command still counts toward the total query count.
- Exceeding the query budget or review budget will result in analysis failure.

When you have gathered enough information, submit your final diagnostic report. The answer should contain all and only the positions with state 1, in ascending order.

## Query and Answer Format (must be strictly followed)

Each query must contain only one tag. Use the following XML format:

- Range Count Query (e.g., scanning range [5, 12]):
<query_range>5,12</query_range>

- Point Probe Query (e.g., reviewing position 7):
<query_point>7</query_point>

When submitting the final answer, list all positions with state 1 (comma-separated, in ascending order), using this format:

<answer>1,4,7,10,13</answer>

If you believe no position has state 1, submit an empty answer:

<answer></answer>
"""

    contextualized_rule_zh_3 = """\
我们现在来玩一个“核心素养考点分布推理”游戏，规则如下：

作为教研专家，你需要审核包含 {n} 个连续知识模块的课程大纲（模块索引从 1 到 {n}）。大纲中核心考核点的分布遵循某种隐蔽的周期性教学规律：
- 存在一个隐藏的教学周期长度 P（2 到 10 之间）和一个长度为 P 的模块模板 M（由 0代表常规内容 和 1代表核心考点 组成，至少包含一个核心考点 1）。
- 课程模块序列 A 从位置 1 开始，按照模板 M 周期性重复生成。即对于任意模块 i（1 到 {n}），其属性 A[i] 的值等于模板 M 中第 ((i-1) 取模 P + 1) 个位置的值。

你的目标是推断出大纲中所有值为 1（核心考点）的模块位置，并提交一个有序列表。你可以通过以下两种方式向系统提问：

1. 批量教学评估（区间计数查询）：询问模块区间 [L, R] 内有多少个模块的属性为 1。
   - 约束：L 和 R 必须满足 1 小于等于 L 小于等于 R 小于等于 {n}，且评估区间长度（R - L + 1）必须大于等于 {wmin}。
   - 回答：返回一个整数，表示该区间内核心考点模块的数量。

2. 模块深度审阅（单点探测查询）：询问某个特定模块 i 的属性是否为 1。
   - 约束：i 必须在 1 到 {n} 之间。
   - 回答：“是”或“否”。
   - 注意：深度审阅的精力有限，最多只能使用 {smax} 次。

查询约束：
- 总查询次数（批量评估 + 深度审阅）不能超过 {qmax} 次。
- 深度审阅次数不能超过 {smax} 次。
- 任何不合法或越界的指令仍会计入总查询次数。
- 超出评估预算或审阅预算将导致审核失败。

当你收集足够信息后，请提交最终考点分布报告。答案应包含所有且仅有属性为 1 的模块位置，按升序排列。

## 询问与提交答案的格式（必须严格遵守）

每次询问只能包含一个标签。请使用以下 XML 格式：

- 区间计数查询（例如评估区间 [5, 12]）：
<query_range>5,12</query_range>

- 单点探测查询（例如审阅位置 7）：
<query_point>7</query_point>

提交最终答案时，必须列出所有属性为 1 的位置（用逗号分隔，按升序排列），格式如下：

<answer>1,4,7,10,13</answer>

如果认为没有任何位置的属性为 1，则提交空答案：

<answer></answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Let's play a "Core Competency Node Distribution Deduction" game. Here are the rules:

As a teaching research expert, you need to review a curriculum syllabus containing {n} continuous knowledge modules (indexed from 1 to {n}). The distribution of core assessment nodes follows a hidden periodic instructional pattern:
- There exists a hidden teaching period length P (between 2 and 10) and a module template M of length P (consisting of 0s for regular content and 1s for core nodes, with at least one 1).
- The module sequence A is generated by repeating template M periodically starting from position 1. That is, for any module i (1 to {n}), its attribute A[i] equals the value at position ((i-1) modulo P + 1) in template M.

Your goal is to infer all positions where the attribute is 1 (core node) and submit an ordered list. You can ask questions in two ways:

1. Batch Instructional Assessment (Range Count Query): Ask how many modules in the range [L, R] have attribute 1.
   - Constraint: L and R must satisfy 1 less than or equal to L less than or equal to R less than or equal to {n}, and the assessment range length (R - L + 1) must be greater than or equal to {wmin}.
   - Response: Returns an integer representing the count of core node modules in that range.

2. Module In-depth Review (Point Probe Query): Ask whether a specific module i has attribute 1.
   - Constraint: i must be between 1 and {n}.
   - Response: "Yes" or "No".
   - Note: In-depth reviews are limited to a maximum of {smax} uses.

Query Constraints:
- Total query count (batch assessment + in-depth review) cannot exceed {qmax} times.
- In-depth review count cannot exceed {smax} times.
- Any illegal or out-of-bounds command still counts toward the total query count.
- Exceeding the assessment budget or review budget will result in audit failure.

When you have gathered enough information, submit your final node distribution report. The answer should contain all and only the positions with attribute 1, in ascending order.

## Query and Answer Format (must be strictly followed)

Each query must contain only one tag. Use the following XML format:

- Range Count Query (e.g., assessing range [5, 12]):
<query_range>5,12</query_range>

- Point Probe Query (e.g., reviewing position 7):
<query_point>7</query_point>

When submitting the final answer, list all positions with attribute 1 (comma-separated, in ascending order), using this format:

<answer>1,4,7,10,13</answer>

If you believe no position has attribute 1, submit an empty answer:

<answer></answer>
"""

    contextualized_rule_zh_4 = """\
我们现在来玩一个“产线周期性缺陷排查”游戏，规则如下：

作为工业质检工程师，你需要检测流水线上连续生产的 {n} 个精密部件（部件编号从 1 到 {n}）。由于机器校准的周期性偏差，缺陷部件的出现呈现隐蔽的规律性：
- 存在一个隐藏的偏差周期长度 P（2 到 10 之间）和一个长度为 P 的质量模板 M（由 0代表合格 和 1代表缺陷 组成，至少包含一个缺陷部件 1）。
- 生产序列 A 从位置 1 开始，按照模板 M 周期性重复生成。即对于任意部件 i（1 到 {n}），质量状态 A[i] 的值等于模板 M 中第 ((i-1) 取模 P + 1) 个位置的值。

你的目标是推断出所有状态为 1（存在微观缺陷）的部件位置，并提交一个有序列表。你可以通过以下两种方式向系统提问：

1. 批量光学筛选（区间计数查询）：询问部件区间 [L, R] 内有多少个部件的状态为 1。
   - 约束：L 和 R 必须满足 1 小于等于 L 小于等于 R 小于等于 {n}，且筛选区间长度（R - L + 1）必须大于等于 {wmin}。
   - 回答：返回一个整数，表示该批次内缺陷部件的数量。

2. 显微破坏抽检（单点探测查询）：询问某个特定部件 i 的状态是否为 1。
   - 约束：i 必须在 1 到 {n} 之间。
   - 回答：“是”或“否”。
   - 注意：破坏性抽检成本高昂，最多只能使用 {smax} 次。

查询约束：
- 总查询次数（批量筛选 + 破坏抽检）不能超过 {qmax} 次。
- 破坏抽检次数不能超过 {smax} 次。
- 任何不合法或越界的指令仍会计入总查询次数。
- 超出检测预算或抽检预算将导致质检任务失败。

当你收集足够信息后，请提交最终残次品召回报告。答案应包含所有且仅有状态为 1 的部件编号，按升序排列。

## 询问与提交答案的格式（必须严格遵守）

每次询问只能包含一个标签。请使用以下 XML 格式：

- 区间计数查询（例如筛选区间 [5, 12]）：
<query_range>5,12</query_range>

- 单点探测查询（例如抽检位置 7）：
<query_point>7</query_point>

提交最终答案时，必须列出所有状态为 1 的位置（用逗号分隔，按升序排列），格式如下：

<answer>1,4,7,10,13</answer>

如果认为没有任何位置的状态为 1，则提交空答案：

<answer></answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
Let's play a "Periodic Assembly Line Defect Troubleshooting" game. Here are the rules:

As an industrial quality control engineer, you need to inspect {n} precision components continuously produced on an assembly line (indexed from 1 to {n}). Due to periodic deviations in machine calibration, the occurrence of defective components follows a hidden pattern:
- There exists a hidden deviation period length P (between 2 and 10) and a quality template M of length P (consisting of 0s for qualified and 1s for defective, with at least one 1).
- The production sequence A is generated by repeating template M periodically starting from position 1. That is, for any component i (1 to {n}), the quality state A[i] equals the value at position ((i-1) modulo P + 1) in template M.

Your goal is to infer all positions where the state is 1 (having micro-defects) and submit an ordered list. You can ask questions in two ways:

1. Batch Optical Screening (Range Count Query): Ask how many components in the range [L, R] have state 1.
   - Constraint: L and R must satisfy 1 less than or equal to L less than or equal to R less than or equal to {n}, and the screening range length (R - L + 1) must be greater than or equal to {wmin}.
   - Response: Returns an integer representing the count of defective components in that batch.

2. Microscopic Destructive Sampling (Point Probe Query): Ask whether a specific component i has state 1.
   - Constraint: i must be between 1 and {n}.
   - Response: "Yes" or "No".
   - Note: Destructive sampling is costly and limited to a maximum of {smax} uses.

Query Constraints:
- Total query count (batch screening + destructive sampling) cannot exceed {qmax} times.
- Destructive sampling count cannot exceed {smax} times.
- Any illegal or out-of-bounds command still counts toward the total query count.
- Exceeding the screening budget or sampling budget will result in inspection failure.

When you have gathered enough information, submit your final defective product recall report. The answer should contain all and only the positions with state 1, in ascending order.

## Query and Answer Format (must be strictly followed)

Each query must contain only one tag. Use the following XML format:

- Range Count Query (e.g., screening range [5, 12]):
<query_range>5,12</query_range>

- Point Probe Query (e.g., sampling position 7):
<query_point>7</query_point>

When submitting the final answer, list all positions with state 1 (comma-separated, in ascending order), using this format:

<answer>1,4,7,10,13</answer>

If you believe no position has state 1, submit an empty answer:

<answer></answer>
"""

    contextualized_rule_zh_5 = """\
我们现在来玩一个“连环伪造账目追踪”游戏，规则如下：

作为司法审计员，你需要审查案卷中连续编号的 {n} 份财务流水凭证（卷宗编号从 1 到 {n}）。犯罪分子采用了某种隐蔽的周期性洗钱算法来混入伪造的账目：
- 存在一个隐藏的洗钱周期长度 P（2 到 10 之间）和一个长度为 P 的账目模板 M（由 0代表合法 和 1代表伪造 组成，至少包含一份伪造账目 1）。
- 凭证序列 A 从位置 1 开始，按照模板 M 周期性重复生成。即对于任意凭证 i（1 到 {n}），其合法性状态 A[i] 的值等于模板 M 中第 ((i-1) 取模 P + 1) 个位置的值。

你的目标是推断出所有状态为 1（涉嫌伪造/洗钱）的凭证位置，并提交一个有序列表。你可以通过以下两种方式向系统提问：

1. 批量资金流向核查（区间计数查询）：询问卷宗区间 [L, R] 内有多少份凭证的状态为 1。
   - 约束：L 和 R 必须满足 1 小于等于 L 小于等于 R 小于等于 {n}，且核查区间长度（R - L + 1）必须大于等于 {wmin}。
   - 回答：返回一个整数，表示该区间内伪造账目的数量。

2. 定点传唤质询（单点探测查询）：询问某份特定凭证 i 的状态是否为 1。
   - 约束：i 必须在 1 到 {n} 之间。
   - 回答：“是”或“否”。
   - 注意：传唤程序繁琐，质询次数最多只能使用 {smax} 次。

查询约束：
- 总查询次数（批量核查 + 定点质询）不能超过 {qmax} 次。
- 定点质询次数不能超过 {smax} 次。
- 任何不合法或越界的指令仍会计入总查询次数。
- 超出核查预算或质询预算将导致审计失败。

当你收集足够信息后，请提交最终追赃稽查报告。答案应包含所有且仅有状态为 1 的凭证编号，按升序排列。

## 询问与提交答案的格式（必须严格遵守）

每次询问只能包含一个标签。请使用以下 XML 格式：

- 区间计数查询（例如核查区间 [5, 12]）：
<query_range>5,12</query_range>

- 单点探测查询（例如质询位置 7）：
<query_point>7</query_point>

提交最终答案时，必须列出所有状态为 1 的位置（用逗号分隔，按升序排列），格式如下：

<answer>1,4,7,10,13</answer>

如果认为没有任何位置的状态为 1，则提交空答案：

<answer></answer>
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
Let's play a "Serial Forged Accounts Tracking" game. Here are the rules:

As a forensic auditor, you need to examine {n} consecutively numbered financial transaction vouchers in a case file (indexed from 1 to {n}). Criminals have used a hidden periodic money laundering algorithm to mix in forged accounts:
- There exists a hidden laundering period length P (between 2 and 10) and an account template M of length P (consisting of 0s for legal and 1s for forged, with at least one 1).
- The voucher sequence A is generated by repeating template M periodically starting from position 1. That is, for any voucher i (1 to {n}), its legality state A[i] equals the value at position ((i-1) modulo P + 1) in template M.

Your goal is to infer all positions where the state is 1 (suspected forgery/laundering) and submit an ordered list. You can ask questions in two ways:

1. Batch Fund Flow Verification (Range Count Query): Ask how many vouchers in the range [L, R] have state 1.
   - Constraint: L and R must satisfy 1 less than or equal to L less than or equal to R less than or equal to {n}, and the verification range length (R - L + 1) must be greater than or equal to {wmin}.
   - Response: Returns an integer representing the count of forged accounts in that range.

2. Point Summons Interrogation (Point Probe Query): Ask whether a specific voucher i has state 1.
   - Constraint: i must be between 1 and {n}.
   - Response: "Yes" or "No".
   - Note: The summons procedure is cumbersome; interrogations are limited to a maximum of {smax} uses.

Query Constraints:
- Total query count (batch verification + point interrogation) cannot exceed {qmax} times.
- Point interrogation count cannot exceed {smax} times.
- Any illegal or out-of-bounds command still counts toward the total query count.
- Exceeding the verification budget or interrogation budget will result in audit failure.

When you have gathered enough information, submit your final asset recovery and inspection report. The answer should contain all and only the positions with state 1, in ascending order.

## Query and Answer Format (must be strictly followed)

Each query must contain only one tag. Use the following XML format:

- Range Count Query (e.g., verifying range [5, 12]):
<query_range>5,12</query_range>

- Point Probe Query (e.g., interrogating position 7):
<query_point>7</query_point>

When submitting the final answer, list all positions with state 1 (comma-separated, in ascending order), using this format:

<answer>1,4,7,10,13</answer>

If you believe no position has state 1, submit an empty answer:

<answer></answer>
"""

    tags = ["answer", "query_range", "query_point"]
    reasoning_type = "归纳推理"
    data_structure = "序列"

    # 难度配置说明：
    # 1 (简单)       - N=40,  P=4,  M=1001,   Qmax=20, Smax=3, Wmin=3
    # 2 (中等偏下)   - N=60,  P=5,  M=10101,  Qmax=20, Smax=3, Wmin=3
    # 3 (中等偏上)   - N=80,  P=6,  M=110010, Qmax=20, Smax=3, Wmin=3
    # 4 (较难)       - N=100, P=7,  M=1010011, Qmax=20, Smax=3, Wmin=3
    # 5 (难)         - N=120, P=9,  M=101001101, Qmax=20, Smax=3, Wmin=3

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 40,
                "p": 4,
                "template": "1001",
                "qmax": 20,
                "smax": 3,
                "wmin": 3,
            },
            2: {
                "n": 60,
                "p": 5,
                "template": "10101",
                "qmax": 20,
                "smax": 3,
                "wmin": 3,
            },
            3: {
                "n": 80,
                "p": 6,
                "template": "110010",
                "qmax": 20,
                "smax": 3,
                "wmin": 3,
            },
            4: {
                "n": 100,
                "p": 7,
                "template": "1010011",
                "qmax": 20,
                "smax": 3,
                "wmin": 3,
            },
            5: {
                "n": 120,
                "p": 9,
                "template": "101001101",
                "qmax": 20,
                "smax": 3,
                "wmin": 3,
            },
        },
        "en": {
            1: {
                "n": 40,
                "p": 4,
                "template": "1001",
                "qmax": 20,
                "smax": 3,
                "wmin": 3,
            },
            2: {
                "n": 60,
                "p": 5,
                "template": "10101",
                "qmax": 20,
                "smax": 3,
                "wmin": 3,
            },
            3: {
                "n": 80,
                "p": 6,
                "template": "110010",
                "qmax": 20,
                "smax": 3,
                "wmin": 3,
            },
            4: {
                "n": 100,
                "p": 7,
                "template": "1010011",
                "qmax": 20,
                "smax": 3,
                "wmin": 3,
            },
            5: {
                "n": 120,
                "p": 9,
                "template": "101001101",
                "qmax": 20,
                "smax": 3,
                "wmin": 3,
            },
        },
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        """初始化游戏，设置周期序列和查询计数器"""
        lang = self.config.language
        diff = int(self.config.difficulty)

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        
        # 设置游戏参数
        self.n = cfg["n"]
        self.p = cfg["p"]
        self.template = cfg["template"]
        self.qmax = cfg["qmax"]
        self.smax = cfg["smax"]
        self.wmin = cfg["wmin"]
        
        # 保存到 game_info 用于格式化规则文本
        self._game_info["n"] = self.n
        self._game_info["qmax"] = self.qmax
        self._game_info["smax"] = self.smax
        self._game_info["wmin"] = self.wmin
        
        # 生成完整序列 A
        self.sequence = []
        for i in range(1, self.n + 1):
            template_idx = ((i - 1) % self.p)
            self.sequence.append(int(self.template[template_idx]))
        
        # 计算所有值为 1 的位置（Ground Truth）
        self.true_ones = set()
        for i in range(1, self.n + 1):
            if self.sequence[i - 1] == 1:
                self.true_ones.add(i)
        
        # 初始化查询计数器
        self.total_queries = 0
        self.point_queries = 0

    def evaluate(self, parsed_info):
        """评估提交的答案是否正确"""
        raw_ans = parsed_info["answer"].strip()
        
        # 处理空答案的情况
        if raw_ans == "":
            submitted_ones = set()
        else:
            try:
                # 解析提交的位置列表
                submitted_ones = set()
                for pos_str in raw_ans.split(","):
                    pos_str = pos_str.strip()
                    if pos_str:
                        pos = int(pos_str)
                        if pos < 1 or pos > self.n:
                            return False
                        submitted_ones.add(pos)
            except:
                return False
        
        # 检查是否完全匹配
        return submitted_ones == self.true_ones

    def _cf_core_produce(self, parsed_info):
        """核心业务逻辑"""
        # 检查是否超出总查询次数
        if self.total_queries >= self.qmax:
            if self.config.language == "zh":
                raise ValueError(f"查询次数已达上限 {self.qmax} 次")
            else:
                raise ValueError(f"Query limit of {self.qmax} reached")
        
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
            error_format = "错误：格式无效或参数错误。"
            error_range = "错误：区间参数不合法或窗口长度小于 {wmin}。"
            error_point_limit = f"错误：单点探测次数已达上限 {self.smax} 次。"
            error_point_range = f"错误：位置超出范围 [1, {self.n}]。"
        else:
            yes_res, no_res = "Yes", "No"
            error_format = "Error: Invalid format or parameters."
            error_range = "Error: Invalid range parameters or window size less than {wmin}."
            error_point_limit = f"Error: Point probe limit of {self.smax} reached."
            error_point_range = f"Error: Position out of range [1, {self.n}]."
        
        # 优先处理 query_range
        if "query_range" in parsed_info:
            self.total_queries += 1
            try:
                raw = parsed_info["query_range"].strip()
                parts = [x.strip() for x in raw.split(",")]
                if len(parts) != 2:
                    return error_format
                
                L, R = int(parts[0]), int(parts[1])
                
                # 检查范围合法性
                if L < 1 or R > self.n or L > R:
                    return error_range.format(wmin=self.wmin)
                
                # 检查窗口长度
                if R - L + 1 < self.wmin:
                    return error_range.format(wmin=self.wmin)
                
                # 计算区间内值为 1 的数量
                count = sum(1 for i in range(L, R + 1) if self.sequence[i - 1] == 1)
                return str(count)
            except:
                return error_format
        
        # 处理 query_point
        elif "query_point" in parsed_info:
            # 先检查单点查询次数限制
            if self.point_queries >= self.smax:
                self.total_queries += 1
                return error_point_limit
            
            self.total_queries += 1
            self.point_queries += 1
            
            try:
                raw = parsed_info["query_point"].strip()
                i = int(raw)
                
                # 检查位置合法性
                if i < 1 or i > self.n:
                    return error_point_range
                
                # 返回该位置的值
                return yes_res if self.sequence[i - 1] == 1 else no_res
            except:
                return error_format
        
        else:
            raise ValueError("No valid query tag found.")

    def get_all_possible_queries(self) -> list[dict]:
        """
        枚举部分具有代表性的合法查询并返回对应的正确答案。
        为防止在难度为 5 (N=120) 时区间查询数量达到 7000+ 导致上下文爆炸，
        仅生成以下查询：
        1. 前 smax 个单点探测查询。
        2. 所有长度等于 wmin 的区间计数查询。
        3. 整个序列的全局区间查询。

        Returns:
            list of dict, 每项格式：
            {
                "query" : str,   # 查询内容字符串（XML格式），明确包含查询标签
                "answer": str,   # 调用游戏逻辑后得到的正确答案字符串
            }
        """
        queries = []
        
        # 确定回答的语言
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
        else:
            yes_res, no_res = "Yes", "No"

        # 1. 选取前 smax 个合法的单点探测查询 (Point Probe)
        for i in range(1, min(self.smax, self.n) + 1):
            query_str = f"<query_point>{i}</query_point>"
            val = self.sequence[i - 1]
            ans_str = yes_res if val == 1 else no_res
            queries.append({
                "query": query_str,
                "answer": ans_str
            })

        # 2. 选取长度刚好为 wmin 的区间计数查询 (Range Count)
        for L in range(1, self.n - self.wmin + 2):
            R = L + self.wmin - 1
            query_str = f"<query_range>{L},{R}</query_range>"
            count = sum(self.sequence[L - 1 : R])
            ans_str = str(count)
            queries.append({
                "query": query_str,
                "answer": ans_str
            })
            
        # 3. 添加一个覆盖全局的区间查询作为额外冗余
        queries.append({
            "query": f"<query_range>1,{self.n}</query_range>",
            "answer": str(sum(self.sequence))
        })
                
        return queries

    def _cf_make_wrong(self, correct):
        if correct.isdigit():
            return str(int(correct) + 1)
        
        # 检查是否为中文回答
        if correct == "是":
            return "否"
        elif correct == "否":
            return "是"
        
        # 检查是否为英文回答（忽略大小写但保留格式）
        lower_correct = correct.lower()
        if lower_correct == "yes":
            # 保持原大小写风格（简单处理：首字母大写）
            return "No"
        elif lower_correct == "no":
            return "Yes"
            
        return correct + "_WRONG"