from .base import Game
import re

class GraphRuleInferenceGame(Game):

    game_rule_zh = """\
我们来玩一个"图规则推断"游戏，规则如下：

游戏设定了一个无向简单图，节点集合为 {{A, B, C, D, E, F, G, H}}，无自环。每个节点带有两个二元属性 α 和 β，取值均为 0 或 1。具体赋值为：
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

整个图的边生成遵循且仅遵循以下四个候选规则之一（整局内不变）：
1. 规则1：当且仅当两节点的 α 相同时，二者之间有边。
2. 规则2：当且仅当两节点的 β 相同时，二者之间有边。
3. 规则3：当且仅当两节点的 α 不同时，二者之间有边。
4. 规则4：当且仅当两节点的 β 不同时，二者之间有边。

你的目标是：
1. 推断出当前采用的真实规则（从规则1、规则2、规则3、规则4中选一个）。
2. 判断节点 A 与节点 D 之间是否存在边。

你可以多轮查询任意两个节点之间是否有边，每次查询会如实告诉你"有边"或"无边"。但有以下约束：
- 禁止查询任何包含节点 A 或节点 D 的节点对。
- 至少需要进行两次有效且互不重复的查询后，才可提交最终答案。

每次查询边的存在性时，使用以下 XML 格式（X、Y 为节点名称，且 X、Y 不能是 A 或 D）：

<query_edge>X-Y</query_edge>

提交最终答案时，必须包含推断的规则编号（1、2、3 或 4）以及 A-D 是否有边（有边 或 无边），格式如下：

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

其中 {{rule_number}} 为 1、2、3 或 4，{{edge_status}} 为 "有边" 或 "无边"。
"""

    game_rule_en = """\
Let's play a "Graph Rule Inference" game. Here are the rules:

There is an undirected simple graph with node set {{A, B, C, D, E, F, G, H}}, and no self-loops. Each node has two binary attributes α and β, each taking value 0 or 1. The specific assignments are:
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

The edges in the graph are generated by exactly one of the following four candidate rules (fixed throughout the game):
1. Rule1: An edge exists between two nodes if and only if their α values are the same.
2. Rule2: An edge exists between two nodes if and only if their β values are the same.
3. Rule3: An edge exists between two nodes if and only if their α values are different.
4. Rule4: An edge exists between two nodes if and only if their β values are different.

Your goals are:
1. Infer the actual rule being used (choose from Rule1, Rule2, Rule3, or Rule4).
2. Determine whether there is an edge between node A and node D.

You can query whether an edge exists between any two nodes across multiple rounds. Each query will truthfully tell you "edge exists" or "no edge". However, there are constraints:
- You are forbidden to query any node pair that includes node A or node D.
- You must perform at least two valid and non-duplicate queries before submitting your final answer.

When querying edge existence, use the following XML format (X, Y are node names, and neither X nor Y can be A or D):

<query_edge>X-Y</query_edge>

When submitting the final answer, you must include the inferred rule number (1, 2, 3, or 4) and whether A-D has an edge (edge exists or no edge), in the following format:

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

Where {{rule_number}} is 1, 2, 3, or 4, and {{edge_status}} is "edge exists" or "no edge".
"""

    contextualized_rule_zh_1 = """\
我们来测试一个"交通路网规则推断"系统，规则如下：

系统设定了一个城市交通路网，包含8个核心枢纽，集合为 {{A, B, C, D, E, F, G, H}}，无自环。每个枢纽带有两个二元属性 α（区域分布：0为北区，1为南区）和 β（枢纽类型：0为客运，1为货运）。具体赋值为：
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

整个路网的直达线路（边）生成遵循且仅遵循以下四个候选规则之一（整局内不变）：
1. 规则1：当且仅当两枢纽的 α 相同时，二者之间有边（线路）。
2. 规则2：当且仅当两枢纽的 β 相同时，二者之间有边（线路）。
3. 规则3：当且仅当两枢纽的 α 不同时，二者之间有边（线路）。
4. 规则4：当且仅当两枢纽的 β 不同时，二者之间有边（线路）。

你的目标是：
1. 推断出当前采用的真实规则（从规则1、规则2、规则3、规则4中选一个）。
2. 判断枢纽 A 与枢纽 D 之间是否存在边（线路）。

你可以多轮查询任意两个枢纽之间是否有边，每次查询会如实告诉你"有边"或"无边"。但有以下约束：
- 禁止查询任何包含枢纽 A 或枢纽 D 的枢纽对。
- 至少需要进行两次有效且互不重复的查询后，才可提交最终答案。

每次查询边的存在性时，使用以下 XML 格式（X、Y 为枢纽名称，且 X、Y 不能是 A 或 D）：

<query_edge>X-Y</query_edge>

提交最终答案时，必须包含推断的规则编号（1、2、3 或 4）以及 A-D 是否有边（有边 或 无边），格式如下：

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

其中 {{rule_number}} 为 1、2、3 或 4，{{edge_status}} 为 "有边" 或 "无边"。
"""

    contextualized_rule_en_1 = """\
[Transportation Scenario]
Let's test a "Traffic Network Rule Inference" system. Here are the rules:

The system models an urban traffic network with a hub set {{A, B, C, D, E, F, G, H}}, and no self-loops. Each hub has two binary attributes α (zone: 0 for North, 1 for South) and β (type: 0 for Passenger, 1 for Freight). The specific assignments are:
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

The direct routes (edges) in the network are generated by exactly one of the following four candidate rules (fixed throughout the game):
1. Rule1: An edge (route) exists between two hubs if and only if their α values are the same.
2. Rule2: An edge (route) exists between two hubs if and only if their β values are the same.
3. Rule3: An edge (route) exists between two hubs if and only if their α values are different.
4. Rule4: An edge (route) exists between two hubs if and only if their β values are different.

Your goals are:
1. Infer the actual rule being used (choose from Rule1, Rule2, Rule3, or Rule4).
2. Determine whether there is an edge (route) between hub A and hub D.

You can query whether an edge exists between any two hubs across multiple rounds. Each query will truthfully tell you "edge exists" or "no edge". However, there are constraints:
- You are forbidden to query any hub pair that includes hub A or hub D.
- You must perform at least two valid and non-duplicate queries before submitting your final answer.

When querying edge existence, use the following XML format (X, Y are hub names, and neither X nor Y can be A or D):

<query_edge>X-Y</query_edge>

When submitting the final answer, you must include the inferred rule number (1, 2, 3, or 4) and whether A-D has an edge (edge exists or no edge), in the following format:

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

Where {{rule_number}} is 1, 2, 3, or 4, and {{edge_status}} is "edge exists" or "no edge".
"""

    contextualized_rule_zh_2 = """\
我们来测试一个"医疗院感追踪规则推断"系统，规则如下：

系统设定了一个传染病隔离区，包含8名首发病例，节点集合为 {{A, B, C, D, E, F, G, H}}，无自环。每个病例带有两个二元属性 α（感染毒株：0为甲型，1为乙型）和 β（病区分布：0为东区，1为西区）。具体赋值为：
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

病例间的密切接触网络（边）生成遵循且仅遵循以下四个候选流调规则之一（整局内不变）：
1. 规则1：当且仅当两病例的 α 相同时，二者之间有边（接触史）。
2. 规则2：当且仅当两病例的 β 相同时，二者之间有边（接触史）。
3. 规则3：当且仅当两病例的 α 不同时，二者之间有边（接触史）。
4. 规则4：当且仅当两病例的 β 不同时，二者之间有边（接触史）。

你的目标是：
1. 推断出当前追踪采用的真实规则（从规则1、规则2、规则3、规则4中选一个）。
2. 判断病例 A 与病例 D 之间是否存在边（接触史）。

你可以多轮查询任意两个病例之间是否有边，每次查询会如实告诉你"有边"或"无边"。但有以下约束：
- 禁止查询任何包含病例 A 或病例 D 的病例对。
- 至少需要进行两次有效且互不重复的查询后，才可提交最终答案。

每次查询边的存在性时，使用以下 XML 格式（X、Y 为病例名称，且 X、Y 不能是 A 或 D）：

<query_edge>X-Y</query_edge>

提交最终答案时，必须包含推断的规则编号（1、2、3 或 4）以及 A-D 是否有边（有边 或 无边），格式如下：

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

其中 {{rule_number}} 为 1、2、3 或 4，{{edge_status}} 为 "有边" 或 "无边"。
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
Let's test a "Medical Infection Tracking Rule Inference" system. Here are the rules:

The system models a quarantine zone with 8 primary cases, forming a node set {{A, B, C, D, E, F, G, H}}, with no self-loops. Each case has two binary attributes α (virus strain: 0 for Strain A, 1 for Strain B) and β (ward location: 0 for East, 1 for West). The specific assignments are:
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

The close contact networks (edges) among cases are generated by exactly one of the following four candidate epidemiological rules (fixed throughout the game):
1. Rule1: An edge (contact) exists between two cases if and only if their α values are the same.
2. Rule2: An edge (contact) exists between two cases if and only if their β values are the same.
3. Rule3: An edge (contact) exists between two cases if and only if their α values are different.
4. Rule4: An edge (contact) exists between two cases if and only if their β values are different.

Your goals are:
1. Infer the actual rule being used (choose from Rule1, Rule2, Rule3, or Rule4).
2. Determine whether there is an edge (contact) between case A and case D.

You can query whether an edge exists between any two cases across multiple rounds. Each query will truthfully tell you "edge exists" or "no edge". However, there are constraints:
- You are forbidden to query any case pair that includes case A or case D.
- You must perform at least two valid and non-duplicate queries before submitting your final answer.

When querying edge existence, use the following XML format (X, Y are case names, and neither X nor Y can be A or D):

<query_edge>X-Y</query_edge>

When submitting the final answer, you must include the inferred rule number (1, 2, 3, or 4) and whether A-D has an edge (edge exists or no edge), in the following format:

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

Where {{rule_number}} is 1, 2, 3, or 4, and {{edge_status}} is "edge exists" or "no edge".
"""

    contextualized_rule_zh_3 = """\
我们来测试一个"校园专用网络连接推断"系统，规则如下：

系统设定了一个大学教育网络，包含8栋核心教学楼，节点集合为 {{A, B, C, D, E, F, G, H}}，无自环。每栋楼带有两个二元属性 α（校区归属：0为本部，1为新校区）和 β（建筑功能：0为教学，1为科研）。具体赋值为：
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

整个专用光纤网络的直连链路（边）生成遵循且仅遵循以下四个候选网络拓扑规则之一（整局内不变）：
1. 规则1：当且仅当两栋楼的 α 相同时，二者之间有边（光纤直连）。
2. 规则2：当且仅当两栋楼的 β 相同时，二者之间有边（光纤直连）。
3. 规则3：当且仅当两栋楼的 α 不同时，二者之间有边（光纤直连）。
4. 规则4：当且仅当两栋楼的 β 不同时，二者之间有边（光纤直连）。

你的目标是：
1. 推断出当前校园网实际采用的真实规则（从规则1、规则2、规则3、规则4中选一个）。
2. 判断大楼 A 与大楼 D 之间是否存在边（光纤直连）。

你可以多轮查询任意两栋大楼之间是否有边，每次查询会如实告诉你"有边"或"无边"。但有以下约束：
- 禁止查询任何包含大楼 A 或大楼 D 的建筑组合。
- 至少需要进行两次有效且互不重复的查询后，才可提交最终答案。

每次查询边的存在性时，使用以下 XML 格式（X、Y 为大楼名称，且 X、Y 不能是 A 或 D）：

<query_edge>X-Y</query_edge>

提交最终答案时，必须包含推断的规则编号（1、2、3 或 4）以及 A-D 是否有边（有边 或 无边），格式如下：

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

其中 {{rule_number}} 为 1、2、3 或 4，{{edge_status}} 为 "有边" 或 "无边"。
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Let's test a "Campus Intranet Connectivity Inference" system. Here are the rules:

The system models a university educational network with 8 core buildings, forming a node set {{A, B, C, D, E, F, G, H}}, with no self-loops. Each building has two binary attributes α (campus affiliation: 0 for Main, 1 for New) and β (functionality: 0 for Teaching, 1 for Research). The specific assignments are:
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

The direct fiber-optic links (edges) of the intranet are generated by exactly one of the following four candidate network topology rules (fixed throughout the game):
1. Rule1: An edge (fiber link) exists between two buildings if and only if their α values are the same.
2. Rule2: An edge (fiber link) exists between two buildings if and only if their β values are the same.
3. Rule3: An edge (fiber link) exists between two buildings if and only if their α values are different.
4. Rule4: An edge (fiber link) exists between two buildings if and only if their β values are different.

Your goals are:
1. Infer the actual rule being used (choose from Rule1, Rule2, Rule3, or Rule4).
2. Determine whether there is an edge (fiber link) between building A and building D.

You can query whether an edge exists between any two buildings across multiple rounds. Each query will truthfully tell you "edge exists" or "no edge". However, there are constraints:
- You are forbidden to query any building pair that includes building A or building D.
- You must perform at least two valid and non-duplicate queries before submitting your final answer.

When querying edge existence, use the following XML format (X, Y are building names, and neither X nor Y can be A or D):

<query_edge>X-Y</query_edge>

When submitting the final answer, you must include the inferred rule number (1, 2, 3, or 4) and whether A-D has an edge (edge exists or no edge), in the following format:

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

Where {{rule_number}} is 1, 2, 3, or 4, and {{edge_status}} is "edge exists" or "no edge".
"""

    contextualized_rule_zh_4 = """\
我们来测试一个"工业AGV调度路径推断"系统，规则如下：

系统设定了一个智能制造工厂，包含8个核心生产车间，节点集合为 {{A, B, C, D, E, F, G, H}}，无自环。每个车间带有两个二元属性 α（生产环节：0为初加工，1为精装配）和 β（作业班次：0为白班，1为夜班）。具体赋值为：
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

车间之间的AGV自动导航车直达通道（边）生成遵循且仅遵循以下四个候选调度规则之一（整局内不变）：
1. 规则1：当且仅当两车间的 α 相同时，二者之间有边（AGV通道）。
2. 规则2：当且仅当两车间的 β 相同时，二者之间有边（AGV通道）。
3. 规则3：当且仅当两车间的 α 不同时，二者之间有边（AGV通道）。
4. 规则4：当且仅当两车间的 β 不同时，二者之间有边（AGV通道）。

你的目标是：
1. 推断出当前控制系统实际采用的真实规则（从规则1、规则2、规则3、规则4中选一个）。
2. 判断车间 A 与车间 D 之间是否存在边（AGV通道）。

你可以多轮查询任意两个车间之间是否有边，每次查询会如实告诉你"有边"或"无边"。但有以下约束：
- 禁止查询任何包含车间 A 或车间 D 的组合。
- 至少需要进行两次有效且互不重复的查询后，才可提交最终答案。

每次查询边的存在性时，使用以下 XML 格式（X、Y 为车间名称，且 X、Y 不能是 A 或 D）：

<query_edge>X-Y</query_edge>

提交最终答案时，必须包含推断的规则编号（1、2、3 或 4）以及 A-D 是否有边（有边 或 无边），格式如下：

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

其中 {{rule_number}} 为 1、2、3 或 4，{{edge_status}} 为 "有边" 或 "无边"。
"""

    contextualized_rule_en_4 = """\
[Manufacturing/Industrial Scenario]
Let's test an "Industrial AGV Routing Rule Inference" system. Here are the rules:

The system models a smart manufacturing plant with 8 core production workshops, forming a node set {{A, B, C, D, E, F, G, H}}, with no self-loops. Each workshop has two binary attributes α (production phase: 0 for Preliminary, 1 for Assembly) and β (operational shift: 0 for Day, 1 for Night). The specific assignments are:
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

The direct Automated Guided Vehicle (AGV) paths (edges) between workshops are generated by exactly one of the following four candidate routing rules (fixed throughout the game):
1. Rule1: An edge (AGV path) exists between two workshops if and only if their α values are the same.
2. Rule2: An edge (AGV path) exists between two workshops if and only if their β values are the same.
3. Rule3: An edge (AGV path) exists between two workshops if and only if their α values are different.
4. Rule4: An edge (AGV path) exists between two workshops if and only if their β values are different.

Your goals are:
1. Infer the actual rule being used (choose from Rule1, Rule2, Rule3, or Rule4).
2. Determine whether there is an edge (AGV path) between workshop A and workshop D.

You can query whether an edge exists between any two workshops across multiple rounds. Each query will truthfully tell you "edge exists" or "no edge". However, there are constraints:
- You are forbidden to query any workshop pair that includes workshop A or workshop D.
- You must perform at least two valid and non-duplicate queries before submitting your final answer.

When querying edge existence, use the following XML format (X, Y are workshop names, and neither X nor Y can be A or D):

<query_edge>X-Y</query_edge>

When submitting the final answer, you must include the inferred rule number (1, 2, 3, or 4) and whether A-D has an edge (edge exists or no edge), in the following format:

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

Where {{rule_number}} is 1, 2, 3, or 4, and {{edge_status}} is "edge exists" or "no edge".
"""

    contextualized_rule_zh_5 = """\
我们来测试一个"企业商业关联规则推断"系统，规则如下：

系统设定了一个商业网络，包含8个核心企业实体，节点集合为 {{A, B, C, D, E, F, G, H}}，无自环。每个企业实体带有两个二元属性 α（注册管辖区：0为境内，1为离岸）和 β（实体类型：0为子公司，1为控股公司）。具体赋值为：
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

企业间的直接资金往来通道（边）生成遵循且仅遵循以下四个候选合规规则之一（整局内不变）：
1. 规则1：当且仅当两企业的 α 相同时，二者之间有边（资金通道）。
2. 规则2：当且仅当两企业的 β 相同时，二者之间有边（资金通道）。
3. 规则3：当且仅当两企业的 α 不同时，二者之间有边（资金通道）。
4. 规则4：当且仅当两企业的 β 不同时，二者之间有边（资金通道）。

你的目标是：
1. 推断出当前商业网络实际采用的真实规则（从规则1、规则2、规则3、规则4中选一个）。
2. 判断企业 A 与企业 D 之间是否存在边（资金通道）。

你可以多轮查询任意两个企业之间是否有边，每次查询会如实告诉你"有边"或"无边"。但有以下约束：
- 禁止查询任何包含企业 A 或企业 D 的关联对。
- 至少需要进行两次有效且互不重复的查询后，才可提交最终答案。

每次查询边的存在性时，使用以下 XML 格式（X、Y 为企业名称，且 X、Y 不能是 A 或 D）：

<query_edge>X-Y</query_edge>

提交最终答案时，必须包含推断的规则编号（1、2、3 或 4）以及 A-D 是否有边（有边 或 无边），格式如下：

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

其中 {{rule_number}} 为 1、2、3 或 4，{{edge_status}} 为 "有边" 或 "无边"。
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
Let's test a "Corporate Business Association Rule Inference" system. Here are the rules:

The system models a business network with 8 core corporate entities, forming a node set {{A, B, C, D, E, F, G, H}}, with no self-loops. Each entity has two binary attributes α (jurisdiction: 0 for Domestic, 1 for Offshore) and β (entity type: 0 for Subsidiary, 1 for Holding). The specific assignments are:
- A(0,0), B(0,1), C(1,0), D(1,1), E(0,0), F(0,1), G(1,0), H(1,1)

The direct financial transaction channels (edges) between entities are generated by exactly one of the following four candidate compliance rules (fixed throughout the game):
1. Rule1: An edge (financial channel) exists between two entities if and only if their α values are the same.
2. Rule2: An edge (financial channel) exists between two entities if and only if their β values are the same.
3. Rule3: An edge (financial channel) exists between two entities if and only if their α values are different.
4. Rule4: An edge (financial channel) exists between two entities if and only if their β values are different.

Your goals are:
1. Infer the actual rule being used (choose from Rule1, Rule2, Rule3, or Rule4).
2. Determine whether there is an edge (financial channel) between entity A and entity D.

You can query whether an edge exists between any two entities across multiple rounds. Each query will truthfully tell you "edge exists" or "no edge". However, there are constraints:
- You are forbidden to query any entity pair that includes entity A or entity D.
- You must perform at least two valid and non-duplicate queries before submitting your final answer.

When querying edge existence, use the following XML format (X, Y are entity names, and neither X nor Y can be A or D):

<query_edge>X-Y</query_edge>

When submitting the final answer, you must include the inferred rule number (1, 2, 3, or 4) and whether A-D has an edge (edge exists or no edge), in the following format:

<answer>rule={{rule_number}}, A-D={{edge_status}}</answer>

Where {{rule_number}} is 1, 2, 3, or 4, and {{edge_status}} is "edge exists" or "no edge".
"""

    tags = ["answer", "query_edge"]
    user_prompt_zh = "你可以开始第一次查询了。"
    user_prompt_en = "You can start your first query now."

    reasoning_type = "溯因推理"
    data_structure = "图"

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {"rule": 1},
            2: {"rule": 2},
            3: {"rule": 3},
            4: {"rule": 4},
            5: {"rule": 1},
        },
        "en": {
            1: {"rule": 1},
            2: {"rule": 2},
            3: {"rule": 3},
            4: {"rule": 4},
            5: {"rule": 1},
        },
    }

    def __init__(self, config):
        self.node_attrs = {
            "A": (0, 0), "B": (0, 1), "C": (1, 0), "D": (1, 1),
            "E": (0, 0), "F": (0, 1), "G": (1, 0), "H": (1, 1),
        }
        self.query_history = set()
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = int(self.config.difficulty)

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        self.true_rule = cfg["rule"]
        
        self._game_info = {}

    def _has_edge(self, node1, node2):
        alpha1, beta1 = self.node_attrs[node1]
        alpha2, beta2 = self.node_attrs[node2]
        
        if self.true_rule == 1:
            return alpha1 == alpha2
        elif self.true_rule == 2:
            return beta1 == beta2
        elif self.true_rule == 3:
            return alpha1 != alpha2
        elif self.true_rule == 4:
            return beta1 != beta2
        else:
            raise ValueError(f"Unknown rule: {self.true_rule}")

    def evaluate(self, parsed_info):
        raw_ans = parsed_info["answer"]
        
        
        try:
            rule_match = re.search(r'rule\s*=\s*(\d+)', raw_ans, re.IGNORECASE)
            
            ad_match = re.search(r'A-D\s*=\s*([^,]+)', raw_ans, re.IGNORECASE)
            
            if not rule_match or not ad_match:
                return False
            
            submitted_rule = int(rule_match.group(1))
            submitted_ad = ad_match.group(1).strip()
            
            if submitted_rule != self.true_rule:
                return False
            
            true_ad_edge = self._has_edge("A", "D")
            
            if self.config.language == "zh":
                expected_ad = "有边" if true_ad_edge else "无边"
            else:
                expected_ad = "edge exists" if true_ad_edge else "no edge"
            
            return submitted_ad.lower().replace(" ", "") == expected_ad.lower().replace(" ", "")
            
        except Exception:
            return False

    def _cf_core_produce(self, parsed_info):
        if "query_edge" not in parsed_info:
            raise ValueError("No valid query tag found.")
        
        query_str = parsed_info["query_edge"].strip()
        
        if "-" in query_str:
            parts = query_str.split("-")
        elif "," in query_str:
            parts = query_str.split(",")
        else:
            if self.config.language == "zh":
                return "错误：查询格式无效，请使用 X-Y 格式。"
            else:
                return "Error: Invalid query format, please use X-Y format."
        
        if len(parts) != 2:
            if self.config.language == "zh":
                return "错误：查询必须包含恰好两个节点。"
            else:
                return "Error: Query must contain exactly two nodes."
        
        node1, node2 = parts[0].strip().upper(), parts[1].strip().upper()
        
        if node1 not in self.node_attrs or node2 not in self.node_attrs:
            if self.config.language == "zh":
                return "错误：节点名称无效。"
            else:
                return "Error: Invalid node name."
        
        if node1 == node2:
            if self.config.language == "zh":
                return "错误：不能查询同一个节点。"
            else:
                return "Error: Cannot query the same node."
        
        if node1 in ["A", "D"] or node2 in ["A", "D"]:
            if self.config.language == "zh":
                return "错误：禁止查询包含节点 A 或 D 的节点对。"
            else:
                return "Error: Queries involving node A or D are forbidden."
        
        normalized_pair = tuple(sorted([node1, node2]))
        self.query_history.add(normalized_pair)
        
        has_edge = self._has_edge(node1, node2)
        
        if self.config.language == "zh":
            return "有边" if has_edge else "无边"
        else:
            return "edge exists" if has_edge else "no edge"

    def _cf_make_wrong(self, correct):
        if self.config.language == "zh":
            if correct == "有边":
                return "无边"
            if correct == "无边":
                return "有边"
        else:
            lower_c = correct.lower().strip()
            if lower_c == "edge exists":
                return "no edge"
            if lower_c == "no edge":
                return "edge exists"
        
        return correct + "_WRONG"

    def get_all_possible_queries(self):
        valid_nodes = sorted([n for n in self.node_attrs.keys() if n not in ["A", "D"]])
        results = []
        
        for i in range(len(valid_nodes)):
            for j in range(i + 1, len(valid_nodes)):
                node1 = valid_nodes[i]
                node2 = valid_nodes[j]
                
                query_content = f"<query_edge>{node1}-{node2}</query_edge>"
                
                has_edge = self._has_edge(node1, node2)
                
                if self.config.language == "zh":
                    answer = "有边" if has_edge else "无边"
                else:
                    answer = "edge exists" if has_edge else "no edge"
                
                results.append({
                    "query": query_content,
                    "answer": answer
                })
        
        return results