from .base import Game
import re

class HiddenSequenceGame(Game):
    reasoning_type = "归纳推理"
    data_structure = "序列"

    game_rule_zh = """\
我们来玩一个"隐藏序列推理"游戏，规则如下：

游戏设定了一个长度为 {n} 的隐藏整数序列 S，其中每项取值范围为 0 到 9。该序列由一个固定的规律生成（例如：周期重复、等差变化、分段模式等），但这个规律对你保密。

已知信息：
- 序列长度 N = {n}
- 目标索引 T = {target}（索引从 1 开始）
- 前缀和定义：P(k) 表示从第 1 项到第 k 项的累加和

你的目标是在尽可能少的测量次数内，推断出序列规律并准确预测 P({target}) 的值。

你可以进行以下两类查询：

1. 测量请求（计入测量次数）：
   - 查询某个索引 k 的前缀和 P(k)（k 的范围是 1 到 {n}，但不能等于 {target}）
   - 我会回答 P(k) 的具体数值
   - 注意：你最多只能进行 {max_queries} 次测量

2. 比较请求（不计入测量次数）：
   - 比较两个索引 k1 和 k2 的前缀和大小关系（k1 和 k2 都不能等于 {target}）
   - 我会回答 P(k1) 与 P(k2) 的大小关系（大于、等于或小于）

提示：你可以通过两个前缀和的差值计算区间和，从而识别序列规律。

每次只能包含一个查询标签。使用以下 XML 格式：

- 测量请求（例如查询索引 5 的前缀和）：
<query_measure>5</query_measure>

- 比较请求（例如比较索引 3 和 7 的前缀和）：
<query_compare>3,7</query_compare>

提交最终答案时，必须包含以下信息：
1. 规律描述：简要说明序列的生成规律（不超过 100 字）
2. 目标前缀和：P({target}) 的预测值
3. 两个校验点：选择两个未测量且不等于 {target} 的索引 u1 和 u2，并预测它们的前缀和

答案格式如下：
<answer>
pattern=你的规律描述
target={target},value=预测的P({target})值
check1=u1索引,value=预测的P(u1)值
check2=u2索引,value=预测的P(u2)值
</answer>

例如：
<answer>
pattern=序列为周期重复 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    game_rule_en = """\
Let's play a "Hidden Sequence Deduction" game. Here are the rules:

A hidden integer sequence S of length {n} has been set up, where each element ranges from 0 to 9. The sequence is generated by a fixed pattern (e.g., periodic repetition, arithmetic progression, segmented patterns, etc.), but this pattern is kept secret from you.

Known information:
- Sequence length N = {n}
- Target index T = {target} (1-indexed)
- Prefix sum definition: P(k) represents the cumulative sum from element 1 to element k

Your goal is to infer the sequence pattern and accurately predict the value of P({target}) with as few measurements as possible.

You can perform the following two types of queries:

1. Measurement Query (counts toward the limit):
   - Query the prefix sum P(k) for some index k (k ranges from 1 to {n}, but cannot equal {target})
   - I will respond with the exact value of P(k)
   - Note: You can perform at most {max_queries} measurements

2. Comparison Query (does not count toward the limit):
   - Compare the prefix sums of two indices k1 and k2 (neither k1 nor k2 can equal {target})
   - I will respond with the relationship between P(k1) and P(k2) (greater than, equal to, or less than)

Hint: You can calculate interval sums using the difference between two prefix sums to identify the sequence pattern.

Each query must contain only one tag. Use the following XML format:

- Measurement Query (e.g., querying prefix sum at index 5):
<query_measure>5</query_measure>

- Comparison Query (e.g., comparing prefix sums at indices 3 and 7):
<query_compare>3,7</query_compare>

When submitting your final answer, you must include:
1. Pattern description: Brief explanation of the sequence generation pattern (no more than 100 words)
2. Target prefix sum: Predicted value of P({target})
3. Two checkpoints: Choose two unmeasured indices u1 and u2 (both not equal to {target}) and predict their prefix sums

Answer format:
<answer>
pattern=your pattern description
target={target},value=predicted P({target}) value
check1=u1 index,value=predicted P(u1) value
check2=u2 index,value=predicted P(u2) value
</answer>

Example:
<answer>
pattern=Sequence is periodic repetition of 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    contextualized_rule_zh_1 = """\
你是一个智能交通控制系统的分析师。系统中记录了一段长度为 {n} 的隐藏车流量序列 S，其中每项取值范围为 0 到 9，代表某路段在特定时间段内的拥堵指数。该序列由固定的交通规律生成（如早晚高峰周期、递增模式等），但这个规律对你保密。

已知信息：
- 序列长度 N = {n}
- 目标索引 T = {target}（阶段索引从 1 开始）
- 前缀和定义：P(k) 表示从第 1 阶段到第 k 阶段的累加拥堵负荷

你的目标是在尽可能少的测量次数内，推断出车流规律并准确预测 P({target}) 的值。

你可以进行以下两类查询：

1. 测量请求（计入测量次数）：
   - 查询某个索引 k 的前缀和 P(k)（k 的范围是 1 到 {n}，但不能等于 {target}）
   - 我会回答 P(k) 的具体数值
   - 注意：你最多只能进行 {max_queries} 次测量

2. 比较请求（不计入测量次数）：
   - 比较两个索引 k1 和 k2 的前缀和大小关系（k1 和 k2 都不能等于 {target}）
   - 我会回答 P(k1) 与 P(k2) 的大小关系（大于、等于或小于）

提示：你可以通过两个前缀和的差值计算区间和，从而识别交通规律。

每次只能包含一个查询标签。使用以下 XML 格式：

- 测量请求（例如查询阶段索引 5 的累加负荷）：
<query_measure>5</query_measure>

- 比较请求（例如比较阶段索引 3 和 7 的累加负荷）：
<query_compare>3,7</query_compare>

提交最终答案时，必须包含以下信息：
1. 规律描述：简要说明车流量的生成规律（不超过 100 字）
2. 目标前缀和：P({target}) 的预测值
3. 两个校验点：选择两个未测量且不等于 {target} 的索引 u1 和 u2，并预测它们的前缀和

答案格式如下：
<answer>
pattern=你的规律描述
target={target},value=预测的P({target})值
check1=u1索引,value=预测的P(u1)值
check2=u2索引,value=预测的P(u2)值
</answer>

例如：
<answer>
pattern=车流规律为早晚高峰周期 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
You are an analyst for a smart traffic control system. The system has recorded a hidden traffic flow sequence S of length {n}, where each element ranges from 0 to 9, representing the congestion index of a road segment during specific time periods. This sequence is generated by a fixed traffic pattern (e.g., periodic rush hours, progressive changes, etc.), but this pattern is kept secret from you.

Known information:
- Sequence length N = {n}
- Target index T = {target} (1-indexed)
- Prefix sum definition: P(k) represents the cumulative congestion load from period 1 to period k

Your goal is to infer the traffic pattern and accurately predict the value of P({target}) with as few measurements as possible.

You can perform the following two types of queries:

1. Measurement Query (counts toward the limit):
   - Query the prefix sum P(k) for some index k (k ranges from 1 to {n}, but cannot equal {target})
   - I will respond with the exact value of P(k)
   - Note: You can perform at most {max_queries} measurements

2. Comparison Query (does not count toward the limit):
   - Compare the prefix sums of two indices k1 and k2 (neither k1 nor k2 can equal {target})
   - I will respond with the relationship between P(k1) and P(k2) (greater than, equal to, or less than)

Hint: You can calculate interval sums using the difference between two prefix sums to identify the traffic pattern.

Each query must contain only one tag. Use the following XML format:

- Measurement Query (e.g., querying prefix sum at index 5):
<query_measure>5</query_measure>

- Comparison Query (e.g., comparing prefix sums at indices 3 and 7):
<query_compare>3,7</query_compare>

When submitting your final answer, you must include:
1. Pattern description: Brief explanation of the sequence generation pattern (no more than 100 words)
2. Target prefix sum: Predicted value of P({target})
3. Two checkpoints: Choose two unmeasured indices u1 and u2 (both not equal to {target}) and predict their prefix sums

Answer format:
<answer>
pattern=your pattern description
target={target},value=predicted P({target}) value
check1=u1 index,value=predicted P(u1) value
check2=u2 index,value=predicted P(u2) value
</answer>

Example:
<answer>
pattern=Sequence is periodic rush hour repetition of 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    contextualized_rule_zh_2 = """\
你是一名医学临床数据分析员。患者监测设备生成了一段长度为 {n} 的隐藏生命体征波动序列 S，其中每项取值范围为 0 到 9，代表某种生化指标的异常波动级别。该波动遵循特定的生理节律（如周期重复、渐进变化、分段模式等），但这个节律对你保密。

已知信息：
- 序列长度 N = {n}
- 目标索引 T = {target}（小时索引从 1 开始）
- 前缀和定义：P(k) 表示从第 1 小时到第 k 小时的累计生化负荷

你的目标是在尽可能少的测量次数内，推断出生理节律并准确预测 P({target}) 的值。

你可以进行以下两类查询：

1. 测量请求（计入测量次数）：
   - 查询某个索引 k 的前缀和 P(k)（k 的范围是 1 到 {n}，但不能等于 {target}）
   - 我会回答 P(k) 的具体数值
   - 注意：你最多只能进行 {max_queries} 次测量

2. 比较请求（不计入测量次数）：
   - 比较两个索引 k1 和 k2 的前缀和大小关系（k1 和 k2 都不能等于 {target}）
   - 我会回答 P(k1) 与 P(k2) 的大小关系（大于、等于或小于）

提示：你可以通过两个前缀和的差值计算区间和，从而识别生理节律。

每次只能包含一个查询标签。使用以下 XML 格式：

- 测量请求（例如查询索引 5 的累计负荷）：
<query_measure>5</query_measure>

- 比较请求（例如比较索引 3 和 7 的累计负荷）：
<query_compare>3,7</query_compare>

提交最终答案时，必须包含以下信息：
1. 规律描述：简要说明波动的生成节律（不超过 100 字）
2. 目标前缀和：P({target}) 的预测值
3. 两个校验点：选择两个未测量且不等于 {target} 的索引 u1 和 u2，并预测它们的前缀和

答案格式如下：
<answer>
pattern=你的规律描述
target={target},value=预测的P({target})值
check1=u1索引,value=预测的P(u1)值
check2=u2索引,value=预测的P(u2)值
</answer>

例如：
<answer>
pattern=生理节律为周期重复 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
You are a clinical data analyst. Patient monitoring equipment has generated a hidden vital sign fluctuation sequence S of length {n}, where each element ranges from 0 to 9, representing the abnormality level of a biochemical marker. This sequence is generated by a specific physiological rhythm (e.g., periodic repetition, progressive changes, etc.), but this rhythm is kept secret from you.

Known information:
- Sequence length N = {n}
- Target index T = {target} (1-indexed)
- Prefix sum definition: P(k) represents the cumulative biochemical load from hour 1 to hour k

Your goal is to infer the physiological rhythm and accurately predict the value of P({target}) with as few measurements as possible.

You can perform the following two types of queries:

1. Measurement Query (counts toward the limit):
   - Query the prefix sum P(k) for some index k (k ranges from 1 to {n}, but cannot equal {target})
   - I will respond with the exact value of P(k)
   - Note: You can perform at most {max_queries} measurements

2. Comparison Query (does not count toward the limit):
   - Compare the prefix sums of two indices k1 and k2 (neither k1 nor k2 can equal {target})
   - I will respond with the relationship between P(k1) and P(k2) (greater than, equal to, or less than)

Hint: You can calculate interval sums using the difference between two prefix sums to identify the physiological rhythm.

Each query must contain only one tag. Use the following XML format:

- Measurement Query (e.g., querying prefix sum at index 5):
<query_measure>5</query_measure>

- Comparison Query (e.g., comparing prefix sums at indices 3 and 7):
<query_compare>3,7</query_compare>

When submitting your final answer, you must include:
1. Pattern description: Brief explanation of the physiological rhythm pattern (no more than 100 words)
2. Target prefix sum: Predicted value of P({target})
3. Two checkpoints: Choose two unmeasured indices u1 and u2 (both not equal to {target}) and predict their prefix sums

Answer format:
<answer>
pattern=your pattern description
target={target},value=predicted P({target}) value
check1=u1 index,value=predicted P(u1) value
check2=u2 index,value=predicted P(u2) value
</answer>

Example:
<answer>
pattern=Rhythm is periodic repetition of 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    contextualized_rule_zh_3 = """\
你是一位教育评估专家。学习系统记录了一段长度为 {n} 的隐藏学生专注度缺失序列 S，其中每项取值范围为 0 到 9，代表学生在某知识节点上的分心评分。该序列由固定的学习疲劳与恢复规律生成（例如：周期性波动、线性衰减、分段模式等），但这个规律对你保密。

已知信息：
- 序列长度 N = {n}
- 目标索引 T = {target}（节点索引从 1 开始）
- 前缀和定义：P(k) 表示从第 1 个节点到第 k 个节点的累计疲劳负荷

你的目标是在尽可能少的测量次数内，推断出疲劳规律并准确预测 P({target}) 的值。

你可以进行以下两类查询：

1. 测量请求（计入测量次数）：
   - 查询某个索引 k 的前缀和 P(k)（k 的范围是 1 到 {n}，但不能等于 {target}）
   - 我会回答 P(k) 的具体数值
   - 注意：你最多只能进行 {max_queries} 次测量

2. 比较请求（不计入测量次数）：
   - 比较两个索引 k1 和 k2 的前缀和大小关系（k1 和 k2 都不能等于 {target}）
   - 我会回答 P(k1) 与 P(k2) 的大小关系（大于、等于或小于）

提示：你可以通过两个前缀和的差值计算区间和，从而识别疲劳规律。

每次只能包含一个查询标签。使用以下 XML 格式：

- 测量请求（例如查询索引 5 的累计负荷）：
<query_measure>5</query_measure>

- 比较请求（例如比较索引 3 和 7 的累计负荷）：
<query_compare>3,7</query_compare>

提交最终答案时，必须包含以下信息：
1. 规律描述：简要说明专注度缺失的生成规律（不超过 100 字）
2. 目标前缀和：P({target}) 的预测值
3. 两个校验点：选择两个未测量且不等于 {target} 的索引 u1 和 u2，并预测它们的前缀和

答案格式如下：
<answer>
pattern=你的规律描述
target={target},value=预测的P({target})值
check1=u1索引,value=预测的P(u1)值
check2=u2索引,value=预测的P(u2)值
</answer>

例如：
<answer>
pattern=疲劳规律为周期重复 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
You are an educational assessment expert. The learning system has recorded a hidden student focus deficiency sequence S of length {n}, where each element ranges from 0 to 9, representing the distraction score at specific knowledge nodes. This sequence follows a fixed pattern of learning fatigue and recovery (e.g., periodic fluctuation, linear decay, etc.), but this pattern is kept secret from you.

Known information:
- Sequence length N = {n}
- Target index T = {target} (1-indexed)
- Prefix sum definition: P(k) represents the cumulative fatigue load from node 1 to node k

Your goal is to infer the fatigue pattern and accurately predict the value of P({target}) with as few measurements as possible.

You can perform the following two types of queries:

1. Measurement Query (counts toward the limit):
   - Query the prefix sum P(k) for some index k (k ranges from 1 to {n}, but cannot equal {target})
   - I will respond with the exact value of P(k)
   - Note: You can perform at most {max_queries} measurements

2. Comparison Query (does not count toward the limit):
   - Compare the prefix sums of two indices k1 and k2 (neither k1 nor k2 can equal {target})
   - I will respond with the relationship between P(k1) and P(k2) (greater than, equal to, or less than)

Hint: You can calculate interval sums using the difference between two prefix sums to identify the fatigue pattern.

Each query must contain only one tag. Use the following XML format:

- Measurement Query (e.g., querying prefix sum at index 5):
<query_measure>5</query_measure>

- Comparison Query (e.g., comparing prefix sums at indices 3 and 7):
<query_compare>3,7</query_compare>

When submitting your final answer, you must include:
1. Pattern description: Brief explanation of the fatigue and recovery pattern (no more than 100 words)
2. Target prefix sum: Predicted value of P({target})
3. Two checkpoints: Choose two unmeasured indices u1 and u2 (both not equal to {target}) and predict their prefix sums

Answer format:
<answer>
pattern=your pattern description
target={target},value=predicted P({target}) value
check1=u1 index,value=predicted P(u1) value
check2=u2 index,value=predicted P(u2) value
</answer>

Example:
<answer>
pattern=Fatigue pattern is periodic repetition of 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    contextualized_rule_zh_4 = """\
你是一名工业质检自动化工程师。生产流水线上的传感器记录了一段长度为 {n} 的隐藏加工误差序列 S，其中每项取值范围为 0 到 9，代表产品在某个加工环节的微小偏差值。该偏差由机器周转规律生成（例如：机械周期重复、磨损递增、分段模式等），但这个规律对你保密。

已知信息：
- 序列长度 N = {n}
- 目标索引 T = {target}（环节索引从 1 开始）
- 前缀和定义：P(k) 表示从第 1 环节到第 k 环节的累计加工偏差

你的目标是在尽可能少的测量次数内，推断出机器运转规律并准确预测 P({target}) 的值。

你可以进行以下两类查询：

1. 测量请求（计入测量次数）：
   - 查询某个索引 k 的前缀和 P(k)（k 的范围是 1 到 {n}，但不能等于 {target}）
   - 我会回答 P(k) 的具体数值
   - 注意：你最多只能进行 {max_queries} 次测量

2. 比较请求（不计入测量次数）：
   - 比较两个索引 k1 和 k2 的前缀和大小关系（k1 和 k2 都不能等于 {target}）
   - 我会回答 P(k1) 与 P(k2) 的大小关系（大于、等于或小于）

提示：你可以通过两个前缀和的差值计算区间和，从而识别机器运转规律。

每次只能包含一个查询标签。使用以下 XML 格式：

- 测量请求（例如查询索引 5 的累计偏差）：
<query_measure>5</query_measure>

- 比较请求（例如比较索引 3 和 7 的累计偏差）：
<query_compare>3,7</query_compare>

提交最终答案时，必须包含以下信息：
1. 规律描述：简要说明误差的生成规律（不超过 100 字）
2. 目标前缀和：P({target}) 的预测值
3. 两个校验点：选择两个未测量且不等于 {target} 的索引 u1 和 u2，并预测它们的前缀和

答案格式如下：
<answer>
pattern=你的规律描述
target={target},value=预测的P({target})值
check1=u1索引,value=预测的P(u1)值
check2=u2索引,value=预测的P(u2)值
</answer>

例如：
<answer>
pattern=运转规律为机械周期重复 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
You are an industrial quality control automation engineer. Sensors on the production line have recorded a hidden processing error sequence S of length {n}, where each element ranges from 0 to 9, representing micro-deviations in specific processing steps. This sequence is generated by machine operational cycles (e.g., mechanical periodicity, increasing wear, etc.), but this pattern is kept secret from you.

Known information:
- Sequence length N = {n}
- Target index T = {target} (1-indexed)
- Prefix sum definition: P(k) represents the cumulative processing deviation from step 1 to step k

Your goal is to infer the machine operational pattern and accurately predict the value of P({target}) with as few measurements as possible.

You can perform the following two types of queries:

1. Measurement Query (counts toward the limit):
   - Query the prefix sum P(k) for some index k (k ranges from 1 to {n}, but cannot equal {target})
   - I will respond with the exact value of P(k)
   - Note: You can perform at most {max_queries} measurements

2. Comparison Query (does not count toward the limit):
   - Compare the prefix sums of two indices k1 and k2 (neither k1 nor k2 can equal {target})
   - I will respond with the relationship between P(k1) and P(k2) (greater than, equal to, or less than)

Hint: You can calculate interval sums using the difference between two prefix sums to identify the machine operational pattern.

Each query must contain only one tag. Use the following XML format:

- Measurement Query (e.g., querying prefix sum at index 5):
<query_measure>5</query_measure>

- Comparison Query (e.g., comparing prefix sums at indices 3 and 7):
<query_compare>3,7</query_compare>

When submitting your final answer, you must include:
1. Pattern description: Brief explanation of the error generation pattern (no more than 100 words)
2. Target prefix sum: Predicted value of P({target})
3. Two checkpoints: Choose two unmeasured indices u1 and u2 (both not equal to {target}) and predict their prefix sums

Answer format:
<answer>
pattern=your pattern description
target={target},value=predicted P({target}) value
check1=u1 index,value=predicted P(u1) value
check2=u2 index,value=predicted P(u2) value
</answer>

Example:
<answer>
pattern=Machine operational pattern is periodic repetition of 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    contextualized_rule_zh_5 = """\
你是一位卷宗数据鉴证专家。系统分析了一系列案件记录，生成了一段长度为 {n} 的隐藏风险指数序列 S，其中每项取值范围为 0 到 9，代表特定法庭辩论阶段中的违规风险级别。该指数按固定的诉讼推进规律变化（例如：周期性拉扯、情绪递增、分段模式等），但这个规律对你保密。

已知信息：
- 序列长度 N = {n}
- 目标索引 T = {target}（阶段索引从 1 开始）
- 前缀和定义：P(k) 表示从第 1 阶段到第 k 阶段的累计诉讼风险负荷

你的目标是在尽可能少的测量次数内，推断出诉讼推进规律并准确预测 P({target}) 的值。

你可以进行以下两类查询：

1. 测量请求（计入测量次数）：
   - 查询某个索引 k 的前缀和 P(k)（k 的范围是 1 到 {n}，但不能等于 {target}）
   - 我会回答 P(k) 的具体数值
   - 注意：你最多只能进行 {max_queries} 次测量

2. 比较请求（不计入测量次数）：
   - 比较两个索引 k1 和 k2 的前缀和大小关系（k1 和 k2 都不能等于 {target}）
   - 我会回答 P(k1) 与 P(k2) 的大小关系（大于、等于或小于）

提示：你可以通过两个前缀和的差值计算区间和，从而识别诉讼推进规律。

每次只能包含一个查询标签。使用以下 XML 格式：

- 测量请求（例如查询阶段索引 5 的累计负荷）：
<query_measure>5</query_measure>

- 比较请求（例如比较阶段索引 3 和 7 的累计负荷）：
<query_compare>3,7</query_compare>

提交最终答案时，必须包含以下信息：
1. 规律描述：简要说明风险指数的变化规律（不超过 100 字）
2. 目标前缀和：P({target}) 的预测值
3. 两个校验点：选择两个未测量且不等于 {target} 的索引 u1 和 u2，并预测它们的前缀和

答案格式如下：
<answer>
pattern=你的规律描述
target={target},value=预测的P({target})值
check1=u1索引,value=预测的P(u1)值
check2=u2索引,value=预测的P(u2)值
</answer>

例如：
<answer>
pattern=诉讼推进规律为周期性拉扯 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
You are a case file data forensics expert. The system has analyzed a series of case records to generate a hidden risk index sequence S of length {n}, where each element ranges from 0 to 9, representing the violation risk level during specific court debate stages. This sequence changes according to fixed litigation advancement patterns (e.g., cyclic arguments, escalating emotions, etc.), but this pattern is kept secret from you.

Known information:
- Sequence length N = {n}
- Target index T = {target} (1-indexed)
- Prefix sum definition: P(k) represents the cumulative litigation risk load from stage 1 to stage k

Your goal is to infer the litigation advancement pattern and accurately predict the value of P({target}) with as few measurements as possible.

You can perform the following two types of queries:

1. Measurement Query (counts toward the limit):
   - Query the prefix sum P(k) for some index k (k ranges from 1 to {n}, but cannot equal {target})
   - I will respond with the exact value of P(k)
   - Note: You can perform at most {max_queries} measurements

2. Comparison Query (does not count toward the limit):
   - Compare the prefix sums of two indices k1 and k2 (neither k1 nor k2 can equal {target})
   - I will respond with the relationship between P(k1) and P(k2) (greater than, equal to, or less than)

Hint: You can calculate interval sums using the difference between two prefix sums to identify the litigation advancement pattern.

Each query must contain only one tag. Use the following XML format:

- Measurement Query (e.g., querying prefix sum at index 5):
<query_measure>5</query_measure>

- Comparison Query (e.g., comparing prefix sums at indices 3 and 7):
<query_compare>3,7</query_compare>

When submitting your final answer, you must include:
1. Pattern description: Brief explanation of the risk index advancement pattern (no more than 100 words)
2. Target prefix sum: Predicted value of P({target})
3. Two checkpoints: Choose two unmeasured indices u1 and u2 (both not equal to {target}) and predict their prefix sums

Answer format:
<answer>
pattern=your pattern description
target={target},value=predicted P({target}) value
check1=u1 index,value=predicted P(u1) value
check2=u2 index,value=predicted P(u2) value
</answer>

Example:
<answer>
pattern=Litigation advancement pattern is cyclic arguments of 3,1,4
target={target},value=42
check1=5,value=15
check2=10,value=28
</answer>
"""

    tags = ["answer", "query_measure", "query_compare"]

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 18,
                "target": 10,
                "max_queries": 9,
                "pattern_type": "周期重复",
                "sequence": [2, 3, 1] * 6,
                "description": "序列为周期 3 的重复：2,3,1"
            },
            2: {
                "n": 22,
                "target": 12,
                "max_queries": 9,
                "pattern_type": "等差序列",
                "sequence": [i % 10 for i in range(1, 23)],
                "description": "序列为从 1 开始的等差数列，模 10"
            },
            3: {
                "n": 26,
                "target": 15,
                "max_queries": 9,
                "pattern_type": "分段周期",
                "sequence": [3, 1, 4] * 4 + [2, 7] * 7,
                "description": "前 12 项为周期 3(3,1,4)，后 14 项为周期 2(2,7)"
            },
            4: {
                "n": 30,
                "target": 18,
                "max_queries": 9,
                "pattern_type": "等差交替",
                "sequence": [1, 9, 2, 8, 3, 7, 4, 6, 5, 5, 6, 4, 7, 3, 8, 2, 9, 1, 0, 0, 
                           1, 9, 2, 8, 3, 7, 4, 6, 5, 5],
                "description": "奇数位递增，偶数位递减，交替模式"
            },
            5: {
                "n": 35,
                "target": 22,
                "max_queries": 9,
                "pattern_type": "复杂分段",
                "sequence": [0, 1, 1, 2, 3, 5, 8, 3, 1, 4] + 
                           [5, 2, 8, 1, 6] * 3 + 
                           [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
                "description": "前 10 项为斐波那契数列模 10，中间 15 项为周期 5(5,2,8,1,6)，后 10 项递减"
            },
        },
        "en": {
            1: {
                "n": 18,
                "target": 10,
                "max_queries": 9,
                "pattern_type": "periodic repetition",
                "sequence": [2, 3, 1] * 6,
                "description": "Sequence is periodic with period 3: 2,3,1"
            },
            2: {
                "n": 22,
                "target": 12,
                "max_queries": 9,
                "pattern_type": "arithmetic sequence",
                "sequence": [i % 10 for i in range(1, 23)],
                "description": "Sequence is arithmetic starting from 1, modulo 10"
            },
            3: {
                "n": 26,
                "target": 15,
                "max_queries": 9,
                "pattern_type": "segmented periods",
                "sequence": [3, 1, 4] * 4 + [2, 7] * 7,
                "description": "First 12 terms are period 3(3,1,4), last 14 terms are period 2(2,7)"
            },
            4: {
                "n": 30,
                "target": 18,
                "max_queries": 9,
                "pattern_type": "alternating arithmetic",
                "sequence": [1, 9, 2, 8, 3, 7, 4, 6, 5, 5, 6, 4, 7, 3, 8, 2, 9, 1, 0, 0, 
                           1, 9, 2, 8, 3, 7, 4, 6, 5, 5],
                "description": "Odd positions increasing, even positions decreasing, alternating pattern"
            },
            5: {
                "n": 35,
                "target": 22,
                "max_queries": 9,
                "pattern_type": "complex segmentation",
                "sequence": [0, 1, 1, 2, 3, 5, 8, 3, 1, 4] + 
                           [5, 2, 8, 1, 6] * 3 + 
                           [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
                "description": "First 10 terms Fibonacci mod 10, middle 15 terms period 5(5,2,8,1,6), last 10 terms decreasing"
            },
        },
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = int(self.config.difficulty)

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        
        self._game_info["n"] = cfg["n"]
        self._game_info["target"] = cfg["target"]
        self._game_info["max_queries"] = cfg["max_queries"]
        
        self.sequence = list(cfg["sequence"])
        self.target_index = cfg["target"]
        self.max_queries = cfg["max_queries"]
        self.true_description = cfg["description"]
        
        self.prefix_sums = [0]
        cumsum = 0
        for val in self.sequence:
            cumsum += val
            self.prefix_sums.append(cumsum)
        
        self.query_count = 0
        self.measured_indices = set()

    def evaluate(self, parsed_info):
        try:
            raw_ans = parsed_info["answer"]
            
            ans_dict = {}
            
            pattern_match = re.search(r'pattern\s*=\s*(.+?)(?=target=|\Z)', raw_ans, re.DOTALL | re.IGNORECASE)
            if pattern_match:
                ans_dict["pattern"] = pattern_match.group(1).strip()
            
            target_match = re.search(r'target\s*=\s*(\d+)\s*,\s*value\s*=\s*(\d+)', raw_ans, re.IGNORECASE)
            if target_match:
                ans_dict["target_idx"] = int(target_match.group(1))
                ans_dict["target_value"] = int(target_match.group(2))
            
            check1_match = re.search(r'check1\s*=\s*(\d+)\s*,\s*value\s*=\s*(\d+)', raw_ans, re.IGNORECASE)
            if check1_match:
                ans_dict["check1_idx"] = int(check1_match.group(1))
                ans_dict["check1_value"] = int(check1_match.group(2))
            
            check2_match = re.search(r'check2\s*=\s*(\d+)\s*,\s*value\s*=\s*(\d+)', raw_ans, re.IGNORECASE)
            if check2_match:
                ans_dict["check2_idx"] = int(check2_match.group(1))
                ans_dict["check2_value"] = int(check2_match.group(2))
            
            required_keys = ["target_idx", "target_value", "check1_idx", "check1_value", "check2_idx", "check2_value"]
            if not all(k in ans_dict for k in required_keys):
                return False
            
            if ans_dict["target_idx"] != self.target_index:
                return False
            
            if ans_dict["check1_idx"] == self.target_index or ans_dict["check2_idx"] == self.target_index:
                return False
            
            n = self._game_info["n"]
            for idx_key in ["target_idx", "check1_idx", "check2_idx"]:
                if not (1 <= ans_dict[idx_key] <= n):
                    return False
            
            checks = [
                (ans_dict["target_idx"], ans_dict["target_value"]),
                (ans_dict["check1_idx"], ans_dict["check1_value"]),
                (ans_dict["check2_idx"], ans_dict["check2_value"]),
            ]
            
            for idx, predicted_value in checks:
                if self.prefix_sums[idx] != predicted_value:
                    return False
            
            return True
            
        except Exception as e:
            return False

    def _cf_core_produce(self, parsed_info):
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
            gt_res, eq_res, lt_res = "大于", "等于", "小于"
        else:
            yes_res, no_res = "Yes", "No"
            gt_res, eq_res, lt_res = "Greater than", "Equal to", "Less than"

        if "query_measure" in parsed_info:
            if self.query_count >= self.max_queries:
                if self.config.language == "zh":
                    return f"错误：已达到最大测量次数 {self.max_queries}。请提交答案。"
                else:
                    return f"Error: Maximum measurement limit of {self.max_queries} reached. Please submit your answer."
            
            try:
                idx = int(parsed_info["query_measure"].strip())
                
                if idx < 1 or idx > self._game_info["n"]:
                    if self.config.language == "zh":
                        return f"错误：索引超出范围（1 到 {self._game_info['n']}）。"
                    else:
                        return f"Error: Index out of range (1 to {self._game_info['n']})."
                
                if idx == self.target_index:
                    if self.config.language == "zh":
                        return f"错误：不能查询目标索引 {self.target_index}。"
                    else:
                        return f"Error: Cannot query target index {self.target_index}."
                
                self.query_count += 1
                self.measured_indices.add(idx)
                
                result = self.prefix_sums[idx]
                if self.config.language == "zh":
                    return f"P({idx}) = {result}（已使用 {self.query_count}/{self.max_queries} 次测量）"
                else:
                    return f"P({idx}) = {result} (Used {self.query_count}/{self.max_queries} measurements)"
                
            except ValueError:
                if self.config.language == "zh":
                    return "错误：索引格式无效，请输入整数。"
                else:
                    return "Error: Invalid index format, please provide an integer."

        elif "query_compare" in parsed_info:
            try:
                raw = parsed_info["query_compare"]
                parts = [x.strip() for x in raw.split(",")]
                if len(parts) != 2:
                    raise ValueError
                
                k1, k2 = int(parts[0]), int(parts[1])
                
                if k1 < 1 or k1 > self._game_info["n"] or k2 < 1 or k2 > self._game_info["n"]:
                    if self.config.language == "zh":
                        return f"错误：索引超出范围（1 到 {self._game_info['n']}）。"
                    else:
                        return f"Error: Index out of range (1 to {self._game_info['n']})."
                
                if k1 == self.target_index or k2 == self.target_index:
                    if self.config.language == "zh":
                        return f"错误：不能比较涉及目标索引 {self.target_index} 的前缀和。"
                    else:
                        return f"Error: Cannot compare prefix sums involving target index {self.target_index}."
                
                p1 = self.prefix_sums[k1]
                p2 = self.prefix_sums[k2]
                
                if p1 > p2:
                    relation = gt_res
                elif p1 == p2:
                    relation = eq_res
                else:
                    relation = lt_res
                
                if self.config.language == "zh":
                    return f"P({k1}) {relation} P({k2})"
                else:
                    return f"P({k1}) {relation} P({k2})"
                
            except ValueError:
                if self.config.language == "zh":
                    return "错误：比较请求格式无效，请使用 'k1,k2' 格式。"
                else:
                    return "Error: Invalid comparison format, please use 'k1,k2' format."

        else:
            raise ValueError("No valid query tag found.")

    def get_all_possible_queries(self) -> list[dict]:
        queries = []
        n = self._game_info["n"]
        target = self.target_index
        max_q = self.max_queries
        
        if self.config.language == "zh":
            gt_txt, eq_txt, lt_txt = "大于", "等于", "小于"
            measure_tpl = "P({k}) = {val}（已使用 {count}/{max_q} 次测量）"
            compare_tpl = "P({k1}) {rel} P({k2})"
        else:
            gt_txt, eq_txt, lt_txt = "Greater than", "Equal to", "Less than"
            measure_tpl = "P({k}) = {val} (Used {count}/{max_q} measurements)"
            compare_tpl = "P({k1}) {rel} P({k2})"

        measure_count = 0
        for k in range(1, n + 1):
            if k == target:
                continue
            if measure_count >= max_q:
                break
            
            measure_count += 1
            val = self.prefix_sums[k]
            ans = measure_tpl.format(k=k, val=val, count=measure_count, max_q=max_q)
            
            queries.append({
                "query": f"<query_measure>{k}</query_measure>",
                "answer": ans
            })

        for k1 in range(1, n):
            k2 = k1 + 1
            if k1 == target or k2 == target:
                continue
            
            p1 = self.prefix_sums[k1]
            p2 = self.prefix_sums[k2]
            
            if p1 > p2:
                rel = gt_txt
            elif p1 == p2:
                rel = eq_txt
            else:
                rel = lt_txt
            
            ans = compare_tpl.format(k1=k1, k2=k2, rel=rel)
            
            queries.append({
                "query": f"<query_compare>{k1},{k2}</query_compare>",
                "answer": ans
            })
                
        return queries

    def _cf_make_wrong(self, correct):
        import re as _re
        
        measure_match = _re.search(r'P\(\d+\)\s*=\s*(\d+)', correct)
        if measure_match:
            val = int(measure_match.group(1))
            wrong_val = val + 3
            return correct.replace(measure_match.group(1), str(wrong_val), 1)

        replacements_zh = {"大于": "小于", "小于": "大于", "等于": "大于"}
        for orig, repl in replacements_zh.items():
            if orig in correct:
                return correct.replace(orig, repl, 1)
        
        replacements_en = {
            "Greater than": "Less than",
            "Less than": "Greater than",
            "Equal to": "Greater than",
        }
        for orig, repl in replacements_en.items():
            if orig in correct:
                return correct.replace(orig, repl, 1)

        return correct + " [WRONG]"