from .base import Game
import re

class PeriodicSequenceGame(Game):

    game_rule_zh = """\
我们来玩一个"周期序列推理"游戏，规则如下：

游戏设定了一个长度为 {n} 的二值序列 S[1..{n}]，每个元素的值为 0 或 1。这个序列由一个隐藏的周期结构生成：存在一个未知的周期 P（P 大于等于 1）和一个未知的二值片段 M（长度为 P），使得序列中每个位置 i 的值等于 M 中对应周期位置的值。

简单来说，序列是由一个模式不断重复而成的（最后一个周期可能不完整）。你的目标是找出所有值为 1 的位置。

你可以进行以下三种类型的查询来获取信息（请尽可能少地使用查询次数）：

1. **单点查询**：询问某个位置 i 的值是 0 还是 1。
2. **区段计数查询**：询问某个区间 [l, r] 内有多少个 1。
3. **等差抽样计数查询**：询问从起点 s 开始，每隔步长 k 取一个位置（即 s, s+k, s+2k, ...），在这些位置中有多少个 1。

当你收集到足够信息后，请提交最终答案。若答案错误或格式不符，游戏失败。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 单点查询（例如查询位置 5）：
<query_point>5</query_point>

- 区段计数查询（例如查询区间 [3, 7]）：
<query_range>3,7</query_range>

- 等差抽样计数查询（例如起点 2，步长 3）：
<query_arithmetic>2,3</query_arithmetic>

提交最终答案时，列出所有值为 1 的位置（用逗号隔开，按升序排列）：

<answer>1,3,5,7</answer>

如果没有任何位置的值为 1，请提交：

<answer></answer>
"""

    game_rule_en = """\
Let's play a "Periodic Sequence Deduction" game. Here are the rules:

The game has set up a binary sequence S[1..{n}] of length {n}, where each element is either 0 or 1. This sequence is generated by a hidden periodic structure: there exists an unknown period P (P greater than or equal to 1) and an unknown binary segment M (of length P), such that the value at each position i in the sequence equals the corresponding value in M based on the periodic position.

In simple terms, the sequence is formed by repeating a pattern (the last period may be incomplete). Your goal is to find all positions with value 1.

You can perform the following three types of queries to gather information (try to use as few queries as possible):

1. **Point Query**: Ask for the value (0 or 1) at a specific position i.
2. **Range Count Query**: Ask how many 1s are in the interval [l, r].
3. **Arithmetic Sampling Count Query**: Ask how many 1s are at positions starting from s with step k (i.e., s, s+k, s+2k, ...).

When you have gathered enough information, submit your final answer. If the answer is wrong or the format is invalid, the game fails.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying position 5):
<query_point>5</query_point>

- Range Count Query (e.g., querying interval [3, 7]):
<query_range>3,7</query_range>

- Arithmetic Sampling Count Query (e.g., start 2, step 3):
<query_arithmetic>2,3</query_arithmetic>

When submitting the final answer, list all positions with value 1 (comma-separated, in ascending order):

<answer>1,3,5,7</answer>

If there are no positions with value 1, submit:

<answer></answer>
"""

    contextualized_rule_zh_1 = """\
我们来进行“公交调度周期推演”分析。

系统记录了一个长度为 {n} 的调度时间槽序列 S[1..{n}]，每个时间槽的状态为 0 或 1，其中 1 代表发车，0 代表未发车。该线路受限于一个隐藏的排班周期：存在一个未知的周期 P（P 大于等于 1）和一个未知的发车片段 M（长度为 P），使得整个时间槽序列由 M 不断循环重复构成（最后一个周期可能不完整）。你的目标是找出所有发车（值为 1）的时间槽编号。

你可以进行以下三种类型的查询来获取信息（请尽可能少地使用查询次数）：

1. **单点查询**：询问某个时间槽 i 是否发车（0 或 1）。
2. **区段计数查询**：询问时间槽区间 [l, r] 内总共发了多少班车。
3. **等差抽样计数查询**：询问从起点时间槽 s 开始，每隔步长 k 取一个时间槽（即 s, s+k, s+2k, ...），在这些时间槽内总共有多少次发车。

当你收集到足够信息后，请提交最终答案。若答案错误或格式不符，排班推演失败。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 单点查询（例如查询时间槽 5）：
<query_point>5</query_point>

- 区段计数查询（例如查询时间槽区间 [3, 7]）：
<query_range>3,7</query_range>

- 等差抽样计数查询（例如起点 2，步长 3）：
<query_arithmetic>2,3</query_arithmetic>

提交最终答案时，列出所有发车（值为 1）的时间槽（用逗号隔开，按升序排列）：

<answer>1,3,5,7</answer>

如果没有任何时间槽发车，请提交：

<answer></answer>
"""

    contextualized_rule_en_1 = """\
[Transportation Scenario]
Let's perform a "Bus Dispatch Schedule Deduction" analysis.

The system has recorded a dispatch time slot sequence S[1..{n}] of length {n}, where each slot's status is 0 or 1 (1 means a bus is dispatched, 0 means no bus). This route is governed by a hidden scheduling cycle: there exists an unknown period P (P >= 1) and an unknown dispatch pattern M (of length P), such that the entire sequence is formed by repeatedly looping M (the last period may be incomplete). Your goal is to find all time slot numbers where a bus is dispatched (value 1).

You can perform the following three types of queries to gather information (try to use as few queries as possible):

1. **Point Query**: Ask whether a bus is dispatched at a specific time slot i (0 or 1).
2. **Range Count Query**: Ask how many buses were dispatched in the time slot interval [l, r].
3. **Arithmetic Sampling Count Query**: Ask how many buses were dispatched at time slots starting from s with step k (i.e., s, s+k, s+2k, ...).

When you have gathered enough information, submit your final answer. If the answer is wrong or the format is invalid, the deduction fails.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying time slot 5):
<query_point>5</query_point>

- Range Count Query (e.g., querying interval [3, 7]):
<query_range>3,7</query_range>

- Arithmetic Sampling Count Query (e.g., start 2, step 3):
<query_arithmetic>2,3</query_arithmetic>

When submitting the final answer, list all time slots with a bus dispatched (comma-separated, in ascending order):

<answer>1,3,5,7</answer>

If no buses were dispatched at all, submit:

<answer></answer>
"""

    contextualized_rule_zh_2 = """\
我们来进行“心室节律异常监测”。

设备记录了一段长度为 {n} 秒的心电采样序列 S[1..{n}]，每一秒的状态为 0 或 1。其中 1 代表检测到异常搏动，0 代表节律正常。受特定生理机制影响，该异常波动由一个隐藏的周期结构生成：存在一个未知的生理周期 P（P 大于等于 1）和一个未知的波动片段 M（长度为 P），使得整个序列由 M 不断循环重复而成（最后一个周期可能不完整）。你的目标是找出所有出现异常搏动（值为 1）的秒数位置。

你可以进行以下三种类型的查询来获取信息（请尽可能少地使用查询次数）：

1. **单点查询**：询问第 i 秒的心电状态是 0 还是 1。
2. **区段计数查询**：询问在时间区间 [l, r] 秒内，总共出现了多少次异常搏动。
3. **等差抽样计数查询**：询问从起点第 s 秒开始，每隔步长 k 秒取样一次（即 s, s+k, s+2k, ...），在这些采样点中有多少次异常搏动。

当你收集到足够信息后，请提交最终出具的诊断结果。若答案错误或格式不符，诊断判定失败。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 单点查询（例如查询第 5 秒）：
<query_point>5</query_point>

- 区段计数查询（例如查询区间 [3, 7] 秒）：
<query_range>3,7</query_range>

- 等差抽样计数查询（例如起点第 2 秒，步长 3 秒）：
<query_arithmetic>2,3</query_arithmetic>

提交最终诊断结果时，列出所有出现异常搏动（值为 1）的秒数位置（用逗号隔开，按升序排列）：

<answer>1,3,5,7</answer>

如果没有任何异常搏动，请提交：

<answer></answer>
"""

    contextualized_rule_en_2 = """\
[Healthcare Scenario]
Let's perform a "Ventricular Rhythm Anomaly Monitoring".

The device has recorded an ECG sampling sequence S[1..{n}] of length {n} seconds, where each second's status is 0 or 1. A value of 1 indicates an abnormal heartbeat detected, while 0 indicates a normal rhythm. Due to specific physiological mechanisms, this abnormal fluctuation is generated by a hidden periodic structure: there exists an unknown physiological period P (P >= 1) and an unknown fluctuation segment M (of length P), such that the entire sequence is formed by repeatedly looping M (the last period may be incomplete). Your goal is to find all the second markers with abnormal heartbeats (value 1).

You can perform the following three types of queries to gather information (try to use as few queries as possible):

1. **Point Query**: Ask whether the ECG status at the i-th second is 0 or 1.
2. **Range Count Query**: Ask how many abnormal heartbeats occurred in the time interval [l, r].
3. **Arithmetic Sampling Count Query**: Ask how many abnormal heartbeats are recorded starting from the s-th second with a step of k seconds (i.e., s, s+k, s+2k, ...).

When you have gathered enough information, submit your final diagnostic report. If the answer is wrong or the format is invalid, the diagnosis fails.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying the 5th second):
<query_point>5</query_point>

- Range Count Query (e.g., querying interval [3, 7]):
<query_range>3,7</query_range>

- Arithmetic Sampling Count Query (e.g., start 2, step 3):
<query_arithmetic>2,3</query_arithmetic>

When submitting the final answer, list all second markers with abnormal heartbeats (comma-separated, in ascending order):

<answer>1,3,5,7</answer>

If there are no abnormal heartbeats at all, submit:

<answer></answer>
"""

    contextualized_rule_zh_3 = """\
我们来进行“课堂专注度切片分析”。

系统生成了一份长度为 {n} 的学习行为切片序列 S[1..{n}]，每个切片的值为 0 或 1。其中 1 代表学生处于高频互动（专注）状态，0 代表低频互动（游离）。由于学生的认知节律，该状态序列具有隐藏的周期性：存在一个未知的认知起伏周期 P（P 大于等于 1）和一个未知的行为片段 M（长度为 P），使得状态序列由 M 循环重复而成（最后一个周期可能不完整）。你的目标是找出所有处于高频互动（值为 1）的切片编号。

你可以进行以下三种类型的查询来获取信息（请尽可能少地使用查询次数）：

1. **单点查询**：询问某个切片 i 的状态是 0 还是 1。
2. **区段计数查询**：询问某个切片区间 [l, r] 内包含多少个高频互动的切片。
3. **等差抽样计数查询**：询问从起点切片 s 开始，每隔步长 k 提取一个切片（即 s, s+k, s+2k, ...），在这些切片中有多少个高频互动。

当你收集到足够信息后，请提交最终分析报告。若答案错误或格式不符，分析评定失败。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 单点查询（例如查询切片 5）：
<query_point>5</query_point>

- 区段计数查询（例如查询切片区间 [3, 7]）：
<query_range>3,7</query_range>

- 等差抽样计数查询（例如起点 2，步长 3）：
<query_arithmetic>2,3</query_arithmetic>

提交最终分析报告时，列出所有高频互动（值为 1）的切片编号（用逗号隔开，按升序排列）：

<answer>1,3,5,7</answer>

如果没有任何切片处于高频互动状态，请提交：

<answer></answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Let's perform a "Classroom Attention Slice Analysis".

The system has generated a learning behavior slice sequence S[1..{n}] of length {n}, where each slice's value is 0 or 1. A value of 1 represents a high-frequency interaction (engaged) state, while 0 represents a low-frequency interaction (distracted) state. Due to the students' cognitive rhythms, this state sequence has a hidden periodicity: there exists an unknown cognitive fluctuation period P (P >= 1) and an unknown behavioral segment M (of length P), such that the state sequence is formed by repeatedly looping M (the last period may be incomplete). Your goal is to find all the slice numbers that are in a high-frequency interaction state (value 1).

You can perform the following three types of queries to gather information (try to use as few queries as possible):

1. **Point Query**: Ask whether the state of a specific slice i is 0 or 1.
2. **Range Count Query**: Ask how many engaged slices are in the interval [l, r].
3. **Arithmetic Sampling Count Query**: Ask how many engaged slices are recorded starting from slice s with a step of k slices (i.e., s, s+k, s+2k, ...).

When you have gathered enough information, submit your final analysis report. If the answer is wrong or the format is invalid, the evaluation fails.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying slice 5):
<query_point>5</query_point>

- Range Count Query (e.g., querying interval [3, 7]):
<query_range>3,7</query_range>

- Arithmetic Sampling Count Query (e.g., start 2, step 3):
<query_arithmetic>2,3</query_arithmetic>

When submitting the final answer, list all engaged slice numbers (comma-separated, in ascending order):

<answer>1,3,5,7</answer>

If there are no engaged slices at all, submit:

<answer></answer>
"""

    contextualized_rule_zh_4 = """\
我们来进行“自动产线缺陷定位”排查。

质检系统输出了一条长度为 {n} 的生产流水线零件序列 S[1..{n}]，每个零件的质检值为 0 或 1。其中 1 代表残次品，0 代表良品。由于设备主轴磨损，缺陷的出现遵循一个隐藏的机械周期：存在一个未知的故障周期 P（P 大于等于 1）和特定误差片段 M（长度为 P），使得整条生产线的不良品分布由 M 循环重复产生（最后一个周期可能不完整）。你的目标是找出所有残次品（值为 1）的零件编号。

你可以进行以下三种类型的查询来获取信息（请尽可能少地使用查询次数）：

1. **单点查询**：询问流水线上第 i 个零件是 0 还是 1。
2. **区段计数查询**：询问零件批次区间 [l, r] 内总共有多少个残次品。
3. **等差抽样计数查询**：询问从第 s 个零件开始，每隔步长 k 抽检一次（即 s, s+k, s+2k, ...），在这些抽检零件中有多少个残次品。

当你收集到足够信息后，请提交最终的排查结果。若答案错误或格式不符，排查任务失败。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 单点查询（例如查询第 5 个零件）：
<query_point>5</query_point>

- 区段计数查询（例如查询区间 [3, 7]）：
<query_range>3,7</query_range>

- 等差抽样计数查询（例如起点 2，步长 3）：
<query_arithmetic>2,3</query_arithmetic>

提交排查结果时，列出所有残次品（值为 1）的零件编号（用逗号隔开，按升序排列）：

<answer>1,3,5,7</answer>

如果没有任何残次品，请提交：

<answer></answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
Let's perform an "Automated Production Line Defect Localization".

The quality inspection system has output a sequence S[1..{n}] of length {n} representing continuous parts on an assembly line, where each part's quality value is 0 or 1. A value of 1 represents a defective part, while 0 represents a passing part. Due to main spindle wear on the equipment, the occurrence of defects follows a hidden mechanical cycle: there exists an unknown fault period P (P >= 1) and an unknown error segment M (of length P), such that the distribution of defective parts on the line is formed by repeatedly looping M (the last period may be incomplete). Your goal is to find all the part sequence numbers that are defective (value 1).

You can perform the following three types of queries to gather information (try to use as few queries as possible):

1. **Point Query**: Ask whether the i-th part on the line is 0 or 1.
2. **Range Count Query**: Ask how many defective parts are in the batch interval [l, r].
3. **Arithmetic Sampling Count Query**: Ask how many defective parts are found starting from the s-th part, sampling every k parts (i.e., s, s+k, s+2k, ...).

When you have gathered enough information, submit your final inspection results. If the answer is wrong or the format is invalid, the troubleshooting fails.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying the 5th part):
<query_point>5</query_point>

- Range Count Query (e.g., querying interval [3, 7]):
<query_range>3,7</query_range>

- Arithmetic Sampling Count Query (e.g., start 2, step 3):
<query_arithmetic>2,3</query_arithmetic>

When submitting the final answer, list all defective part sequence numbers (comma-separated, in ascending order):

<answer>1,3,5,7</answer>

If there are no defective parts at all, submit:

<answer></answer>
"""

    contextualized_rule_zh_5 = """\
我们来进行“监控录像篡改取证”。

安防系统提取了一段长度为 {n} 的连续监控视频帧序列 S[1..{n}]，每帧的鉴定值为 0 或 1。其中 1 代表该帧被恶意软件覆盖篡改，0 代表原始安全帧。经过初步分析，作弊软件依靠自动脚本按隐藏周期运作：存在一个未知的循环周期 P（P 大于等于 1）和一个未知的篡改片段 M（长度为 P），使得篡改痕迹由 M 循环覆盖生成（最后一个周期可能不完整）。你的目标是定位出所有被篡改（值为 1）的视频帧序号。

你可以进行以下三种类型的查询来获取证据信息（请尽可能少地使用查询次数）：

1. **单点查询**：询问第 i 帧的安全状态是 0 还是 1。
2. **区段计数查询**：询问在视频帧区间 [l, r] 内，总共包含多少个被篡改的帧。
3. **等差抽样计数查询**：询问从起点帧 s 开始，每隔步长 k 抽取一帧（即 s, s+k, s+2k, ...），在这些采样帧中有多少帧被篡改。

当你收集到足够信息后，请提交最终的取证报告。若答案错误或格式不符，取证线索将失效。

每次查询只能包含一个标签。请使用以下 XML 格式：

- 单点查询（例如查询第 5 帧）：
<query_point>5</query_point>

- 区段计数查询（例如查询区间 [3, 7]）：
<query_range>3,7</query_range>

- 等差抽样计数查询（例如起点 2，步长 3）：
<query_arithmetic>2,3</query_arithmetic>

提交取证报告时，列出所有被篡改（值为 1）的视频帧序号（用逗号隔开，按升序排列）：

<answer>1,3,5,7</answer>

如果没有任何被篡改的帧，请提交：

<answer></answer>
"""

    contextualized_rule_en_5 = """\
[Law Scenario]
Let's perform a "Surveillance Video Tampering Forensics".

The security system has extracted a sequence S[1..{n}] of length {n} consisting of continuous surveillance video frames, where the authentication value of each frame is 0 or 1. A value of 1 represents a frame maliciously overwritten/tampered with, while 0 represents an original secure frame. Preliminary analysis shows that the cheating software operates on a hidden cycle using an automated script: there exists an unknown looping period P (P >= 1) and an unknown tampered segment M (of length P), such that the tampering traces are generated by repeatedly looping M (the last period may be incomplete). Your goal is to pinpoint all the sequence numbers of the tampered frames (value 1).

You can perform the following three types of queries to gather evidence (try to use as few queries as possible):

1. **Point Query**: Ask whether the security status of the i-th frame is 0 or 1.
2. **Range Count Query**: Ask how many tampered frames are in the interval [l, r].
3. **Arithmetic Sampling Count Query**: Ask how many tampered frames are found starting from the s-th frame, sampling every k frames (i.e., s, s+k, s+2k, ...).

When you have gathered enough information, submit your final forensic report. If the answer is wrong or the format is invalid, the forensic lead is lost.

Each query must contain only one tag. Use the following XML format:

- Point Query (e.g., querying the 5th frame):
<query_point>5</query_point>

- Range Count Query (e.g., querying interval [3, 7]):
<query_range>3,7</query_range>

- Arithmetic Sampling Count Query (e.g., start 2, step 3):
<query_arithmetic>2,3</query_arithmetic>

When submitting the final answer, list all tampered frame numbers (comma-separated, in ascending order):

<answer>1,3,5,7</answer>

If there are no tampered frames at all, submit:

<answer></answer>
"""

    tags = ["answer", "query_point", "query_range", "query_arithmetic"]
    
    reasoning_type = "归纳推理"
    data_structure = "序列"
    enable_counterfactual = False

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 10,
                "period": 2,
                "pattern": "10",
            },
            2: {
                "n": 15,
                "period": 3,
                "pattern": "101",
            },
            3: {
                "n": 20,
                "period": 4,
                "pattern": "1100",
            },
            4: {
                "n": 24,
                "period": 6,
                "pattern": "110010",
            },
            5: {
                "n": 30,
                "period": 7,
                "pattern": "1010110",
            },
        },
        "en": {
            1: {
                "n": 10,
                "period": 2,
                "pattern": "10",
            },
            2: {
                "n": 15,
                "period": 3,
                "pattern": "101",
            },
            3: {
                "n": 20,
                "period": 4,
                "pattern": "1100",
            },
            4: {
                "n": 24,
                "period": 6,
                "pattern": "110010",
            },
            5: {
                "n": 30,
                "period": 7,
                "pattern": "1010110",
            },
        },
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = self.config.difficulty

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        self._game_info["n"] = cfg["n"]
        
        self.n = cfg["n"]
        self.period = cfg["period"]
        self.pattern = [int(x) for x in cfg["pattern"]]
        
        self.sequence = {}
        for i in range(1, self.n + 1):
            pattern_idx = (i - 1) % self.period
            self.sequence[i] = self.pattern[pattern_idx]
        
        self.ones_positions = set()
        for i in range(1, self.n + 1):
            if self.sequence[i] == 1:
                self.ones_positions.add(i)

    def evaluate(self, parsed_info):
        raw_ans = parsed_info["answer"].strip()
        
        if not raw_ans:
            model_positions = set()
        else:
            try:
                model_positions = set()
                for x in raw_ans.split(","):
                    pos = int(x.strip())
                    if pos < 1 or pos > self.n:
                        return False
                    model_positions.add(pos)
            except:
                return False
        
        return model_positions == self.ones_positions

    def _cf_core_produce(self, parsed_info):
        if "query_point" in parsed_info:
            try:
                pos = int(parsed_info["query_point"].strip())
                if pos < 1 or pos > self.n:
                    return "错误：位置超出范围。" if self.config.language == "zh" else "Error: Position out of range."
                return str(self.sequence[pos])
            except:
                return "错误：无效的位置格式。" if self.config.language == "zh" else "Error: Invalid position format."
        
        elif "query_range" in parsed_info:
            try:
                raw = parsed_info["query_range"].strip()
                l, r = [int(x.strip()) for x in raw.split(",")]
                if l < 1 or r > self.n or l > r:
                    return "错误：区间无效。" if self.config.language == "zh" else "Error: Invalid range."
                
                count = sum(self.sequence[i] for i in range(l, r + 1))
                return str(count)
            except:
                return "错误：无效的区间格式。" if self.config.language == "zh" else "Error: Invalid range format."
        
        elif "query_arithmetic" in parsed_info:
            try:
                raw = parsed_info["query_arithmetic"].strip()
                s, k = [int(x.strip()) for x in raw.split(",")]
                if s < 1 or s > self.n or k < 2:
                    return "错误：起点或步长无效。" if self.config.language == "zh" else "Error: Invalid start or step."
                
                count = 0
                pos = s
                while pos <= self.n:
                    count += self.sequence[pos]
                    pos += k
                return str(count)
            except:
                return "错误：无效的抽样格式。" if self.config.language == "zh" else "Error: Invalid sampling format."
        
        else:
            raise ValueError("No valid query tag found.")

    def _cf_make_wrong(self, correct: str) -> str:
        if correct.isdigit():
            return str(int(correct) + 1)
        
        if self.config.language == "zh":
            if "是" in correct:
                return correct.replace("是", "否")
            elif "否" in correct:
                return correct.replace("否", "是")
        elif self.config.language == "en":
            if "Yes" in correct:
                return correct.replace("Yes", "No")
            elif "No" in correct:
                return correct.replace("No", "Yes")
            elif "yes" in correct:
                return correct.replace("yes", "no")
            elif "no" in correct:
                return correct.replace("no", "yes")
        
        return correct + "_WRONG"

    def get_all_possible_queries(self) -> list[dict]:
        results = []
        
        for i in range(1, self.n + 1):
            query_tag = f"<query_point>{i}</query_point>"
            ans = str(self.sequence[i])
            results.append({"query": query_tag, "answer": ans})
        
        for l in range(1, self.n + 1):
            for r in range(l, self.n + 1):
                query_tag = f"<query_range>{l},{r}</query_range>"
                count = sum(self.sequence[x] for x in range(l, r + 1))
                results.append({"query": query_tag, "answer": str(count)})
        
        for s in range(1, self.n + 1):
            for k in range(2, self.n + 1):
                query_tag = f"<query_arithmetic>{s},{k}</query_arithmetic>"
                
                count = 0
                pos = s
                while pos <= self.n:
                    count += self.sequence[pos]
                    pos += k
                
                results.append({"query": query_tag, "answer": str(count)})
        
        return results