from .base import Game
import re

class PeriodicSequenceInferenceGame(Game):

    game_rule_zh = """\
我们来玩一个"周期序列推断"游戏，规则如下：

游戏设定了一个长度为 {n} 的有序整数序列 S，其中每个元素都是 0 到 9 之间的整数。这个序列由一个隐藏的"基段"B 重复拼接而成：基段 B 的长度为 L（称为"最小周期"），B 按顺序不断重复，直到拼满 {n} 个位置（最后可能截断）。L 的范围在 2 到 12 之间，且 B 不能再由更短的周期重复得到。

你的目标是：
1. 推断出最小周期 L 和对应的基段 B；
2. 计算出禁测区间 [{forbidden_start}, {forbidden_end}] 在聚合方式"{target_agg}"下的真实值。

你可以进行以下类型的查询，但总查询次数不得超过 {max_queries} 次：

1. **区间求和查询**：查询区间 [a, b] 中所有元素的和。
   - 约束：区间长度（b-a+1）必须大于等于 {min_interval_len}，且 1 小于等于 a 小于等于 b 小于等于 {n}。
   - 不得直接查询禁测区间 [{forbidden_start}, {forbidden_end}]（但可以查询与之重叠的其他区间）。

2. **区间求最大值查询**：查询区间 [a, b] 中的最大元素值。
   - 约束同上。

3. **区间求最小值查询**：查询区间 [a, b] 中的最小元素值。
   - 约束同上。

4. **剩余次数查询**：询问还剩多少次查询机会。

5. **规则复述查询**：重新获取游戏的基本设定参数。

若查询请求不符合约束（如索引越界、区间长度不足、直接查询禁测区间、或查询次数已用尽），系统会返回错误提示，且不消耗查询次数。

每次只能提交一个查询或一个答案。请使用以下 XML 格式：

- 区间求和查询（例如查询区间 [1, 5]）：
<query_sum>1,5</query_sum>

- 区间求最大值查询（例如查询区间 [2, 8]）：
<query_max>2,8</query_max>

- 区间求最小值查询（例如查询区间 [3, 10]）：
<query_min>3,10</query_min>

- 剩余次数查询：
<query_remaining></query_remaining>

- 规则复述查询：
<query_rules></query_rules>

- 提交最终答案（必须同时包含周期、基段和禁测区间的聚合值）：
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- 基段 B 允许循环位移等价（例如 [1,2,3] 和 [2,3,1] 和 [3,1,2] 视为等价）。
- 你需要在查询次数限制内完成推断并提交答案。
- 答案的三个部分（L、B、forbidden_value）必须同时正确才算成功。
"""

    game_rule_en = """\
Let's play a "Periodic Sequence Inference" game. Here are the rules:

A sequence S of length {n} has been set up, where each element is an integer between 0 and 9. This sequence is generated by repeatedly concatenating a hidden "base segment" B: the length of B is L (called the "minimum period"), and B is repeated in order until {n} positions are filled (the last occurrence may be truncated). L ranges from 2 to 12, and B cannot be obtained by repeating a shorter pattern.

Your goals are:
1. Infer the minimum period L and the corresponding base segment B;
2. Calculate the true value of the forbidden interval [{forbidden_start}, {forbidden_end}] under the aggregation method "{target_agg}".

You can perform the following types of queries, but the total number of queries cannot exceed {max_queries}:

1. **Interval Sum Query**: Query the sum of all elements in interval [a, b].
   - Constraints: interval length (b-a+1) must be greater than or equal to {min_interval_len}, and 1 less than or equal to a less than or equal to b less than or equal to {n}.
   - You cannot directly query the forbidden interval [{forbidden_start}, {forbidden_end}] (but you can query other intervals that overlap with it).

2. **Interval Max Query**: Query the maximum element value in interval [a, b].
   - Same constraints as above.

3. **Interval Min Query**: Query the minimum element value in interval [a, b].
   - Same constraints as above.

4. **Remaining Queries Query**: Ask how many query opportunities remain.

5. **Rules Recap Query**: Retrieve the game's basic configuration parameters.

If a query request violates the constraints (such as index out of bounds, insufficient interval length, direct query of forbidden interval, or queries exhausted), the system will return an error message without consuming a query count.

Each time you can only submit one query or one answer. Use the following XML format:

- Interval sum query (e.g., query interval [1, 5]):
<query_sum>1,5</query_sum>

- Interval max query (e.g., query interval [2, 8]):
<query_max>2,8</query_max>

- Interval min query (e.g., query interval [3, 10]):
<query_min>3,10</query_min>

- Remaining queries query:
<query_remaining></query_remaining>

- Rules recap query:
<query_rules></query_rules>

- Submit final answer (must include period, base segment, and aggregation value of forbidden interval):
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- Base segment B allows cyclic shift equivalence (e.g., [1,2,3], [2,3,1], and [3,1,2] are considered equivalent).
- You need to complete the inference and submit the answer within the query limit.
- All three parts of the answer (L, B, forbidden_value) must be correct simultaneously to succeed.
"""

    contextualized_rule_zh_1 = """\
【城市交通流量监控网络】
我们来执行一次"交通流量周期推断"任务，规则如下：

系统记录了一条干道上连续分布的 {n} 个流量传感器的车流量指数序列，每个指数是 0 到 9 之间的整数。受信号灯调控影响，车流指数由一个隐藏的"基础波段" B 周期性拼接而成：B 的长度为 L（称为"最小调度周期"），B 按顺序不断重复，直到涵盖所有 {n} 个传感器位置（末尾可能截断）。L 的范围在 2 到 12 之间，且 B 不能再由更短的周期重复得到。

你的目标是：
1. 推断出最小调度周期 L 和对应的基础波段 B；
2. 由于设备故障，传感器区间 [{forbidden_start}, {forbidden_end}] 处于"监测盲区"无法直接读取，请计算出该盲区在聚合方式"{target_agg}"下的真实总计指标。

你可以进行以下类型的查询，但总查询次数不得超过 {max_queries} 次：

1. **区间求和查询**：查询区间 [a, b] 中所有传感器的车流量总和。
   - 约束：区间跨度（b-a+1）必须大于等于 {min_interval_len}，且 1 小于等于 a 小于等于 b 小于等于 {n}。
   - 不得直接查询监测盲区 [{forbidden_start}, {forbidden_end}]（但可以查询与之重叠的其他区间）。

2. **区间求最大值查询**：查询区间 [a, b] 中的最高车流量指数。
   - 约束同上。

3. **区间求最小值查询**：查询区间 [a, b] 中的最低车流量指数。
   - 约束同上。

4. **剩余次数查询**：询问还剩多少次系统查询权限。

5. **规则复述查询**：重新获取任务的基本设定参数。

若查询请求不符合约束（如索引越界、跨度不足、直接查询盲区、或权限已用尽），系统会返回错误提示，且不消耗查询次数。

每次只能提交一个查询或一个答案。请使用以下 XML 格式：

- 区间求和查询（例如查询区间 [1, 5]）：
<query_sum>1,5</query_sum>

- 区间求最大值查询（例如查询区间 [2, 8]）：
<query_max>2,8</query_max>

- 区间求最小值查询（例如查询区间 [3, 10]）：
<query_min>3,10</query_min>

- 剩余次数查询：
<query_remaining></query_remaining>

- 规则复述查询：
<query_rules></query_rules>

- 提交最终答案（必须同时包含调度周期、基础波段和盲区的聚合值）：
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- 基础波段 B 允许循环位移等价（例如 [1,2,3] 和 [2,3,1] 和 [3,1,2] 视为等价）。
- 你需要在查询次数限制内完成推断并提交答案。
- 答案的三个部分（L、B、forbidden_value）必须同时正确才算成功。
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
Let's execute a "Traffic Flow Periodic Inference" task. Here are the rules:

The system has recorded a sequence of traffic volume indices from {n} continuous flow sensors on a main road, where each index is an integer between 0 and 9. Influenced by traffic light coordination, the volume index is generated by repeatedly concatenating a hidden "base wave" B: the length of B is L (called the "minimum scheduling period"), and B is repeated in order until {n} sensor positions are filled (the last occurrence may be truncated). L ranges from 2 to 12, and B cannot be obtained by repeating a shorter pattern.

Your goals are:
1. Infer the minimum scheduling period L and the corresponding base wave B;
2. Due to equipment failure, the sensor interval [{forbidden_start}, {forbidden_end}] is a "monitoring blind zone" and cannot be read directly. Calculate the true value of this blind zone under the aggregation method "{target_agg}".

You can perform the following types of system queries, but the total number of queries cannot exceed {max_queries}:

1. **Interval Sum Query**: Query the sum of traffic volumes for all sensors in interval [a, b].
   - Constraints: interval span (b-a+1) must be greater than or equal to {min_interval_len}, and 1 less than or equal to a less than or equal to b less than or equal to {n}.
   - You cannot directly query the monitoring blind zone [{forbidden_start}, {forbidden_end}] (but you can query other intervals that overlap with it).

2. **Interval Max Query**: Query the maximum traffic volume index in interval [a, b].
   - Same constraints as above.

3. **Interval Min Query**: Query the minimum traffic volume index in interval [a, b].
   - Same constraints as above.

4. **Remaining Queries Query**: Ask how many system query permissions remain.

5. **Rules Recap Query**: Retrieve the task's basic configuration parameters.

If a query request violates the constraints (such as index out of bounds, insufficient span, direct query of the blind zone, or permissions exhausted), the system will return an error message without consuming a query count.

Each time you can only submit one query or one answer. Use the following XML format:

- Interval sum query (e.g., query interval [1, 5]):
<query_sum>1,5</query_sum>

- Interval max query (e.g., query interval [2, 8]):
<query_max>2,8</query_max>

- Interval min query (e.g., query interval [3, 10]):
<query_min>3,10</query_min>

- Remaining queries query:
<query_remaining></query_remaining>

- Rules recap query:
<query_rules></query_rules>

- Submit final answer (must include scheduling period, base wave, and aggregation value of the blind zone):
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- Base wave B allows cyclic shift equivalence (e.g., [1,2,3], [2,3,1], and [3,1,2] are considered equivalent).
- You need to complete the inference and submit the answer within the query limit.
- All three parts of the answer (L, B, forbidden_value) must be correct simultaneously to succeed.
"""

    contextualized_rule_zh_2 = """\
【连续生命体征监测系统】
我们来执行一次"生理信号波形推断"任务，规则如下：

系统在一段连续的观察期内采集了 {n} 个采样点的心电特征序列，每个特征值是 0 到 9 之间的整数。患者的生理节律导致信号由一个隐藏的"基准波形" B 周期性构成：B 的长度为 L（称为"生理节律周期"），B 按顺序不断重复，直到填满所有 {n} 个采样点位置（末尾可能截断）。L 的范围在 2 到 12 之间，且 B 不能由更短的周期模式重复得到。

你的目标是：
1. 诊断出生理节律周期 L 及对应的基准波形 B；
2. 由于仪器电磁干扰，采样区间 [{forbidden_start}, {forbidden_end}] 变为"数据锁定区"无法直接调阅，请推算该锁定区在聚合方式"{target_agg}"下的真实指标。

你可以进行以下类型的查询，但总查询次数不得超过 {max_queries} 次：

1. **区间求和查询**：查询区间 [a, b] 中所有特征值的总和。
   - 约束：监测跨度（b-a+1）必须大于等于 {min_interval_len}，且 1 小于等于 a 小于等于 b 小于等于 {n}。
   - 不得直接查询数据锁定区 [{forbidden_start}, {forbidden_end}]（但可以查询与之重叠的其他正常区间）。

2. **区间求最大值查询**：查询区间 [a, b] 中的最高特征值（波峰）。
   - 约束同上。

3. **区间求最小值查询**：查询区间 [a, b] 中的最低特征值（波谷）。
   - 约束同上。

4. **剩余次数查询**：询问还剩多少次系统操作权限。

5. **规则复述查询**：重新获取任务的基本设定参数。

若查询请求不符合约束（如越界、观察窗口过小、直接查询锁定区、或诊断次数用尽），系统会返回错误提示，且不消耗查询次数。

每次只能提交一个查询或一个答案。请使用以下 XML 格式：

- 区间求和查询（例如查询区间 [1, 5]）：
<query_sum>1,5</query_sum>

- 区间求最大值查询（例如查询区间 [2, 8]）：
<query_max>2,8</query_max>

- 区间求最小值查询（例如查询区间 [3, 10]）：
<query_min>3,10</query_min>

- 剩余次数查询：
<query_remaining></query_remaining>

- 规则复述查询：
<query_rules></query_rules>

- 提交最终诊断答案（必须同时包含节律周期、基准波形和锁定区的聚合值）：
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- 基准波形 B 允许循环位移等价（例如 [1,2,3] 和 [2,3,1] 和 [3,1,2] 视为生理等效）。
- 你需要在查询次数限制内完成诊断并提交答案。
- 答案的三个部分（L、B、forbidden_value）必须同时正确才算成功。
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
Let's execute a "Physiological Signal Waveform Inference" task. Here are the rules:

The system collected an ECG feature sequence of {n} continuous sampling points over an observation period, where each feature value is an integer between 0 and 9. Physiological rhythms cause the signals to be formed by continuously looping a hidden "baseline waveform" B: the length of B is L (called the "physiological rhythm period"), and B is repeated in order until {n} sampling positions are filled (the last occurrence may be truncated). L ranges from 2 to 12, and B cannot be obtained by repeating a shorter pattern.

Your goals are:
1. Diagnose the physiological rhythm period L and the corresponding baseline waveform B;
2. Due to electromagnetic interference, the sampling interval [{forbidden_start}, {forbidden_end}] has become a "data lockout zone" and cannot be reviewed directly. Calculate the true indicator of this lockout zone under the aggregation method "{target_agg}".

You can perform the following types of queries, but the total number of queries cannot exceed {max_queries}:

1. **Interval Sum Query**: Query the sum of all feature values in interval [a, b].
   - Constraints: observation span (b-a+1) must be greater than or equal to {min_interval_len}, and 1 less than or equal to a less than or equal to b less than or equal to {n}.
   - You cannot directly query the data lockout zone [{forbidden_start}, {forbidden_end}] (but you can query other intervals that overlap with it).

2. **Interval Max Query**: Query the maximum feature value (peak) in interval [a, b].
   - Same constraints as above.

3. **Interval Min Query**: Query the minimum feature value (trough) in interval [a, b].
   - Same constraints as above.

4. **Remaining Queries Query**: Ask how many system operation permissions remain.

5. **Rules Recap Query**: Retrieve the task's basic configuration parameters.

If a query request violates the constraints (such as index out of bounds, observation window too small, direct query of lockout zone, or diagnostic limits exhausted), the system will return an error message without consuming a query count.

Each time you can only submit one query or one answer. Use the following XML format:

- Interval sum query (e.g., query interval [1, 5]):
<query_sum>1,5</query_sum>

- Interval max query (e.g., query interval [2, 8]):
<query_max>2,8</query_max>

- Interval min query (e.g., query interval [3, 10]):
<query_min>3,10</query_min>

- Remaining queries query:
<query_remaining></query_remaining>

- Rules recap query:
<query_rules></query_rules>

- Submit final diagnosis answer (must include rhythm period, baseline waveform, and aggregation value of the lockout zone):
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- Baseline waveform B allows cyclic shift equivalence (e.g., [1,2,3], [2,3,1], and [3,1,2] are considered physiologically equivalent).
- You need to complete the diagnosis and submit the answer within the query limit.
- All three parts of the answer (L, B, forbidden_value) must be correct simultaneously to succeed.
"""

    contextualized_rule_zh_3 = """\
【智能题库生成系统】
我们来执行一次"认知难度循环分析"任务，规则如下：

一套标准化测试卷包含了连续的 {n} 道题，系统记录了各题的认知难度系数，每个系数是 0 到 9 之间的整数。试卷设计遵循一种教育心理学上的认知难度循环模式：由一个隐藏的"基底难度段" B 周期性拼接而成。B 包含 L 道题（称为"循环模块跨度"），B 按题号不断重复，直到涵盖所有 {n} 道题（末尾可能截断）。L 的范围在 2 到 12 之间，且 B 不能再由更短的难度周期重复得到。

你的目标是：
1. 破译循环模块跨度 L 及对应的基底难度段 B；
2. 试卷题号区间 [{forbidden_start}, {forbidden_end}] 属于保密的"加密考核区"无法直接透传，请计算出该题号段在聚合方式"{target_agg}"下的真实指标。

你可以进行以下类型的查询，但总抽取次数不得超过 {max_queries} 次：

1. **区间求和查询**：抽取并统计区间 [a, b] 题目的难度系数总和。
   - 约束：抽题数量（b-a+1）必须大于等于 {min_interval_len}，且 1 小于等于 a 小于等于 b 小于等于 {n}。
   - 不得直接查询加密考核区 [{forbidden_start}, {forbidden_end}]（但可以抽取与之重叠的其他题组）。

2. **区间求最大值查询**：抽取并统计区间 [a, b] 题目中的最高难度。
   - 约束同上。

3. **区间求最小值查询**：抽取并统计区间 [a, b] 题目中的最低难度。
   - 约束同上。

4. **剩余次数查询**：询问还剩多少次试卷抽取权限。

5. **规则复述查询**：重新获取任务的基本设定参数。

若查询请求不符合约束（如题号越界、抽题量不足、直接查询保密区、或抽题权限已用尽），系统会返回错误提示，且不消耗查询次数。

每次只能提交一个查询或一个答案。请使用以下 XML 格式：

- 区间求和查询（例如查询区间 [1, 5]）：
<query_sum>1,5</query_sum>

- 区间求最大值查询（例如查询区间 [2, 8]）：
<query_max>2,8</query_max>

- 区间求最小值查询（例如查询区间 [3, 10]）：
<query_min>3,10</query_min>

- 剩余次数查询：
<query_remaining></query_remaining>

- 规则复述查询：
<query_rules></query_rules>

- 提交最终答案（必须同时包含模块跨度、基底难度段和加密区的聚合值）：
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- 基底难度段 B 允许循环位移等价（例如 [1,2,3] 和 [2,3,1] 和 [3,1,2] 视为等价的认知模型）。
- 你需要在抽题次数限制内完成分析并提交答案。
- 答案的三个部分（L、B、forbidden_value）必须同时正确才算破译成功。
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Let's execute a "Cognitive Difficulty Cycle Analysis" task. Here are the rules:

A standardized test contains a continuous sequence of {n} questions, recording cognitive difficulty coefficients (an integer between 0 and 9) for each. The test design follows a cognitive difficulty cycle in educational psychology: it is generated by repeatedly concatenating a hidden "base difficulty segment" B. The length of B is L (called the "cycle module span"), and B is repeated across question numbers until {n} positions are filled (the last occurrence may be truncated). L ranges from 2 to 12, and B cannot be obtained by repeating a shorter pattern.

Your goals are:
1. Decipher the cycle module span L and the corresponding base difficulty segment B;
2. Question interval [{forbidden_start}, {forbidden_end}] belongs to a confidential "encrypted assessment zone" and cannot be passed directly. Calculate the true value of this zone under the aggregation method "{target_agg}".

You can perform the following types of extraction queries, but the total number of queries cannot exceed {max_queries}:

1. **Interval Sum Query**: Extract and sum the difficulty coefficients of questions in interval [a, b].
   - Constraints: the number of questions extracted (b-a+1) must be greater than or equal to {min_interval_len}, and 1 less than or equal to a less than or equal to b less than or equal to {n}.
   - You cannot directly query the encrypted assessment zone [{forbidden_start}, {forbidden_end}] (but you can extract question groups that overlap with it).

2. **Interval Max Query**: Extract and query the maximum difficulty in interval [a, b].
   - Same constraints as above.

3. **Interval Min Query**: Extract and query the minimum difficulty in interval [a, b].
   - Same constraints as above.

4. **Remaining Queries Query**: Ask how many extraction permissions remain.

5. **Rules Recap Query**: Retrieve the task's basic configuration parameters.

If a query request violates the constraints (such as index out of bounds, insufficient questions extracted, direct query of encrypted zone, or permissions exhausted), the system will return an error message without consuming a query count.

Each time you can only submit one query or one answer. Use the following XML format:

- Interval sum query (e.g., query interval [1, 5]):
<query_sum>1,5</query_sum>

- Interval max query (e.g., query interval [2, 8]):
<query_max>2,8</query_max>

- Interval min query (e.g., query interval [3, 10]):
<query_min>3,10</query_min>

- Remaining queries query:
<query_remaining></query_remaining>

- Rules recap query:
<query_rules></query_rules>

- Submit final answer (must include module span, base difficulty segment, and aggregation value of the encrypted zone):
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- Base difficulty segment B allows cyclic shift equivalence (e.g., [1,2,3], [2,3,1], and [3,1,2] are considered equivalent cognitive models).
- You need to complete the deciphering and submit the answer within the extraction limit.
- All three parts of the answer (L, B, forbidden_value) must be correct simultaneously to succeed.
"""

    contextualized_rule_zh_4 = """\
【自动化流水线质量追踪系统】
我们来执行一次"机械公差周期检测"任务，规则如下：

系统记录了某批次连续的 {n} 个产线产品的缺陷评级，每个评级值是 0 到 9 之间的整数。受机床重复运作的校准机制影响，缺陷呈现出特定的"基准瑕疵段" B 周期性发生：B 的长度为 L（称为"机械公差周期"），B 随产出批次不断重复，直到涵盖所有 {n} 个工位位置（末尾可能截断）。L 的范围在 2 到 12 之间，且 B 不能再由更短的公差模式重复得到。

你的目标是：
1. 推导出机械公差周期 L 和对应的基准瑕疵段 B；
2. 流水线区间 [{forbidden_start}, {forbidden_end}] 存在光学遮挡，被划定为"质检盲区"无法直接测定，请估算出该盲区内产品在聚合方式"{target_agg}"下的真实总评价指标。

你可以进行以下类型的抽样查询，但总查询次数不得超过 {max_queries} 次：

1. **区间求和查询**：抽样并汇总区间 [a, b] 产品的缺陷评级总和。
   - 约束：批量检测长度（b-a+1）必须大于等于 {min_interval_len}，且 1 小于等于 a 小于等于 b 小于等于 {n}。
   - 不得直接抽样检测质检盲区 [{forbidden_start}, {forbidden_end}]（但可以抽检与之重叠的其他正常区段）。

2. **区间求最大值查询**：抽样并反馈区间 [a, b] 产品中的最高缺陷评级。
   - 约束同上。

3. **区间求最小值查询**：抽样并反馈区间 [a, b] 产品中的最低缺陷评级。
   - 约束同上。

4. **剩余次数查询**：询问还剩多少次系统抽检权限。

5. **规则复述查询**：重新获取任务的基本设定参数。

若抽检请求不符合约束（如工位越界、批量不足、直接抽检盲区、或权限已用尽），系统会拦截请求并返回错误提示，不消耗抽检次数。

每次只能提交一个查询或一个答案。请使用以下 XML 格式：

- 区间求和查询（例如查询区间 [1, 5]）：
<query_sum>1,5</query_sum>

- 区间求最大值查询（例如查询区间 [2, 8]）：
<query_max>2,8</query_max>

- 区间求最小值查询（例如查询区间 [3, 10]）：
<query_min>3,10</query_min>

- 剩余次数查询：
<query_remaining></query_remaining>

- 规则复述查询：
<query_rules></query_rules>

- 提交最终质检报告（必须同时包含公差周期、基准瑕疵段和盲区的聚合值）：
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- 基准瑕疵段 B 允许循环位移等价（例如 [1,2,3] 和 [2,3,1] 和 [3,1,2] 视为等效公差）。
- 你需要在抽检次数限制内完成推导并提交报告。
- 答案的三个部分（L、B、forbidden_value）必须同时正确才算推导成功。
"""

    contextualized_rule_en_4 = """\
[Manufacturing/Industrial Scenario]
Let's execute a "Mechanical Tolerance Period Detection" task. Here are the rules:

The system recorded defect ratings for {n} continuous products on an assembly line, where each rating is an integer between 0 and 9. Due to machine tool calibration repetition, defects present a specific "base flaw segment" B that occurs periodically: the length of B is L (called the "mechanical tolerance period"), and B is repeatedly outputted until {n} workstation positions are filled (the last occurrence may be truncated). L ranges from 2 to 12, and B cannot be obtained by repeating a shorter tolerance pattern.

Your goals are:
1. Derive the mechanical tolerance period L and the corresponding base flaw segment B;
2. Assembly line interval [{forbidden_start}, {forbidden_end}] suffers from optical occlusion and is designated as an "inspection blind spot", which cannot be measured directly. Estimate the true evaluation indicator of this blind spot under the aggregation method "{target_agg}".

You can perform the following types of sampling queries, but the total number of queries cannot exceed {max_queries}:

1. **Interval Sum Query**: Sample and sum the defect ratings of products in interval [a, b].
   - Constraints: batch inspection length (b-a+1) must be greater than or equal to {min_interval_len}, and 1 less than or equal to a less than or equal to b less than or equal to {n}.
   - You cannot directly sample the inspection blind spot [{forbidden_start}, {forbidden_end}] (but you can sample other sections that overlap with it).

2. **Interval Max Query**: Sample and return the maximum defect rating among products in interval [a, b].
   - Same constraints as above.

3. **Interval Min Query**: Sample and return the minimum defect rating among products in interval [a, b].
   - Same constraints as above.

4. **Remaining Queries Query**: Ask how many system sampling permissions remain.

5. **Rules Recap Query**: Retrieve the task's basic configuration parameters.

If a sampling request violates the constraints (such as workstation out of bounds, insufficient batch size, direct sampling of blind spot, or permissions exhausted), the system will intercept the request and return an error message without consuming a sampling count.

Each time you can only submit one query or one answer. Use the following XML format:

- Interval sum query (e.g., query interval [1, 5]):
<query_sum>1,5</query_sum>

- Interval max query (e.g., query interval [2, 8]):
<query_max>2,8</query_max>

- Interval min query (e.g., query interval [3, 10]):
<query_min>3,10</query_min>

- Remaining queries query:
<query_remaining></query_remaining>

- Rules recap query:
<query_rules></query_rules>

- Submit final inspection report (must include tolerance period, base flaw segment, and aggregation value of the blind spot):
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- Base flaw segment B allows cyclic shift equivalence (e.g., [1,2,3], [2,3,1], and [3,1,2] are considered equivalent tolerances).
- You need to complete the derivation and submit the report within the query limit.
- All three parts of the answer (L, B, forbidden_value) must be correct simultaneously to succeed.
"""

    contextualized_rule_zh_5 = """\
【犯罪时间线分析与卷宗梳理系统】
我们来执行一次"作案行为规律推断"任务，规则如下：

调查证据链包含了连续的 {n} 个时间节点的风险指数，每个风险指数是 0 到 9 之间的整数。嫌疑人的活动规律暴露出一种高度模式化的"行为基段" B 周期性重复：B 包含 L 个节点（称为"作案行为周期"），B 按时间轴不断循环，直到涵盖所有 {n} 个时间节点（末尾可能截断）。L 的范围在 2 到 12 之间，且 B 不能由更短的行为模式重复得到。

你的目标是：
1. 侦破作案行为周期 L 以及对应的行为基段 B；
2. 证据链上的节点 [{forbidden_start}, {forbidden_end}] 因涉及保护关键证人被划为"机密封存区"无法直接调阅，请推算该封存区在聚合方式"{target_agg}"下的真实汇总证据指标。

你可以进行以下类型的调阅查询，但总调阅次数不得超过 {max_queries} 次：

1. **区间求和查询**：调阅并统计时间区间 [a, b] 内风险指数的总和。
   - 约束：调查跨度（b-a+1）必须大于等于 {min_interval_len}，且 1 小于等于 a 小于等于 b 小于等于 {n}。
   - 不得直接查询机密封存区 [{forbidden_start}, {forbidden_end}]（但可以调阅与之重叠的其他公开时间段）。

2. **区间求最大值查询**：调阅并统计时间区间 [a, b] 中的最高风险评级。
   - 约束同上。

3. **区间求最小值查询**：调阅并统计时间区间 [a, b] 中的最低风险评级。
   - 约束同上。

4. **剩余次数查询**：询问还剩多少次卷宗调阅权限。

5. **规则复述查询**：重新获取调查任务的基本设定参数。

若调阅请求不符合约束（如时间轴越界、跨度过短、直接调阅机密区、或调阅权限已用尽），系统会驳回请求并提示错误，且不消耗调阅次数。

每次只能提交一个查询或一个结论。请使用以下 XML 格式：

- 区间求和查询（例如查询区间 [1, 5]）：
<query_sum>1,5</query_sum>

- 区间求最大值查询（例如查询区间 [2, 8]）：
<query_max>2,8</query_max>

- 区间求最小值查询（例如查询区间 [3, 10]）：
<query_min>3,10</query_min>

- 剩余次数查询：
<query_remaining></query_remaining>

- 规则复述查询：
<query_rules></query_rules>

- 提交最终侦查结论（必须同时包含作案周期、行为基段和封存区的聚合值）：
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- 行为基段 B 允许循环位移等价（例如 [1,2,3] 和 [2,3,1] 和 [3,1,2] 视为等效作案模式）。
- 你需要在权限次数限制内完成侦破并提交结论。
- 答案的三个部分（L、B、forbidden_value）必须同时正确才算破案成功。
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
Let's execute a "Modus Operandi Inference" task. Here are the rules:

The chain of investigative evidence contains risk indices across {n} continuous time nodes, where each index is an integer between 0 and 9. The suspect's activities reveal a highly patterned "behavioral base segment" B that repeats periodically: B contains L nodes (called the "modus operandi period"), and B loops continuously along the timeline until {n} time nodes are covered (the last occurrence may be truncated). L ranges from 2 to 12, and B cannot be obtained by repeating a shorter behavioral pattern.

Your goals are:
1. Detect the modus operandi period L and the corresponding behavioral base segment B;
2. Evidence nodes [{forbidden_start}, {forbidden_end}] have been designated as a "classified sealed zone" to protect key witnesses and cannot be reviewed directly. Deduce the true summary evidence indicator of this sealed zone under the aggregation method "{target_agg}".

You can perform the following types of review queries, but the total number of queries cannot exceed {max_queries}:

1. **Interval Sum Query**: Review and sum the risk indices within time interval [a, b].
   - Constraints: investigation span (b-a+1) must be greater than or equal to {min_interval_len}, and 1 less than or equal to a less than or equal to b less than or equal to {n}.
   - You cannot directly query the classified sealed zone [{forbidden_start}, {forbidden_end}] (but you can review other public timeframes that overlap with it).

2. **Interval Max Query**: Review and query the maximum risk rating within time interval [a, b].
   - Same constraints as above.

3. **Interval Min Query**: Review and query the minimum risk rating within time interval [a, b].
   - Same constraints as above.

4. **Remaining Queries Query**: Ask how many dossier review permissions remain.

5. **Rules Recap Query**: Retrieve the investigation task's basic configuration parameters.

If a review request violates the constraints (such as timeline out of bounds, span too short, direct review of classified zone, or permissions exhausted), the system will reject the request with an error prompt without consuming a review count.

Each time you can only submit one query or one conclusion. Use the following XML format:

- Interval sum query (e.g., query interval [1, 5]):
<query_sum>1,5</query_sum>

- Interval max query (e.g., query interval [2, 8]):
<query_max>2,8</query_max>

- Interval min query (e.g., query interval [3, 10]):
<query_min>3,10</query_min>

- Remaining queries query:
<query_remaining></query_remaining>

- Rules recap query:
<query_rules></query_rules>

- Submit final investigation conclusion (must include modus operandi period, behavioral base segment, and aggregation value of the sealed zone):
<answer>L=3, B=[1,2,3], forbidden_value=15</answer>

- Behavioral base segment B allows cyclic shift equivalence (e.g., [1,2,3], [2,3,1], and [3,1,2] are considered equivalent modus operandi patterns).
- You need to complete the detection and submit the conclusion within the permission limit.
- All three parts of the answer (L, B, forbidden_value) must be correct simultaneously to succeed.
"""

    tags = ["answer", "query_sum", "query_max", "query_min", "query_remaining", "query_rules"]
    
    reasoning_type = "归纳推理"
    data_structure = "序列"

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 12,
                "base_segment": [1, 2, 3],
                "max_queries": 25,
                "min_interval_len": 4,
                "forbidden_start": 4,
                "forbidden_end": 7,
                "target_agg": "求和",
                "target_agg_func": "sum",
            },
            2: {
                "n": 18,
                "base_segment": [2, 5, 1, 8],
                "max_queries": 20,
                "min_interval_len": 4,
                "forbidden_start": 6,
                "forbidden_end": 11,
                "target_agg": "求最大值",
                "target_agg_func": "max",
            },
            3: {
                "n": 24,
                "base_segment": [3, 7, 2, 9, 0, 4],
                "max_queries": 18,
                "min_interval_len": 5,
                "forbidden_start": 8,
                "forbidden_end": 15,
                "target_agg": "求最小值",
                "target_agg_func": "min",
            },
            4: {
                "n": 30,
                "base_segment": [1, 6, 3, 8, 2, 9, 4, 7],
                "max_queries": 15,
                "min_interval_len": 5,
                "forbidden_start": 10,
                "forbidden_end": 20,
                "target_agg": "求和",
                "target_agg_func": "sum",
            },
            5: {
                "n": 36,
                "base_segment": [5, 2, 8, 1, 6, 9, 3, 7, 4, 0],
                "max_queries": 12,
                "min_interval_len": 6,
                "forbidden_start": 12,
                "forbidden_end": 25,
                "target_agg": "求最大值",
                "target_agg_func": "max",
            },
        },
        "en": {
            1: {
                "n": 12,
                "base_segment": [1, 2, 3],
                "max_queries": 25,
                "min_interval_len": 4,
                "forbidden_start": 4,
                "forbidden_end": 7,
                "target_agg": "sum",
                "target_agg_func": "sum",
            },
            2: {
                "n": 18,
                "base_segment": [2, 5, 1, 8],
                "max_queries": 20,
                "min_interval_len": 4,
                "forbidden_start": 6,
                "forbidden_end": 11,
                "target_agg": "max",
                "target_agg_func": "max",
            },
            3: {
                "n": 24,
                "base_segment": [3, 7, 2, 9, 0, 4],
                "max_queries": 18,
                "min_interval_len": 5,
                "forbidden_start": 8,
                "forbidden_end": 15,
                "target_agg": "min",
                "target_agg_func": "min",
            },
            4: {
                "n": 30,
                "base_segment": [1, 6, 3, 8, 2, 9, 4, 7],
                "max_queries": 15,
                "min_interval_len": 5,
                "forbidden_start": 10,
                "forbidden_end": 20,
                "target_agg": "sum",
                "target_agg_func": "sum",
            },
            5: {
                "n": 36,
                "base_segment": [5, 2, 8, 1, 6, 9, 3, 7, 4, 0],
                "max_queries": 12,
                "min_interval_len": 6,
                "forbidden_start": 12,
                "forbidden_end": 25,
                "target_agg": "max",
                "target_agg_func": "max",
            },
        },
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = int(self.config.difficulty)

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        
        self._game_info["n"] = cfg["n"]
        self._game_info["max_queries"] = cfg["max_queries"]
        self._game_info["min_interval_len"] = cfg["min_interval_len"]
        self._game_info["forbidden_start"] = cfg["forbidden_start"]
        self._game_info["forbidden_end"] = cfg["forbidden_end"]
        self._game_info["target_agg"] = cfg["target_agg"]
        
        self.base_segment = cfg["base_segment"]
        self.period = len(self.base_segment)
        self.target_agg_func = cfg["target_agg_func"]
        
        self.sequence = []
        n = cfg["n"]
        for i in range(n):
            self.sequence.append(self.base_segment[i % self.period])
        
        forbidden_slice = self.sequence[cfg["forbidden_start"] - 1 : cfg["forbidden_end"]]
        if self.target_agg_func == "sum":
            self.forbidden_true_value = sum(forbidden_slice)
        elif self.target_agg_func == "max":
            self.forbidden_true_value = max(forbidden_slice)
        elif self.target_agg_func == "min":
            self.forbidden_true_value = min(forbidden_slice)
        else:
            raise ValueError(f"Unknown aggregation function: {self.target_agg_func}")
        
        self.queries_used = 0

    def _is_cyclic_equivalent(self, seg1, seg2):
        if len(seg1) != len(seg2):
            return False
        doubled = seg1 + seg1
        return seg2 in [doubled[i:i + len(seg2)] for i in range(len(seg1))]

    def _parse_answer(self, answer_str):
        try:
            l_match = re.search(r'L\s*=\s*(\d+)', answer_str, re.IGNORECASE)
            if not l_match:
                return None, None, None
            l_value = int(l_match.group(1))
            
            b_match = re.search(r'B\s*=\s*\[([\d,\s]+)\]', answer_str, re.IGNORECASE)
            if not b_match:
                return None, None, None
            b_str = b_match.group(1)
            b_value = [int(x.strip()) for x in b_str.split(',') if x.strip()]
            
            fv_match = re.search(r'forbidden_value\s*=\s*(\d+)', answer_str, re.IGNORECASE)
            if not fv_match:
                return None, None, None
            fv_value = int(fv_match.group(1))
            
            return l_value, b_value, fv_value
        except:
            return None, None, None

    def evaluate(self, parsed_info):
        answer_str = parsed_info["answer"]
        l_value, b_value, fv_value = self._parse_answer(answer_str)
        
        if l_value is None or b_value is None or fv_value is None:
            return False
        
        if l_value != self.period:
            return False
        
        if len(b_value) != l_value:
            return False
        
        if not self._is_cyclic_equivalent(b_value, self.base_segment):
            return False
        
        if fv_value != self.forbidden_true_value:
            return False
        
        return True

    def _cf_make_wrong(self, correct: str) -> str:
        try:
            val = int(correct)
            return str(val + 1)
        except ValueError:
            pass
        
        if self.config.language == "zh":
            if "是" in correct:
                return correct.replace("是", "否")
            elif "否" in correct:
                return correct.replace("否", "是")
        elif self.config.language == "en":
            if "Yes" in correct:
                return correct.replace("Yes", "No")
            elif "No" in correct:
                return correct.replace("No", "Yes")
            elif "yes" in correct:
                return correct.replace("yes", "no")
            elif "no" in correct:
                return correct.replace("no", "yes")
        
        return correct + "_WRONG"

    def get_all_possible_queries(self) -> list[dict]:
        queries = []
        n = self._game_info["n"]
        min_len = self._game_info["min_interval_len"]
        f_start = self._game_info["forbidden_start"]
        f_end = self._game_info["forbidden_end"]
        
        for a in range(1, n + 1):
            for b in range(a, n + 1):
                if b - a + 1 < min_len:
                    continue
                
                if a == f_start and b == f_end:
                    continue
                
                interval_slice = self.sequence[a - 1 : b]
                
                queries.append({
                    "query": f"<query_sum>{a},{b}</query_sum>",
                    "answer": str(sum(interval_slice))
                })
                
                queries.append({
                    "query": f"<query_max>{a},{b}</query_max>",
                    "answer": str(max(interval_slice))
                })
                
                queries.append({
                    "query": f"<query_min>{a},{b}</query_min>",
                    "answer": str(min(interval_slice))
                })
        
        return queries

    def _cf_core_produce(self, parsed_info):
        lang = self.config.language
        
        if "query_remaining" in parsed_info:
            remaining = self._game_info["max_queries"] - self.queries_used
            if lang == "zh":
                return f"还剩 {remaining} 次查询机会。"
            else:
                return f"You have {remaining} queries remaining."
        
        if "query_rules" in parsed_info:
            if lang == "zh":
                return (f"N={self._game_info['n']}，"
                       f"Q={self._game_info['max_queries']}，"
                       f"m={self._game_info['min_interval_len']}，"
                       f"禁测区间=[{self._game_info['forbidden_start']},{self._game_info['forbidden_end']}]，"
                       f"目标聚合方式={self._game_info['target_agg']}")
            else:
                return (f"N={self._game_info['n']}, "
                       f"Q={self._game_info['max_queries']}, "
                       f"m={self._game_info['min_interval_len']}, "
                       f"forbidden interval=[{self._game_info['forbidden_start']},{self._game_info['forbidden_end']}], "
                       f"target aggregation={self._game_info['target_agg']}")
        
        if self.queries_used >= self._game_info["max_queries"]:
            if lang == "zh":
                return "无效：查询次数已用尽。"
            else:
                return "Invalid: Query limit exhausted."
        
        query_type = None
        if "query_sum" in parsed_info:
            query_type = "sum"
            query_str = parsed_info["query_sum"]
        elif "query_max" in parsed_info:
            query_type = "max"
            query_str = parsed_info["query_max"]
        elif "query_min" in parsed_info:
            query_type = "min"
            query_str = parsed_info["query_min"]
        
        if query_type:
            try:
                parts = [x.strip() for x in query_str.split(',')]
                if len(parts) != 2:
                    raise ValueError
                a, b = int(parts[0]), int(parts[1])
                
                if a < 1 or b > self._game_info["n"] or a > b:
                    if lang == "zh":
                        return f"无效：索引越界（必须满足 1 小于等于 a 小于等于 b 小于等于 {self._game_info['n']}）。"
                    else:
                        return f"Invalid: Index out of bounds (must satisfy 1 <= a <= b <= {self._game_info['n']})."
                
                interval_len = b - a + 1
                if interval_len < self._game_info["min_interval_len"]:
                    if lang == "zh":
                        return f"无效：区间长度不足（必须大于等于 {self._game_info['min_interval_len']}）。"
                    else:
                        return f"Invalid: Interval length insufficient (must be >= {self._game_info['min_interval_len']})."
                
                if (a == self._game_info["forbidden_start"] and 
                    b == self._game_info["forbidden_end"]):
                    if lang == "zh":
                        return f"无效：不得直接查询禁测区间 [{self._game_info['forbidden_start']}, {self._game_info['forbidden_end']}]。"
                    else:
                        return f"Invalid: Cannot directly query forbidden interval [{self._game_info['forbidden_start']}, {self._game_info['forbidden_end']}]."
                
                interval_slice = self.sequence[a - 1 : b]
                if query_type == "sum":
                    result = sum(interval_slice)
                elif query_type == "max":
                    result = max(interval_slice)
                elif query_type == "min":
                    result = min(interval_slice)
                
                self.queries_used += 1
                
                return str(result)
                
            except ValueError:
                if lang == "zh":
                    return "无效：查询格式错误（应为两个用逗号分隔的整数）。"
                else:
                    return "Invalid: Query format error (should be two comma-separated integers)."
            except Exception as e:
                if lang == "zh":
                    return f"无效：{str(e)}"
                else:
                    return f"Invalid: {str(e)}"
        
        if lang == "zh":
            return "无效：无法识别的查询类型。"
        else:
            return "Invalid: Unrecognized query type."