# -*- coding: utf-8 -*-
# 自动生成 | 模型: api/claude-sonnet-4-5-20250929
# 推理类型: 归纳推理（完全自主总结规律）：从多次反馈的样本中，总结出背后隐藏的规律/模式。例如猜拳游戏，模型需要总结对手出拳的模式。
# 数据结构: 序列：存在一个长度为N的有序序列。
# 知识点:   前缀聚合：序列前k个元素的累计和/最大值是多少
# ============================================================

from .base import Game
import re
from typing import List, Dict
import random as _random


class PrefixAggregateReconstructionGame(Game):

    game_rule_zh = """\
我们现在来玩一个"前缀聚合序列重构"的推理游戏，规则如下：

游戏设定了一个长度为 {N} 的整数序列 a1, a2, ..., a{N}，其中每个元素 ai 都是 0 到 9 之间的整数（包含 0 和 9）。这个序列由一个固定的隐藏生成规律产生，该规律在整个游戏过程中不会改变，也不会对外披露。

你的目标是通过有限次查询来推断出这个序列。你可以进行以下两种类型的查询：

1. **前缀和查询**：给定一个位置 k（1 到 {N} 之间的整数），我会告诉你前 k 个元素的和，即 S(k) = a1 + a2 + ... + ak。
2. **前缀最大值查询**：给定一个位置 k（1 到 {N} 之间的整数），我会告诉你前 k 个元素中的最大值，即 M(k) = max(a1, a2, ..., ak)。

你最多可以进行 {Q} 次查询。请尽可能少地使用查询次数，在收集足够信息后提交最终答案。

提交答案时，你可以选择以下两种方式之一：
- **方式一**：提交完整的序列预测，即所有 {N} 个元素的值。
- **方式二**：提交所有前缀聚合值，即所有位置的前缀和 S(k) 和前缀最大值 M(k)（k = 1 到 {N}）。

若答案与真实序列不一致，或查询次数超过限制，游戏失败。

## 查询与提交答案的格式（必须严格遵守）

每次只能进行一个查询。请使用以下 XML 格式：

- 前缀和查询（例如查询位置 3）：
<query_sum>3</query_sum>

- 前缀最大值查询（例如查询位置 5）：
<query_max>5</query_max>

提交最终答案时，请选择以下格式之一：

- 方式一，提交完整序列（例如序列为 1,2,3,4,5）：
<answer>sequence=1,2,3,4,5</answer>

- 方式二，提交所有前缀聚合值（例如 N=3 时）：
<answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    game_rule_en = """\
Let's play a "Prefix Aggregate Sequence Reconstruction" deduction game. Here are the rules:

There is a sequence of length {N}, denoted as a1, a2, ..., a{N}, where each element ai is an integer between 0 and 9 (inclusive). This sequence is generated by a fixed hidden rule, which remains constant throughout the game and is not disclosed.

Your goal is to infer this sequence through a limited number of queries. You can perform the following two types of queries:

1. **Prefix Sum Query**: Given a position k (an integer between 1 and {N}), I will tell you the sum of the first k elements, i.e., S(k) = a1 + a2 + ... + ak.
2. **Prefix Maximum Query**: Given a position k (an integer between 1 and {N}), I will tell you the maximum value among the first k elements, i.e., M(k) = max(a1, a2, ..., ak).

You can perform at most {Q} queries. Try to use as few queries as possible, and submit your final answer after collecting enough information.

When submitting your answer, you can choose one of the following two methods:
- **Method 1**: Submit the complete sequence prediction, i.e., the values of all {N} elements.
- **Method 2**: Submit all prefix aggregate values, i.e., all prefix sums S(k) and prefix maxima M(k) for k = 1 to {N}.

If your answer does not match the true sequence, or if you exceed the query limit, the game fails.

## Query and Answer Format (strictly required)

Each turn allows only one query. Use the following XML format:

- Prefix Sum Query (e.g., querying position 3):
<query_sum>3</query_sum>

- Prefix Maximum Query (e.g., querying position 5):
<query_max>5</query_max>

When submitting the final answer, use one of the following formats:

- Method 1, submit complete sequence (e.g., sequence is 1,2,3,4,5):
<answer>sequence=1,2,3,4,5</answer>

- Method 2, submit all prefix aggregate values (e.g., when N=3):
<answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    contextualized_rule_zh_1 = """\
【交通流监控场景】
我们正在对一段包含 {N} 个连续匝道汇入点的高速公路进行交通流监测。
每个汇入点 i 在特定时间段内新汇入的车辆数为一个 0 到 9 之间的整数（单位：百辆）。车流分布遵循某种未公开的宏观调度规律。

作为交通分析系统，你需要通过系统接口进行有限次调阅，来重构每个匝道的真实汇入量序列。系统支持两种查询指令：

1. **累计流量查询**：输入监测点 k（1 到 {N} 之间的整数），系统返回从起点到第 k 个汇入点累计驶入的车辆总数 S(k)。
2. **峰值流量查询**：输入监测点 k（1 到 {N} 之间的整数），系统返回前 k 个汇入点中，单点最高汇入车流量 M(k)。

你最多可以调用接口 {Q} 次。在收集足够数据后，提交全路段的流量重构报告。

报告提交方式（二选一）：
- **方式一**：提交完整的各匝道汇入量序列。
- **方式二**：提交每个节点的累计流量 S(k) 和峰值流量 M(k)。

若数据与真实记录不符，或查询次数超限，任务失败。

## 接口调用规范（严格匹配 XML 格式）

每次只能发起一次调用：
- 累计流量查询（如查询第 3 节点）：<query_sum>3</query_sum>
- 峰值流量查询（如查询第 5 节点）：<query_max>5</query_max>

提交重构报告的格式：
- 方式一，完整序列（例：1,2,3,4,5）：<answer>sequence=1,2,3,4,5</answer>
- 方式二，所有聚合数据（例 N=3）：<answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    contextualized_rule_en_1 = """\
[Transportation Scenario]
We are conducting traffic flow monitoring on a highway segment comprising {N} consecutive ramp merge points.
During a specific time window, the number of newly merged vehicles at each point i is an integer between 0 and 9 (in hundreds). The flow distribution strictly follows an undisclosed macro-dispatching pattern.

As the traffic analysis system, your task is to reconstruct the exact merge volume sequence for each ramp by querying the interface a limited number of times. The system supports two query commands:

1. **Cumulative Flow Query**: Enter checkpoint k (integer from 1 to {N}), and the system will return the total accumulated number of merged vehicles up to point k, denoted as S(k).
2. **Peak Flow Query**: Enter checkpoint k (integer from 1 to {N}), and the system will return the maximum single-point merge volume recorded among the first k points, denoted as M(k).

You may call the interface a maximum of {Q} times. Once sufficient data is gathered, submit the full highway flow reconstruction report.

Submission Methods (Choose one):
- **Method 1**: Submit the complete sequence of merge volumes for all ramps.
- **Method 2**: Submit the cumulative flow S(k) and peak flow M(k) for all nodes.

The task fails if your data misaligns with the true records or if the query limit is exceeded.

## Interface Call Specifications (Strictly follow XML format)

Only one call per turn:
- Cumulative Flow Query (e.g., node 3): <query_sum>3</query_sum>
- Peak Flow Query (e.g., node 5): <query_max>5</query_max>

Reconstruction Report Submission Formats:
- Method 1, complete sequence (e.g., 1,2,3,4,5): <answer>sequence=1,2,3,4,5</answer>
- Method 2, all aggregate data (e.g., N=3): <answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    contextualized_rule_zh_2 = """\
【医疗体征监测场景】
系统正在分析一位危重患者连续 {N} 个小时的体征异常指数。
每个小时的异常指数是一个 0 到 9 之间的整数，这些指数的起伏受到某种尚未查明的病理周期的固定影响。

作为主治医生，你需要通过有限的病历检索来还原这 {N} 个小时内的精确体征轨迹。你可以进行两种检索：

1. **累计风险负荷查询**：指定时间节点 k（1 到 {N}），系统会返回前 k 个小时的总异常指数积分 S(k)。
2. **极限峰值查询**：指定时间节点 k（1 到 {N}），系统会返回前 k 个小时内出现的最高单小时异常指数 M(k)。

你最多只能进行 {Q} 次检索操作。在掌握足够线索后，请开具完整的体征评估报告。

提交报告的方式（二选一）：
- **方式一**：提交每一小时的完整异常指数序列。
- **方式二**：提交每一小时的累计风险负荷 S(k) 及极限峰值 M(k)。

若评估偏差，或超过检索次数，患者诊断进度将延误，任务失败。

## 检索与提交格式规范（必须严格遵守）

单次检索请使用以下 XML 标签：
- 累计风险查询（如查询第 3 小时）：<query_sum>3</query_sum>
- 极限峰值查询（如查询第 5 小时）：<query_max>5</query_max>

提交最终体征评估报告格式：
- 方式一，完整序列（例：1,2,3,4,5）：<answer>sequence=1,2,3,4,5</answer>
- 方式二，所有聚合体征（例 N=3）：<answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    contextualized_rule_en_2 = """\
[Healthcare Scenario]
The system is analyzing the vital sign anomaly indices of a critical patient over {N} consecutive hours.
The anomaly index for each hour is an integer between 0 and 9. The fluctuations are governed by an underlying, undisclosed pathological cycle.

As the attending physician, your objective is to accurately reconstruct the patient's vital trajectory across these {N} hours through limited medical record retrievals. Two retrieval types are available:

1. **Cumulative Risk Load Query**: Specify hour k (from 1 to {N}), and the system returns the total integrated anomaly index up to hour k, denoted as S(k).
2. **Extreme Peak Query**: Specify hour k (from 1 to {N}), and the system returns the highest single-hour anomaly index recorded within the first k hours, denoted as M(k).

You are restricted to a maximum of {Q} retrieval operations. Once sufficient clinical evidence is gathered, issue the comprehensive vital assessment report.

Report Submission Methods (Choose one):
- **Method 1**: Submit the complete sequence of hourly anomaly indices.
- **Method 2**: Submit the cumulative risk load S(k) and extreme peak M(k) for every hour.

Failure occurs if the assessment is inaccurate or if the retrieval limit is breached.

## Retrieval and Submission Formats (Strictly required)

Use the following XML tags for a single retrieval:
- Cumulative Risk Query (e.g., hour 3): <query_sum>3</query_sum>
- Extreme Peak Query (e.g., hour 5): <query_max>5</query_max>

Final Vital Assessment Report Formats:
- Method 1, complete sequence (e.g., 1,2,3,4,5): <answer>sequence=1,2,3,4,5</answer>
- Method 2, all aggregate vitals (e.g., N=3): <answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    contextualized_rule_zh_3 = """\
【教育测评跟踪场景】
我们正在评估一名学员在 {N} 个递进式学习模块中的技能掌握情况。
该学员在每个模块中获得的技能点均为 0 到 9 之间的整数，其得分分布反映了他/她固有的学习吸收规律（此规律固定且不对外公开）。

作为教研员，你需要在查阅次数受限的前提下，推导还原出学员在所有模块的具体得分序列。平台提供两种查阅方式：

1. **累计学分查询**：输入模块进度 k（1 到 {N}），系统将反馈前 k 个模块累计获得的技能点总和 S(k)。
2. **单项高分查询**：输入模块进度 k（1 到 {N}），系统将反馈前 k 个模块中，单次模块获得的最高技能点 M(k)。

你最多可执行 {Q} 次查阅。请以最经济的方式收集数据，并最终提交学员的学情画像图谱。

提交画像可以选择以下方式之一：
- **方式一**：提交学员在全部 {N} 个模块中的完整得分序列。
- **方式二**：提交每个模块阶段的累计学分 S(k) 和单项高分 M(k) 数据。

成绩预测错误或查阅超限均视为评估失败。

## 查阅与报告提交格式（需严格遵循 XML 标签）

单次查询请求：
- 累计学分查询（例：查阅前 3 模块）：<query_sum>3</query_sum>
- 单项高分查询（例：查阅前 5 模块）：<query_max>5</query_max>

学情画像提交格式：
- 方式一，完整序列（例：1,2,3,4,5）：<answer>sequence=1,2,3,4,5</answer>
- 方式二，所有聚合数据（例 N=3）：<answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
We are evaluating a student's competency mastery across {N} sequential learning modules.
The skill points earned in each module are integers ranging from 0 to 9. This scoring distribution reflects the student's inherent learning curve, which remains fixed and undisclosed.

As an educational researcher, your task is to deduce the student's exact score sequence across all modules, constrained by a limited number of inquiries. The platform provides two inquiry modes:

1. **Cumulative Credits Query**: Input module progress k (from 1 to {N}), and the system feeds back the total accumulated skill points up to module k, denoted as S(k).
2. **Single-Module High Score Query**: Input module progress k (from 1 to {N}), and the system feeds back the highest skill points achieved in any single module among the first k modules, denoted as M(k).

You are allowed a maximum of {Q} inquiries. Gather data efficiently and ultimately submit the student's learning profile.

Profile Submission Methods (Choose one):
- **Method 1**: Submit the complete sequence of scores across all {N} modules.
- **Method 2**: Submit the cumulative credits S(k) and single-module high score M(k) for each stage.

An incorrect prediction or exceeding the inquiry limit results in a failed assessment.

## Inquiry and Report Formats (Strict XML compliance required)

Single inquiry requests:
- Cumulative Credits Query (e.g., first 3 modules): <query_sum>3</query_sum>
- High Score Query (e.g., first 5 modules): <query_max>5</query_max>

Learning Profile Submission Formats:
- Method 1, complete sequence (e.g., 1,2,3,4,5): <answer>sequence=1,2,3,4,5</answer>
- Method 2, all aggregate data (e.g., N=3): <answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    contextualized_rule_zh_4 = """\
【制造业/工业质控场景】
在一条包含 {N} 个自动化工位的精密装配流水线上，产品正在进行逐级加工。
受到设备公差影响，每个工位 i 会向产品引入一定数量的微小瑕疵（0 到 9 之间的整数）。这一瑕疵引入序列遵循设备固有的机械偏移规律。

作为质控工程师，你需要通过非破坏性探伤检测来确定每个工位的具体瑕疵贡献量。你可以使用以下两种检测模式：

1. **缺陷累积检测**：定位至工位 k（1 到 {N}），仪器将返回产品经过前 k 个工位后累积的瑕疵总数 S(k)。
2. **最大公差检测**：定位至工位 k（1 到 {N}），仪器将返回前 k 个工位中，单个工位造成的最大瑕疵数量 M(k)。

设备的检测寿命限制你只能进行 {Q} 次操作。请在获取充分的参数后，提交工位质控校准数据。

数据提交支持以下方式（二选一）：
- **方式一**：提交各工位的完整瑕疵引入序列。
- **方式二**：提交通过各工位后的缺陷累积 S(k) 和最大公差 M(k)。

参数误判或检测超限，将导致整条流水线校准失败。

## 检测仪指令格式（必须精准输入）

每次只能输入一条指令：
- 缺陷累积检测（如定位工位 3）：<query_sum>3</query_sum>
- 最大公差检测（如定位工位 5）：<query_max>5</query_max>

校准数据提交格式：
- 方式一，完整序列（例：1,2,3,4,5）：<answer>sequence=1,2,3,4,5</answer>
- 方式二，所有聚合读数（例 N=3）：<answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing/Industrial Scenario]
On a precision assembly line comprising {N} automated workstations, a product undergoes sequential processing.
Due to equipment tolerances, each workstation i introduces a specific number of micro-defects (an integer from 0 to 9) to the product. This sequence of defect introduction adheres to the machinery's inherent deviation pattern.

As a Quality Control Engineer, you must determine the precise defect contribution of each workstation using non-destructive testing. You can utilize two testing modes:

1. **Cumulative Defect Test**: Target workstation k (from 1 to {N}), and the instrument returns the total accumulated defects on the product after passing the first k workstations, denoted as S(k).
2. **Maximum Tolerance Test**: Target workstation k (from 1 to {N}), and the instrument returns the highest number of defects introduced by any single workstation among the first k, denoted as M(k).

Instrument lifespan restricts you to {Q} operations. Upon gathering sufficient parameters, submit the workstation QC calibration data.

Data Submission Methods (Choose one):
- **Method 1**: Submit the complete sequence of defects introduced by each workstation.
- **Method 2**: Submit the cumulative defects S(k) and maximum tolerance M(k) measured at each station.

Misjudging the parameters or exceeding the operation limit will result in calibration failure for the entire line.

## Instrument Command Formats (Input precisely)

Input only one command at a time:
- Cumulative Defect Test (e.g., station 3): <query_sum>3</query_sum>
- Maximum Tolerance Test (e.g., station 5): <query_max>5</query_max>

Calibration Data Submission Formats:
- Method 1, complete sequence (e.g., 1,2,3,4,5): <answer>sequence=1,2,3,4,5</answer>
- Method 2, all aggregate readings (e.g., N=3): <answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    contextualized_rule_zh_5 = """\
【法律案件审查场景】
你正在梳理一宗复杂经济案件的证据链，该案件按时间顺序包含 {N} 份核心卷宗。
法务系统已对每份卷宗提取了"证据权重指数"（0 到 9 之间的整数）。这一权重序列隐藏了作案者严密的资金腾挪规律。

作为首席审查官，需通过受限的卷宗检索权限，完全还原这 {N} 份卷宗各自的证据效力。权限允许两种检索模式：

1. **效力累加检索**：指定卷宗编号 k（1 到 {N}），系统汇总并返回前 k 份卷宗的累计证据效力总和 S(k)。
2. **核心铁证检索**：指定卷宗编号 k（1 到 {N}），系统比对并返回前 k 份卷宗里单份最高的证据权重指数 M(k)。

司法审计的合规要求限制你最多调用 {Q} 次检索。请以最高效的逻辑完成拼图，并提交完整的证据效力鉴定书。

鉴定书提交方式（二选一）：
- **方式一**：提交 {N} 份卷宗完整的权重指数序列。
- **方式二**：提交所有卷宗节点上的效力累加值 S(k) 和核心铁证值 M(k)。

证据链出现任何断点或检索超载，将被视为审查不合格。

## 系统检索与鉴定提交流程（严禁修改 XML 语法）

每次提交单条检索请求：
- 效力累加检索（例：编号 3）：<query_sum>3</query_sum>
- 核心铁证检索（例：编号 5）：<query_max>5</query_max>

证据效力鉴定书格式：
- 方式一，完整序列（例：1,2,3,4,5）：<answer>sequence=1,2,3,4,5</answer>
- 方式二，所有聚合权重（例 N=3）：<answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    contextualized_rule_en_5 = """\
[Law Scenario]
You are untangling the evidence chain of a complex financial case, which comprises {N} core case files organized chronologically.
The legal system has assigned an "Evidentiary Weight Index" (an integer from 0 to 9) to each file. This weight sequence conceals the perpetrator's rigorous fund-transfer pattern.

As the Chief Investigator, you must fully reconstruct the evidentiary validity of each of the {N} files under restricted docket retrieval permissions. Two retrieval modes are permitted:

1. **Cumulative Validity Retrieval**: Specify file number k (from 1 to {N}), and the system calculates and returns the total accumulated evidentiary weight of the first k files, denoted as S(k).
2. **Core Proof Retrieval**: Specify file number k (from 1 to {N}), and the system compares and returns the highest single-file evidentiary weight index among the first k files, denoted as M(k).

Judicial audit compliance limits you to a maximum of {Q} retrievals. Piece the puzzle together with optimal logic and submit the complete Evidentiary Validity Statement.

Statement Submission Methods (Choose one):
- **Method 1**: Submit the complete sequence of weight indices for all {N} files.
- **Method 2**: Submit the cumulative validity S(k) and core proof M(k) values up to every file node.

Any discrepancy in the evidence chain or surpassing the retrieval limit yields a failed review.

## System Retrieval and Statement Submission (Do not alter XML syntax)

Submit one retrieval request at a time:
- Cumulative Validity Retrieval (e.g., file 3): <query_sum>3</query_sum>
- Core Proof Retrieval (e.g., file 5): <query_max>5</query_max>

Evidentiary Validity Statement Formats:
- Method 1, complete sequence (e.g., 1,2,3,4,5): <answer>sequence=1,2,3,4,5</answer>
- Method 2, all aggregate weights (e.g., N=3): <answer>prefixes=S(1)=1,S(2)=3,S(3)=6,M(1)=1,M(2)=2,M(3)=3</answer>
"""

    tags = ["answer", "query_sum", "query_max"]
    
    reasoning_type = "归纳推理"
    data_structure = "序列"

    # 难度配置说明：
    # 1 (简单)       - N=3, 等差数列
    # 2 (中等偏下)   - N=5, 常数序列
    # 3 (中等偏上)   - N=6, 递增序列
    # 4 (较难)       - N=8, 周期序列
    # 5 (难)         - N=10, 复杂模式

    DIFFICULTY_CONFIG = {
        1: {"N": 3, "Q": 3, "value_range": (0, 9)},
        2: {"N": 5, "Q": 5, "value_range": (0, 9)},
        3: {"N": 6, "Q": 6, "value_range": (0, 9)},
        4: {"N": 8, "Q": 8, "value_range": (0, 9)},
        5: {"N": 10, "Q": 10, "value_range": (0, 9)},
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        diff = int(self.config.difficulty)

        if diff not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[diff]
        
        self.N = cfg["N"]
        self.Q = cfg["Q"]
        lo, hi = cfg["value_range"]
        
        # 使用固定种子确保可复现
        rng = _random.Random(42 + diff)
        self.sequence = [rng.randint(lo, hi) for _ in range(self.N)]
        
        # 预计算前缀和与前缀最大值
        self.prefix_sum = {}
        self.prefix_max = {}
        
        current_sum = 0
        current_max = -1
        
        for i in range(1, self.N + 1):
            current_sum += self.sequence[i - 1]
            current_max = max(current_max, self.sequence[i - 1])
            self.prefix_sum[i] = current_sum
            self.prefix_max[i] = current_max
        
        # 查询计数器
        self.query_count = 0
        
        # 填充游戏信息
        self._game_info["N"] = self.N
        self._game_info["Q"] = self.Q

    def evaluate(self, parsed_info):
        """评估最终答案是否正确"""
        raw_ans = parsed_info["answer"].strip()
        
        # 方式一：完整序列提交
        if raw_ans.startswith("sequence="):
            try:
                seq_str = raw_ans.split("sequence=", 1)[1].strip()
                predicted_seq = [int(x.strip()) for x in seq_str.split(",")]
                
                # 检查长度
                if len(predicted_seq) != self.N:
                    return False
                
                # 逐项比较
                return predicted_seq == self.sequence
            except:
                return False
        
        # 方式二：前缀聚合值提交
        elif raw_ans.startswith("prefixes="):
            try:
                prefixes_str = raw_ans.split("prefixes=", 1)[1].strip()
                
                # 解析所有的 S(k)=value 和 M(k)=value
                predicted_sum = {}
                predicted_max = {}
                
                # 匹配 S(k)=value
                sum_pattern = r'S\((\d+)\)=(\d+)'
                for match in re.finditer(sum_pattern, prefixes_str):
                    k = int(match.group(1))
                    val = int(match.group(2))
                    predicted_sum[k] = val
                
                # 匹配 M(k)=value
                max_pattern = r'M\((\d+)\)=(\d+)'
                for match in re.finditer(max_pattern, prefixes_str):
                    k = int(match.group(1))
                    val = int(match.group(2))
                    predicted_max[k] = val
                
                # 检查是否所有位置都提交了
                if len(predicted_sum) != self.N or len(predicted_max) != self.N:
                    return False
                
                # 逐项比较
                for k in range(1, self.N + 1):
                    if k not in predicted_sum or k not in predicted_max:
                        return False
                    if predicted_sum[k] != self.prefix_sum[k]:
                        return False
                    if predicted_max[k] != self.prefix_max[k]:
                        return False
                
                return True
            except:
                return False
        else:
            return False

    def _cf_make_wrong(self, correct: str) -> str:
        """将正确的查询结果篡改为一个错误值"""
        try:
            correct_val = int(correct)
            # 使用确定性偏移，确保不等于原值
            offset = (correct_val % 3) + 1  # 确定性偏移 1~3
            wrong_val = correct_val + offset
            return str(wrong_val)
        except (ValueError, TypeError):
            return correct + "_wrong"

    def _cf_core_produce(self, parsed_info):
        """核心业务逻辑处理查询请求"""
        if self.query_count >= self.Q:
            if self.config.language == "zh":
                return f"查询次数已达上限 {self.Q} 次，请提交最终答案。"
            else:
                return f"Query limit of {self.Q} reached. Please submit your final answer."
        
        has_sum = "query_sum" in parsed_info
        has_max = "query_max" in parsed_info
        
        # 同时包含两种查询时，只处理第一个并提醒
        if has_sum and has_max:
            if self.config.language == "zh":
                warning = "（注意：每次只能进行一个查询，已忽略多余查询。）\n"
            else:
                warning = "(Note: Only one query per turn is allowed. Extra queries were ignored.)\n"
        else:
            warning = ""
        
        if has_sum:
            try:
                k = int(parsed_info["query_sum"].strip())
                if k < 1 or k > self.N:
                    if self.config.language == "zh":
                        return f"错误：位置 {k} 超出范围 [1, {self.N}]。"
                    else:
                        return f"Error: Position {k} is out of range [1, {self.N}]."
                self.query_count += 1
                return warning + str(self.prefix_sum[k])
            except ValueError:
                if self.config.language == "zh":
                    return "错误：无效的查询格式。"
                else:
                    return "Error: Invalid query format."
        
        elif has_max:
            try:
                k = int(parsed_info["query_max"].strip())
                if k < 1 or k > self.N:
                    if self.config.language == "zh":
                        return f"错误：位置 {k} 超出范围 [1, {self.N}]。"
                    else:
                        return f"Error: Position {k} is out of range [1, {self.N}]."
                self.query_count += 1
                return warning + str(self.prefix_max[k])
            except ValueError:
                if self.config.language == "zh":
                    return "错误：无效的查询格式。"
                else:
                    return "Error: Invalid query format."
        
        else:
            if self.config.language == "zh":
                return "错误：未找到有效的查询标签，请使用 <query_sum> 或 <query_max>。"
            else:
                return "Error: No valid query tag found. Please use <query_sum> or <query_max>."

    def get_all_possible_queries(self) -> List[Dict[str, str]]:
        """
        枚举所有合法查询并返回对应的正确答案。

        Returns:
            list of dict, 每项格式：
            {
                "query" : str,   # 查询内容字符串，与游戏中 parsed_info["query"] 的值格式一致
                "answer": str,   # 调用游戏逻辑后得到的正确答案字符串
            }
        """
        possible_queries = []
        
        # 枚举所有位置的前缀和查询
        for k in range(1, self.N + 1):
            possible_queries.append({
                "query": f"<query_sum>{k}</query_sum>",
                "answer": str(self.prefix_sum[k])
            })
            
        # 枚举所有位置的前缀最大值查询
        for k in range(1, self.N + 1):
            possible_queries.append({
                "query": f"<query_max>{k}</query_max>",
                "answer": str(self.prefix_max[k])
            })
            
        return possible_queries