from .base import Game
import random

class PeriodicSequenceGame(Game):

    game_rule_zh = """\
我们来玩一个"周期序列推理"游戏，规则如下：

游戏设定了一个长度为 {n} 的序列 S，序列中每个位置的值来自字母表 {{R, G, B}}（即红、绿、蓝三种颜色）。这个序列是由一个未知的"基序" P 重复多次并截断到长度 {n} 而生成的。基序 P 的长度称为"最小周期" t，满足 2 到 8 之间。

你的目标是通过查询推断出这个序列 S（或等价地推断出最小周期 t 和基序 P）。你需要在尽可能少的查询次数内完成推理。

每次查询只能包含一个标签，你可以使用以下两种查询：

1. **前缀匹配查询**：提供一个猜测序列 Q（长度在 1 到 {n} 之间），我会告诉你 Q 与真实序列 S 的最长公共前缀长度 K。即从序列开头起，Q 和 S 有多少个连续位置的值相同。

   格式示例（查询序列 "RGBR"）：
   <query_prefix>RGBR</query_prefix>

2. **d-周期前缀查询**：提供一个正整数 d，我会告诉你序列 S 的前缀中，最长的满足"间隔为 d 的位置都相同"的前缀长度 L。即找到最大的 L，使得对于所有 1 到 L 减 d 之间的位置 i，都有 S[i] 等于 S[i+d]。

   格式示例（查询 d=3）：
   <query_period>3</query_period>

当你收集到足够信息后，可以提交最终答案。你可以选择以下两种提交方式之一：

1. **提交完整序列**：直接给出长度为 {n} 的完整序列。

   格式示例：
   <answer>sequence=RGBRGBRGB</answer>

2. **提交基序描述**：给出最小周期 t 和对应的基序 P（P 的长度必须等于 t）。

   格式示例：
   <answer>period=3, motif=RGB</answer>

注意：答案错误或格式不符，游戏失败。每次只能提交一个查询或答案标签。
"""

    game_rule_en = """\
Let's play a "Periodic Sequence Inference" game. Here are the rules:

A sequence S of length {n} has been set up, where each position contains a value from the alphabet {{R, G, B}} (Red, Green, Blue). This sequence is generated by repeating an unknown "motif" P multiple times and truncating it to length {n}. The length of motif P is called the "minimal period" t, which is between 2 and 8.

Your goal is to infer the sequence S (or equivalently, infer the minimal period t and motif P) through queries. You should complete the inference with as few queries as possible.

Each query must contain only one tag. You can use the following two types of queries:

1. **Prefix Match Query**: Provide a guessed sequence Q (length between 1 and {n}), and I will tell you the longest common prefix length K between Q and the true sequence S. That is, how many consecutive positions from the beginning have the same values in Q and S.

   Format example (querying sequence "RGBR"):
   <query_prefix>RGBR</query_prefix>

2. **d-Period Prefix Query**: Provide a positive integer d, and I will tell you the length L of the longest prefix of sequence S that satisfies "all positions with distance d have the same value". That is, find the maximum L such that for all positions i from 1 to L minus d, S[i] equals S[i+d].

   Format example (querying d=3):
   <query_period>3</query_period>

When you have collected enough information, you can submit your final answer. You can choose one of the following two submission methods:

1. **Submit Complete Sequence**: Directly provide the complete sequence of length {n}.

   Format example:
   <answer>sequence=RGBRGBRGB</answer>

2. **Submit Motif Description**: Provide the minimal period t and the corresponding motif P (P's length must equal t).

   Format example:
   <answer>period=3, motif=RGB</answer>

Note: Incorrect answer or invalid format results in game failure. Only one query or answer tag can be submitted each time.
"""

    contextualized_rule_zh_1 = """\
我们正在调试"智能交通信号灯优化系统"，规则如下：

路网中心设定了一个长度为 {n} 的交通状态序列 S，序列中每个时间片的状态值为 {{R, G, B}}（即红灯拥堵、绿灯畅通、蓝灯缓慢）。这个状态序列是由一个未知的"基础信号周期" P 循环执行并截断到长度 {n} 生成的。基础信号周期 P 的长度称为"最小周期" t，满足 2 到 8 之间。

你的目标是通过系统查询推断出完整的状态序列 S（或等价地推断出最小周期 t 和基础信号周期 P）。你需要以最少的查询次数完成故障排查。

每次查询只能包含一个标签，你可以使用以下两种查询指令：

1. **历史状态验证（前缀匹配查询）**：提供一个预估状态序列 Q（长度在 1 到 {n} 之间），系统会反馈 Q 与真实序列 S 的最长公共前缀长度 K。即从第一个时间片起，Q 和 S 有多少个连续状态完全匹配。

   格式示例（查询序列 "RGBR"）：
   <query_prefix>RGBR</query_prefix>

2. **周期稳定性测试（d-周期前缀查询）**：提供一个正整数 d，系统会反馈序列 S 的前缀中，最长的满足"间隔为 d 的状态皆一致"的前缀时段长度 L。即找到最大的 L，使得对于所有 1 到 L 减 d 之间的时间片 i，都有 S[i] 等于 S[i+d]。

   格式示例（查询 d=3）：
   <query_period>3</query_period>

收集到足够信息后，请提交最终诊断。你可以选择以下两种方式之一：

1. **提交完整序列**：直接给出长度为 {n} 的完整状态序列。

   格式示例：
   <answer>sequence=RGBRGBRGB</answer>

2. **提交基础信号周期描述**：给出最小周期 t 和对应的基础信号周期 P（P 的长度必须等于 t）。

   格式示例：
   <answer>period=3, motif=RGB</answer>

注意：诊断错误或格式不符，系统将锁定失败。每次只能提交一个查询或诊断标签。
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
We are debugging the "Intelligent Traffic Signal Optimization System". The rules are as follows:

The traffic control center has recorded a state sequence S of length {n}, where the state of each time slice is from {{R, G, B}} (Red for congested, Green for clear, Blue for slow). This sequence is generated by repeating an unknown "base signal cycle" P multiple times and truncating it to length {n}. The length of cycle P is called the "minimal period" t, which is between 2 and 8.

Your goal is to infer the complete sequence S (or equivalently, infer the minimal period t and cycle P) through system queries. You need to complete the troubleshooting with as few queries as possible.

Each query must contain only one tag. You can use the following two types of queries:

1. **Historical State Validation (Prefix Match Query)**: Provide an estimated sequence Q (length between 1 and {n}), and the system will return the longest common prefix length K between Q and the true sequence S. That is, how many consecutive states match exactly from the beginning.

   Format example (querying sequence "RGBR"):
   <query_prefix>RGBR</query_prefix>

2. **Cycle Stability Test (d-Period Prefix Query)**: Provide a positive integer d, and the system will return the length L of the longest prefix of S that satisfies "all states with distance d are identical". That is, find the maximum L such that for all time slices i from 1 to L minus d, S[i] equals S[i+d].

   Format example (querying d=3):
   <query_period>3</query_period>

When you have collected enough information, submit your final diagnosis using one of the following methods:

1. **Submit Complete Sequence**: Directly provide the complete state sequence of length {n}.

   Format example:
   <answer>sequence=RGBRGBRGB</answer>

2. **Submit Cycle Description**: Provide the minimal period t and the corresponding base signal cycle P (P's length must equal t).

   Format example:
   <answer>period=3, motif=RGB</answer>

Note: Incorrect diagnosis or invalid format results in system lock-out. Only one query or diagnosis tag can be submitted each time.
"""

    contextualized_rule_zh_2 = """\
我们正在进行"医学基因组变异序列分析"，规则如下：

医学实验室提取了一段长度为 {n} 的核苷酸变体序列 S，序列中每个点位的特征值为 {{R, G, B}}（即三种特定的核苷酸修饰变体）。这个序列是由一个未知的"基础基因片段" P 多次复制嵌套并截断到长度 {n} 形成的。片段 P 的长度称为"最小周期" t，满足 2 到 8 之间。

你的目标是通过比对查询推断出完整的突变序列 S（或等价地推断出最小周期 t 和基础基因片段 P）。你需要在尽可能少的化验查询次数内完成测序推演。

每次化验查询只能包含一个标签，你可以使用以下两种查询手段：

1. **基因序列比对（前缀匹配查询）**：提供一个假定的基因片段序列 Q（长度在 1 到 {n} 之间），测序仪会反馈 Q 与真实患者序列 S 的最长公共前缀长度 K。即从序列端点起，Q 和 S 有多少个连续位点的变体特征完全一致。

   格式示例（查询序列 "RGBR"）：
   <query_prefix>RGBR</query_prefix>

2. **同源间隔检测（d-周期前缀查询）**：提供一个正整数 d，测序仪会反馈序列 S 的前缀中，最长的满足"间隔为 d 的位点特征皆一致"的前缀片段长度 L。即找到最大的 L，使得对于所有 1 到 L 减 d 之间的位点 i，都有 S[i] 等于 S[i+d]。

   格式示例（查询 d=3）：
   <query_period>3</query_period>

当数据充分后，可以提交最终测序报告。你可以选择以下两种方式之一：

1. **提交完整序列**：直接给出长度为 {n} 的完整突变序列。

   格式示例：
   <answer>sequence=RGBRGBRGB</answer>

2. **提交基础片段描述**：给出最小周期 t 和对应的基础基因片段 P（P 的长度必须等于 t）。

   格式示例：
   <answer>period=3, motif=RGB</answer>

注意：测序结果错误或格式不符将导致实验失败。每次只能提交一个查询或报告标签。
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
We are conducting "Medical Genomic Variant Sequence Analysis". The rules are as follows:

The medical laboratory has extracted a nucleotide variant sequence S of length {n}, where the feature value of each locus is from {{R, G, B}} (representing three specific nucleotide modification variants). This sequence is formed by repeatedly duplicating an unknown "base gene segment" P and truncating it to length {n}. The length of segment P is called the "minimal period" t, which is between 2 and 8.

Your goal is to infer the complete mutated sequence S (or equivalently, infer the minimal period t and base gene segment P) through alignment queries. You need to complete the sequencing inference with as few assay queries as possible.

Each assay query must contain only one tag. You can use the following two query methods:

1. **Gene Sequence Alignment (Prefix Match Query)**: Provide a hypothetical gene segment sequence Q (length between 1 and {n}), and the sequencer will return the longest common prefix length K between Q and the true patient sequence S. That is, how many consecutive loci variants match exactly from the starting end.

   Format example (querying sequence "RGBR"):
   <query_prefix>RGBR</query_prefix>

2. **Homologous Interval Detection (d-Period Prefix Query)**: Provide a positive integer d, and the sequencer will return the length L of the longest prefix of S that satisfies "all loci with distance d have identical features". That is, find the maximum L such that for all loci i from 1 to L minus d, S[i] equals S[i+d].

   Format example (querying d=3):
   <query_period>3</query_period>

When the data is sufficient, you can submit the final sequencing report. You can choose one of the following two methods:

1. **Submit Complete Sequence**: Directly provide the complete mutated sequence of length {n}.

   Format example:
   <answer>sequence=RGBRGBRGB</answer>

2. **Submit Base Segment Description**: Provide the minimal period t and the corresponding base gene segment P (P's length must equal t).

   Format example:
   <answer>period=3, motif=RGB</answer>

Note: Incorrect sequencing results or invalid format will lead to experimental failure. Only one query or report tag can be submitted each time.
"""

    contextualized_rule_zh_3 = """\
我们正在排布"智能教学课表规划系统"，规则如下：

教务系统生成了一段长度为 {n} 的课程活动序列 S，序列中每节课的活动类型为 {{R, G, B}}（即阅读理解、小组讨论、实践操作）。这个学期课表是由一个未知的"基础教学模块" P 循环排布并截断到长度 {n} 构成的。教学模块 P 的长度称为"最小周期" t，满足 2 到 8 之间。

你的目标是通过系统排查推断出完整的学期课表序列 S（或等价地推断出最小周期 t 和基础教学模块 P）。你需要在尽可能少的试探排课次数内完成系统同步。

每次查询只能包含一个标签，你可以使用以下两种排查手段：

1. **课表匹配度评估（前缀匹配查询）**：提供一个你设计的课程序列 Q（长度在 1 到 {n} 之间），系统会反馈 Q 与真实课表 S 的最长公共前缀长度 K。即从第一节课起，Q 和 S 有多少个连续课时的活动安排完全吻合。

   格式示例（查询序列 "RGBR"）：
   <query_prefix>RGBR</query_prefix>

2. **模块化排课规律排查（d-周期前缀查询）**：提供一个正整数 d，系统会反馈序列 S 的前缀中，最长的满足"间隔为 d 的活动类型皆一致"的课表前缀长度 L。即找到最大的 L，使得对于所有 1 到 L 减 d 之间的课时 i，都有 S[i] 等于 S[i+d]。

   格式示例（查询 d=3）：
   <query_period>3</query_period>

掌握规律后，请提交最终教学计划。你可以选择以下两种方式之一：

1. **提交完整课表**：直接给出长度为 {n} 的完整学期活动序列。

   格式示例：
   <answer>sequence=RGBRGBRGB</answer>

2. **提交基础模块描述**：给出最小周期 t 和对应的基础教学模块 P（P 的长度必须等于 t）。

   格式示例：
   <answer>period=3, motif=RGB</answer>

注意：计划错误或格式不符，系统将拒绝排课并判定失败。每次只能提交一个查询或计划标签。
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
We are organizing the "Intelligent Teaching Schedule Planning System". The rules are as follows:

The academic system has generated a course activity sequence S of length {n}, where the activity type for each class is from {{R, G, B}} (Reading comprehension, Group discussion, Practical operation). This semester's schedule is formed by cyclically arranging an unknown "base teaching module" P and truncating it to length {n}. The length of module P is called the "minimal period" t, which is between 2 and 8.

Your goal is to infer the complete semester schedule sequence S (or equivalently, infer the minimal period t and base teaching module P) through system checks. You need to complete the system synchronization with as few trial scheduling queries as possible.

Each query must contain only one tag. You can use the following two screening methods:

1. **Schedule Match Evaluation (Prefix Match Query)**: Provide a designed course sequence Q (length between 1 and {n}), and the system will return the longest common prefix length K between Q and the actual schedule S. That is, how many consecutive class activities match exactly from the first period.

   Format example (querying sequence "RGBR"):
   <query_prefix>RGBR</query_prefix>

2. **Modular Scheduling Pattern Check (d-Period Prefix Query)**: Provide a positive integer d, and the system will return the length L of the longest prefix of S that satisfies "all activity types with a distance of d are identical". That is, find the maximum L such that for all periods i from 1 to L minus d, S[i] equals S[i+d].

   Format example (querying d=3):
   <query_period>3</query_period>

Once you grasp the pattern, please submit the final teaching plan. You can choose one of the following two methods:

1. **Submit Complete Schedule**: Directly provide the complete semester activity sequence of length {n}.

   Format example:
   <answer>sequence=RGBRGBRGB</answer>

2. **Submit Base Module Description**: Provide the minimal period t and the corresponding base teaching module P (P's length must equal t).

   Format example:
   <answer>period=3, motif=RGB</answer>

Note: Incorrect plan or invalid format will lead to scheduling rejection and failure. Only one query or plan tag can be submitted each time.
"""

    contextualized_rule_zh_4 = """\
我们正在操作"自动化装配线质量监测系统"，规则如下：

装配线刚刚生产了一批长度为 {n} 的组件序列 S，序列中每个组件的规格参数为 {{R, G, B}}（即三种不同材质或尺寸的标准化零件）。这个生产序列是由机器内部一个未知的"模具转盘排布" P 循环加工并截断到长度 {n} 吐出的。转盘排布 P 的长度称为"最小周期" t，满足 2 到 8 之间。

你的目标是通过质检查询推断出完整的组件序列 S（或等价地反向推导出最小周期 t 和模具转盘排布 P）。你需要在尽可能少的停机抽检次数内完成产线溯源。

每次抽检查询只能包含一个标签，你可以使用以下两种检测指令：

1. **生产线抽样比对（前缀匹配查询）**：提供一个预测的组件序列 Q（长度在 1 到 {n} 之间），监测系统会反馈 Q 与实际出库序列 S 的最长公共前缀长度 K。即从第一个下线的零件起，Q 和 S 有多少个连续下线的组件规格完全吻合。

   格式示例（查询序列 "RGBR"）：
   <query_prefix>RGBR</query_prefix>

2. **转盘步长一致性校验（d-周期前缀查询）**：提供一个正整数 d，系统会反馈序列 S 的前缀中，最长的满足"间隔为 d 的组件规格皆一致"的流水线前缀长度 L。即找到最大的 L，使得对于所有 1 到 L 减 d 之间的流片位置 i，都有 S[i] 等于 S[i+d]。

   格式示例（查询 d=3）：
   <query_period>3</query_period>

完成溯源后，请提交最终产线报告。你可以选择以下两种方式之一：

1. **提交完整组件序列**：直接给出长度为 {n} 的完整出库序列。

   格式示例：
   <answer>sequence=RGBRGBRGB</answer>

2. **提交模具转盘排布描述**：给出最小周期 t 和对应的模具转盘排布 P（P 的长度必须等于 t）。

   格式示例：
   <answer>period=3, motif=RGB</answer>

注意：报告错误或格式不符，将导致整条产线安全锁死。每次只能提交一个查询或报告标签。
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
We are operating the "Automated Assembly Line Quality Monitoring System". The rules are as follows:

The assembly line has just produced a component sequence S of length {n}, where the specification parameter of each component is from {{R, G, B}} (representing three standardized parts of different materials or dimensions). This production sequence is generated by a machine internally circulating an unknown "mold carousel layout" P and truncating the output to length {n}. The length of the carousel layout P is called the "minimal period" t, which is between 2 and 8.

Your goal is to infer the complete component sequence S (or equivalently, reverse-engineer the minimal period t and the mold carousel layout P) through quality inspection queries. You need to complete the production line tracing with as few machine-stop sampling queries as possible.

Each sampling query must contain only one tag. You can use the following two inspection commands:

1. **Production Line Sampling Alignment (Prefix Match Query)**: Provide a predicted component sequence Q (length between 1 and {n}), and the monitoring system will return the longest common prefix length K between Q and the actual output sequence S. That is, how many consecutive components exactly match the specifications starting from the first part off the line.

   Format example (querying sequence "RGBR"):
   <query_prefix>RGBR</query_prefix>

2. **Carousel Step Consistency Check (d-Period Prefix Query)**: Provide a positive integer d, and the system will return the length L of the longest prefix of S that satisfies "all components with a distance of d have identical specifications". That is, find the maximum L such that for all flow positions i from 1 to L minus d, S[i] equals S[i+d].

   Format example (querying d=3):
   <query_period>3</query_period>

Once the tracing is complete, submit the final production report. You can choose one of the following two methods:

1. **Submit Complete Component Sequence**: Directly provide the complete output sequence of length {n}.

   Format example:
   <answer>sequence=RGBRGBRGB</answer>

2. **Submit Carousel Layout Description**: Provide the minimal period t and the corresponding mold carousel layout P (P's length must equal t).

   Format example:
   <answer>period=3, motif=RGB</answer>

Note: Incorrect report or invalid format will trigger a safety lock on the entire production line. Only one query or report tag can be submitted each time.
"""

    contextualized_rule_zh_5 = """\
我们正在使用"智能合规审查系统"进行案件梳理，规则如下：

法务部导入了一份长度为 {n} 的格式化合同条款序列 S，序列中每条条款的属性类别为 {{R, G, B}}（即权利赋权条款、义务约束条款、违约责任条款）。该合同由于采用标准化起草，其序列是由一套未知的"基础模板组合" P 循环嵌套并截断到长度 {n} 生成的。模板组合 P 的包含条款数称为"最小周期" t，满足 2 到 8 之间。

你的目标是通过合规检索推断出完整的合同条款序列 S（或等价地推断出最小周期 t 和基础模板组合 P）。你需要在尽可能少的审查指令下完成法务尽职调查。

每次审查查询只能包含一个标签，你可以使用以下两种检索指令：

1. **条款内容审查比对（前缀匹配查询）**：提供一个推测的条款属性序列 Q（长度在 1 到 {n} 之间），系统会反馈 Q 与真实合同序列 S 的最长公共前缀长度 K。即从第一条起，Q 和 S 有多少个连续条款的属性分类完全吻合。

   格式示例（查询序列 "RGBR"）：
   <query_prefix>RGBR</query_prefix>

2. **模板同构性检索（d-周期前缀查询）**：提供一个正整数 d，系统会反馈合同序列 S 的前缀中，最长的满足"间隔为 d 的条款属性皆一致"的有效条款前缀长度 L。即找到最大的 L，使得对于所有 1 到 L 减 d 之间的条款索引 i，都有 S[i] 等于 S[i+d]。

   格式示例（查询 d=3）：
   <query_period>3</query_period>

完成尽调后，请提交最终合规审查报告。你可以选择以下两种方式之一：

1. **提交完整条款序列**：直接给出长度为 {n} 的完整合同属性序列。

   格式示例：
   <answer>sequence=RGBRGBRGB</answer>

2. **提交基础模板描述**：给出最小周期 t 和对应的基础模板组合 P（P 的长度必须等于 t）。

   格式示例：
   <answer>period=3, motif=RGB</answer>

注意：报告定性错误或格式不符将导致法律风险预警并终止审查。每次只能提交一个查询或报告标签。
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
We are using the "Intelligent Compliance Review System" for case analysis. The rules are as follows:

The legal department has imported a formatted contract clause sequence S of length {n}, where the attribute category of each clause is from {{R, G, B}} (Rights enabling clause, Obligation binding clause, Breach of contract liability clause). Due to standardized drafting, this sequence is generated by cyclically nesting an unknown "base template combination" P and truncating it to length {n}. The number of clauses in template combination P is called the "minimal period" t, which is between 2 and 8.

Your goal is to infer the complete contract clause sequence S (or equivalently, infer the minimal period t and base template combination P) through compliance retrieval. You need to complete the legal due diligence with as few review commands as possible.

Each review query must contain only one tag. You can use the following two retrieval commands:

1. **Clause Content Review Alignment (Prefix Match Query)**: Provide an inferred clause attribute sequence Q (length between 1 and {n}), and the system will return the longest common prefix length K between Q and the actual contract sequence S. That is, how many consecutive clause attributes exactly match starting from the first clause.

   Format example (querying sequence "RGBR"):
   <query_prefix>RGBR</query_prefix>

2. **Template Isomorphism Retrieval (d-Period Prefix Query)**: Provide a positive integer d, and the system will return the length L of the longest valid clause prefix of S that satisfies "all clause attributes with a distance of d are identical". That is, find the maximum L such that for all clause indices i from 1 to L minus d, S[i] equals S[i+d].

   Format example (querying d=3):
   <query_period>3</query_period>

Once due diligence is complete, please submit the final compliance review report. You can choose one of the following two methods:

1. **Submit Complete Clause Sequence**: Directly provide the complete contract attribute sequence of length {n}.

   Format example:
   <answer>sequence=RGBRGBRGB</answer>

2. **Submit Base Template Description**: Provide the minimal period t and the corresponding base template combination P (P's length must equal t).

   Format example:
   <answer>period=3, motif=RGB</answer>

Note: Qualitative errors in the report or invalid formats will trigger a legal risk warning and terminate the review. Only one query or report tag can be submitted each time.
"""

    tags = ["answer", "query_prefix", "query_period"]

    reasoning_type = "归纳推理"
    data_structure = "序列"

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {"n": 8, "t": 2, "motif": "RG"},
            2: {"n": 12, "t": 3, "motif": "RGB"},
            3: {"n": 15, "t": 5, "motif": "RGBRG"},
            4: {"n": 20, "t": 6, "motif": "RGBGBR"},
            5: {"n": 24, "t": 8, "motif": "RGBGBRRG"},
        },
        "en": {
            1: {"n": 8, "t": 2, "motif": "RG"},
            2: {"n": 12, "t": 3, "motif": "RGB"},
            3: {"n": 15, "t": 5, "motif": "RGBRG"},
            4: {"n": 20, "t": 6, "motif": "RGBGBR"},
            5: {"n": 24, "t": 8, "motif": "RGBGBRRG"},
        },
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = self.config.difficulty

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        self.n = cfg["n"]
        self.t = cfg["t"]
        self.motif = cfg["motif"]
        
        full_repeats = (self.n // self.t) + 1
        self.sequence = (self.motif * full_repeats)[:self.n]
        
        self._game_info["n"] = self.n

    def _compute_lcp(self, q, s):
        lcp = 0
        for i in range(min(len(q), len(s))):
            if q[i] == s[i]:
                lcp += 1
            else:
                break
        return lcp

    def _compute_d_period_prefix(self, d):
        if d < 1:
            return 0
        
        L = min(d, self.n)
        
        while L < self.n:
            if self.sequence[L - d] == self.sequence[L]:
                L += 1
            else:
                break
        
        return L

    def evaluate(self, parsed_info):
        raw_ans = parsed_info["answer"].strip()
        
        
        if "sequence=" in raw_ans:
            try:
                seq_part = raw_ans.split("sequence=")[1].strip()
                seq_part = seq_part.split(",")[0].strip().upper()
                return seq_part == self.sequence
            except:
                return False
                
        elif "period=" in raw_ans and "motif=" in raw_ans:
            try:
                parts = [x.strip() for x in raw_ans.split(",")]
                ans_dict = {}
                for part in parts:
                    if "=" in part:
                        k, v = part.split("=", 1)
                        ans_dict[k.strip()] = v.strip()
                
                if "period" not in ans_dict or "motif" not in ans_dict:
                    return False
                
                period = int(ans_dict["period"])
                motif = ans_dict["motif"].upper()
                
                if period != self.t:
                    return False
                
                if motif != self.motif:
                    return False
                
                if len(motif) != period:
                    return False
                    
                return True
            except:
                return False
        else:
            return False

    def _cf_core_produce(self, parsed_info):
        
        if "query_prefix" in parsed_info:
            query_seq = parsed_info["query_prefix"].strip().upper()
            
            valid_chars = set("RGB")
            if not all(c in valid_chars for c in query_seq):
                raise ValueError(
                    "Query sequence contains invalid characters. Only R, G, B are allowed."
                    if self.config.language == "en" else
                    "查询序列包含无效字符，仅允许 R、G、B。"
                )
            
            if len(query_seq) < 1 or len(query_seq) > self.n:
                raise ValueError(
                    f"Query sequence length must be between 1 and {self.n}."
                    if self.config.language == "en" else
                    f"查询序列长度必须在 1 到 {self.n} 之间。"
                )
            
            lcp = self._compute_lcp(query_seq, self.sequence)
            return str(lcp)
        
        elif "query_period" in parsed_info:
            try:
                d = int(parsed_info["query_period"].strip())
            except ValueError:
                raise ValueError(
                    "d must be a valid integer."
                    if self.config.language == "en" else
                    "d 必须是有效的整数。"
                )
            
            if d < 1:
                raise ValueError(
                    "d must be a positive integer."
                    if self.config.language == "en" else
                    "d 必须是正整数。"
                )
            
            L = self._compute_d_period_prefix(d)
            return str(L)
        
        else:
            raise ValueError("No valid query tag found.")

    def _cf_make_wrong(self, correct: str) -> str:
        try:
            val = int(correct)
            offset = random.choice([-3, -2, -1, 1, 2, 3])
            wrong_val = val + offset
            wrong_val = max(0, min(self.n, wrong_val))
            if wrong_val == val:
                wrong_val = (val + 1) if val < self.n else (val - 1)
            return str(wrong_val)
        except (ValueError, TypeError):
            return "0"

    def get_all_possible_queries(self) -> list[dict]:
        results = []
        
        for d in range(1, self.n + 1):
            ans = self._compute_d_period_prefix(d)
            results.append({
                "query": f"<query_period>{d}</query_period>",
                "answer": str(ans)
            })

        for length in range(1, self.n + 1):
            prefix = self.sequence[:length]
            ans = self._compute_lcp(prefix, self.sequence)
            results.append({
                "query": f"<query_prefix>{prefix}</query_prefix>",
                "answer": str(ans)
            })
            
        for i in range(min(self.t, self.n)):
            correct_char = self.sequence[i]
            prefix_so_far = self.sequence[:i]
            for char in ["R", "G", "B"]:
                if char != correct_char:
                    test_prefix = prefix_so_far + char
                    ans = self._compute_lcp(test_prefix, self.sequence)
                    results.append({
                        "query": f"<query_prefix>{test_prefix}</query_prefix>",
                        "answer": str(ans)
                    })
                
        return results