Structural property violated: distance sums for different residue classes are not all distinct. sums: {0: 19, 1: 18, 2: 18}

# -*- coding: utf-8 -*-
# 自动生成 | 模型: api/gemini-3-pro-preview
# 推理类型: 归纳推理（完全自主总结规律）：从多次反馈的样本中，总结出背后隐藏的规律/模式。例如猜拳游戏，模型需要总结对手出拳的模式。
# 数据结构: 图：存在一个由节点和边构成的图。
# 知识点:   单源距离和：从某节点到所有其他节点的最短距离之和是多少
# ============================================================

import random
from collections import deque
from .base import Game


class ModularGraphDistanceSumGame(Game):

    reasoning_type = "归纳推理"
    data_structure = "图"

    game_rule_zh = """\
我们来玩一个"模图距离和推理"游戏，规则如下：

游戏设定了一个无向图，其节点编号为 0 到 {n_minus_1}（共 {n} 个节点）。所有索引和加减运算均按模 {n} 计算。

图的结构由以下规则生成（但具体参数对你隐藏）：

1. **基础边**：对每个节点 i，都连有边 (i, i+1) 和 (i, i-1)。
2. **周期性增广边**：存在一个未知的周期 r（2 到 8 之间的整数，且 r 是 {n} 的因子）以及一个未知的数组 L，长度为 r。数组中每个元素 L[c] 是一个介于 2 到 {max_step} 之间的整数。对于任意节点 i，还会连接边 (i, i+L[i mod r]) 和 (i, i-L[i mod r])（这些边与基础边不重合）。
3. 图保证连通。

定义：
- 两个节点 u 和 v 之间的**距离** dist(u,v) 为它们之间的最短路径边数。
- 节点 u 的**距离和** Σ(u) 定义为：对所有不等于 u 的节点 v，dist(u,v) 的总和。

结构性质：
- 如果两个节点 u 和 v 满足 u 除以 r 的余数等于 v 除以 r 的余数，那么 Σ(u) = Σ(v)。
- 不同余数对应的 Σ 值两两不同。

游戏目标：我已经选定了一个特殊节点 S = {target_node}，你需要推断出 Σ(S) 的值。

你可以使用以下三类查询（每类查询有额度限制）：

1. **步长查询**：询问节点 u 对应的增广步长。返回 L[u mod r] 的值。
   - 额度：最多 {quota_step} 次
   
2. **距离查询**：询问节点 u 和节点 v 之间的最短路径距离。返回 dist(u,v)。
   - 额度：最多 {quota_dist} 次
   
3. **距离和查询**：询问节点 u 的距离和。返回 Σ(u)。
   - 限制：不能查询 u = S
   - 额度：最多 {quota_sum} 次

当你收集到足够信息后，请提交你推断的 Σ(S) 值。如果答案错误或超出查询额度，游戏失败。

## 查询与提交答案的格式

每次查询只能包含一个标签，使用以下 XML 格式：

- 步长查询（例如查询节点 5）：
<query_step>5</query_step>

- 距离查询（例如查询节点 3 到节点 7 的距离）：
<query_dist>3,7</query_dist>

- 距离和查询（例如查询节点 2 的距离和）：
<query_sum>2</query_sum>

提交最终答案时，格式如下（X 为你推断的整数值）：
<answer>X</answer>
"""

    game_rule_en = """\
Let's play a "Modular Graph Distance Sum Inference" game. Here are the rules:

The game defines an undirected graph with nodes numbered from 0 to {n_minus_1} (total {n} nodes). All index and arithmetic operations are performed modulo {n}.

The graph structure is generated by the following rules (but specific parameters are hidden from you):

1. **Base edges**: For each node i, there are edges (i, i+1) and (i, i-1).
2. **Periodic augmented edges**: There exists an unknown period r (an integer between 2 and 8, and r divides {n}) and an unknown array L of length r. Each element L[c] is an integer between 2 and {max_step}. For any node i, additional edges (i, i+L[i mod r]) and (i, i-L[i mod r]) are added (these edges do not overlap with base edges).
3. The graph is guaranteed to be connected.

Definitions:
- The **distance** dist(u,v) between two nodes u and v is the number of edges in their shortest path.
- The **distance sum** Σ(u) of node u is defined as: the sum of dist(u,v) for all nodes v not equal to u.

Structural property:
- If two nodes u and v satisfy that u modulo r equals v modulo r, then Σ(u) = Σ(v).
- Distance sums for different residue classes are all distinct.

Game objective: I have selected a special node S = {target_node}, and you need to infer the value of Σ(S).

You can use the following three types of queries (each type has a quota limit):

1. **Step query**: Ask for the augmented step length corresponding to node u. Returns the value of L[u mod r].
   - Quota: at most {quota_step} times
   
2. **Distance query**: Ask for the shortest path distance between node u and node v. Returns dist(u,v).
   - Quota: at most {quota_dist} times
   
3. **Distance sum query**: Ask for the distance sum of node u. Returns Σ(u).
   - Restriction: cannot query u = S
   - Quota: at most {quota_sum} times

When you have collected enough information, submit your inferred value of Σ(S). If the answer is incorrect or you exceed any query quota, the game fails.

## Query and Answer Format

Each query must contain only one tag, using the following XML format:

- Step query (e.g., querying node 5):
<query_step>5</query_step>

- Distance query (e.g., querying distance from node 3 to node 7):
<query_dist>3,7</query_dist>

- Distance sum query (e.g., querying distance sum of node 2):
<query_sum>2</query_sum>

When submitting the final answer, use this format (X is your inferred integer value):
<answer>X</answer>
"""

    contextualized_rule_zh_1 = """\
欢迎使用“环线交通枢纽效能评估系统”。

本系统模拟了一个环状交通网络，包含从 0 到 {n_minus_1} 的 {n} 个站点。所有站点编号和站点间的增减运算均按模 {n} 的环形规则计算。

该交通网络的线路分布由以下规则自动生成（核心参数已对您加密）：

1. **基础慢线**：对每个站点 i，都开通了直达相邻站点 (i, i+1) 和 (i, i-1) 的普通公交线路。
2. **周期性快速公交（BRT）线**：城市划分为未知的交通大区，形成一个周期 r（2 到 8 之间的整数，且 r 是 {n} 的因数）。同时存在一个未知的跨区站距数组 L，长度为 r。数组中的每个跨站距 L[c] 是一个介于 2 到 {max_step} 之间的整数。对于任意站点 i，系统额外开通了跨度为 L[i mod r] 的双向快速公交线路，即连接站点 (i, i+L[i mod r]) 和 (i, i-L[i mod r])（这些线路与基础慢线不重合）。
3. 整个交通网络保证全线贯通。

系统效能指标定义：
- 两个站点 u 和 v 之间的**通勤耗时** dist(u,v) 为它们之间所需的最少乘车区间数（最短路线所经历的线路段数）。
- 站点 u 的**全局通勤负担** Σ(u) 定义为：从该站点前往其他所有不同站点 v 的通勤耗时总和。

管网结构性质：
- 如果两个站点 u 和 v 在交通大区划分中的相对位置（即除以 r 的余数）相同，那么它们的全局通勤负担 Σ(u) = Σ(v)。
- 不同相对位置站点的 Σ 值各不相同。

评估目标：指挥中心已指定了一个拟建核心枢纽站点 S = {target_node}，您需要推断出该枢纽的全局通勤负担 Σ(S) 值。

您可以使用指挥系统的以下三种查询指令（各指令有调用配额限制）：

1. **跨站距查询**：询问站点 u 对应的 BRT 跨站步长。返回 L[u mod r] 的值。
   - 配额：最多 {quota_step} 次
   
2. **通勤耗时查询**：询问站点 u 和站点 v 之间的最少乘车区间数。返回 dist(u,v)。
   - 配额：最多 {quota_dist} 次
   
3. **全局负担查询**：询问站点 u 的全局通勤负担。返回 Σ(u)。
   - 限制：不允许查询目标站点 u = S
   - 配额：最多 {quota_sum} 次

当您通过指令收集到充分的交通数据后，请提交您推算的 Σ(S) 值。如果计算错误或超出系统查询配额，评估任务失败。

## 查询与提交结果的系统指令格式

每次系统交互仅允许包含一个指令标签，请严格使用以下 XML 格式：

- 跨站距查询（例如查询站点 5 的 BRT 跨度）：
<query_step>5</query_step>

- 通勤耗时查询（例如查询站点 3 到站点 7 的区间数）：
<query_dist>3,7</query_dist>

- 全局负担查询（例如查询站点 2 的通勤负担）：
<query_sum>2</query_sum>

提交最终评估结果时，格式如下（X 为您推算的整数结果）：
<answer>X</answer>
"""

    contextualized_rule_en_1 = """\
[Transportation Scenario]
Welcome to the "Ring Line Transit Hub Efficiency Assessment System".

This system simulates a circular transportation network comprising {n} stations numbered from 0 to {n_minus_1}. All station IDs and arithmetic operations are performed under a modulo {n} circular rule.

The network layout is generated by the following rules (with core parameters encrypted):

1. **Base Local Lines**: For each station i, local bus routes connect to adjacent stations (i, i+1) and (i, i-1).
2. **Periodic Bus Rapid Transit (BRT) Lines**: The city is divided into transit zones forming an unknown period r (an integer between 2 and 8, where r divides {n}). There is also an unknown span array L of length r. Each element L[c] is an integer ranging from 2 to {max_step}. For any station i, additional bidirectional BRT routes are established with a span of L[i mod r], linking stations (i, i+L[i mod r]) and (i, i-L[i mod r]) (these routes do not overlap with local lines).
3. The transit network is guaranteed to be fully connected.

System Efficiency Metrics:
- The **commute time** dist(u,v) between two stations u and v is the minimum number of transit segments (edges) in their shortest route.
- The **global commute burden** Σ(u) of station u is defined as: the sum of the commute times to all other distinct stations v.

Structural Properties:
- If two stations u and v share the same relative zone position (i.e., u modulo r equals v modulo r), their global commute burden is identical: Σ(u) = Σ(v).
- The Σ values for different relative positions are distinctly unique.

Assessment Objective: The command center has designated a proposed core hub station S = {target_node}. You must infer the value of Σ(S) for this hub.

You may use the following three types of system queries (subject to strict quotas):

1. **Span Query**: Inquire about the BRT route span originating from station u. Returns the value of L[u mod r].
   - Quota: Maximum {quota_step} times
   
2. **Commute Time Query**: Inquire about the minimum transit segments between station u and station v. Returns dist(u,v).
   - Quota: Maximum {quota_dist} times
   
3. **Global Burden Query**: Inquire about the global commute burden of station u. Returns Σ(u).
   - Restriction: You cannot query the target station u = S.
   - Quota: Maximum {quota_sum} times

Once you have gathered sufficient transit data, please submit your calculated value for Σ(S). The assessment fails if your answer is incorrect or if you exceed any query quotas.

## Command Format for Queries and Submission

Each interaction must contain only one command tag, strictly adhering to the following XML format:

- Span Query (e.g., querying the BRT span for station 5):
<query_step>5</query_step>

- Commute Time Query (e.g., querying transit segments from station 3 to station 7):
<query_dist>3,7</query_dist>

- Global Burden Query (e.g., querying the commute burden of station 2):
<query_sum>2</query_sum>

When submitting your final assessment result, use this format (where X is your calculated integer):
<answer>X</answer>
"""

    contextualized_rule_zh_2 = """\
欢迎登录“大型综合医院物流调度规划系统”。

本系统模拟了一个环形医疗建筑群，包含从 0 到 {n_minus_1} 的 {n} 个科室/病区。所有科室编号和距离运算均按模 {n} 的环形结构计算。

院内物资传输网络的布局由以下规则生成（具体参数出于安全保密已隐去）：

1. **基础步行走廊**：对每个科室 i，都建有连接相邻科室 (i, i+1) 和 (i, i-1) 的普通走廊。
2. **周期性气动物流管网**：医院被划分为若干个标准医疗组团，形成一个未知的组团周期 r（2 到 8 之间的整数，且 r 是 {n} 的因数）。存在一个未知的管网跨度数组 L，长度为 r。数组中每个跨度 L[c] 是介于 2 到 {max_step} 之间的整数。对于任意科室 i，系统还铺设了专用的双向气动物流管道，直通科室 (i, i+L[i mod r]) 和 (i, i-L[i mod r])（此管网与普通走廊不重合）。
3. 整个传输网络保证各个科室均可连通。

物流调度指标定义：
- 两个科室 u 和 v 之间的**物流中转次数** dist(u,v) 为它们之间所需的最少管网或走廊段数（最短传输路径）。
- 科室 u 的**全局配送负荷** Σ(u) 定义为：从该科室向其他所有不同科室 v 发送物资的物流中转次数总和。

建筑结构性质：
- 如果两个科室 u 和 v 在医疗组团中的相对顺位（即除以 r 的余数）相同，那么它们的全局配送负荷 Σ(u) = Σ(v)。
- 不同相对顺位科室的 Σ 值互不相同。

规划目标：院方计划设立一个新型中央药房 S = {target_node}，您需要推断出该药房的全局配送负荷 Σ(S) 值。

您可以调用以下三类系统接口进行调研（各接口有调用次数限制）：

1. **管网跨度查询**：询问科室 u 对应的气动物流直达跨度。返回 L[u mod r] 的值。
   - 额度：最多 {quota_step} 次
   
2. **中转次数查询**：询问科室 u 和科室 v 之间的最少中转段数。返回 dist(u,v)。
   - 额度：最多 {quota_dist} 次
   
3. **配送负荷查询**：询问科室 u 的全局配送负荷。返回 Σ(u)。
   - 限制：禁止直接查询目标药房 u = S
   - 额度：最多 {quota_sum} 次

当您收集到足够的网络数据后，请提交您推算的 Σ(S) 值。若计算错误或超出接口额度，规划任务将被判定为失败。

## 接口查询与结果提交格式

每次调用只能包含一个数据标签，请使用以下 XML 格式：

- 管网跨度查询（例如查询科室 5 的气动物流跨度）：
<query_step>5</query_step>

- 中转次数查询（例如查询科室 3 到科室 7 的传输段数）：
<query_dist>3,7</query_dist>

- 配送负荷查询（例如查询科室 2 的配送负荷）：
<query_sum>2</query_sum>

提交最终规划结果时，格式如下（X 为您推算的整数负荷值）：
<answer>X</answer>
"""

    contextualized_rule_en_2 = """\
[Healthcare Scenario]
Welcome to the "General Hospital Logistics Dispatch Planning System".

This system models a circular hospital complex containing {n} departments/wards numbered from 0 to {n_minus_1}. All department IDs and spatial calculations follow a modulo {n} circular layout.

The medical material transport network is governed by the following rules (with specific parameters classified for security):

1. **Base Pedestrian Corridors**: For each department i, standard corridors connect to adjacent departments (i, i+1) and (i, i-1).
2. **Periodic Pneumatic Tube Systems**: The hospital is organized into standard medical clusters, yielding an unknown period r (an integer between 2 and 8, where r divides {n}). There is also an unknown span array L of length r. Each span L[c] is an integer ranging from 2 to {max_step}. For any department i, dedicated bidirectional pneumatic tubes are installed, directly linking departments (i, i+L[i mod r]) and (i, i-L[i mod r]) (these tubes are distinct from pedestrian corridors).
3. The transport network is fully interconnected, reaching every department.

Logistics Dispatch Metrics:
- The **transport transit count** dist(u,v) between two departments u and v is the minimum number of tube or corridor segments required for transit (the shortest path).
- The **global delivery load** Σ(u) of department u is defined as: the total transport transit count to deliver materials to all other distinct departments v.

Architectural Properties:
- If two departments u and v share the same relative position within their medical clusters (i.e., modulo r remainders are equal), their global delivery load is identical: Σ(u) = Σ(v).
- The Σ values across different relative positions are completely unique.

Planning Objective: The hospital administration plans to establish a new central pharmacy S = {target_node}. You need to infer the value of Σ(S) for this pharmacy.

You may invoke the following three types of system interfaces for your investigation (each subject to a quota):

1. **Tube Span Query**: Inquire about the pneumatic tube bypass span originating from department u. Returns the value of L[u mod r].
   - Quota: Maximum {quota_step} times
   
2. **Transit Count Query**: Inquire about the minimum transit segments between department u and department v. Returns dist(u,v).
   - Quota: Maximum {quota_dist} times
   
3. **Delivery Load Query**: Inquire about the global delivery load of department u. Returns Σ(u).
   - Restriction: Direct queries for the target pharmacy u = S are prohibited.
   - Quota: Maximum {quota_sum} times

Upon collecting sufficient network data, submit your calculated value for Σ(S). The planning task fails if the calculation is incorrect or any interface quota is exceeded.

## Interface Query and Submission Format

Each API call must contain exactly one data tag, formatted in XML:

- Tube Span Query (e.g., querying the tube span for department 5):
<query_step>5</query_step>

- Transit Count Query (e.g., querying transit segments from department 3 to 7):
<query_dist>3,7</query_dist>

- Delivery Load Query (e.g., querying the delivery load of department 2):
<query_sum>2</query_sum>

When submitting your final planned load, use this format (where X is your inferred integer):
<answer>X</answer>
"""

    contextualized_rule_zh_3 = """\
欢迎进入“认知负荷与课程体系图谱分析平台”。

本平台构建了一个环形的学科知识网络，包含从 0 到 {n_minus_1} 的 {n} 个核心知识模块。所有模块编号和学习跨度的推演均按模 {n} 规则循环计算。

该课程图谱的认知路径由以下教学法规则生成（系统内禀参数已隐藏）：

1. **基础递进路径**：针对每个知识模块 i，都存在与相邻模块 (i, i+1) 和 (i, i-1) 直接关联的标准前置与后继学习路径。
2. **周期性认知跳跃路径**：课程体系被划分为未知的教学主题周期 r（2 到 8 之间的整数，且 r 是 {n} 的约数）。同时设定了一个未知的认知跨度数组 L，长度为 r。数组中每个跨度 L[c] 介于 2 到 {max_step} 之间。对于任意模块 i，教学大纲设计了跨学科的联结路径，允许学习者直接跳跃至模块 (i, i+L[i mod r]) 和 (i, i-L[i mod r])（这些跳跃路径是对基础路径的额外扩充）。
3. 课程图谱保证所有知识模块均连通，不存在孤立知识点。

学习效能指标定义：
- 两个模块 u 和 v 之间的**认知距离** dist(u,v) 为理解这两者所需经历的最少关联路径数（最短推导步骤）。
- 模块 u 的**综合认知负荷** Σ(u) 定义为：从该模块出发，推导和关联到其他所有不同模块 v 的认知距离总和。

教学结构性质：
- 如果两个模块 u 和 v 在教学主题周期中的特征节拍相同（即除以 r 的余数相等），那么它们的综合认知负荷 Σ(u) = Σ(v)。
- 不同特征节拍模块的 Σ 值必定各不相同。

分析目标：教学委员会指定了一个需要重点评估的“顶点综合课程”模块 S = {target_node}，您需要推演出该核心模块的综合认知负荷 Σ(S) 值。

您可以调用以下三类学术评估指令（存在调用次数限制）：

1. **认知跨度查询**：询问模块 u 对应的跳跃学习跨度。返回 L[u mod r] 的值。
   - 额度：最多 {quota_step} 次
   
2. **认知距离查询**：询问模块 u 和模块 v 之间的最少推导步骤。返回 dist(u,v)。
   - 额度：最多 {quota_dist} 次
   
3. **综合负荷查询**：询问模块 u 的综合认知负荷。返回 Σ(u)。
   - 限制：禁止直接查询目标顶点模块 u = S
   - 额度：最多 {quota_sum} 次

当您通过指令获取足够的图谱结构信息后，请提交您推算的 Σ(S) 值。若结论错误或探测超载，分析任务将被强制终止。

## 指令调用与结果汇报格式

每次查询只能包含一个指令标签，使用如下 XML 格式：

- 认知跨度查询（例如探测模块 5 的跳跃跨度）：
<query_step>5</query_step>

- 认知距离查询（例如探测模块 3 到模块 7 的推导步骤）：
<query_dist>3,7</query_dist>

- 综合负荷查询（例如探测模块 2 的认知负荷）：
<query_sum>2</query_sum>

提交最终图谱分析报告时，格式如下（X 为您推导的整数负荷值）：
<answer>X</answer>
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Welcome to the "Cognitive Load and Curriculum Graph Analysis Platform".

This platform models a cyclical disciplinary knowledge network containing {n} core modules numbered from 0 to {n_minus_1}. All module IDs and learning progression spans are calculated via modulo {n} rules.

The cognitive pathways within this curriculum graph are established by the following pedagogical rules (with intrinsic parameters concealed):

1. **Base Progression Paths**: For each knowledge module i, standard prerequisite and successor links connect adjacent modules (i, i+1) and (i, i-1).
2. **Periodic Cognitive Leap Paths**: The curriculum is divided into unknown thematic cycles of period r (an integer between 2 and 8, where r divides {n}). Additionally, there is an unknown cognitive span array L of length r. Each span L[c] ranges from 2 to {max_step}. For any module i, interdisciplinary connections enable a direct cognitive leap to modules (i, i+L[i mod r]) and (i, i-L[i mod r]) (these leap paths augment the base progression).
3. The curriculum graph guarantees that all knowledge modules are fully interconnected, leaving no isolated concepts.

Learning Efficiency Metrics:
- The **cognitive distance** dist(u,v) between two modules u and v represents the minimum number of associative paths (shortest derivation steps) required to conceptualize the link between them.
- The **aggregate cognitive load** Σ(u) of module u is defined as: the total cognitive distance required to relate this module to all other distinct modules v.

Pedagogical Structural Properties:
- If modules u and v share the same rhythmic beat within the thematic cycle (i.e., modulo r remainders are equal), their aggregate cognitive load is identical: Σ(u) = Σ(v).
- The Σ values for different rhythmic beats are strictly distinct.

Analysis Objective: The academic committee has designated a critical "capstone synthesis" module S = {target_node}. You must deduce the aggregate cognitive load Σ(S) for this module.

You may employ the following three academic assessment commands (subject to usage limits):

1. **Cognitive Span Query**: Inquire about the leap span linked to module u. Returns the value of L[u mod r].
   - Quota: Maximum {quota_step} times
   
2. **Cognitive Distance Query**: Inquire about the minimum derivation steps between module u and module v. Returns dist(u,v).
   - Quota: Maximum {quota_dist} times
   
3. **Aggregate Load Query**: Inquire about the aggregate cognitive load of module u. Returns Σ(u).
   - Restriction: Direct queries for the target capstone module u = S are restricted.
   - Quota: Maximum {quota_sum} times

Upon successfully mapping the graph's structure, please submit your calculated value for Σ(S). The analysis will be terminated if your deduction is flawed or if you exceed your command quotas.

## Command Invocation and Reporting Format

Each query must include exactly one command tag, using the following XML format:

- Cognitive Span Query (e.g., probing the leap span of module 5):
<query_step>5</query_step>

- Cognitive Distance Query (e.g., probing derivation steps between modules 3 and 7):
<query_dist>3,7</query_dist>

- Aggregate Load Query (e.g., probing the cognitive load of module 2):
<query_sum>2</query_sum>

When submitting your final graph analysis report, use this format (where X is your deduced integer value):
<answer>X</answer>
"""

    contextualized_rule_zh_4 = """\
欢迎接入“柔性制造车间物流拓扑计算终端”。

本终端正在监控一条闭环的自动化流水线，分布着从 0 到 {n_minus_1} 的 {n} 个加工工位。工位的编码定址和物流路由计算皆依循模 {n} 的环形法则。

车间的物料传送网络依据以下物理拓扑规则搭建（系统关键参数目前处于锁定状态）：

1. **基础履带线**：对每个工位 i，均配有直达相邻工位 (i, i+1) 和 (i, i-1) 的标准化传输履带。
2. **周期性 AGV 快速轨道**：车间产线被划分为具备特定周期的生产单元组合，存在一个未知的单元周期 r（2 到 8 之间的整数，且 r 是 {n} 的因数）。系统中设有一个未知的跨站运行数组 L，长度为 r。数组中每个跨站参数 L[c] 为 2 到 {max_step} 之间的整数。对于任意工位 i，空中悬挂式 AGV 提供直接跳跃到工位 (i, i+L[i mod r]) 和 (i, i-L[i mod r]) 的快速配送服务（此轨道独立于基础履带）。
3. 拓扑网络具有自适应性，保证所有工位间的物流连通。

物流延迟评估指标：
- 两个工位 u 和 v 之间的**路由跳数** dist(u,v) 为物流件在这两个工位间流转所需的最少传送段数（最短路径）。
- 工位 u 的**全局物流延时** Σ(u) 定义为：将零部件从该工位分发至其他所有不同工位 v 的路由跳数总和。

生产单元结构特性：
- 如果两个工位 u 和 v 在生产单元组合中的逻辑位置（即除以 r 的余数）一致，则它们的全局物流延时 Σ(u) = Σ(v)。
- 不同逻辑位置的工位，其 Σ 值具有唯一性且各不相同。

计算目标：工程部计划对一个关键的“成品终检工位” S = {target_node} 进行产能核算，您需要推断出该工位的全局物流延时 Σ(S) 值。

您可以通过终端发起以下三类诊断轮询（受限于系统通信带宽配额）：

1. **跨站参数轮询**：询问工位 u 对应的 AGV 快速跳跃步长。返回 L[u mod r] 的值。
   - 带宽：最多 {quota_step} 次
   
2. **路由跳数轮询**：询问工位 u 和工位 v 之间的最少传送段数。返回 dist(u,v)。
   - 带宽：最多 {quota_dist} 次
   
3. **全局延时轮询**：询问工位 u 的全局物流延时。返回 Σ(u)。
   - 限制：系统防呆机制禁止直接查询终检工位 u = S
   - 带宽：最多 {quota_sum} 次

在提取了充分的拓扑特征后，请提交您的 Σ(S) 测算值。如果数据计算出现偏差或轮询超限，系统将触发异常报警并终结任务。

## 轮询与上报数据的终端格式

每次交互报文只能解析一个控制标签，请遵循标准 XML 格式：

- 跨站参数轮询（例如轮询工位 5 的 AGV 跨站步长）：
<query_step>5</query_step>

- 路由跳数轮询（例如轮询工位 3 到工位 7 的传送段数）：
<query_dist>3,7</query_dist>

- 全局延时轮询（例如轮询工位 2 的物流延时）：
<query_sum>2</query_sum>

上报最终产能核算数据时，使用如下格式（X 为您推导的整数延时值）：
<answer>X</answer>
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
Welcome to the "Flexible Manufacturing Floor Logistics Topology Terminal".

This terminal monitors a closed-loop automated assembly line featuring {n} workstations numbered from 0 to {n_minus_1}. All station addressing and routing calculations strictly adhere to modulo {n} circular logic.

The material handling network is constructed according to the following physical topology rules (critical parameters are currently locked):

1. **Base Conveyor Lines**: Standard motorized conveyors link every workstation i directly to its adjacent counterparts, (i, i+1) and (i, i-1).
2. **Periodic AGV Express Tracks**: The assembly line is segmented into production cell combinations with an unknown periodicity r (an integer between 2 and 8, where r divides {n}). An unknown bypass routing array L of length r is configured in the system. Each bypass parameter L[c] is an integer from 2 to {max_step}. For any workstation i, overhead Automated Guided Vehicles (AGVs) provide express delivery skipping to workstations (i, i+L[i mod r]) and (i, i-L[i mod r]) (these tracks operate independently of the base conveyors).
3. The topology network is adaptive and guarantees comprehensive logistical connectivity among all workstations.

Logistics Latency Evaluation Metrics:
- The **routing hops** dist(u,v) between two workstations u and v equals the minimum number of transfer segments required to move a part between them (the shortest path).
- The **global logistics latency** Σ(u) for workstation u is defined as: the aggregate routing hops required to distribute components from this station to all other distinct stations v.

Production Cell Structural Properties:
- If workstations u and v share the same logical alignment within their production cells (i.e., modulo r remainders are identical), their global logistics latency is the same: Σ(u) = Σ(v).
- The Σ values for different logical alignments are strictly unique.

Computation Objective: The engineering department is executing a capacity audit on a critical "Final Quality Control Station" S = {target_node}. You must infer the global logistics latency Σ(S) for this station.

You may initiate the following three types of diagnostic polls via the terminal (subject to bandwidth quotas):

1. **Bypass Parameter Poll**: Query the AGV express leap span associated with workstation u. Returns the value of L[u mod r].
   - Bandwidth: Maximum {quota_step} times
   
2. **Routing Hops Poll**: Query the minimum transfer segments between workstation u and workstation v. Returns dist(u,v).
   - Bandwidth: Maximum {quota_dist} times
   
3. **Global Latency Poll**: Query the global logistics latency of workstation u. Returns Σ(u).
   - Restriction: The system's mistake-proofing mechanism prevents direct polling of the QC station u = S.
   - Bandwidth: Maximum {quota_sum} times

Once sufficient topology characteristics have been extracted, submit your calculated value for Σ(S). If your calculation deviates or if polling limits are exceeded, the system will trigger a fault alarm and terminate the task.

## Terminal Format for Polling and Reporting

Each communication packet must parse only one control tag, adhering to standard XML formatting:

- Bypass Parameter Poll (e.g., polling the AGV leap span of workstation 5):
<query_step>5</query_step>

- Routing Hops Poll (e.g., polling transfer segments between workstations 3 and 7):
<query_dist>3,7</query_dist>

- Global Latency Poll (e.g., polling the logistics latency of workstation 2):
<query_sum>2</query_sum>

When reporting the final capacity audit data, use this format (where X is your derived integer latency):
<answer>X</answer>
"""

    contextualized_rule_zh_5 = """\
欢迎使用“司法判例援引深度与法理网络检索系统”。

本系统收录了一个闭环式的法理知识图谱，包含编号从 0 到 {n_minus_1} 的 {n} 个核心判例。所有判例索引与法理延伸跨度均依照模 {n} 规则进行推演。

该判例引用网络的法理逻辑由以下规则构成（核心分类权重对普通用户隐藏）：

1. **基础递进援引**：对于每一个判例 i，均存在依据时间或基础分类对相邻判例 (i, i+1) 和 (i, i-1) 的直接程序性援引。
2. **周期性法理穿透援引**：判例库按特定的法理精神（如违宪审查、衡平原则等）被划分为周期为 r 的主题集群（r 是 2 到 8 之间的整数，且为 {n} 的公因数）。系统中设有一个未知的法理跨度数组 L，长度为 r。数组中每个跨度值 L[c] 为 2 到 {max_step} 之间的整数。对于任意判例 i，存在基于深层法理原则跳跃关联到判例 (i, i+L[i mod r]) 和 (i, i-L[i mod r]) 的穿透性援引（该援引路径与基础递进相互独立）。
3. 知识图谱具备完备性，确保所有核心判例在法理逻辑上均可连通。

判例检索指标定义：
- 判例 u 与判例 v 之间的**援引链条长度** dist(u,v) 是在法庭辩论中，建立两者合法关联所需的最少援引层数（即图谱中的最短路径）。
- 判例 u 的**全局法理深度** Σ(u) 定义为：从该判例出发，建立与所有其他不同判例 v 的合法关联所需的援引链条长度总和。

法理结构特性：
- 倘若判例 u 和判例 v 在主题集群中的法理落脚点（即除以 r 的余数）一致，则它们具有等同的全局法理深度 Σ(u) = Σ(v)。
- 属于不同法理落脚点的判例，其 Σ 值必然各不相同。

检索目标：首席大法官指定了一个具有深远影响的“里程碑判例” S = {target_node}，您需要推断出该核心判例的全局法理深度 Σ(S) 的精确值。

您可以调用以下三类高级检索卷宗指令（受限于系统算力配额）：

1. **法理跨度检索**：调取判例 u 对应的穿透性法理跳跃跨度。返回 L[u mod r] 的值。
   - 配额：最多 {quota_step} 次
   
2. **援引链条检索**：调取判例 u 和判例 v 之间的最少援引层数。返回 dist(u,v)。
   - 配额：最多 {quota_dist} 次
   
3. **全局深度检索**：调取判例 u 的全局法理深度。返回 Σ(u)。
   - 限制：司法保密协议禁止直接查询目标判例 u = S
   - 配额：最多 {quota_sum} 次

在获取了充分的引用网络数据后，请提交您的 Σ(S) 推断结果。如果逻辑推演错误或指令调用超出配额，检索任务将被宣告无效。

## 检索卷宗与提交裁决结果的格式

每次系统提交仅限使用一个动作标签，请严格遵循下列 XML 规范：

- 法理跨度检索（例如调取判例 5 的跳跃跨度）：
<query_step>5</query_step>

- 援引链条检索（例如调取判例 3 与判例 7 的援引层数）：
<query_dist>3,7</query_dist>

- 全局深度检索（例如调取判例 2 的法理深度）：
<query_sum>2</query_sum>

提交最终里程碑判例深度裁决时，请按如下格式（X 为您推演的整数结果）：
<answer>X</answer>
"""

    contextualized_rule_en_5 = """\
[Law Scenario]
Welcome to the "Judicial Precedent Citation Depth and Jurisprudence Network Retrieval System".

This system archives a closed-loop jurisprudence knowledge graph encompassing {n} core precedents numbered from 0 to {n_minus_1}. All precedent indexing and legal extension spans are calculated according to modulo {n} rules.

The jurisprudential logic of this citation network is structured by the following principles (core categorization weights are concealed from standard users):

1. **Base Progressive Citations**: For each precedent i, there exists a direct procedural citation to adjacent precedents (i, i+1) and (i, i-1) based on chronology or basic categorization.
2. **Periodic Jurisprudential Penetration Citations**: The precedent database is classified into thematic clusters according to specific legal doctrines (e.g., constitutional review, principles of equity) forming a period r (an integer between 2 and 8, where r is a common factor of {n}). The system features an unknown jurisprudential span array L of length r. Each span value L[c] is an integer between 2 and {max_step}. For any precedent i, penetrating citations jump to connect precedents (i, i+L[i mod r]) and (i, i-L[i mod r]) based on deep legal principles (these citation paths are independent of base progressions).
3. The knowledge graph maintains completeness, ensuring that all core precedents are legally interconnected.

Precedent Retrieval Metrics:
- The **citation chain length** dist(u,v) between precedent u and precedent v is the minimum number of citation tiers required to legally correlate them during a court argument (i.e., the shortest path in the graph).
- The **global jurisprudential depth** Σ(u) of precedent u is defined as: the aggregate citation chain length required to legally correlate this precedent with all other distinct precedents v.

Jurisprudential Structural Properties:
- If precedents u and v share the same legal footing within their thematic clusters (i.e., their modulo r remainders are identical), they possess an equivalent global jurisprudential depth: Σ(u) = Σ(v).
- Precedents belonging to different legal footings unequivocally have unique Σ values.

Retrieval Objective: The Chief Justice has designated a profoundly impactful "Landmark Precedent" S = {target_node}. You are required to deduce the precise value of the global jurisprudential depth Σ(S) for this core precedent.

You may execute the following three advanced dossier retrieval commands (subject to computational quotas):

1. **Jurisprudential Span Retrieval**: Extract the penetrating legal leap span corresponding to precedent u. Returns the value of L[u mod r].
   - Quota: Maximum {quota_step} times
   
2. **Citation Chain Retrieval**: Extract the minimum citation tiers between precedent u and precedent v. Returns dist(u,v).
   - Quota: Maximum {quota_dist} times
   
3. **Global Depth Retrieval**: Extract the global jurisprudential depth of precedent u. Returns Σ(u).
   - Restriction: Judicial confidentiality protocols prohibit direct queries regarding the target precedent u = S.
   - Quota: Maximum {quota_sum} times

Upon acquiring sufficient citation network data, submit your inferred result for Σ(S). The retrieval task will be invalidated if your logical deduction is flawed or if command quotas are exceeded.

## Formatting for Dossier Retrieval and Ruling Submission

Each system submission is restricted to a single action tag, strictly adhering to the following XML specifications:

- Jurisprudential Span Retrieval (e.g., extracting the leap span for precedent 5):
<query_step>5</query_step>

- Citation Chain Retrieval (e.g., extracting citation tiers between precedents 3 and 7):
<query_dist>3,7</query_dist>

- Global Depth Retrieval (e.g., extracting the jurisprudential depth of precedent 2):
<query_sum>2</query_sum>

When submitting your final ruling on the landmark precedent's depth, use the format below (where X is your deduced integer result):
<answer>X</answer>
"""

    tags = ["answer", "query_step", "query_dist", "query_sum"]

    # 难度配置：
    # 1 (简单)       - N=12, r=3, 步长查询12次, 距离查询3次, 距离和查询2次
    # 2 (中等偏下)   - N=16, r=4, 步长查询12次, 距离查询3次, 距离和查询2次
    # 3 (中等偏上)   - N=20, r=4, 步长查询12次, 距离查询3次, 距离和查询2次
    # 4 (较难)       - N=24, r=6, 步长查询12次, 距离查询3次, 距离和查询2次
    # 5 (难)         - N=32, r=8, 步长查询12次, 距离查询3次, 距离和查询2次
    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 12,
                "r": 3,
                "steps": [3, 4, 6],
                "target_node": 7,
                "quota_step": 12,
                "quota_dist": 3,
                "quota_sum": 2,
            },
            2: {
                "n": 16,
                "r": 4,
                "steps": [3, 5, 6, 7],
                "target_node": 9,
                "quota_step": 12,
                "quota_dist": 3,
                "quota_sum": 2,
            },
            3: {
                "n": 20,
                "r": 4,
                "steps": [3, 5, 7, 9],
                "target_node": 13,
                "quota_step": 12,
                "quota_dist": 3,
                "quota_sum": 2,
            },
            4: {
                "n": 24,
                "r": 6,
                "steps": [2, 4, 6, 3, 5, 7],
                "target_node": 17,
                "quota_step": 12,
                "quota_dist": 3,
                "quota_sum": 2,
            },
            5: {
                "n": 32,
                "r": 8,
                "steps": [2, 4, 6, 8, 3, 5, 7, 9],
                "target_node": 21,
                "quota_step": 12,
                "quota_dist": 3,
                "quota_sum": 2,
            },
        },
        "en": {
            1: {
                "n": 12,
                "r": 3,
                "steps": [3, 4, 6],
                "target_node": 7,
                "quota_step": 12,
                "quota_dist": 3,
                "quota_sum": 2,
            },
            2: {
                "n": 16,
                "r": 4,
                "steps": [3, 5, 6, 7],
                "target_node": 9,
                "quota_step": 12,
                "quota_dist": 3,
                "quota_sum": 2,
            },
            3: {
                "n": 20,
                "r": 4,
                "steps": [3, 5, 7, 9],
                "target_node": 13,
                "quota_step": 12,
                "quota_dist": 3,
                "quota_sum": 2,
            },
            4: {
                "n": 24,
                "r": 6,
                "steps": [2, 4, 6, 3, 5, 7],
                "target_node": 17,
                "quota_step": 12,
                "quota_dist": 3,
                "quota_sum": 2,
            },
            5: {
                "n": 32,
                "r": 8,
                "steps": [2, 4, 6, 8, 3, 5, 7, 9],
                "target_node": 21,
                "quota_step": 12,
                "quota_dist": 3,
                "quota_sum": 2,
            },
        },
    }

    def __init__(self, config):
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = int(self.config.difficulty)  # 确保是整数

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        
        # 游戏参数
        self.n = cfg["n"]
        self.r = cfg["r"]
        self.steps = cfg["steps"]  # L数组
        self.target_node = cfg["target_node"]  # S
        
        # 查询额度
        self.quota_step = cfg["quota_step"]
        self.quota_dist = cfg["quota_dist"]
        self.quota_sum = cfg["quota_sum"]
        
        # 查询计数器
        self.used_step = 0
        self.used_dist = 0
        self.used_sum = 0
        
        # 构建图（邻接表）
        self.graph = [[] for _ in range(self.n)]
        for i in range(self.n):
            # 基础边: (i, i±1)
            self.graph[i].append((i + 1) % self.n)
            self.graph[i].append((i - 1) % self.n)
            
            # 增广边: (i, i±L[i mod r])
            step = self.steps[i % self.r]
            self.graph[i].append((i + step) % self.n)
            self.graph[i].append((i - step) % self.n)
        
        # 去重邻接表
        for i in range(self.n):
            self.graph[i] = list(set(self.graph[i]))
        
        # 预计算所有距离和
        self.distance_sums = {}
        for u in range(self.n):
            self.distance_sums[u] = self._compute_distance_sum(u)
        
        # 保存正确答案
        self.correct_answer = self.distance_sums[self.target_node]
        
        # 填充游戏信息用于规则模板
        self._game_info["n"] = self.n
        self._game_info["n_minus_1"] = self.n - 1
        self._game_info["max_step"] = (self.n - 1) // 2
        self._game_info["target_node"] = self.target_node
        self._game_info["quota_step"] = self.quota_step
        self._game_info["quota_dist"] = self.quota_dist
        self._game_info["quota_sum"] = self.quota_sum
        
        # 验证：不同余数类的距离和应各不相同
        residue_sums = {}
        for c in range(self.r):
            # 取余数为 c 的第一个节点
            representative = c
            residue_sums[c] = self.distance_sums[representative]
        
        sum_values = list(residue_sums.values())
        assert len(sum_values) == len(set(sum_values)), (
            f"Structural property violated: distance sums for different residue classes are not all distinct. sums: {residue_sums}"
        )

    def _compute_distance_sum(self, source):
        """使用BFS计算从source到所有其他节点的距离和"""
        dist = [-1] * self.n
        dist[source] = 0
        queue = deque([source])
        
        while queue:
            u = queue.popleft()
            for v in self.graph[u]:
                if dist[v] == -1:
                    dist[v] = dist[u] + 1
                    queue.append(v)
        
        return sum(d for d in dist if d > 0)

    def _compute_distance(self, u, v):
        """使用BFS计算节点u到节点v的最短距离"""
        if u == v:
            return 0
        
        dist = [-1] * self.n
        dist[u] = 0
        queue = deque([u])
        
        while queue:
            node = queue.popleft()
            for neighbor in self.graph[node]:
                if dist[neighbor] == -1:
                    dist[neighbor] = dist[node] + 1
                    if neighbor == v:
                        return dist[neighbor]
                    queue.append(neighbor)
        
        return -1  # 不应该到达这里，因为图是连通的

    def get_all_possible_queries(self) -> list[dict]:
        """
        枚举所有合法查询并返回对应的正确答案。
        """
        queries = []
        
        # 1. 步长查询 (query_step)
        # 对应规则：询问节点 u 对应的增广步长。返回 L[u mod r]。
        # 范围：0 到 n-1
        for u in range(self.n):
            ans = str(self.steps[u % self.r])
            queries.append({
                "query": f"<query_step>{u}</query_step>",
                "answer": ans
            })
        
        # 2. 距离查询 (query_dist)
        # 对应规则：询问节点 u 和节点 v 之间的最短路径距离。
        # 范围：任意两个不同节点 (u, v)。
        for u in range(self.n):
            for v in range(self.n):
                if u == v:
                    continue
                ans = str(self._compute_distance(u, v))
                queries.append({
                    "query": f"<query_dist>{u},{v}</query_dist>",
                    "answer": ans
                })

        # 3. 距离和查询 (query_sum)
        # 对应规则：询问节点 u 的距离和。
        # 限制：不能查询 u = S (target_node)
        for u in range(self.n):
            if u == self.target_node:
                continue
            ans = str(self.distance_sums[u])
            queries.append({
                "query": f"<query_sum>{u}</query_sum>",
                "answer": ans
            })
            
        return queries

    def evaluate(self, parsed_info):
        """评估最终答案"""
        try:
            answer = int(parsed_info["answer"].strip())
            return answer == self.correct_answer
        except:
            return False

    def _cf_make_wrong(self, correct: str) -> str:
        """
        将正确的查询响应篡改为一个错误的响应。
        correct 是一个数字字符串（步长值、距离值或距离和值）。
        """
        try:
            val = int(correct)
            # 偏移一个随机量，保证结果不同且为正
            offset = random.choice([1, 2, 3, -1, -2, -3])
            wrong_val = val + offset
            if wrong_val < 0:
                wrong_val = val + abs(offset)
            if wrong_val == val:
                wrong_val = val + 1
            return str(wrong_val)
        except (ValueError, TypeError):
            return correct + " [error]"

    def _cf_core_produce(self, parsed_info):
        """原始的业务逻辑，改名为 _cf_core_produce"""
        if self.config.language == "zh":
            error_format = "错误：格式无效。"
            error_range = "错误：节点编号超出范围。"
            error_quota = "错误：查询额度已用尽。"
            error_forbidden = "错误：不能查询目标节点 S = {} 的距离和。"
            error_no_query = "错误：未找到有效的查询标签。"
        else:
            error_format = "Error: Invalid format."
            error_range = "Error: Node ID out of range."
            error_quota = "Error: Query quota exhausted."
            error_forbidden = "Error: Cannot query distance sum for target node S = {}."
            error_no_query = "Error: No valid query tag found."
        
        # 步长查询
        if "query_step" in parsed_info:
            if self.used_step >= self.quota_step:
                return error_quota
            
            try:
                u = int(parsed_info["query_step"].strip())
                if u < 0 or u >= self.n:
                    return error_range
                
                self.used_step += 1
                step_value = self.steps[u % self.r]
                return str(step_value)
            except (ValueError, TypeError, IndexError):
                return error_format
        
        # 距离查询
        elif "query_dist" in parsed_info:
            if self.used_dist >= self.quota_dist:
                return error_quota
            
            try:
                raw = parsed_info["query_dist"].strip()
                parts = [x.strip() for x in raw.split(",")]
                if len(parts) != 2:
                    return error_format
                
                u, v = int(parts[0]), int(parts[1])
                if u < 0 or u >= self.n or v < 0 or v >= self.n:
                    return error_range
                
                self.used_dist += 1
                distance = self._compute_distance(u, v)
                return str(distance)
            except (ValueError, TypeError, IndexError):
                return error_format
        
        # 距离和查询
        elif "query_sum" in parsed_info:
            if self.used_sum >= self.quota_sum:
                return error_quota
            
            try:
                u = int(parsed_info["query_sum"].strip())
                if u < 0 or u >= self.n:
                    return error_range
                
                if u == self.target_node:
                    return error_forbidden.format(self.target_node)
                
                self.used_sum += 1
                dist_sum = self.distance_sums[u]
                return str(dist_sum)
            except (ValueError, TypeError, IndexError):
                return error_format
        
        else:
            return error_no_query