from .base import Game
import random

class PeriodicSequenceGame(Game):

    game_rule_zh = """\
我们来玩一个"周期序列推理"游戏。规则如下：

存在一个长度为 {n} 的二值序列 A[1..{n}]，其中每个元素 A[i] 属于集合 {{0,1}}。

该序列由某个未知的最小周期 P 和基模式 B[1..P] 重复拼接并截断生成：A[i] = B[(i-1 mod P)+1]。基模式 B 至少包含一个 0 和一个 1。最小周期 P 的取值范围为 3 到 20 之间（含边界）。

你的目标是：确定序列 A 中全为 1 的最长连续子段的长度 L* 以及该子段的最左起点 S*。若存在多个同样长度的最长子段，取起点最小者作为 S*。

你可以通过以下三种查询方式与我交互（每次只能提一个问题）：

1. **值查询**：询问位置 i 的值，其中 1 小于等于 i 小于等于 {n}。我会回答 A[i] 的值（0 或 1）。此查询的成本为 1。
2. **相等查询**：询问位置 i 和位置 j 的值是否相等，其中 1 小于等于 i, j 小于等于 {n}。我会回答"是"或"否"。此查询的成本为 1。
3. **周期性测试**：询问某个周期 p 是否成立，其中 2 小于等于 p 小于等于 {n}。我会回答"是"或"否"，表示对所有合法的 i（满足 i+p 小于等于 {n}）是否都有 A[i] = A[i+p]。注意返回"是"仅表示 p 是一个周期，未必是最小周期。此查询的成本为 3。

你需要在总询问成本不超过限制的情况下，尽可能少地使用查询次数，最终提交答案。

每次询问只能包含一个标签。请使用以下 XML 格式：

- 值查询（例如询问位置 5）：
<query_value>5</query_value>

- 相等查询（例如询问位置 3 和位置 7）：
<query_equal>3,7</query_equal>

- 周期性测试（例如测试周期 6）：
<query_period>6</query_period>

提交最终答案时，必须说明最长全 1 子段的起点 S 和长度 L，格式如下：
<answer>S=5, L=8</answer>

你的总询问成本上限为 {cost_limit}。
注意：若答案错误、格式不符或成本超限，游戏将失败。
"""

    game_rule_en = """\
Let's play a "Periodic Sequence Deduction" game. Here are the rules:

There exists a binary sequence A[1..{n}] of length {n}, where each element A[i] belongs to the set {{0,1}}.

The sequence is generated by repeating and truncating an unknown minimal period P and base pattern B[1..P]: A[i] = B[(i-1 mod P)+1]. The base pattern B contains at least one 0 and one 1. The minimal period P ranges from 3 to 20 (inclusive).

Your goal is: determine the length L* of the longest contiguous substring of all 1s in sequence A, and the leftmost starting position S* of that substring. If there are multiple longest substrings of the same length, take the one with the smallest starting position as S*.

You can interact with me through the following three types of queries (one question at a time):

1. **Value Query**: Ask for the value at position i, where 1 is less than or equal to i is less than or equal to {n}. I will answer the value of A[i] (0 or 1). This query costs 1.
2. **Equality Query**: Ask whether the values at positions i and j are equal, where 1 is less than or equal to i, j is less than or equal to {n}. I will answer "Yes" or "No". This query costs 1.
3. **Periodicity Test**: Ask whether a period p holds, where 2 is less than or equal to p is less than or equal to {n}. I will answer "Yes" or "No", indicating whether A[i] = A[i+p] for all valid i (satisfying i+p is less than or equal to {n}). Note that returning "Yes" only means p is a period, not necessarily the minimal period. This query costs 3.

You need to submit your answer using as few queries as possible while keeping the total query cost within the limit.

Each query must contain only one tag. Use the following XML format:

- Value Query (e.g., asking about position 5):
<query_value>5</query_value>

- Equality Query (e.g., asking about positions 3 and 7):
<query_equal>3,7</query_equal>

- Periodicity Test (e.g., testing period 6):
<query_period>6</query_period>

When submitting the final answer, specify the starting position S and length L of the longest all-1 substring in this format:
<answer>S=5, L=8</answer>

Your total query cost limit is {cost_limit}.
Note: The game will fail if the answer is incorrect, the format is invalid, or the cost limit is exceeded.
"""

    contextualized_rule_zh_1 = """\
智能交通控制系统遇到了一项"周期规律分析"任务。规则如下：

系统记录了某关键路段连续 {n} 个时间片的通行状态序列 A[1..{n}]，其中每个状态 A[i] 属于集合 {{0,1}}（1 表示畅通，0 表示拥堵）。

由于上游多个红绿灯的联动效应，该状态序列实际上由某个未知的最小循环周期 P 和基础通行模式 B[1..P] 重复拼接并截断生成：A[i] = B[(i-1 mod P)+1]。基础模式 B 中至少包含一个拥堵（0）和一个畅通（1）。最小周期 P 的取值范围为 3 到 20 之间（含边界）。

你的目标是：确定该路段持续畅通的最长连续时间段的长度 L*，以及该时间段的起始时间片编号 S*。若存在多个同样长度的最长畅通段，取起始时间片最小者作为 S*。

你可以通过以下三种查询方式操作交通数据日志（每次只能提一个问题）：

1. **状态查询**：询问时间片 i 的通行状态，其中 1 小于等于 i 小于等于 {n}。系统会返回 A[i] 的值（0 或 1）。此查询的成本为 1。
2. **比对查询**：询问时间片 i 和时间片 j 的通行状态是否相同，其中 1 小于等于 i, j 小于等于 {n}。系统会回答"是"或"否"。此查询的成本为 1。
3. **周期诊断**：测试某个联动周期 p 是否成立，其中 2 小于等于 p 小于等于 {n}。系统会回答"是"或"否"，表示对所有合法的时间片 i（满足 i+p 小于等于 {n}），是否都有 A[i] = A[i+p]。注意返回"是"仅代表 p 是一个可行周期，未必是最小周期。此查询的成本为 3。

你需要在总计算成本不超过限制的情况下，尽可能少地消耗查询资源，最终提交答案。

每次询问只能包含一个标签。请使用以下 XML 格式：

- 状态查询（例如询问时间片 5）：
<query_value>5</query_value>

- 比对查询（例如询问时间片 3 和时间片 7）：
<query_equal>3,7</query_equal>

- 周期诊断（例如测试周期 6）：
<query_period>6</query_period>

提交最终答案时，必须说明最长持续畅通段的起始时间片 S 和长度 L，格式如下：
<answer>S=5, L=8</answer>

你的总询问成本上限为 {cost_limit}。
注意：若答案错误、格式不符或成本超限，系统分析将失败。
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
The intelligent traffic control system is facing a "Periodic Pattern Analysis" task. Here are the rules:

The system has recorded the traffic status sequence A[1..{n}] of a critical road section over {n} consecutive time slots, where each status A[i] belongs to the set {{0,1}} (1 for clear, 0 for congested).

Due to the coordinated effect of upstream traffic lights, this status sequence is actually generated by repeating and truncating an unknown minimal cycle period P and a base traffic pattern B[1..P]: A[i] = B[(i-1 mod P)+1]. The base pattern B contains at least one congestion (0) and one clear (1). The minimal period P ranges from 3 to 20 (inclusive).

Your goal is: determine the length L* of the longest continuous clear time period on this road section, and the starting time slot S* of that period. If there are multiple longest clear periods of the same length, take the one with the smallest starting time slot as S*.

You can query the traffic data logs through the following three types of queries (one question at a time):

1. **Status Query**: Ask for the traffic status at time slot i, where 1 is less than or equal to i is less than or equal to {n}. The system will return the value of A[i] (0 or 1). This query costs 1.
2. **Comparison Query**: Ask whether the traffic statuses at time slots i and j are identical, where 1 is less than or equal to i, j is less than or equal to {n}. The system will answer "Yes" or "No". This query costs 1.
3. **Cycle Diagnosis**: Test whether a coordination period p holds, where 2 is less than or equal to p is less than or equal to {n}. The system will answer "Yes" or "No", indicating whether A[i] = A[i+p] for all valid time slots i (satisfying i+p is less than or equal to {n}). Note that returning "Yes" only means p is a valid period, not necessarily the minimal period. This query costs 3.

You need to submit your answer using as few query resources as possible while keeping the total computational cost within the limit.

Each query must contain only one tag. Use the following XML format:

- Status Query (e.g., asking about time slot 5):
<query_value>5</query_value>

- Comparison Query (e.g., asking about time slots 3 and 7):
<query_equal>3,7</query_equal>

- Cycle Diagnosis (e.g., testing period 6):
<query_period>6</query_period>

When submitting the final answer, specify the starting time slot S and length L of the longest continuous clear period in this format:
<answer>S=5, L=8</answer>

Your total query cost limit is {cost_limit}.
Note: The system analysis will fail if the answer is incorrect, the format is invalid, or the cost limit is exceeded.
"""

    contextualized_rule_zh_2 = """\
我们正在进行一项"生理节律异常筛查"任务。规则如下：

监测仪器获取了某患者连续 {n} 个采样点的心脏电生理信号节律序列 A[1..{n}]，其中每个采样点状态 A[i] 属于集合 {{0,1}}（1 表示心律正常，0 表示早搏/节律异常）。

经初步判定，该电生理序列实际上是由一个潜在的最小病理周期 P 和基础心电模式 B[1..P] 重复拼接并截断生成：A[i] = B[(i-1 mod P)+1]。该基础模式 B 至少包含一次异常（0）和一次正常（1）。最小病理周期 P 的取值范围为 3 到 20 之间（含边界）。

你的目标是：确定患者心律保持正常的最长连续监测段的长度 L*，以及该正常监测段的起始采样点编号 S*。若存在多个同样长度的最长正常段，取起始采样点最小者作为 S*。

你可以通过以下三种医疗数据调取方式进行检查（每次只能提一个问题）：

1. **节点查询**：询问采样点 i 的心律状态，其中 1 小于等于 i 小于等于 {n}。系统会返回 A[i] 的值（0 或 1）。此调取的成本为 1。
2. **状态对比**：询问采样点 i 和采样点 j 的心律状态是否完全相同，其中 1 小于等于 i, j 小于等于 {n}。系统会回答"是"或"否"。此调取的成本为 1。
3. **节律测试**：询问某病理周期 p 是否在全局成立，其中 2 小于等于 p 小于等于 {n}。系统会回答"是"或"否"，表示对所有合法的采样点 i（满足 i+p 小于等于 {n}），是否都有 A[i] = A[i+p]。注意，返回"是"仅表示 p 符合循环特征，未必是最小周期。此调取的成本为 3。

你需要在总计算成本不超过限制的情况下，尽可能少地使用调取次数，最终出具诊断结果。

每次询问只能包含一个标签。请使用以下 XML 格式：

- 节点查询（例如询问采样点 5）：
<query_value>5</query_value>

- 状态对比（例如询问采样点 3 和 7）：
<query_equal>3,7</query_equal>

- 节律测试（例如测试周期 6）：
<query_period>6</query_period>

提交最终诊断时，必须说明最长连续正常心律段的起始点 S 和长度 L，格式如下：
<answer>S=5, L=8</answer>

你的总询问成本上限为 {cost_limit}。
注意：若诊断结果错误、格式不符或成本超限，筛查任务将失败。
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
We are conducting a "Physiological Rhythm Abnormality Screening" task. Here are the rules:

The monitoring device has acquired the cardiac electrophysiological rhythm sequence A[1..{n}] for a patient over {n} consecutive sampling points, where each status A[i] belongs to the set {{0,1}} (1 for normal rhythm, 0 for premature beat/abnormal rhythm).

Preliminary analysis suggests that this electrophysiological sequence is actually generated by repeating and truncating a latent minimal pathological cycle P and a base ECG pattern B[1..P]: A[i] = B[(i-1 mod P)+1]. The base pattern B contains at least one abnormality (0) and one normal reading (1). The minimal pathological cycle P ranges from 3 to 20 (inclusive).

Your goal is: determine the length L* of the longest continuous monitoring period where the patient's heart rhythm remains normal, and the starting sampling point S* of that normal period. If there are multiple longest normal periods of the same length, take the one with the smallest starting point as S*.

You can query the medical data logs through the following three methods (one question at a time):

1. **Node Query**: Ask for the rhythm status at sampling point i, where 1 is less than or equal to i is less than or equal to {n}. The system will return the value of A[i] (0 or 1). This retrieval costs 1.
2. **Status Comparison**: Ask whether the rhythm statuses at sampling points i and j are exactly the same, where 1 is less than or equal to i, j is less than or equal to {n}. The system will answer "Yes" or "No". This retrieval costs 1.
3. **Rhythm Test**: Test whether a pathological cycle p holds globally, where 2 is less than or equal to p is less than or equal to {n}. The system will answer "Yes" or "No", indicating whether A[i] = A[i+p] for all valid sampling points i (satisfying i+p is less than or equal to {n}). Note that returning "Yes" only means p matches the cyclic characteristics, not necessarily the minimal cycle. This retrieval costs 3.

You need to submit your diagnostic results using as few queries as possible while keeping the total computational cost within the limit.

Each query must contain only one tag. Use the following XML format:

- Node Query (e.g., asking about sampling point 5):
<query_value>5</query_value>

- Status Comparison (e.g., asking about sampling points 3 and 7):
<query_equal>3,7</query_equal>

- Rhythm Test (e.g., testing cycle 6):
<query_period>6</query_period>

When submitting the final diagnosis, specify the starting point S and length L of the longest continuous normal rhythm period in this format:
<answer>S=5, L=8</answer>

Your total query cost limit is {cost_limit}.
Note: The screening task will fail if the diagnosis is incorrect, the format is invalid, or the cost limit is exceeded.
"""

    contextualized_rule_zh_3 = """\
欢迎进入"学习状态周期性诊断"分析系统。规则如下：

系统通过多模态设备采集了某学生在连续 {n} 个学习切片内的专注度表现序列 A[1..{n}]，其中每个切片状态 A[i] 属于集合 {{0,1}}（1 表示专注，0 表示分心）。

心理学分析表明，该状态序列由学生内在的最小注意力波动周期 P 和基础状态模式 B[1..P] 循环拼接并截断生成：A[i] = B[(i-1 mod P)+1]。基础模式 B 中至少包含一次分心（0）和一次专注（1）。最小波动周期 P 的取值范围介于 3 到 20 之间（含边界）。

你的目标是：找出该学生保持连续专注的最长切片段长度 L*，以及该高度专注期开始的切片编号 S*。若存在多个同样长度的最长专注段，则取开始时间最早（即编号最小）的切片作为 S*。

你可以通过以下三种方式调用系统接口获取数据（每次只能提一个问题）：

1. **状态点测**：查询切片 i 的表现状态，其中 1 小于等于 i 小于等于 {n}。系统会返回 A[i] 的值（0 或 1）。此接口调用成本为 1。
2. **表现对照**：查询切片 i 和切片 j 的状态是否一致，其中 1 小于等于 i, j 小于等于 {n}。系统会回答"是"或"否"。此接口调用成本为 1。
3. **周期验证**：验证某个潜在周期 p 是否成立，其中 2 小于等于 p 小于等于 {n}。系统会回答"是"或"否"，代表对于所有有效的切片 i（满足 i+p 小于等于 {n}），是否严格满足 A[i] = A[i+p]。注意，返回"是"仅表示 p 是一个可行周期，未必是最小周期。此接口调用成本为 3。

请在评估总调用成本不超过上限的前提下，以最少的交互次数完成分析并提交报告。

每次询问只能包含一个标签。请使用以下 XML 格式：

- 状态点测（例如查询切片 5）：
<query_value>5</query_value>

- 表现对照（例如对照切片 3 和切片 7）：
<query_equal>3,7</query_equal>

- 周期验证（例如验证周期 6）：
<query_period>6</query_period>

提交最终分析报告时，必须标明最长连续专注段的起始切片 S 和长度 L，格式如下：
<answer>S=5, L=8</answer>

你的总询问成本上限为 {cost_limit}。
注意：若结论错误、格式不符或调用成本超限，诊断将判定为无效。
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Welcome to the "Learning State Periodicity Diagnosis" analysis system. Here are the rules:

The system has captured a student's attention performance sequence A[1..{n}] over {n} consecutive learning segments using multimodal devices, where each segment state A[i] belongs to the set {{0,1}} (1 for focused, 0 for distracted).

Psychological analysis suggests that this state sequence is generated by repeating and truncating the student's intrinsic minimal attention fluctuation period P and a baseline state pattern B[1..P]: A[i] = B[(i-1 mod P)+1]. The baseline pattern B contains at least one distraction (0) and one focus (1). The minimal fluctuation period P ranges between 3 and 20 (inclusive).

Your goal is: identify the length L* of the longest continuous segment where the student remains highly focused, and the starting segment number S* of this peak focus period. If there are multiple longest focused periods of the same length, take the one with the earliest start (i.e., smallest segment number) as S*.

You can retrieve data by calling the system interfaces in the following three ways (one question at a time):

1. **State Spot-check**: Query the performance state of segment i, where 1 is less than or equal to i is less than or equal to {n}. The system will return the value of A[i] (0 or 1). This API call costs 1.
2. **Performance Comparison**: Query whether the states of segment i and segment j are consistent, where 1 is less than or equal to i, j is less than or equal to {n}. The system will answer "Yes" or "No". This API call costs 1.
3. **Period Verification**: Verify whether a potential fluctuation period p holds, where 2 is less than or equal to p is less than or equal to {n}. The system will answer "Yes" or "No", indicating whether A[i] = A[i+p] is strictly met for all valid segments i (satisfying i+p is less than or equal to {n}). Note that returning "Yes" only means p is a feasible period, not necessarily the minimal one. This API call costs 3.

Please complete the analysis and submit your report with the fewest possible interactions, ensuring the total call cost does not exceed the limit.

Each query must contain only one tag. Use the following XML format:

- State Spot-check (e.g., querying segment 5):
<query_value>5</query_value>

- Performance Comparison (e.g., comparing segment 3 and segment 7):
<query_equal>3,7</query_equal>

- Period Verification (e.g., verifying period 6):
<query_period>6</query_period>

When submitting the final analysis report, clearly indicate the starting segment S and length L of the longest continuous focused period in this format:
<answer>S=5, L=8</answer>

Your total query cost limit is {cost_limit}.
Note: The diagnosis will be considered invalid if the conclusion is incorrect, the format does not match, or the cost limit is exceeded.
"""

    contextualized_rule_zh_4 = """\
工业物联网控制中心下发了一项"生产线缺陷模式排查"任务。规则如下：

质检传感器记录了某核心生产线连续 {n} 个批次的产品良率达标状态序列 A[1..{n}]，其中每个批次状态 A[i] 属于集合 {{0,1}}（1 表示良品，0 表示残次品）。

经排查，由于传动齿轮的机械磨损，该状态序列实际上是由某个未知的最小磨损周期 P 和基础工艺模式 B[1..P] 循环拼接并截断生成：A[i] = B[(i-1 mod P)+1]。基础模式 B 至少包含一次残次品（0）和一次良品（1）。最小磨损周期 P 的取值范围为 3 到 20 之间（含边界）。

你的任务是：找出该生产线能够维持连续输出良品的最长生产段的批次长度 L*，以及该完美生产段的起始批次号 S*。若存在多个同等长度的最长良品段，选取批次号最小者作为 S*。

你可以通过以下三种指令向工业控制中心发起质检调阅（每次只能提交一个指令）：

1. **批次质检**：查询批次 i 的质检状态，其中 1 小于等于 i 小于等于 {n}。控制中心将返回 A[i] 的值（0 或 1）。此指令耗时成本为 1。
2. **批次比对**：查询批次 i 和批次 j 的质检状态是否相同，其中 1 小于等于 i, j 小于等于 {n}。控制中心会回答"是"或"否"。此指令耗时成本为 1。
3. **周期排查**：诊断某个传动周期 p 是否引发全局性规律，其中 2 小于等于 p 小于等于 {n}。控制中心会回答"是"或"否"，表明对所有合法的批次 i（满足 i+p 小于等于 {n}），是否均满足 A[i] = A[i+p]。注意，反馈为"是"只代表 p 符合周期特征，未必是最小周期。此指令耗时成本为 3。

你需要在总排查成本低于系统预警值的情况下，以最精简的调阅步数完成分析。

每次调阅只能使用一个指令标签。请采用以下 XML 格式：

- 批次质检（例如抽检批次 5）：
<query_value>5</query_value>

- 批次比对（例如比对批次 3 和 7）：
<query_equal>3,7</query_equal>

- 周期排查（例如测试排查周期 6）：
<query_period>6</query_period>

提交最终排查报告时，必须注明最长连续良品段的起始批次 S 和长度 L，格式如下：
<answer>S=5, L=8</answer>

你的总询问成本上限为 {cost_limit}。
注意：如果报告数据错误、格式有误或成本超标，排查任务将被强制中止。
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
The Industrial IoT Control Center has issued a "Production Line Defect Pattern Troubleshooting" task. Here are the rules:

Quality inspection sensors have recorded the yield compliance status sequence A[1..{n}] of a core production line over {n} consecutive batches, where each batch status A[i] belongs to the set {{0,1}} (1 for good product, 0 for defective product).

Upon investigation, due to mechanical wear of transmission gears, this status sequence is actually generated by repeating and truncating an unknown minimal wear cycle P and a base processing pattern B[1..P]: A[i] = B[(i-1 mod P)+1]. The base pattern B contains at least one defect (0) and one good product (1). The minimal wear cycle P ranges from 3 to 20 (inclusive).

Your task is: find the batch length L* of the longest production run where the line can continuously output good products, and the starting batch number S* of this flawless run. If there are multiple longest good runs of the same length, select the one with the smallest batch number as S*.

You can initiate quality reviews with the industrial control center using the following three commands (one command at a time):

1. **Batch Inspection**: Query the quality status of batch i, where 1 is less than or equal to i is less than or equal to {n}. The control center will return the value of A[i] (0 or 1). This command costs 1 in time consumption.
2. **Batch Comparison**: Query whether the quality statuses of batch i and batch j are identical, where 1 is less than or equal to i, j is less than or equal to {n}. The control center will answer "Yes" or "No". This command costs 1 in time consumption.
3. **Cycle Troubleshooting**: Diagnose whether a transmission cycle p causes a global pattern, where 2 is less than or equal to p is less than or equal to {n}. The control center will answer "Yes" or "No", indicating whether A[i] = A[i+p] holds true for all valid batches i (satisfying i+p is less than or equal to {n}). Note that an answer of "Yes" only signifies that p fits the cyclical characteristic, not necessarily the minimal cycle. This command costs 3 in time consumption.

You must complete the analysis with the most streamlined review steps while keeping the total troubleshooting cost below the system warning threshold.

Each review can only use one command tag. Please use the following XML format:

- Batch Inspection (e.g., spot-checking batch 5):
<query_value>5</query_value>

- Batch Comparison (e.g., comparing batches 3 and 7):
<query_equal>3,7</query_equal>

- Cycle Troubleshooting (e.g., testing cycle 6):
<query_period>6</query_period>

When submitting the final troubleshooting report, you must indicate the starting batch S and length L of the longest continuous good run in this format:
<answer>S=5, L=8</answer>

Your total query cost limit is {cost_limit}.
Note: The troubleshooting task will be forcibly aborted if the report data is incorrect, the format is flawed, or the cost limit is exceeded.
"""

    contextualized_rule_zh_5 = """\
合规审计部门正在推进一项"企业运营合规规律审计"项目。规则如下：

法务系统内调取了某企业在连续 {n} 个工作日内的业务合规状态序列 A[1..{n}]，其中每个工作日状态 A[i] 属于集合 {{0,1}}（1 表示合规，0 表示违规）。

审查发现，由于该企业某个固化的业务审批流存在漏洞，该合规序列实际上由某个未知的最小业务周期 P 和基础运作模式 B[1..P] 循环拼接并截断生成：A[i] = B[(i-1 mod P)+1]。基础模式 B 中至少包含一次违规（0）和一次合规（1）。最小业务周期 P 的取值范围为 3 到 20 之间（含边界）。

你的审计目标是：核查该企业能够保持连续合规的最长运营期长度 L*，以及该合规期的首个工作日编号 S*。如果存在多个相同长度的最长合规期，以工作日编号最小者作为 S*。

你可以通过以下三种卷宗调阅手段与法务数据库交互（每次只能提交一项调阅）：

1. **单日审查**：审查第 i 个工作日的合规状态，其中 1 小于等于 i 小于等于 {n}。数据库会返回 A[i] 的取值（0 或 1）。此调阅消耗的审计资源为 1。
2. **状态比对**：比对第 i 和第 j 个工作日的合规状态是否相同，其中 1 小于等于 i, j 小于等于 {n}。数据库会回答"是"或"否"。此调阅消耗的审计资源为 1。
3. **流程溯源**：查证某个潜在审批周期 p 是否造成全局性影响，其中 2 小于等于 p 小于等于 {n}。数据库会回答"是"或"否"，证明对于所有合法的工作日 i（满足 i+p 小于等于 {n}），是否均满足 A[i] = A[i+p]。注意，回答"是"仅表明 p 具备周期重复特性，未必是导致违规的最小周期。此调阅消耗的审计资源为 3。

请在总审计资源不超标的限制下，凭借最少的交互次数完成核查。

每次调阅只能包含一个动作标签。请采用以下 XML 格式：

- 单日审查（例如审查第 5 日）：
<query_value>5</query_value>

- 状态比对（例如比对第 3 日和第 7 日）：
<query_equal>3,7</query_equal>

- 流程溯源（例如验证周期 6）：
<query_period>6</query_period>

提交最终审计结论时，必须指明最长合规期的起始工作日 S 和长度 L，格式如下：
<answer>S=5, L=8</answer>

你的总询问成本上限为 {cost_limit}。
注意：若结论数据错漏、格式不规范或资源消耗越线，本轮审计将被判定为不合格。
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
The Compliance Audit Department is advancing an "Enterprise Operations Compliance Pattern Audit" project. Here are the rules:

The legal system has retrieved the business compliance status sequence A[1..{n}] of a company over {n} consecutive working days, where each daily status A[i] belongs to the set {{0,1}} (1 for compliant, 0 for non-compliant).

Investigations reveal that due to a loophole in the company's rigid business approval flow, this compliance sequence is actually generated by repeating and truncating an unknown minimal business cycle P and a base operational pattern B[1..P]: A[i] = B[(i-1 mod P)+1]. The base pattern B contains at least one non-compliance (0) and one compliance (1). The minimal business cycle P ranges from 3 to 20 (inclusive).

Your audit objective is: ascertain the length L* of the longest operational period during which the enterprise maintains continuous compliance, and the starting working day number S* of this compliant period. If there are multiple longest compliant periods of the same length, prioritize the one with the smallest working day number as S*.

You can interact with the legal database using the following three file retrieval methods (one request at a time):

1. **Single-day Review**: Review the compliance status of the i-th working day, where 1 is less than or equal to i is less than or equal to {n}. The database will return the value of A[i] (0 or 1). This retrieval consumes 1 audit resource.
2. **Status Comparison**: Compare whether the compliance statuses of the i-th and j-th working days are identical, where 1 is less than or equal to i, j is less than or equal to {n}. The database will answer "Yes" or "No". This retrieval consumes 1 audit resource.
3. **Process Traceability**: Verify whether a potential approval cycle p causes a global impact, where 2 is less than or equal to p is less than or equal to {n}. The database will answer "Yes" or "No", proving whether A[i] = A[i+p] is met for all valid working days i (satisfying i+p is less than or equal to {n}). Note that an answer of "Yes" only indicates that p has cyclical repetition characteristics, not necessarily the minimal cycle leading to non-compliance. This retrieval consumes 3 audit resources.

Please complete the verification with the fewest possible interactions while staying within the total audit resource limit.

Each request must contain only one action tag. Please use the following XML format:

- Single-day Review (e.g., reviewing day 5):
<query_value>5</query_value>

- Status Comparison (e.g., comparing days 3 and 7):
<query_equal>3,7</query_equal>

- Process Traceability (e.g., verifying cycle 6):
<query_period>6</query_period>

When submitting the final audit conclusion, you must specify the starting working day S and length L of the longest compliant period in this format:
<answer>S=5, L=8</answer>

Your total query cost limit is {cost_limit}.
Note: The current audit round will be deemed unqualified if the conclusion data is inaccurate, the format is non-standard, or the resource consumption crosses the line.
"""

    tags = ["answer", "query_value", "query_equal", "query_period"]
    
    reasoning_type = "归纳推理"
    data_structure = "序列"

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 80,
                "period": 4,
                "pattern": [1, 1, 1, 0],
                "cost_limit": 45,
            },
            2: {
                "n": 120,
                "period": 6,
                "pattern": [1, 0, 1, 1, 1, 0],
                "cost_limit": 45,
            },
            3: {
                "n": 200,
                "period": 10,
                "pattern": [1, 1, 0, 1, 1, 1, 1, 0, 0, 1],
                "cost_limit": 45,
            },
            4: {
                "n": 300,
                "period": 15,
                "pattern": [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1],
                "cost_limit": 45,
            },
            5: {
                "n": 400,
                "period": 18,
                "pattern": [0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1],
                "cost_limit": 45,
            },
        },
        "en": {
            1: {
                "n": 80,
                "period": 4,
                "pattern": [1, 1, 1, 0],
                "cost_limit": 45,
            },
            2: {
                "n": 120,
                "period": 6,
                "pattern": [1, 0, 1, 1, 1, 0],
                "cost_limit": 45,
            },
            3: {
                "n": 200,
                "period": 10,
                "pattern": [1, 1, 0, 1, 1, 1, 1, 0, 0, 1],
                "cost_limit": 45,
            },
            4: {
                "n": 300,
                "period": 15,
                "pattern": [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1],
                "cost_limit": 45,
            },
            5: {
                "n": 400,
                "period": 18,
                "pattern": [0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1],
                "cost_limit": 45,
            },
        },
    }

    def __init__(self, config):
        self.total_cost = 0
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = int(self.config.difficulty)

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        
        self.n = cfg["n"]
        self.cost_limit = cfg["cost_limit"]
        self.total_cost = 0

        rng = random.Random()
        period = cfg["period"]
        self.period = period

        while True:
            pattern = [rng.randint(0, 1) for _ in range(period)]
            if 0 in pattern and 1 in pattern:
                break
        self.pattern = pattern

        self._game_info["n"] = self.n
        self._game_info["cost_limit"] = self.cost_limit

        self.sequence = []
        for i in range(1, self.n + 1):
            pattern_idx = ((i - 1) % self.period)
            self.sequence.append(self.pattern[pattern_idx])
        
        self._compute_ground_truth()

    def _compute_ground_truth(self):
        max_length = 0
        max_start = 1
        current_length = 0
        current_start = 1
        
        for i in range(self.n):
            if self.sequence[i] == 1:
                if current_length == 0:
                    current_start = i + 1
                current_length += 1
            else:
                if current_length > max_length:
                    max_length = current_length
                    max_start = current_start
                current_length = 0
        
        if current_length > max_length:
            max_length = current_length
            max_start = current_start
        
        if max_length == 0:
            max_start = 1
            max_length = 0
            
        self.ground_truth_start = max_start
        self.ground_truth_length = max_length

    def evaluate(self, parsed_info):
        raw_ans = parsed_info["answer"]
        
        try:
            kv_pairs = [x.strip() for x in raw_ans.split(",")]
            ans_dict = {}
            for kv in kv_pairs:
                if "=" in kv:
                    k, v = kv.split("=", 1)
                    ans_dict[k.strip().upper()] = int(v.strip())
            
            if "S" not in ans_dict or "L" not in ans_dict:
                return False
            
            submitted_start = ans_dict["S"]
            submitted_length = ans_dict["L"]
            
            return (submitted_start == self.ground_truth_start and 
                    submitted_length == self.ground_truth_length)
        except:
            return False

    def _cf_core_produce(self, parsed_info):
        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
            error_format = "错误：格式无效。"
            error_range = "错误：参数超出范围。"
            error_cost = "错误：查询成本超出限制。"
        else:
            yes_res, no_res = "Yes", "No"
            error_format = "Error: Invalid format."
            error_range = "Error: Parameter out of range."
            error_cost = "Error: Query cost exceeded limit."

        if "query_value" in parsed_info:
            if self.total_cost + 1 > self.cost_limit:
                self.state.set_state("failed", "cost limit exceeded")
                return error_cost
            
            self.total_cost += 1
            
            try:
                i = int(parsed_info["query_value"].strip())
                if i < 1 or i > self.n:
                    return error_range
                return str(self.sequence[i - 1])
            except:
                return error_format

        elif "query_equal" in parsed_info:
            if self.total_cost + 1 > self.cost_limit:
                self.state.set_state("failed", "cost limit exceeded")
                return error_cost
            
            self.total_cost += 1
            
            try:
                raw = parsed_info["query_equal"]
                parts = [x.strip() for x in raw.split(",")]
                if len(parts) != 2:
                    return error_format
                i, j = int(parts[0]), int(parts[1])
                if i < 1 or i > self.n or j < 1 or j > self.n:
                    return error_range
                return yes_res if self.sequence[i - 1] == self.sequence[j - 1] else no_res
            except:
                return error_format

        elif "query_period" in parsed_info:
            if self.total_cost + 3 > self.cost_limit:
                self.state.set_state("failed", "cost limit exceeded")
                return error_cost
            
            self.total_cost += 3
            
            try:
                p = int(parsed_info["query_period"].strip())
                if p < 2 or p > self.n:
                    return error_range
                
                is_period = True
                for i in range(1, self.n - p + 1):
                    if self.sequence[i - 1] != self.sequence[i + p - 1]:
                        is_period = False
                        break
                
                return yes_res if is_period else no_res
            except:
                return error_format

        else:
            raise ValueError("No valid query tag found.")

    def _cf_make_wrong(self, correct: str) -> str:
        if correct == "0":
            return "1"
        elif correct == "1":
            return "0"

        if correct.isdigit():
            return str(int(correct) + 1)
        
        if self.config.language == "zh":
            if correct == "是":
                return "否"
            elif correct == "否":
                return "是"
        else:
            lower_correct = correct.lower()
            if lower_correct == "yes":
                return "No" if correct[0].isupper() else "no"
            elif lower_correct == "no":
                return "Yes" if correct[0].isupper() else "yes"
        
        return correct + "_WRONG"

    def get_all_possible_queries(self) -> list[dict]:
        queries = []

        if self.config.language == "zh":
            yes_res, no_res = "是", "否"
        else:
            yes_res, no_res = "Yes", "No"

        for i in range(1, self.n + 1):
            val = str(self.sequence[i - 1])
            queries.append({
                "query": f"<query_value>{i}</query_value>",
                "answer": val
            })

        for p in range(2, self.n + 1):
            is_period = True
            for k in range(1, self.n - p + 1):
                if self.sequence[k - 1] != self.sequence[k + p - 1]:
                    is_period = False
                    break
            ans = yes_res if is_period else no_res
            queries.append({
                "query": f"<query_period>{p}</query_period>",
                "answer": ans
            })

        seen = set()
        for i in range(1, self.n + 1):
            for j_candidate in [i + 1, i + self.period]:
                j = j_candidate
                if j > self.n:
                    continue
                if (i, j) in seen:
                    continue
                seen.add((i, j))
                is_equal = (self.sequence[i - 1] == self.sequence[j - 1])
                ans = yes_res if is_equal else no_res
                queries.append({
                    "query": f"<query_equal>{i},{j}</query_equal>",
                    "answer": ans
                })

        return queries