from .base import Game
import re

class PathCostInferenceGame(Game):

    game_rule_zh = """\
我们现在来玩一个"路径代价推断"游戏，规则如下：

游戏设定了一个无向连通图 G，包含 6 个顶点：v1, v2, v3, v4, v5, v6。

图的边集合为：
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

游戏中存在一条隐藏的目标路径 T，你的任务是推断出该目标路径的总代价。

1. 每条边都有一个非负整数代价，该代价由一个隐藏但固定的规律生成
2. 路径的总代价等于路径上所有边的代价之和
3. 如果路径中重复经过某条边，则该边的代价会按经过次数重复计入
4. 边代价的生成规律在整局游戏中保持一致

你最多可以进行 {max_queries} 次查询，每次查询可以选择以下两种类型之一：

询问某条路径的总代价。路径必须满足：
- 至少包含 3 个顶点（即至少 2 条边）
- 相邻顶点之间必须存在边
- 可以包含重复的顶点或边
- 不能与目标路径完全相同

询问两条路径的代价大小关系。两条路径均需满足上述路径代价查询的约束。

**路径代价查询**（例如查询路径 v1->v2->v3）：
<query_path>v1,v2,v3</query_path>

**路径对比查询**（例如对比路径 v1->v2->v3 和 v1->v3->v5）：
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

当你收集足够信息后，请提交最终答案，格式如下：

<answer>cost=数字, rule=规律描述</answer>

其中：
- cost：你推断的目标路径总代价（整数）
- rule：你归纳出的边代价生成规律的简要描述

例如：
<answer>cost=42, rule=每条边的代价等于其两端顶点编号之和</answer>

- 你不能直接查询目标路径本身
- 非法查询（如路径不满足约束）将返回错误信息
- 若答案错误或规律描述与实际不一致，游戏失败
- 请尽可能高效地使用查询次数
"""

    game_rule_en = """\
Let's play a "Path Cost Inference" game. Here are the rules:

The game is set on an undirected connected graph G with 6 vertices: v1, v2, v3, v4, v5, v6.

The edge set is:
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

There is a hidden target path T in the game. Your task is to infer the total cost of this target path.

1. Each edge has a non-negative integer cost generated by a hidden but fixed rule
2. The total cost of a path equals the sum of all edge costs in the path
3. If an edge is traversed multiple times in a path, its cost is counted multiple times
4. The edge cost generation rule remains consistent throughout the game

You can make at most {max_queries} queries. Each query can be one of the following types:

Ask for the total cost of a path. The path must satisfy:
- At least 3 vertices (i.e., at least 2 edges)
- Adjacent vertices must be connected by an edge
- Can contain repeated vertices or edges
- Cannot be identical to the target path

Ask for the cost relationship between two paths. Both paths must satisfy the above path cost query constraints.

**Path Cost Query** (e.g., querying path v1->v2->v3):
<query_path>v1,v2,v3</query_path>

**Path Comparison Query** (e.g., comparing path v1->v2->v3 and v1->v3->v5):
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

When you have enough information, submit your final answer in this format:

<answer>cost=number, rule=rule description</answer>

Where:
- cost: Your inferred total cost of the target path (integer)
- rule: A brief description of the edge cost generation rule you identified

Example:
<answer>cost=42, rule=Each edge cost equals the sum of its endpoint vertex numbers</answer>

- You cannot directly query the target path itself
- Invalid queries (e.g., paths not satisfying constraints) will return error messages
- If the answer is incorrect or the rule description is inconsistent with reality, the game fails
- Try to use your queries as efficiently as possible
"""

    contextualized_rule_zh_1 = """\
我们现在来玩一个“交通枢纽通行时间推断”游戏，规则如下：

游戏设定了一个城市交通网络 G，包含 6 个交通枢纽节点：v1, v2, v3, v4, v5, v6。

交通网络中的道路（边）集合为：
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

交通网络中存在一条隐藏的关键物资运输路线 T，你的任务是推断出该运输路线的总通行时间。

1. 每条道路都有一个非负整数的通行时间，该时间由一个隐藏但固定的规律生成
2. 路线的总通行时间等于路线上所有道路的通行时间之和
3. 如果路线中重复经过某条道路，则该道路的通行时间会按经过次数重复计入
4. 道路通行时间的生成规律在整个分析过程中保持一致

你最多可以进行 {max_queries} 次查询，每次查询可以选择以下两种类型之一：

询问某条运输路线的总通行时间。路线必须满足：
- 至少包含 3 个枢纽（即至少 2 条道路）
- 相邻枢纽之间必须存在道路连接
- 可以包含重复的枢纽或道路
- 不能与目标运输路线完全相同

询问两条路线的通行时间大小关系。两条路线均需满足上述路线查询的约束。

**路线通行时间查询**（例如查询路线 v1->v2->v3）：
<query_path>v1,v2,v3</query_path>

**路线对比查询**（例如对比路线 v1->v2->v3 和 v1->v3->v5）：
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

当你收集足够信息后，请提交最终推断答案，格式如下：

<answer>cost=数字, rule=规律描述</answer>

其中：
- cost：你推断的隐藏运输路线总通行时间（整数）
- rule：你归纳出的道路通行时间生成规律的简要描述

例如：
<answer>cost=42, rule=每条道路的通行时间等于其两端枢纽编号之和</answer>

- 你不能直接查询目标运输路线本身
- 非法查询（如路线不满足约束）将返回错误信息
- 若推断时间错误或规律描述与实际不一致，则任务失败
- 请尽可能高效地使用查询次数
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
Let's play a "Traffic Hub Travel Time Inference" game. Here are the rules:

The game is set in an urban traffic network G with 6 key hub nodes: v1, v2, v3, v4, v5, v6.

The set of roads (edges) in the network is:
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

There is a hidden critical material transport route T in the network. Your task is to infer the total travel time of this route.

1. Each road has a non-negative integer travel time generated by a hidden but fixed rule
2. The total travel time of a route equals the sum of the travel times of all roads on the route
3. If a road is traversed multiple times in a route, its travel time is counted multiple times
4. The rule for generating road travel time remains consistent throughout the analysis

You can make at most {max_queries} queries. Each query can be one of the following types:

Ask for the total travel time of a transport route. The route must satisfy:
- At least 3 hubs (i.e., at least 2 roads)
- Adjacent hubs must be connected by a road
- Can contain repeated hubs or roads
- Cannot be identical to the target transport route

Ask for the relationship of travel time between two routes. Both routes must satisfy the above route query constraints.

**Route Travel Time Query** (e.g., querying route v1->v2->v3):
<query_path>v1,v2,v3</query_path>

**Route Comparison Query** (e.g., comparing route v1->v2->v3 and v1->v3->v5):
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

When you have enough information, submit your final inferred answer in this format:

<answer>cost=number, rule=rule description</answer>

Where:
- cost: Your inferred total travel time of the hidden transport route (integer)
- rule: A brief description of the travel time generation rule you identified

Example:
<answer>cost=42, rule=The travel time of each road equals the sum of its endpoint hub numbers</answer>

- You cannot directly query the target transport route itself
- Invalid queries (e.g., routes not satisfying constraints) will return error messages
- If the inferred time is incorrect or the rule description is inconsistent with reality, the task fails
- Try to use your queries as efficiently as possible
"""

    contextualized_rule_zh_2 = """\
我们现在来玩一个“康复方案资源消耗推断”游戏，规则如下：

游戏设定了一个标准化康复治疗流程网络 G，包含 6 个治疗阶段节点：v1, v2, v3, v4, v5, v6。

阶段之间可行的过渡环节（边）集合为：
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

医疗系统中存在一条隐藏的特效康复方案路径 T，你的任务是推断出执行该方案所需的总医疗资源消耗量。

1. 每个过渡环节都有一个非负整数的资源消耗量，该消耗量由一个隐藏但固定的规律生成
2. 方案的总资源消耗等于路径上所有过渡环节的资源消耗之和
3. 如果方案中重复经过某个过渡环节，则该环节的资源消耗会按经过次数重复计入
4. 资源消耗量的生成规律在整个评估过程中保持一致

你最多可以进行 {max_queries} 次查询，每次查询可以选择以下两种类型之一：

询问某条特定康复方案路径的总资源消耗。路径必须满足：
- 至少包含 3 个治疗阶段（即至少 2 个过渡环节）
- 相邻阶段之间必须存在过渡环节连接
- 可以包含重复的阶段或环节
- 不能与目标康复方案完全相同

询问两条康复方案的资源消耗大小关系。两条方案路径均需满足上述消耗查询的约束。

**方案消耗查询**（例如查询方案 v1->v2->v3）：
<query_path>v1,v2,v3</query_path>

**方案对比查询**（例如对比方案 v1->v2->v3 和 v1->v3->v5）：
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

当你收集足够信息后，请提交最终推断答案，格式如下：

<answer>cost=数字, rule=规律描述</answer>

其中：
- cost：你推断的隐藏康复方案总医疗资源消耗量（整数）
- rule：你归纳出的过渡环节消耗量生成规律的简要描述

例如：
<answer>cost=42, rule=每个环节的资源消耗等于其两端治疗阶段编号之和</answer>

- 你不能直接查询目标康复方案本身
- 非法查询（如方案不满足约束）将返回错误信息
- 若推断消耗量错误或规律描述与实际不一致，则评估失败
- 请尽可能高效地使用查询次数
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
Let's play a "Rehabilitation Plan Resource Consumption Inference" game. Here are the rules:

The game is set in a standardized rehabilitation treatment workflow network G, with 6 treatment stage nodes: v1, v2, v3, v4, v5, v6.

The set of feasible transition links (edges) between stages is:
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

There is a hidden effective rehabilitation plan path T in the medical system. Your task is to infer the total medical resource consumption required to execute this plan.

1. Each transition link has a non-negative integer resource consumption generated by a hidden but fixed rule
2. The total resource consumption of a plan equals the sum of the consumption of all transition links on the path
3. If a link is traversed multiple times in a plan, its resource consumption is counted multiple times
4. The rule for generating resource consumption remains consistent throughout the evaluation

You can make at most {max_queries} queries. Each query can be one of the following types:

Ask for the total resource consumption of a specific rehabilitation plan path. The path must satisfy:
- At least 3 treatment stages (i.e., at least 2 transition links)
- Adjacent stages must be connected by a transition link
- Can contain repeated stages or links
- Cannot be identical to the target rehabilitation plan

Ask for the relationship of resource consumption between two plans. Both plan paths must satisfy the above consumption query constraints.

**Plan Consumption Query** (e.g., querying plan v1->v2->v3):
<query_path>v1,v2,v3</query_path>

**Plan Comparison Query** (e.g., comparing plan v1->v2->v3 and v1->v3->v5):
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

When you have enough information, submit your final inferred answer in this format:

<answer>cost=number, rule=rule description</answer>

Where:
- cost: Your inferred total medical resource consumption of the hidden rehabilitation plan (integer)
- rule: A brief description of the link consumption generation rule you identified

Example:
<answer>cost=42, rule=The resource consumption of each link equals the sum of its endpoint stage numbers</answer>

- You cannot directly query the target rehabilitation plan itself
- Invalid queries (e.g., plans not satisfying constraints) will return error messages
- If the inferred consumption is incorrect or the rule description is inconsistent with reality, the evaluation fails
- Try to use your queries as efficiently as possible
"""

    contextualized_rule_zh_3 = """\
我们现在来玩一个“学习路径课时消耗推断”游戏，规则如下：

游戏设定了一个学科知识网络 G，包含 6 个核心学习模块：v1, v2, v3, v4, v5, v6。

模块之间的知识链接（边）集合为：
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

教学大纲中存在一条隐藏的推荐学习路径 T，你的任务是推断出完成该路径所需的总课时消耗。

1. 每个知识链接都有一个非负整数的课时消耗，该消耗由一个隐藏但固定的规律生成
2. 学习路径的总课时消耗等于路径上所有知识链接的课时消耗之和
3. 如果路径中重复经过某个知识链接，则该链接的课时消耗会按经过次数重复计入
4. 课时消耗的生成规律在整个分析过程中保持一致

你最多可以进行 {max_queries} 次查询，每次查询可以选择以下两种类型之一：

询问某条特定学习路径的总课时消耗。路径必须满足：
- 至少包含 3 个学习模块（即至少 2 个知识链接）
- 相邻模块之间必须存在知识链接
- 可以包含重复的模块或链接
- 不能与目标学习路径完全相同

询问两条学习路径的课时消耗大小关系。两条路径均需满足上述路径查询的约束。

**路径课时查询**（例如查询路径 v1->v2->v3）：
<query_path>v1,v2,v3</query_path>

**路径对比查询**（例如对比路径 v1->v2->v3 和 v1->v3->v5）：
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

当你收集足够信息后，请提交最终推断答案，格式如下：

<answer>cost=数字, rule=规律描述</answer>

其中：
- cost：你推断的隐藏推荐学习路径总课时消耗（整数）
- rule：你归纳出的知识链接课时消耗生成规律的简要描述

例如：
<answer>cost=42, rule=每个链接的课时消耗等于其两端学习模块编号之和</answer>

- 你不能直接查询目标推荐学习路径本身
- 非法查询（如路径不满足约束）将返回错误信息
- 若推断课时错误或规律描述与实际不一致，则任务失败
- 请尽可能高效地使用查询次数
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Let's play a "Learning Path Class Hour Consumption Inference" game. Here are the rules:

The game is set in a subject knowledge network G with 6 core learning modules: v1, v2, v3, v4, v5, v6.

The set of knowledge links (edges) between modules is:
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

There is a hidden recommended learning path T in the syllabus. Your task is to infer the total class hour consumption required to complete this path.

1. Each knowledge link has a non-negative integer class hour consumption generated by a hidden but fixed rule
2. The total class hour consumption of a path equals the sum of the consumption of all knowledge links on the path
3. If a link is traversed multiple times in a path, its class hour consumption is counted multiple times
4. The rule for generating class hour consumption remains consistent throughout the analysis

You can make at most {max_queries} queries. Each query can be one of the following types:

Ask for the total class hour consumption of a specific learning path. The path must satisfy:
- At least 3 learning modules (i.e., at least 2 knowledge links)
- Adjacent modules must be connected by a knowledge link
- Can contain repeated modules or links
- Cannot be identical to the target learning path

Ask for the relationship of class hour consumption between two learning paths. Both paths must satisfy the above query constraints.

**Path Class Hour Query** (e.g., querying path v1->v2->v3):
<query_path>v1,v2,v3</query_path>

**Path Comparison Query** (e.g., comparing path v1->v2->v3 and v1->v3->v5):
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

When you have enough information, submit your final inferred answer in this format:

<answer>cost=number, rule=rule description</answer>

Where:
- cost: Your inferred total class hour consumption of the hidden recommended learning path (integer)
- rule: A brief description of the link consumption generation rule you identified

Example:
<answer>cost=42, rule=The class hour consumption of each link equals the sum of its endpoint module numbers</answer>

- You cannot directly query the target recommended learning path itself
- Invalid queries (e.g., paths not satisfying constraints) will return error messages
- If the inferred consumption is incorrect or the rule description is inconsistent with reality, the task fails
- Try to use your queries as efficiently as possible
"""

    contextualized_rule_zh_4 = """\
我们现在来玩一个“加工流程能耗推断”游戏，规则如下：

游戏设定了一个车间生产网络 G，包含 6 个加工工作站节点：v1, v2, v3, v4, v5, v6。

工作站之间的物料流转轨道（边）集合为：
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

生产计划中存在一条隐藏的特定产品定制加工流程 T，你的任务是推断出该流程的总物料流转能耗。

1. 每条流转轨道都有一个非负整数的搬运能耗，该能耗由一个隐藏但固定的规律生成
2. 流程的总流转能耗等于流程中所有经过轨道的搬运能耗之和
3. 如果流程中重复经过某条流转轨道，则该轨道的能耗会按经过次数重复计入
4. 流转能耗的生成规律在整个测算过程中保持一致

你最多可以进行 {max_queries} 次查询，每次查询可以选择以下两种类型之一：

询问某条加工流程的总流转能耗。流程必须满足：
- 至少包含 3 个工作站（即至少 2 条流转轨道）
- 相邻工作站之间必须存在流转轨道连接
- 可以包含重复的工作站或轨道
- 不能与目标加工流程完全相同

询问两条加工流程的流转能耗大小关系。两条流程均需满足上述能耗查询的约束。

**流程能耗查询**（例如查询流程 v1->v2->v3）：
<query_path>v1,v2,v3</query_path>

**流程对比查询**（例如对比流程 v1->v2->v3 和 v1->v3->v5）：
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

当你收集足够信息后，请提交最终推断答案，格式如下：

<answer>cost=数字, rule=规律描述</answer>

其中：
- cost：你推断的隐藏定制加工流程总流转能耗（整数）
- rule：你归纳出的轨道流转能耗生成规律的简要描述

例如：
<answer>cost=42, rule=每条轨道的能耗等于其两端工作站编号之和</answer>

- 你不能直接查询目标加工流程本身
- 非法查询（如流程不满足约束）将返回错误信息
- 若推断能耗错误或规律描述与实际不一致，则测算失败
- 请尽可能高效地使用查询次数
"""

    contextualized_rule_en_4 = """\
[Manufacturing/Industry Scenario]
Let's play a "Processing Workflow Energy Consumption Inference" game. Here are the rules:

The game is set in a workshop production network G with 6 processing workstation nodes: v1, v2, v3, v4, v5, v6.

The set of material transfer tracks (edges) between workstations is:
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

There is a hidden custom processing workflow T for a specific product in the production plan. Your task is to infer the total material transfer energy consumption of this workflow.

1. Each transfer track has a non-negative integer handling energy consumption generated by a hidden but fixed rule
2. The total transfer energy consumption of a workflow equals the sum of the consumption of all tracks passed in the workflow
3. If a track is traversed multiple times in a workflow, its energy consumption is counted multiple times
4. The rule for generating transfer energy consumption remains consistent throughout the estimation

You can make at most {max_queries} queries. Each query can be one of the following types:

Ask for the total transfer energy consumption of a processing workflow. The workflow must satisfy:
- At least 3 workstations (i.e., at least 2 transfer tracks)
- Adjacent workstations must be connected by a transfer track
- Can contain repeated workstations or tracks
- Cannot be identical to the target processing workflow

Ask for the relationship of transfer energy consumption between two workflows. Both workflows must satisfy the above query constraints.

**Workflow Energy Consumption Query** (e.g., querying workflow v1->v2->v3):
<query_path>v1,v2,v3</query_path>

**Workflow Comparison Query** (e.g., comparing workflow v1->v2->v3 and v1->v3->v5):
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

When you have enough information, submit your final inferred answer in this format:

<answer>cost=number, rule=rule description</answer>

Where:
- cost: Your inferred total transfer energy consumption of the hidden processing workflow (integer)
- rule: A brief description of the track energy consumption generation rule you identified

Example:
<answer>cost=42, rule=The energy consumption of each track equals the sum of its endpoint workstation numbers</answer>

- You cannot directly query the target processing workflow itself
- Invalid queries (e.g., workflows not satisfying constraints) will return error messages
- If the inferred energy consumption is incorrect or the rule description is inconsistent with reality, the estimation fails
- Try to use your queries as efficiently as possible
"""

    contextualized_rule_zh_5 = """\
我们现在来玩一个“诉讼程序审核周期推断”游戏，规则如下：

游戏设定了一个标准的司法审理流程图 G，包含 6 个法定审核程序节点：v1, v2, v3, v4, v5, v6。

程序之间合法的推进路径（边）集合为：
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

卷宗中存在一条隐藏的特定复杂案件审理程序路线 T，你的任务是推断出该路线所需的总法务审核周期（天数）。

1. 每条推进路径都有一个非负整数的审核周期，该周期由一个隐藏但固定的规则生成
2. 路线的总审核周期等于路线上所有推进路径的审核周期之和
3. 如果路线中重复经过某条推进路径，则该路径的审核周期会按经过次数重复计入
4. 推进路径审核周期的生成规则在整个分析过程中保持一致

你最多可以进行 {max_queries} 次查询，每次查询可以选择以下两种类型之一：

询问某条特定审理程序路线的总审核周期。路线必须满足：
- 至少包含 3 个审核程序（即至少 2 条推进路径）
- 相邻程序之间必须存在合法的推进路径连接
- 可以包含重复的程序或路径
- 不能与目标案件的审理程序路线完全相同

询问两条路线的审核周期大小关系。两条路线均需满足上述周期查询的约束。

**路线周期查询**（例如查询路线 v1->v2->v3）：
<query_path>v1,v2,v3</query_path>

**路线对比查询**（例如对比路线 v1->v2->v3 和 v1->v3->v5）：
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

当你收集足够信息后，请提交最终推断答案，格式如下：

<answer>cost=数字, rule=规律描述</answer>

其中：
- cost：你推断的隐藏案件审理程序路线总审核周期（整数）
- rule：你归纳出的推进路径审核周期生成规则的简要描述

例如：
<answer>cost=42, rule=每条推进路径的审核周期等于其两端程序节点编号之和</answer>

- 你不能直接查询目标审理程序路线本身
- 非法查询（如路线不满足约束）将返回错误信息
- 若推断周期错误或规则描述与实际不一致，则分析失败
- 请尽可能高效地使用查询次数
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
Let's play a "Litigation Procedure Review Cycle Inference" game. Here are the rules:

The game is set in a standard judicial trial flowchart G with 6 statutory review procedure nodes: v1, v2, v3, v4, v5, v6.

The set of legal advancement paths (edges) between procedures is:
- (v1,v2), (v2,v3), (v3,v4), (v4,v5), (v5,v6), (v6,v1)
- (v1,v3), (v3,v5), (v2,v4), (v4,v6)

There is a hidden trial procedure route T for a specific complex case in the dossier. Your task is to infer the total legal review cycle (in days) required for this route.

1. Each advancement path has a non-negative integer review cycle generated by a hidden but fixed rule
2. The total review cycle of a route equals the sum of the cycles of all advancement paths on the route
3. If a path is traversed multiple times in a route, its review cycle is counted multiple times
4. The rule for generating the review cycle remains consistent throughout the analysis

You can make at most {max_queries} queries. Each query can be one of the following types:

Ask for the total review cycle of a specific trial procedure route. The route must satisfy:
- At least 3 review procedures (i.e., at least 2 advancement paths)
- Adjacent procedures must be connected by a legal advancement path
- Can contain repeated procedures or paths
- Cannot be identical to the target trial procedure route

Ask for the relationship of review cycle between two routes. Both routes must satisfy the above query constraints.

**Route Cycle Query** (e.g., querying route v1->v2->v3):
<query_path>v1,v2,v3</query_path>

**Route Comparison Query** (e.g., comparing route v1->v2->v3 and v1->v3->v5):
<query_compare>v1,v2,v3|v1,v3,v5</query_compare>

When you have enough information, submit your final inferred answer in this format:

<answer>cost=number, rule=rule description</answer>

Where:
- cost: Your inferred total legal review cycle of the hidden trial procedure route (integer)
- rule: A brief description of the path review cycle generation rule you identified

Example:
<answer>cost=42, rule=The review cycle of each path equals the sum of its endpoint procedure numbers</answer>

- You cannot directly query the target trial procedure route itself
- Invalid queries (e.g., routes not satisfying constraints) will return error messages
- If the inferred cycle is incorrect or the rule description is inconsistent with reality, the analysis fails
- Try to use your queries as efficiently as possible
"""

    tags = ["answer", "query_path", "query_compare"]
    
    reasoning_type = "归纳推理"
    data_structure = "图"

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "max_queries": 8,
                "target_path": ["v1", "v2", "v3", "v4"],
                "rule_type": "sum",
                "vertex_params": None,
            },
            2: {
                "max_queries": 8,
                "target_path": ["v1", "v3", "v5", "v6", "v4"],
                "rule_type": "diff_plus_one",
                "vertex_params": None,
            },
            3: {
                "max_queries": 8,
                "target_path": ["v1", "v2", "v4", "v3", "v5", "v6"],
                "rule_type": "product_mod",
                "vertex_params": None,
            },
            4: {
                "max_queries": 8,
                "target_path": ["v2", "v1", "v3", "v5", "v4", "v6", "v1"],
                "rule_type": "square_sum_mod",
                "vertex_params": None,
            },
            5: {
                "max_queries": 8,
                "target_path": ["v1", "v2", "v4", "v3", "v5", "v6", "v1"],
                "rule_type": "vertex_weight",
                "vertex_params": {"v1": 3, "v2": 5, "v3": 2, "v4": 7, "v5": 4, "v6": 6},
            },
        },
        "en": {
            1: {
                "max_queries": 8,
                "target_path": ["v1", "v2", "v3", "v4"],
                "rule_type": "sum",
                "vertex_params": None,
            },
            2: {
                "max_queries": 8,
                "target_path": ["v1", "v3", "v5", "v6", "v4"],
                "rule_type": "diff_plus_one",
                "vertex_params": None,
            },
            3: {
                "max_queries": 8,
                "target_path": ["v1", "v2", "v4", "v3", "v5", "v6"],
                "rule_type": "product_mod",
                "vertex_params": None,
            },
            4: {
                "max_queries": 8,
                "target_path": ["v2", "v1", "v3", "v5", "v4", "v6", "v1"],
                "rule_type": "square_sum_mod",
                "vertex_params": None,
            },
            5: {
                "max_queries": 8,
                "target_path": ["v1", "v2", "v4", "v3", "v5", "v6", "v1"],
                "rule_type": "vertex_weight",
                "vertex_params": {"v1": 3, "v2": 5, "v3": 2, "v4": 7, "v5": 4, "v6": 6},
            },
        },
    }

    def __init__(self, config):
        self.edges = {
            ("v1", "v2"), ("v2", "v1"),
            ("v2", "v3"), ("v3", "v2"),
            ("v3", "v4"), ("v4", "v3"),
            ("v4", "v5"), ("v5", "v4"),
            ("v5", "v6"), ("v6", "v5"),
            ("v6", "v1"), ("v1", "v6"),
            ("v1", "v3"), ("v3", "v1"),
            ("v3", "v5"), ("v5", "v3"),
            ("v2", "v4"), ("v4", "v2"),
            ("v4", "v6"), ("v6", "v4"),
        }
        self.query_count = 0
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = self.config.difficulty

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        self._game_info["max_queries"] = cfg["max_queries"]
        self.max_queries = cfg["max_queries"]
        self.target_path = cfg["target_path"]
        self.rule_type = cfg["rule_type"]
        self.vertex_params = cfg["vertex_params"]
        
        self.target_cost = self._calculate_path_cost(self.target_path)

    def _get_vertex_number(self, vertex):
        return int(vertex[1])

    def _calculate_edge_cost(self, v1, v2):
        if self.rule_type == "sum":
            return self._get_vertex_number(v1) + self._get_vertex_number(v2)
        
        elif self.rule_type == "diff_plus_one":
            n1 = self._get_vertex_number(v1)
            n2 = self._get_vertex_number(v2)
            return abs(n1 - n2) + 1
        
        elif self.rule_type == "product_mod":
            n1 = self._get_vertex_number(v1)
            n2 = self._get_vertex_number(v2)
            return (n1 * n2) % 7
        
        elif self.rule_type == "square_sum_mod":
            n1 = self._get_vertex_number(v1)
            n2 = self._get_vertex_number(v2)
            return (n1 * n1 + n2 * n2) % 10
        
        elif self.rule_type == "vertex_weight":
            return self.vertex_params[v1] + self.vertex_params[v2]
        
        else:
            raise ValueError(f"Unknown rule type: {self.rule_type}")

    def _calculate_path_cost(self, path):
        total_cost = 0
        for i in range(len(path) - 1):
            total_cost += self._calculate_edge_cost(path[i], path[i + 1])
        return total_cost

    def _validate_path(self, path):
        if len(path) < 3:
            return False, "路径长度不足（至少需要3个顶点）" if self.config.language == "zh" else "Path too short (at least 3 vertices required)"
        
        for v in path:
            if not re.match(r'^v[1-6]$', v):
                return False, f"无效的顶点名称: {v}" if self.config.language == "zh" else f"Invalid vertex name: {v}"
        
        for i in range(len(path) - 1):
            if (path[i], path[i + 1]) not in self.edges:
                return False, f"顶点 {path[i]} 和 {path[i + 1]} 之间不存在边" if self.config.language == "zh" else f"No edge between {path[i]} and {path[i + 1]}"
        
        if path == self.target_path:
            return False, "不能直接查询目标路径" if self.config.language == "zh" else "Cannot query the target path directly"
        
        return True, ""

    def _get_rule_description(self):
        if self.config.language == "zh":
            if self.rule_type == "sum":
                return ["两端点编号之和", "顶点编号之和", "端点编号和"]
            elif self.rule_type == "diff_plus_one":
                return ["端点编号差的绝对值加1", "编号差的绝对值+1", "|编号差|+1"]
            elif self.rule_type == "product_mod":
                return ["端点编号乘积模7", "编号乘积mod7", "(编号乘积)%7"]
            elif self.rule_type == "square_sum_mod":
                return ["端点编号平方和模10", "编号平方和mod10", "(编号平方和)%10"]
            elif self.rule_type == "vertex_weight":
                return ["两端点权重之和", "顶点权重之和", "端点权重和"]
        else:
            if self.rule_type == "sum":
                return ["sum of endpoint numbers", "vertex number sum", "endpoint sum"]
            elif self.rule_type == "diff_plus_one":
                return ["absolute difference of endpoint numbers plus 1", "|difference| + 1"]
            elif self.rule_type == "product_mod":
                return ["product of endpoint numbers mod 7", "(product) % 7"]
            elif self.rule_type == "square_sum_mod":
                return ["sum of squared endpoint numbers mod 10", "(square sum) % 10"]
            elif self.rule_type == "vertex_weight":
                return ["sum of endpoint weights", "vertex weight sum"]
        return []

    def evaluate(self, parsed_info):
        raw_ans = parsed_info["answer"]
        
        try:
            cost_match = re.search(r'cost\s*=\s*(-?\d+)', raw_ans, re.IGNORECASE)
            if not cost_match:
                return False
            predicted_cost = int(cost_match.group(1))
            
            if predicted_cost != self.target_cost:
                return False
            
            rule_match = re.search(r'rule\s*=\s*(.+)', raw_ans, re.IGNORECASE)
            if not rule_match or not rule_match.group(1).strip():
                return False
            
            return True
            
        except Exception:
            return False

    def produce_response(self, parsed_info):
        if self.query_count >= self.max_queries:
            if self.config.language == "zh":
                return f"错误：已达到最大查询次数（{self.max_queries}次）"
            else:
                return f"Error: Maximum query limit reached ({self.max_queries} queries)"
        
        return super().produce_response(parsed_info)

    def _cf_core_produce(self, parsed_info):
        if "query_path" in parsed_info:
            path_str = parsed_info["query_path"].strip()
            path = [v.strip() for v in path_str.split(",")]
            
            is_valid, error_msg = self._validate_path(path)
            if not is_valid:
                if self.config.language == "zh":
                    return f"无效查询：{error_msg}"
                else:
                    return f"Invalid query: {error_msg}"
            
            self.query_count += 1
            cost = self._calculate_path_cost(path)
            
            if self.config.language == "zh":
                return f"路径代价：{cost}；剩余查询次数：{self.max_queries - self.query_count}"
            else:
                return f"Path cost: {cost}; Remaining queries: {self.max_queries - self.query_count}"
        
        elif "query_compare" in parsed_info:
            compare_str = parsed_info["query_compare"].strip()
            
            if "|" not in compare_str:
                if self.config.language == "zh":
                    return "无效查询：对比查询格式错误，请使用'路径A|路径B'的格式"
                else:
                    return "Invalid query: Comparison format error, use 'pathA|pathB'"
            
            path_a_str, path_b_str = compare_str.split("|", 1)
            path_a = [v.strip() for v in path_a_str.split(",")]
            path_b = [v.strip() for v in path_b_str.split(",")]
            
            is_valid_a, error_msg_a = self._validate_path(path_a)
            if not is_valid_a:
                if self.config.language == "zh":
                    return f"无效查询：路径A - {error_msg_a}"
                else:
                    return f"Invalid query: Path A - {error_msg_a}"
            
            is_valid_b, error_msg_b = self._validate_path(path_b)
            if not is_valid_b:
                if self.config.language == "zh":
                    return f"无效查询：路径B - {error_msg_b}"
                else:
                    return f"Invalid query: Path B - {error_msg_b}"
            
            self.query_count += 1
            cost_a = self._calculate_path_cost(path_a)
            cost_b = self._calculate_path_cost(path_b)
            
            if cost_a > cost_b:
                comparison = "A>B"
            elif cost_a < cost_b:
                comparison = "A<B"
            else:
                comparison = "A=B"
            
            if self.config.language == "zh":
                return f"比较结果：{comparison}；剩余查询次数：{self.max_queries - self.query_count}"
            else:
                return f"Comparison result: {comparison}; Remaining queries: {self.max_queries - self.query_count}"
        
        else:
            if self.config.language == "zh":
                return "无效查询：未找到有效的查询标签"
            else:
                return "Invalid query: No valid query tag found"

    def _cf_make_wrong(self, correct):
        import random as _rnd
        cost_match = re.search(r'(\d+)', correct)
        if cost_match:
            original_val = int(cost_match.group(1))
            wrong_val = original_val + _rnd.choice([1, 2, 3, -1, -2, -3])
            if wrong_val < 0:
                wrong_val = original_val + 5
            return correct.replace(cost_match.group(1), str(wrong_val), 1)
        return correct + " [corrupted]"

    def get_all_possible_queries(self) -> list[dict]:
        queries = []
        
        adj = {f"v{i}": set() for i in range(1, 7)}
        for (u, v) in self.edges:
            adj[u].add(v)
        adj = {k: sorted(list(v)) for k, v in adj.items()}
        
        paths = []
        seen_paths = set()
        
        def dfs(path):
            if len(path) >= 3:
                path_key = tuple(path)
                if path_key not in seen_paths:
                    seen_paths.add(path_key)
                    paths.append(path[:])
            
            if len(path) >= 4:
                return
                
            last_v = path[-1]
            for neighbor in adj[last_v]:
                dfs(path + [neighbor])
                
        for start_node in sorted(adj.keys()):
            dfs([start_node])
            
        query_idx = 0
        for p in paths:
            if p == self.target_path:
                continue
                
            path_str = ",".join(p)
            query_content = f"<query_path>{path_str}</query_path>"
            
            cost = self._calculate_path_cost(p)
            query_idx += 1
            remaining = self.max_queries - query_idx
            
            if self.config.language == "zh":
                ans = f"路径代价：{cost}；剩余查询次数：{remaining}"
            else:
                ans = f"Path cost: {cost}; Remaining queries: {remaining}"
                
            queries.append({
                "query": query_content,
                "answer": ans
            })
            
        return queries