from .base import Game
import random
from typing import List, Dict

class GAME162(Game):

    game_rule_zh = """\
我们来玩一个"序列规律推理"游戏，规则如下：

游戏设定了一个长度为 {n} 的正整数序列 a[1], a[2], ..., a[{n}]，其中每个元素 a[i] 都是非负整数。这个序列由某个固定的规律生成（例如：等差数列、周期性模式、多项式规律等），但具体的生成规则对你保密。

你的目标是通过有限次查询，推断出这个序列的规律，并能够准确预测任意位置的前缀和与前缀最大值。

你最多可以进行 {q} 次查询。每次查询时，你需要指定一个索引 k（1 到 {n} 之间），并选择以下两种查询类型之一：

1. 前缀和查询：查询从位置 1 到 k 的所有元素之和，即 S(k) = a[1] + a[2] + ... + a[k]。
2. 前缀最大查询：查询从位置 1 到 k 中的最大元素值，即 M(k) = max(a[1], a[2], ..., a[k])。

注意：你不能直接查询某个位置的具体值 a[k]，只能通过前缀和或前缀最大来间接推断。同一个索引可以重复查询，但每次都会计入查询次数。

当你认为已经掌握了序列规律后，可以提交"结束猜测"指令。之后系统会随机选取 {t} 个你在查询阶段未询问过的索引，要求你预测这些位置的前缀和与前缀最大值。只有当所有预测都完全正确时，你才能获胜。

每次查询只能包含一个标签，使用以下 XML 格式：

- 前缀和查询（例如查询索引 5）：
<query_sum>5</query_sum>

- 前缀最大查询（例如查询索引 8）：
<query_max>8</query_max>

- 结束查询并进入验证阶段：
<finish></finish>

- 在验证阶段提交预测（例如索引 7 的前缀和预测为 28，前缀最大预测为 10）：
<predict>index=7, sum=28, max=10</predict>

每个验证索引都需要单独提交一次预测。
"""

    game_rule_en = """\
Let's play a "Sequence Rule Deduction" game. Here are the rules:

The game has set up a sequence of length {n}, denoted as a[1], a[2], ..., a[{n}], where each element a[i] is a non-negative integer. This sequence is generated by a fixed rule (e.g., arithmetic progression, periodic pattern, polynomial rule, etc.), but the specific generation rule is kept secret from you.

Your goal is to deduce the rule of this sequence through a limited number of queries, and accurately predict the prefix sum and prefix maximum at any position.

You can make at most {q} queries. In each query, you need to specify an index k (between 1 and {n}), and choose one of the following two query types:

1. Prefix Sum Query: Query the sum of all elements from position 1 to k, i.e., S(k) = a[1] + a[2] + ... + a[k].
2. Prefix Maximum Query: Query the maximum element value from position 1 to k, i.e., M(k) = max(a[1], a[2], ..., a[k]).

Note: You cannot directly query the specific value a[k] at a position; you can only infer indirectly through prefix sum or prefix maximum. The same index can be queried multiple times, but each query counts toward the query limit.

When you believe you have mastered the sequence rule, you can submit a "finish" instruction. The system will then randomly select {t} indices that you did not query during the query phase, and ask you to predict the prefix sum and prefix maximum at these positions. You can only win if all predictions are completely correct.

Each query can only contain one tag. Use the following XML format:

- Prefix Sum Query (e.g., querying index 5):
<query_sum>5</query_sum>

- Prefix Maximum Query (e.g., querying index 8):
<query_max>8</query_max>

- Finish queries and enter verification phase:
<finish></finish>

- Submit prediction during verification phase (e.g., for index 7, predict prefix sum as 28 and prefix max as 10):
<predict>index=7, sum=28, max=10</predict>

Each verification index needs to be submitted separately.
"""

    contextualized_rule_zh_1 = """\
我们来玩一个"交通流量推演"游戏，规则如下：

系统设定了一段连续的道路，划分为 {n} 个监测区间，记为区间 1 到 {n}。每个区间的车流量 a[i] 都是非负整数。这个车流序列由交通系统的固定规律生成（例如：早晚高峰周期、平稳车流、路口分流等），但具体的生成规则对你保密。

你的目标是通过有限次查询，推断出这个车流规律，并能够准确预测任意位置的累计车流量与单区间最大车流峰值。

你最多可以进行 {q} 次查询。每次查询时，你需要指定一个区间索引 k（1 到 {n} 之间），并选择以下两种查询类型之一：

1. 前缀和查询：查询从起点到第 k 个区间的累计车流量，即 S(k) = a[1] + a[2] + ... + a[k]。
2. 前缀最大查询：查询从起点到第 k 个区间中，单区间的最大车流量，即 M(k) = max(a[1], a[2], ..., a[k])。

注意：你不能直接查询某个区间 k 的具体车流量 a[k]，只能通过累计值或最大值来间接推断。同一个区间可以重复查询，但每次都会计入查询次数。

当你认为已经掌握了车流规律后，可以提交"结束猜测"指令。之后系统会随机选取 {t} 个你在查询阶段未询问过的区间，要求你预测这些区间的累计车流量与最大车流量。只有当所有预测都完全正确时，你才能获胜。

每次查询只能包含一个标签，使用以下 XML 格式：

- 前缀和查询（例如查询区间 5）：
<query_sum>5</query_sum>

- 前缀最大查询（例如查询区间 8）：
<query_max>8</query_max>

- 结束查询并进入验证阶段：
<finish></finish>

- 在验证阶段提交预测（例如区间 7 的累计车流预测为 28，最大车流预测为 10）：
<predict>index=7, sum=28, max=10</predict>

每个验证区间都需要单独提交一次预测。
"""

    contextualized_rule_en_1 = """\
[Traffic Scenario]
Let's play a "Traffic Flow Deduction" game. Here are the rules:

The system has monitored a continuous road segment divided into {n} intervals, denoted as interval 1 to {n}. The traffic flow a[i] in each interval is a non-negative integer. This sequence is generated by a fixed rule of the traffic system (e.g., peak cycles, steady flow, intersection divergence), but the specific generation rule is kept secret from you.

Your goal is to deduce the traffic flow rule through a limited number of queries, and accurately predict the cumulative traffic flow and the maximum single-interval traffic peak at any position.

You can make at most {q} queries. In each query, you need to specify an interval index k (between 1 and {n}), and choose one of the following two query types:

1. Prefix Sum Query: Query the cumulative traffic flow from interval 1 to k, i.e., S(k) = a[1] + a[2] + ... + a[k].
2. Prefix Maximum Query: Query the maximum traffic flow among intervals from 1 to k, i.e., M(k) = max(a[1], a[2], ..., a[k]).

Note: You cannot directly query the specific traffic flow a[k] at an interval; you can only infer indirectly through cumulative or maximum values. The same interval can be queried multiple times, but each query counts toward the query limit.

When you believe you have mastered the traffic rule, you can submit a "finish" instruction. The system will then randomly select {t} intervals that you did not query during the query phase, and ask you to predict the cumulative and maximum traffic flow at these positions. You can only win if all predictions are completely correct.

Each query can only contain one tag. Use the following XML format:

- Prefix Sum Query (e.g., querying interval 5):
<query_sum>5</query_sum>

- Prefix Maximum Query (e.g., querying interval 8):
<query_max>8</query_max>

- Finish queries and enter verification phase:
<finish></finish>

- Submit prediction during verification phase (e.g., for interval 7, predict cumulative flow as 28 and maximum flow as 10):
<predict>index=7, sum=28, max=10</predict>

Each verification interval needs to be submitted separately.
"""

    contextualized_rule_zh_2 = """\
我们来玩一个"生化指标推演"游戏，规则如下：

系统记录了某患者连续 {n} 天的特定生化代谢物指标，记为第 1 天到第 {n} 天。每天的代谢增量 a[i] 均为非负整数。这些指标增量受限于特定的生理周期或病理模型（如药效半衰、周期性波动等），但具体的生理规律对你保密。

你的目标是通过有限次查询，推断出患者的生化代谢规律，并能够准确预测任意天数区间的累计代谢总量与单日最高代谢极值。

你最多可以进行 {q} 次查询。每次查询时，你需要指定一个天数索引 k（1 到 {n} 之间），并选择以下两种查询类型之一：

1. 前缀和查询：查询从第 1 天到第 k 天的累计代谢总量，即 S(k) = a[1] + a[2] + ... + a[k]。
2. 前缀最大查询：查询从第 1 天到第 k 天中，单日的最高代谢极值，即 M(k) = max(a[1], a[2], ..., a[k])。

注意：你不能直接查询某一天 k 的具体代谢量 a[k]，只能通过累计值或极值来间接推断。同一天可以重复查询，但每次都会计入查询次数。

当你认为已经掌握了代谢规律后，可以提交"结束猜测"指令。之后系统会随机选取 {t} 个你在查询阶段未化验过的天数，要求你预测这些日期的累计代谢总量与单日最高极值。只有当所有预测都完全正确时，你才能获胜。

每次查询只能包含一个标签，使用以下 XML 格式：

- 前缀和查询（例如查询第 5 天）：
<query_sum>5</query_sum>

- 前缀最大查询（例如查询第 8 天）：
<query_max>8</query_max>

- 结束查询并进入验证阶段：
<finish></finish>

- 在验证阶段提交预测（例如第 7 天的累计代谢量预测为 28，最高极值预测为 10）：
<predict>index=7, sum=28, max=10</predict>

每个验证天数都需要单独提交一次预测。
"""

    contextualized_rule_en_2 = """\
[Medical Scenario]
Let's play a "Biochemical Index Deduction" game. Here are the rules:

The system has recorded a patient's specific biochemical metabolic index over a continuous period of {n} days, denoted as day 1 to {n}. The daily metabolic increment a[i] is a non-negative integer. These increments are governed by a specific physiological cycle or pathological model (e.g., drug half-life, periodic fluctuations), but the exact physiological rule is kept secret from you.

Your goal is to deduce the patient's metabolic rule through a limited number of queries, and accurately predict the cumulative metabolic volume and the single-day metabolic peak for any period.

You can make at most {q} queries. In each query, you need to specify a day index k (between 1 and {n}), and choose one of the following two query types:

1. Prefix Sum Query: Query the cumulative metabolic volume from day 1 to k, i.e., S(k) = a[1] + a[2] + ... + a[k].
2. Prefix Maximum Query: Query the highest single-day metabolic peak among days from 1 to k, i.e., M(k) = max(a[1], a[2], ..., a[k]).

Note: You cannot directly query the specific metabolic volume a[k] on a particular day; you can only infer indirectly through cumulative or maximum values. The same day can be queried multiple times, but each query counts toward the query limit.

When you believe you have mastered the metabolic rule, you can submit a "finish" instruction. The system will then randomly select {t} days that you did not query during the testing phase, and ask you to predict the cumulative metabolic volume and maximum single-day peak at these positions. You can only win if all predictions are completely correct.

Each query can only contain one tag. Use the following XML format:

- Prefix Sum Query (e.g., querying day 5):
<query_sum>5</query_sum>

- Prefix Maximum Query (e.g., querying day 8):
<query_max>8</query_max>

- Finish queries and enter verification phase:
<finish></finish>

- Submit prediction during verification phase (e.g., for day 7, predict cumulative metabolism as 28 and maximum peak as 10):
<predict>index=7, sum=28, max=10</predict>

Each verification day needs to be submitted separately.
"""

    contextualized_rule_zh_3 = """\
我们来玩一个"学习进度推演"游戏，规则如下：

系统追踪了一名学生在 {n} 个连续教学周内的学习数据，记为第 1 周到第 {n} 周。每周掌握的新知识点数量 a[i] 均为非负整数。学习进度遵循特定的教学计划规律（如渐进递增、阶段性复习周期等），但具体的教学安排对你保密。

你的目标是通过有限次查询，推断出学生的学习曲线规律，并能够准确预测任意阶段的累计掌握知识点总数与单周最高知识点掌握量。

你最多可以进行 {q} 次查询。每次查询时，你需要指定一个周数索引 k（1 到 {n} 之间），并选择以下两种查询类型之一：

1. 前缀和查询：查询从第 1 周到第 k 周累计掌握的知识点总数，即 S(k) = a[1] + a[2] + ... + a[k]。
2. 前缀最大查询：查询从第 1 周到第 k 周内，单周掌握知识点的最高数量，即 M(k) = max(a[1], a[2], ..., a[k])。

注意：你不能直接查询某一单周 k 的具体掌握量 a[k]，只能通过累计值或最高值来间接推断。同一周次可以重复查询，但每次都会计入测试次数。

当你认为已经摸清了学习规律后，可以提交"结束猜测"指令。之后系统会随机选取 {t} 个你在查询阶段未测验过的周次，要求你预测这些阶段的累计知识点总数与最高单周掌握量。只有当所有预测都完全正确时，你才能获胜。

每次查询只能包含一个标签，使用以下 XML 格式：

- 前缀和查询（例如查询第 5 周）：
<query_sum>5</query_sum>

- 前缀最大查询（例如查询第 8 周）：
<query_max>8</query_max>

- 结束查询并进入验证阶段：
<finish></finish>

- 在验证阶段提交预测（例如第 7 周的累计知识点预测为 28，最高单周数量预测为 10）：
<predict>index=7, sum=28, max=10</predict>

每个验证周次都需要单独提交一次预测。
"""

    contextualized_rule_en_3 = """\
[Education Scenario]
Let's play a "Learning Progress Deduction" game. Here are the rules:

The system has tracked a student's learning data over {n} continuous academic weeks, denoted as week 1 to {n}. The number of new knowledge points mastered each week a[i] is a non-negative integer. The learning progress follows a specific pedagogical rule (e.g., steady increment, periodic review cycles), but the specific teaching arrangement is kept secret from you.

Your goal is to deduce the student's learning curve rule through a limited number of queries, and accurately predict the cumulative knowledge points mastered and the maximum knowledge points per week at any given stage.

You can make at most {q} queries. In each query, you need to specify a week index k (between 1 and {n}), and choose one of the following two query types:

1. Prefix Sum Query: Query the cumulative knowledge points mastered from week 1 to k, i.e., S(k) = a[1] + a[2] + ... + a[k].
2. Prefix Maximum Query: Query the highest number of knowledge points mastered in a single week among weeks from 1 to k, i.e., M(k) = max(a[1], a[2], ..., a[k]).

Note: You cannot directly query the specific number of points a[k] in a single week; you can only infer indirectly through cumulative or maximum values. The same week can be queried multiple times, but each query counts toward the query limit.

When you believe you have figured out the learning rule, you can submit a "finish" instruction. The system will then randomly select {t} weeks that you did not query during the testing phase, and ask you to predict the cumulative and maximum knowledge points at these stages. You can only win if all predictions are completely correct.

Each query can only contain one tag. Use the following XML format:

- Prefix Sum Query (e.g., querying week 5):
<query_sum>5</query_sum>

- Prefix Maximum Query (e.g., querying week 8):
<query_max>8</query_max>

- Finish queries and enter verification phase:
<finish></finish>

- Submit prediction during verification phase (e.g., for week 7, predict cumulative points as 28 and maximum weekly points as 10):
<predict>index=7, sum=28, max=10</predict>

Each verification week needs to be submitted separately.
"""

    contextualized_rule_zh_4 = """\
我们来玩一个"次品率追踪"游戏，规则如下：

某条智能流水线进行了 {n} 个连续的生产批次，记为批次 1 到 {n}。每个批次产出的次品数量 a[i] 均为非负整数。次品率的变化受机器磨损、定期维护等工业规律影响（如常数磨损、周期性维护等），但具体的生产线衰减模型对你保密。

你的目标是通过有限次查询，推断出生产线的衰减与维护规律，并能够准确预测任意批次的累计次品总数与单批次最高次品数量。

你最多可以请求 {q} 次质检查询。每次查询时，你需要指定一个批次索引 k（1 到 {n} 之间），并选择以下两种查询类型之一：

1. 前缀和查询：查询从第 1 批次到第 k 批次的累计次品总数，即 S(k) = a[1] + a[2] + ... + a[k]。
2. 前缀最大查询：查询从第 1 批次到第 k 批次中，单批次次品数量的最高值，即 M(k) = max(a[1], a[2], ..., a[k])。

注意：你不能直接查询某一单批次 k 的具体次品量 a[k]，只能通过累计值或极值来间接推断。同一批次可以重复查询，但每次都会计入质检次数。

当你认为已经掌握了次品产出规律后，可以提交"结束猜测"指令。之后系统会随机选取 {t} 个你在查询阶段未抽检过的批次，要求你预测这些批次的累计次品总数与最高次品峰值。只有当所有预测都完全正确时，你才能获胜。

每次查询只能包含一个标签，使用以下 XML 格式：

- 前缀和查询（例如查询批次 5）：
<query_sum>5</query_sum>

- 前缀最大查询（例如查询批次 8）：
<query_max>8</query_max>

- 结束查询并进入验证阶段：
<finish></finish>

- 在验证阶段提交预测（例如批次 7 的累计次品数预测为 28，最高次品数预测为 10）：
<predict>index=7, sum=28, max=10</predict>

每个验证批次都需要单独提交一次预测。
"""

    contextualized_rule_en_4 = """\
[Manufacturing Scenario]
Let's play a "Defect Rate Tracking" game. Here are the rules:

An assembly line has undergone {n} continuous production batches, denoted as batch 1 to {n}. The number of defective products a[i] in each batch is a non-negative integer. The defect rate is influenced by industrial rules such as machine wear and periodic maintenance (e.g., constant wear, cyclical maintenance), but the exact degradation model is kept secret from you.

Your goal is to deduce the production line's degradation and maintenance rule through a limited number of queries, and accurately predict the cumulative defect count and the maximum single-batch defect count at any given stage.

You can make at most {q} quality inspection queries. In each query, you need to specify a batch index k (between 1 and {n}), and choose one of the following two query types:

1. Prefix Sum Query: Query the cumulative defect count from batch 1 to k, i.e., S(k) = a[1] + a[2] + ... + a[k].
2. Prefix Maximum Query: Query the highest single-batch defect count among batches from 1 to k, i.e., M(k) = max(a[1], a[2], ..., a[k]).

Note: You cannot directly query the specific defect count a[k] for a single batch; you can only infer indirectly through cumulative or maximum values. The same batch can be queried multiple times, but each query counts toward the inspection limit.

When you believe you have mastered the defect rule, you can submit a "finish" instruction. The system will then randomly select {t} batches that you did not query during the testing phase, and ask you to predict the cumulative and maximum defect counts at these positions. You can only win if all predictions are completely correct.

Each query can only contain one tag. Use the following XML format:

- Prefix Sum Query (e.g., querying batch 5):
<query_sum>5</query_sum>

- Prefix Maximum Query (e.g., querying batch 8):
<query_max>8</query_max>

- Finish queries and enter verification phase:
<finish></finish>

- Submit prediction during verification phase (e.g., for batch 7, predict cumulative defects as 28 and maximum single-batch defects as 10):
<predict>index=7, sum=28, max=10</predict>

Each verification batch needs to be submitted separately.
"""

    contextualized_rule_zh_5 = """\
我们来玩一个"合规审查推演"游戏，规则如下：

一家大型企业在连续 {n} 个月内的合规违约数据被审计部门记录，记为第 1 个月到第 {n} 个月。每月的违规事件数量 a[i] 均为非负整数。违规频次受到政策周期、内部审查强度等规律性影响（如阶段性严打、周期性松懈等），但具体的合规波动模型对你保密。

你的目标是通过有限次查询，推演出企业的违约波动规律，并能够准确预测任意审计节点的累计违规事件总数与单月最高爆发违规数。

你最多可以进行 {q} 次审计查询。每次查询时，你需要指定一个月度索引 k（1 到 {n} 之间），并选择以下两种调阅类型之一：

1. 前缀和查询：查询从第 1 个月到第 k 个月的累计违规事件总数，即 S(k) = a[1] + a[2] + ... + a[k]。
2. 前缀最大查询：查询从第 1 个月到第 k 个月中，单月爆发违规事件的最高记录，即 M(k) = max(a[1], a[2], ..., a[k])。

注意：你不能直接调阅某一个月 k 的具体违规数量 a[k]，只能通过累计案卷总数或极值来间接推演。同一个月份可以重复查询，但每次都会消耗审计查询次数。

当你认为已经掌握了合规违约规律后，可以提交"结束猜测"指令。之后系统会随机抽取 {t} 个你在调查阶段未调阅过的月份，要求你预测这些节点的累计违规数与单月最高记录。只有当所有预测都完全正确时，你才能成功完成审计。

每次查询只能包含一个标签，使用以下 XML 格式：

- 前缀和查询（例如查询第 5 个月）：
<query_sum>5</query_sum>

- 前缀最大查询（例如查询第 8 个月）：
<query_max>8</query_max>

- 结束查询并进入验证阶段：
<finish></finish>

- 在验证阶段提交预测（例如月份 7 的累计违规数预测为 28，最高违规数预测为 10）：
<predict>index=7, sum=28, max=10</predict>

每个验证月份都需要单独提交一次预测。
"""

    contextualized_rule_en_5 = """\
[Legal Scenario]
Let's play a "Compliance Audit Deduction" game. Here are the rules:

A large enterprise's compliance violation data over {n} continuous months has been recorded by the auditing department, denoted as month 1 to {n}. The number of violation events each month a[i] is a non-negative integer. The violation frequency is influenced by regulatory cycles and internal audit intensity (e.g., periodic strict enforcement, cyclical laxity), but the exact compliance fluctuation model is kept secret from you.

Your goal is to deduce the enterprise's violation fluctuation rule through a limited number of queries, and accurately predict the cumulative compliance violations and the maximum monthly violations at any given audit node.

You can make at most {q} audit queries. In each query, you need to specify a month index k (between 1 and {n}), and choose one of the following two query types:

1. Prefix Sum Query: Query the cumulative violation events from month 1 to k, i.e., S(k) = a[1] + a[2] + ... + a[k].
2. Prefix Maximum Query: Query the highest single-month violation events recorded among months from 1 to k, i.e., M(k) = max(a[1], a[2], ..., a[k]).

Note: You cannot directly review the specific violation count a[k] for a single month; you can only deduce indirectly through cumulative totals or maximum peaks. The same month can be queried multiple times, but each query consumes an audit query slot.

When you believe you have mastered the compliance violation rule, you can submit a "finish" instruction. The system will then randomly sample {t} months that you did not review during the investigation phase, and ask you to predict the cumulative and maximum violation events at these nodes. You can only successfully complete the audit if all predictions are completely correct.

Each query can only contain one tag. Use the following XML format:

- Prefix Sum Query (e.g., querying month 5):
<query_sum>5</query_sum>

- Prefix Maximum Query (e.g., querying month 8):
<query_max>8</query_max>

- Finish queries and enter verification phase:
<finish></finish>

- Submit prediction during verification phase (e.g., for month 7, predict cumulative violations as 28 and maximum violations as 10):
<predict>index=7, sum=28, max=10</predict>

Each verification month needs to be submitted separately.
"""

    tags = ["query_sum", "query_max", "finish", "predict", "answer"]
    reasoning_type = "归纳推理"
    data_structure = "序列"

    DIFFICULTY_CONFIG = {
        "zh": {
            1: {
                "n": 20,
                "q": 12,
                "t": 3,
                "rule_type": "constant",
                "params": {"value": 5},
                "description": "常数序列"
            },
            2: {
                "n": 30,
                "q": 12,
                "t": 3,
                "rule_type": "arithmetic",
                "params": {"first": 2, "diff": 3},
                "description": "等差数列"
            },
            3: {
                "n": 40,
                "q": 12,
                "t": 4,
                "rule_type": "periodic",
                "params": {"pattern": [1, 3, 2, 5]},
                "description": "周期序列"
            },
            4: {
                "n": 50,
                "q": 12,
                "t": 4,
                "rule_type": "quadratic",
                "params": {"a": 1, "b": 2, "c": 1},
                "description": "二次多项式"
            },
            5: {
                "n": 60,
                "q": 12,
                "t": 5,
                "rule_type": "piecewise",
                "params": {"breakpoint": 30, "rule1": ("constant", 3), "rule2": ("arithmetic", 3, 2)},
                "description": "分段线性"
            },
        },
        "en": {
            1: {
                "n": 20,
                "q": 12,
                "t": 3,
                "rule_type": "constant",
                "params": {"value": 5},
                "description": "Constant Sequence"
            },
            2: {
                "n": 30,
                "q": 12,
                "t": 3,
                "rule_type": "arithmetic",
                "params": {"first": 2, "diff": 3},
                "description": "Arithmetic Sequence"
            },
            3: {
                "n": 40,
                "q": 12,
                "t": 4,
                "rule_type": "periodic",
                "params": {"pattern": [1, 3, 2, 5]},
                "description": "Periodic Sequence"
            },
            4: {
                "n": 50,
                "q": 12,
                "t": 4,
                "rule_type": "quadratic",
                "params": {"a": 1, "b": 2, "c": 1},
                "description": "Quadratic Polynomial"
            },
            5: {
                "n": 60,
                "q": 12,
                "t": 5,
                "rule_type": "piecewise",
                "params": {"breakpoint": 30, "rule1": ("constant", 3), "rule2": ("arithmetic", 3, 2)},
                "description": "Piecewise Linear"
            },
        },
    }

    def __init__(self, config):
        self.sequence = []
        self.prefix_sum = []
        self.prefix_max = []
        self.query_count = 0
        self.queried_indices = set()
        self.verification_phase = False
        self.verification_indices = []
        self.verification_results = {}
        super().__init__(config)

    def _initialize_game(self):
        lang = self.config.language
        diff = int(self.config.difficulty)

        if lang not in self.DIFFICULTY_CONFIG:
            raise KeyError(f"Unsupported language: {lang}")
        if diff not in self.DIFFICULTY_CONFIG[lang]:
            raise KeyError(f"Unsupported difficulty: {diff}")

        cfg = self.DIFFICULTY_CONFIG[lang][diff]
        self._game_info["n"] = cfg["n"]
        self._game_info["q"] = cfg["q"]
        self._game_info["t"] = cfg["t"]
        
        self.max_queries = cfg["q"]
        self.verification_count = cfg["t"]
        self.rule_type = cfg["rule_type"]
        self.params = cfg["params"]
        
        self._generate_sequence()
        
    def _generate_sequence(self):
        n = self._game_info["n"]
        
        if self.rule_type == "constant":
            value = self.params["value"]
            self.sequence = [value] * n
            
        elif self.rule_type == "arithmetic":
            first = self.params["first"]
            diff = self.params["diff"]
            self.sequence = [first + i * diff for i in range(n)]
            
        elif self.rule_type == "periodic":
            pattern = self.params["pattern"]
            period = len(pattern)
            self.sequence = [pattern[i % period] for i in range(n)]
            
        elif self.rule_type == "quadratic":
            a = self.params["a"]
            b = self.params["b"]
            c = self.params["c"]
            self.sequence = [a * (i+1)**2 + b * (i+1) + c for i in range(n)]
            
        elif self.rule_type == "piecewise":
            breakpoint = self.params["breakpoint"]
            rule1_type, *rule1_params = self.params["rule1"]
            rule2_type, *rule2_params = self.params["rule2"]
            
            self.sequence = []
            for i in range(1, n + 1):
                if i <= breakpoint:
                    if rule1_type == "constant":
                        self.sequence.append(rule1_params[0])
                    elif rule1_type == "arithmetic":
                        self.sequence.append(rule1_params[0] + (i - 1) * rule1_params[1])
                else:
                    if rule2_type == "constant":
                        self.sequence.append(rule2_params[0])
                    elif rule2_type == "arithmetic":
                        self.sequence.append(rule2_params[0] + (i - breakpoint - 1) * rule2_params[1])
        
        self.prefix_sum = []
        self.prefix_max = []
        current_sum = 0
        current_max = 0
        
        for val in self.sequence:
            current_sum += val
            current_max = max(current_max, val)
            self.prefix_sum.append(current_sum)
            self.prefix_max.append(current_max)

    def evaluate(self, parsed_info):
        if self.verification_phase and len(self.verification_results) >= len(self.verification_indices):
            for idx in self.verification_indices:
                if idx not in self.verification_results:
                    return False
                pred_sum, pred_max = self.verification_results[idx]
                true_sum = self.prefix_sum[idx - 1]
                true_max = self.prefix_max[idx - 1]
                if pred_sum != true_sum or pred_max != true_max:
                    return False
            return True
        
        if "answer" in parsed_info:
            import re
            ans_text = parsed_info["answer"]
            if "predict" in parsed_info:
                ans_text += " " + parsed_info["predict"]
                
            matches = re.findall(r'index\s*=\s*(\d+)\s*,\s*sum\s*=\s*(\d+)\s*,\s*max\s*=\s*(\d+)', ans_text, re.IGNORECASE)
            
            t = self._game_info.get("t", 3)
            valid_preds = {}
            for match in matches:
                idx = int(match[0])
                pred_sum = int(match[1])
                pred_max = int(match[2])
                if 1 <= idx <= self._game_info["n"]:
                    valid_preds[idx] = (pred_sum, pred_max)
            
            if len(valid_preds) >= t:
                for idx, (pred_sum, pred_max) in valid_preds.items():
                    if pred_sum != self.prefix_sum[idx - 1] or pred_max != self.prefix_max[idx - 1]:
                        return False
                return True
                
        return False

    def _cf_core_produce(self, parsed_info):
        lang = self.config.language
        
        if "query_sum" in parsed_info:
            if self.verification_phase:
                return "错误：已进入验证阶段，不能再进行查询。" if lang == "zh" else "Error: In verification phase, no more queries allowed."
                
            try:
                k = int(parsed_info["query_sum"].strip())
                if k < 1 or k > self._game_info["n"]:
                    return f"错误：索引必须在 1 到 {self._game_info['n']} 之间。" if lang == "zh" else f"Error: Index must be between 1 and {self._game_info['n']}."
                
                self.query_count += 1
                self.queried_indices.add(k)
                
                if self.query_count > self.max_queries:
                    self.state.set_state("failed", "exceeded query limit")
                    return f"查询次数已超过限制 {self.max_queries} 次，游戏失败。" if lang == "zh" else f"Query limit of {self.max_queries} exceeded. Game failed."
                
                result = self.prefix_sum[k - 1]
                remaining = self.max_queries - self.query_count
                return f"前缀和({k}) = {result}。剩余查询次数：{remaining}" if lang == "zh" else f"Prefix sum({k}) = {result}. Remaining queries: {remaining}"
                
            except (ValueError, IndexError):
                return "错误：无效的索引格式。" if lang == "zh" else "Error: Invalid index format."
        
        elif "query_max" in parsed_info:
            if self.verification_phase:
                return "错误：已进入验证阶段，不能再进行查询。" if lang == "zh" else "Error: In verification phase, no more queries allowed."
                
            try:
                k = int(parsed_info["query_max"].strip())
                if k < 1 or k > self._game_info["n"]:
                    return f"错误：索引必须在 1 到 {self._game_info['n']} 之间。" if lang == "zh" else f"Error: Index must be between 1 and {self._game_info['n']}."
                
                self.query_count += 1
                self.queried_indices.add(k)
                
                if self.query_count > self.max_queries:
                    self.state.set_state("failed", "exceeded query limit")
                    return f"查询次数已超过限制 {self.max_queries} 次，游戏失败。" if lang == "zh" else f"Query limit of {self.max_queries} exceeded. Game failed."
                
                result = self.prefix_max[k - 1]
                remaining = self.max_queries - self.query_count
                return f"前缀最大({k}) = {result}。剩余查询次数：{remaining}" if lang == "zh" else f"Prefix max({k}) = {result}. Remaining queries: {remaining}"
                
            except (ValueError, IndexError):
                return "错误：无效的索引格式。" if lang == "zh" else "Error: Invalid index format."
        
        elif "finish" in parsed_info:
            if self.verification_phase:
                return "错误：已在验证阶段。" if lang == "zh" else "Error: Already in verification phase."
            
            self.verification_phase = True
            
            available_indices = [i for i in range(1, self._game_info["n"] + 1) if i not in self.queried_indices]
            
            if len(available_indices) < self.verification_count:
                available_indices = list(range(1, self._game_info["n"] + 1))
            
            rng = random.Random(42)
            self.verification_indices = rng.sample(available_indices, min(self.verification_count, len(available_indices)))
            self.verification_indices.sort()
            
            indices_str = ", ".join(map(str, self.verification_indices))
            if lang == "zh":
                return f"进入验证阶段。请对以下 {len(self.verification_indices)} 个索引分别预测其前缀和与前缀最大值：{indices_str}。每个索引需单独提交一次预测。"
            else:
                return f"Entering verification phase. Please predict the prefix sum and prefix maximum for the following {len(self.verification_indices)} indices: {indices_str}. Submit prediction for each index separately."
        
        elif "predict" in parsed_info:
            if not self.verification_phase:
                return "错误：还未进入验证阶段，请先提交 <finish></finish>。" if lang == "zh" else "Error: Not in verification phase yet. Please submit <finish></finish> first."
            
            try:
                raw_pred = parsed_info["predict"]
                parts = [x.strip() for x in raw_pred.split(",")]
                pred_dict = {}
                for part in parts:
                    if "=" in part:
                        k, v = part.split("=", 1)
                        pred_dict[k.strip()] = v.strip()
                
                if "index" not in pred_dict or "sum" not in pred_dict or "max" not in pred_dict:
                    return "错误：预测格式必须包含 index、sum 和 max。" if lang == "zh" else "Error: Prediction must include index, sum, and max."
                
                idx = int(pred_dict["index"])
                pred_sum = int(pred_dict["sum"])
                pred_max = int(pred_dict["max"])
                
                if idx not in self.verification_indices:
                    return f"错误：索引 {idx} 不在验证列表中。" if lang == "zh" else f"Error: Index {idx} is not in verification list."
                
                if idx in self.verification_results:
                    return f"错误：索引 {idx} 已经提交过预测。" if lang == "zh" else f"Error: Prediction for index {idx} already submitted."
                
                self.verification_results[idx] = (pred_sum, pred_max)
                
                if len(self.verification_results) == len(self.verification_indices):
                    if lang == "zh":
                        return "所有预测已提交。请使用 <answer>提交</answer> 提交最终答案以完成验证。"
                    else:
                        return "All predictions submitted. Please use <answer>submit</answer> to finalize your answer."
                else:
                    remaining = len(self.verification_indices) - len(self.verification_results)
                    if lang == "zh":
                        return f"索引 {idx} 的预测已记录。还需预测 {remaining} 个索引。"
                    else:
                        return f"Prediction for index {idx} recorded. {remaining} more predictions needed."
                    
            except (ValueError, KeyError) as e:
                return f"错误：预测格式无效。{str(e)}" if lang == "zh" else f"Error: Invalid prediction format. {str(e)}"
        
        else:
            return "错误：未识别的查询类型。" if lang == "zh" else "Error: Unrecognized query type."

    def get_all_possible_queries(self) -> list:
        queries = []
        n    = self._game_info["n"]
        lang = self.config.language

        for k in range(1, n + 1):
            val_sum = self.prefix_sum[k - 1]
            ans_sum = (f"前缀和({k}) = {val_sum}" if lang == "zh"
                    else f"Prefix sum({k}) = {val_sum}")
            queries.append({
                "query":  f"<query_sum>{k}</query_sum>",
                "answer": ans_sum,
            })

            val_max = self.prefix_max[k - 1]
            ans_max = (f"前缀最大({k}) = {val_max}" if lang == "zh"
                    else f"Prefix max({k}) = {val_max}")
            queries.append({
                "query":  f"<query_max>{k}</query_max>",
                "answer": ans_max,
            })

        return queries

    def _cf_make_wrong(self, correct: str) -> str:
        import re as _re
        m = _re.search(r'(=\s*)(\d+)', correct)
        if m:
            wrong_val = int(m.group(2)) + 1
            return correct[:m.start(2)] + str(wrong_val) + correct[m.end(2):]
        return correct + "_WRONG"